### ISSUE TITLE
Vertex Removal throws Exception

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#102]
If I try to remove two related vertices in the same transaction, an IllegalArgumentException is thrown.  If the 2 removeVertex operations are performed in independent transactions it seems to work properly.

The following test case fails:

Vertex v1 = g.addVertex(null);
Vertex v2 = g.addVertex(null);

Edge e = g.addEdge(null, v1, v2, "some_edge");

g.stopTransaction(Conclusion.SUCCESS);

v1 = g.getVertex(v1);
v2 = g.getVertex(v2);

g.removeVertex(v1);
g.removeVertex(v2);

g.stopTransaction(Conclusion.SUCCESS);

EXCEPTION:
java.lang.IllegalArgumentException: Vertex has been removed for id: 2000004
    at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.getExisting(AbstractTitanTx.java:174)
    at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.getExistingVertex(AbstractTitanTx.java:156)
    at com.thinkaurelius.titan.graphdb.database.StandardVertexRelationLoader.loadEdge(StandardVertexRelationLoader.java:37)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.loadRelations(StandardTitanGraph.java:314)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.loadRelations(StandardTitanGraph.java:275)
    at com.thinkaurelius.titan.graphdb.transaction.StandardPersistTitanTx.loadRelations(StandardPersistTitanTx.java:150)
    at com.thinkaurelius.titan.graphdb.vertices.AbstractTitanVertex.ensureLoadedEdges(AbstractTitanVertex.java:88)
    at com.thinkaurelius.titan.graphdb.vertices.StandardTitanVertex.getRelations(StandardTitanVertex.java:71)
    at com.thinkaurelius.titan.graphdb.query.SimpleAtomicQuery.relations(SimpleAtomicQuery.java:479)
    at com.thinkaurelius.titan.graphdb.vertices.AbstractTitanVertex.getRelations(AbstractTitanVertex.java:182)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.removeVertex(TitanBlueprintsTransaction.java:79)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.removeVertex(TitanBlueprintsGraph.java:110)

**Comment by castarco** [comment]
I think the problem is not in Titan, but in the fact that you don't delete the created edge in first place.
