### ISSUE TITLE
SubgraphStrategyProcessTest is currently failing

### ISSUE THREAD

**Issue by BrynCooke** [thinkaurelius/titan#1034]
```
java.lang.UnsupportedOperationException: Operation not supported on a stub vertex
    at com.thinkaurelius.titan.graphdb.vertices.PreloadedVertex.stubVertexException(PreloadedVertex.java:143)
    at com.thinkaurelius.titan.graphdb.vertices.PreloadedVertex.query(PreloadedVertex.java:76)
    at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.properties(AbstractVertex.java:168)
    at com.thinkaurelius.titan.graphdb.vertices.PreloadedVertex.properties(PreloadedVertex.java:112)
    at org.apache.tinkerpop.gremlin.structure.Vertex.property(Vertex.java:65)
    at org.apache.tinkerpop.gremlin.structure.Vertex.property(Vertex.java:36)
    at org.apache.tinkerpop.gremlin.structure.Element.value(Element.java:95)
    at org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.SubgraphStrategyProcessTest.lambda$shouldFilterMixedCriteria$183(SubgraphStrategyProcessTest.java:230)
    at org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.SubgraphStrategyProcessTest$$Lambda$123/846918683.test(Unknown Source)
    at org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.SubgraphStrategy.lambda$new$183(SubgraphStrategy.java:54)
    at org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.SubgraphStrategy$$Lambda$75/573958827.test(Unknown Source)
    at org.apache.tinkerpop.gremlin.process.traversal.step.filter.LambdaFilterStep.filter(LambdaFilterStep.java:46)
    at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:38)
    at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:134)
    at java.util.Iterator.forEachRemaining(Iterator.java:115)
    at org.apache.tinkerpop.gremlin.process.computer.traversal.TraverserExecutor.lambda$execute$4(TraverserExecutor.java:80)
    at org.apache.tinkerpop.gremlin.process.computer.traversal.TraverserExecutor$$Lambda$114/94827036.accept(Unknown Source)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at org.apache.tinkerpop.gremlin.process.computer.traversal.TraverserExecutor.execute(TraverserExecutor.java:77)
    at org.apache.tinkerpop.gremlin.process.computer.traversal.TraversalVertexProgram.execute(TraversalVertexProgram.java:185)
    at com.thinkaurelius.titan.graphdb.olap.computer.VertexProgramScanJob.process(VertexProgramScanJob.java:106)
    at com.thinkaurelius.titan.graphdb.olap.VertexJobConverter.process(VertexJobConverter.java:127)
    at com.thinkaurelius.titan.diskstorage.keycolumnvalue.scan.StandardScannerExecutor$Processor.run(StandardScannerExecutor.java:267)
12235 [Thread-67] ERROR com.thinkaurelius.titan.diskstorage.keycolumnvalue.scan.StandardScannerExecutor  - Exception processing row [224-  0-  0-  0-  0-  0-  0-128]: 
java.lang.UnsupportedOperationException: Operation not supported on a stub vertex
    at com.thinkaurelius.titan.graphdb.vertices.PreloadedVertex.stubVertexException(PreloadedVertex.java:143)
    at com.thinkaurelius.titan.graphdb.vertices.PreloadedVertex.query(PreloadedVertex.java:76)
    at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.properties(AbstractVertex.java:168)
    at com.thinkaurelius.titan.graphdb.vertices.PreloadedVertex.properties(PreloadedVertex.java:112)
    at org.apache.tinkerpop.gremlin.structure.Vertex.property(Vertex.java:65)
    at org.apache.tinkerpop.gremlin.structure.Vertex.property(Vertex.java:36)
    at org.apache.tinkerpop.gremlin.structure.Element.value(Element.java:95)
    at org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.SubgraphStrategyProcessTest.lambda$shouldFilterMixedCriteria$183(SubgraphStrategyProcessTest.java:230)
    at org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.SubgraphStrategyProcessTest$$Lambda$123/846918683.test(Unknown Source)
    at org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.SubgraphStrategy.lambda$new$183(SubgraphStrategy.java:54)
    at org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.SubgraphStrategy$$Lambda$75/573958827.test(Unknown Source)
    at org.apache.tinkerpop.gremlin.process.traversal.step.filter.LambdaFilterStep.filter(LambdaFilterStep.java:46)
    at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:38)
    at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:134)
    at java.util.Iterator.forEachRemaining(Iterator.java:115)
    at org.apache.tinkerpop.gremlin.process.computer.traversal.TraverserExecutor.lambda$execute$4(TraverserExecutor.java:80)
    at org.apache.tinkerpop.gremlin.process.computer.traversal.TraverserExecutor$$Lambda$114/94827036.accept(Unknown Source)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at org.apache.tinkerpop.gremlin.process.computer.traversal.TraverserExecutor.execute(TraverserExecutor.java:77)
    at org.apache.tinkerpop.gremlin.process.computer.traversal.TraversalVertexProgram.execute(TraversalVertexProgram.java:185)
    at com.thinkaurelius.titan.graphdb.olap.computer.VertexProgramScanJob.process(VertexProgramScanJob.java:106)
    at com.thinkaurelius.titan.graphdb.olap.VertexJobConverter.process(VertexJobConverter.java:127)
    at com.thinkaurelius.titan.diskstorage.keycolumnvalue.scan.StandardScannerExecutor$Processor.run(StandardScannerExecutor.java:267)

java.lang.IllegalStateException: com.thinkaurelius.titan.core.TitanException: Exception in Titan
    at org.apache.tinkerpop.gremlin.process.computer.traversal.step.map.ComputerResultStep.processNextStart(ComputerResultStep.java:80)
    at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:119)
    at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:34)
    at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:122)
    at org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.SubgraphStrategyProcessTest.shouldFilterMixedCriteria(SubgraphStrategyProcessTest.java:251)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runners.Suite.runChild(Suite.java:127)
    at org.apache.tinkerpop.gremlin.AbstractGremlinSuite.runChild(AbstractGremlinSuite.java:259)
    at org.apache.tinkerpop.gremlin.AbstractGremlinSuite.runChild(AbstractGremlinSuite.java:61)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.util.concurrent.ExecutionException: com.thinkaurelius.titan.core.TitanException: Exception in Titan
    at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1887)
    at org.apache.tinkerpop.gremlin.process.computer.traversal.step.map.ComputerResultStep.processNextStart(ComputerResultStep.java:78)
    ... 43 more
Caused by: com.thinkaurelius.titan.core.TitanException: Exception in Titan
    at com.thinkaurelius.titan.graphdb.olap.computer.FulgoraGraphComputer.lambda$submit$6(FulgoraGraphComputer.java:173)
    at com.thinkaurelius.titan.graphdb.olap.computer.FulgoraGraphComputer$$Lambda$102/596470015.get(Unknown Source)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582)
    at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.thinkaurelius.titan.core.TitanException: Failed to process [2] vertices in vertex program iteration [2]. Computer is aborting.
    at com.thinkaurelius.titan.graphdb.olap.computer.FulgoraGraphComputer.lambda$submit$6(FulgoraGraphComputer.java:164)
    ... 7 more
```

**Comment by BrynCooke** [comment]
Stephen is currently looking at this as a fix on the TP side.

**Comment by mbroecheler** [comment]
This exception is due to the SubgraphStrategy accessing properties on adjacent vertices which causes trouble under the GraphComputer computing style.

**Comment by okram** [comment]
Hm. This works for `SparkGraphComputer` and `GiraphGraphComputer`. ??

**Comment by spmallette** [comment]
i'm am mostly sure that this problem is due to strategy conflicts that will be sorted out before GA.

**Comment by BrynCooke** [comment]
@spmallette Is there an issue on the TP side that tracks this issue? I would like to link to it.

**Comment by spmallette** [comment]
my best guess is that this will be resolved via: https://issues.apache.org/jira/browse/TINKERPOP3-593

**Comment by BrynCooke** [comment]
Tests are passing in 'Berkeley' and 'In Memory'
