### ISSUE TITLE
Kryo serialization error with gremlin server.

### ISSUE THREAD

**Issue by BrynCooke** [thinkaurelius/titan#1039]
Config is now fixed but am getting a weird error

``` java
16:03:31 WARN  io.netty.channel.DefaultChannelPipeline  - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: org.apache.tinkerpop.gremlin.driver.ser.SerializationException: org.apache.tinkerpop.shaded.kryo.KryoException: Encountered unregistered class ID: 121
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at org.apache.tinkerpop.gremlin.driver.handler.WebSocketClientHandler.channelRead0(WebSocketClientHandler.java:90)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.tinkerpop.gremlin.driver.ser.SerializationException: org.apache.tinkerpop.shaded.kryo.KryoException: Encountered unregistered class ID: 121
    at org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0.deserializeResponse(GryoMessageSerializerV1d0.java:194)
    at org.apache.tinkerpop.gremlin.driver.handler.WebSocketGremlinResponseDecoder.decode(WebSocketGremlinResponseDecoder.java:49)
    at org.apache.tinkerpop.gremlin.driver.handler.WebSocketGremlinResponseDecoder.decode(WebSocketGremlinResponseDecoder.java:36)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
    ... 20 more
Caused by: org.apache.tinkerpop.shaded.kryo.KryoException: Encountered unregistered class ID: 121
    at org.apache.tinkerpop.gremlin.structure.io.gryo.GremlinClassResolver.readClass(GremlinClassResolver.java:166)
    at org.apache.tinkerpop.shaded.kryo.Kryo.readClass(Kryo.java:641)
    at org.apache.tinkerpop.shaded.kryo.Kryo.readClassAndObject(Kryo.java:752)
    at org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0.deserializeResponse(GryoMessageSerializerV1d0.java:181)
    ... 23 more
```

**Comment by spmallette** [comment]
When do you see that message?

**Comment by BrynCooke** [comment]
When I connect via gremlin.sh
:remote connect tinkerpop.server conf/remote.yaml //OK
:> g.V().values('name') //ERROR

In addition when I try the curl as per the TP docs I get:
curl "http://localhost:8182?gremlin=100-1"
not a WebSocket handshake request: missing upgrade

**Comment by BrynCooke** [comment]
This is my remote.yaml:

hosts: [localhost]
port: 8182
serializer: { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { serializeResultToString: true }}

**Comment by spmallette** [comment]
you can't curl unless Gremlin Server is configured with the REST channel - it isn't by default.  if you are in the console and using `:>` what happens when you just do a `1+1`? does that work?

**Comment by BrynCooke** [comment]
I get the same error

**Comment by spmallette** [comment]
eek - what version of TP3?  M8? master?

**Comment by BrynCooke** [comment]
M8-incubating

**Comment by spmallette** [comment]
i assume this only happens when you have titan configured in Gremlin Server?  it works otherwise (with like TinkerGraph)?

**Comment by BrynCooke** [comment]
I took out all configured graphs and tried
:> 1+1
and got the same error.
I'm not saying it isn't Titan related but at least the graph isn't involved.

Could this be Kryo version issues?

**Comment by BrynCooke** [comment]
OK. I got it. The gremlin-server.yaml still had the old Kryo serializer it in rather then the new Gryo serializer. I am surprised it didn't blow up on startup though.

**Comment by BrynCooke** [comment]
Fixed as part of https://github.com/thinkaurelius/titan/issues/872
