### ISSUE TITLE
why the configuration of  the cluster.max-partitions with issue?

### ISSUE THREAD

**Issue by gepengxu** [thinkaurelius/titan#1042]
When I want enable Titan-0.5.1-hadoop config with HBase,The HBase with 17 instance,I just want to enable cluster.partition and cluster.max-partitions
When I set in the rexster-hbase.xml with such conf information
                                &lt;cluster.partition&gt;true&lt;/cluster.partition&gt;
                &lt;cluster.max-partitions&gt;34&lt;/cluster.max-partitions&gt;
when Start the instance,I just get such issue
2147 [main] INFO  com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration  - Ignored configuration entry for cluster.max-partitions since it does not map to an option
java.lang.IllegalArgumentException: Invalid configuration value for [root.cluster.max-partitions]: 34
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)
        at com.thinkaurelius.titan.diskstorage.configuration.ConfigOption.verify(ConfigOption.java:169)
        at com.thinkaurelius.titan.diskstorage.configuration.ConfigOption.get(ConfigOption.java:161)
        at com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration.get(BasicConfiguration.java:56)
        at com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration.getAll(BasicConfiguration.java:82)
        at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1781)
        at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:91)
        at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:71)
        at com.thinkaurelius.titan.tinkerpop.rexster.TitanGraphConfiguration.configureGraphInstance(TitanGraphConfiguration.java:33)
        at com.tinkerpop.rexster.config.GraphConfigurationContainer.getGraphFromConfiguration(GraphConfigurationContainer.java:124)
        at com.tinkerpop.rexster.config.GraphConfigurationContainer.<init>(GraphConfigurationContainer.java:54)
        at com.tinkerpop.rexster.server.XmlRexsterApplication.reconfigure(XmlRexsterApplication.java:99)
        at com.tinkerpop.rexster.server.XmlRexsterApplication.<init>(XmlRexsterApplication.java:47)
        at com.tinkerpop.rexster.Application.<init>(Application.java:97)
        at com.tinkerpop.rexster.Application.main(Application.java:189)

I just reference the document of website http://s3.thinkaurelius.com/docs/titan/0.5.0/titan-config-ref.html, which is about 0.5.0
If you find such issue?

**Comment by gepengxu** [comment]
the configuration is as following
&lt;cluster.partition&gt;true&lt;/cluster.partition&gt;
&lt;cluster.max-partitions&gt;34&lt;/cluster.max-partitions&gt;

**Comment by mbroecheler** [comment]
As specified in the documentation, max-partitions must be a power of 2. Hence, 34 is an invalid setting. 32 is valid as is 64.
