### ISSUE TITLE
unparsable data present in cassandra.

### ISSUE THREAD

**Issue by mishraawake** [thinkaurelius/titan#1043]
Hi, 
Relating to bug (https://github.com/thinkaurelius/titan/issues/1013) we have found following findings. 
1. Even on repairing cassandra cluster bug persists.
2. On further investigation we found that, for a particular vertex (with titan id : 291494040 and cassandra row key id: 22bfb130 in edgestore), the data present in cassandra is unparsable by titan.  For your reference following data are present.

 0x0000000022bfb130 |                                       0x010b |               0x0b0002000000
 0x0000000022bfb130 |                                         0x0b | 0x0b00020000000d210b696db280
 0x0000000022bfb130 | 0x0b00010000000200a00b000200000006210b696db6 |   0x50e2b8f5d90000000c00010c
 0x0000000022bfb130 |                                         0x28 |               0x021c7c1d9280
 0x0000000022bfb130 |                                         0x34 | 0x021c7c1d9680000000003ae9ce
 0x0000000022bfb130 | 0x368a110a000313d48a50e2b8f5d90000000c00010c |               0x001540a7fe7f
 0x0000000022bfb130 |                                         0x40 |               0xc975eeb85076

Of which only following keys are valid.
 0x0000000022bfb130 |                                         0x28 |               0x021c7c1d9280
 0x0000000022bfb130 |                                         0x34 | 0x021c7c1d9680000000003ae9ce

Would it mean that titan has wrongly written that data or this corruption happened in cassandra?

Now we are going to rectify this data manually through thirft API (basically we are going to delete the wrong column name from cassandra edgestore). Is this the right approach or you suggest something else to do in this case?

Can you suggest any reason that might lead to corruption of data?

**Comment by mbroecheler** [comment]
@mishraawake I have only seen this data corruption occur in two contexts:
1) Part of the schema information was lost. This would explain why some of the entries can no longer be read since the needed schema information cannot be found
2) Cassandra was operated sub-quorum or in a split-brain scenario for a while before the cluster subsets where merged back together and invalid data was merged into the edgestore.

**Comment by mishraawake** [comment]
1. First point is looking more likely  but if we look at the key name "0x010b", Following sequence of call happens IDHandler. readEdgeType() -> VariableLong.readPositiveWithPrefix() -> VariableLong.readUnsigned(). The last call fails. After looking at code it seems that, its not referring for schema to parse that data at all. It fails because , I think, this key name is not valid for titan (0.4.2) .

Though there are some exception coming which point to the loss of schema also. 
1. We never merged cassandra data ever since we went live. So, its not manual merged. I don't know if merged would have happened automatically.

**Comment by mbroecheler** [comment]
Are you saying that this call `VariableLong.readUnsigned()` is throwing an exception when reading data? Do you have the entire stack trace? Sorry, just saw your comment now.

**Comment by mishraawake** [comment]
We get following stack trace.
We also have some instances where vertex index have been screwed for some vertex..

java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.til.mytimes.titan.mytimes.AnnotationProcessor.executeMethod(AnnotationProcessor.java:111)
    at com.til.mytimes.titan.mytimes.RequestProcessor.handleRequest(RequestProcessor.java:18)
    at com.til.mytimes.titan.netty.MyTimesServerHandler.messageReceived(MyTimesServerHandler.java:89)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:103)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:74)
    at io.netty.channel.DefaultChannelHandlerInvoker$6.run(DefaultChannelHandlerInvoker.java:143)
    at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:57)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:794)
    at java.lang.Thread.run(Thread.java:744)
Caused by: com.esotericsoftware.kryo.KryoException: Buffer too small: capacity: 2, required: 8
    at com.esotericsoftware.kryo.io.Input.require(Input.java:152)
    at com.esotericsoftware.kryo.io.Input.readLong(Input.java:650)
    at com.thinkaurelius.titan.graphdb.database.serialize.kryo.InputScanBuffer.getLong(InputScanBuffer.java:40)
    at com.thinkaurelius.titan.graphdb.database.serialize.attribute.LongSerializer.read(LongSerializer.java:13)
    at com.thinkaurelius.titan.graphdb.database.serialize.attribute.LongSerializer.read(LongSerializer.java:7)
    at com.thinkaurelius.titan.graphdb.database.serialize.kryo.KryoAttributeSerializerAdapter.read(KryoAttributeSerializerAdapter.java:21)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:626)
    at com.thinkaurelius.titan.graphdb.database.serialize.kryo.KryoSerializer.readObjectNotNull(KryoSerializer.java:118)
    at com.thinkaurelius.titan.graphdb.database.EdgeSerializer.parseRelation(EdgeSerializer.java:211)
    at com.thinkaurelius.titan.graphdb.database.EdgeSerializer.readRelation(EdgeSerializer.java:119)
    at com.thinkaurelius.titan.graphdb.database.EdgeSerializer.readRelation(EdgeSerializer.java:59)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$4$3.apply(StandardTitanTx.java:780)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$4$3.apply(StandardTitanTx.java:777)
    at com.google.common.collect.Iterators$8.transform(Iterators.java:860)
    at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
    at com.thinkaurelius.titan.graphdb.query.LimitAdjustingIterator.next(LimitAdjustingIterator.java:55)
    at com.thinkaurelius.titan.graphdb.query.QueryProcessor$MergeSortIterator.nextInternal(QueryProcessor.java:285)
    at com.thinkaurelius.titan.graphdb.query.QueryProcessor$MergeSortIterator.<init>(QueryProcessor.java:260)
    at com.thinkaurelius.titan.graphdb.query.QueryProcessor.getUnwrappedIterator(QueryProcessor.java:115)
    at com.thinkaurelius.titan.graphdb.query.QueryProcessor.access$000(QueryProcessor.java:25)
    at com.thinkaurelius.titan.graphdb.query.QueryProcessor$OuterIterator.<init>(QueryProcessor.java:60)
    at com.thinkaurelius.titan.graphdb.query.QueryProcessor.iterator(QueryProcessor.java:46)
    at com.til.mytimes.titan.mytimes.FeedGeneratorUtils.getVertexesId(FeedGeneratorUtils.java:182)
    at com.til.mytimes.titan.mytimes.TitanReadService.getUsersFollowersFollowee(TitanReadService.java:433)
    ... 12 more

**Comment by mishraawake** [comment]
Is there any progress on this issue? We have experienced same problem on following titan version as well.
titan version :           0.5.3
cassandra version : 2.1.6
