### ISSUE TITLE
Titan/BerkeleyDB error with g.E

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#105]
gremlin> g.E.count()
java.lang.IllegalArgumentException
Display stack trace? [yN] y
java.lang.IllegalArgumentException
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:76)
    at com.thinkaurelius.titan.graphdb.entitystatus.BasicElement.<init>(BasicElement.java:17)
    at com.thinkaurelius.titan.graphdb.vertices.PersistStandardTitanVertex.<init>(PersistStandardTitanVertex.java:23)
    at com.thinkaurelius.titan.graphdb.vertices.factory.StandardVertexFactories$1.createExisting(StandardVertexFactories.java:15)
    at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.getExisting(AbstractTitanTx.java:170)
    at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.getExistingVertex(AbstractTitanTx.java:156)
    at com.thinkaurelius.titan.graphdb.database.StandardVertexRelationLoader.loadEdge(StandardVertexRelationLoader.java:37)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.loadRelations(StandardTitanGraph.java:360)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.loadRelations(StandardTitanGraph.java:321)
    at com.thinkaurelius.titan.graphdb.transaction.StandardPersistTitanTx.loadRelations(StandardPersistTitanTx.java:151)
...
gremlin> g.E[0]
==>e[63:4:36028797018964014][4-hasGenera->16]
gremlin> g.E[1]
==>e[55:4:36028797018964014][4-hasGenera->12]
gremlin> g.E[2]
==>e[47:4:36028797018964014][4-hasGenera->8]
gremlin> g.E[3]
==>e[89:20:36028797018964014][20-hasGenera->28]
gremlin> g.E[10]
==>e[897:48:36028797018964014][48-hasGenera->16]
gremlin>

**Comment by okram** [comment]
Problem was mixing Titan 0.1.0 with Titan 0.2-SNAPSHOT.

However, g.E.count() runs out of memory with Titan/BerkeleyDB --- true iterator needed.
