### ISSUE TITLE
 Force close instance not working

### ISSUE THREAD

**Issue by BrynCooke** [thinkaurelius/titan#1057]
I can't run the code in the docs:

```
g = TitanFactory.open('conf/titan-cassandra-embedded-es.properties')
GraphOfTheGodsFactory.load(g)
mgmt = g.openManagement()
instances = mgmt.getOpenInstances() //all open instances
mgmt.forceCloseInstance(instances.iterator().next()) //remove 1st instance
mgmt.commit()

java.lang.IllegalArgumentException: Invalid umbrella name provided: 7f0001015528-dunwich1(current). Contains illegal chars
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)
    at com.thinkaurelius.titan.diskstorage.configuration.ConfigElement.getPath(ConfigElement.java:143)
    at com.thinkaurelius.titan.diskstorage.configuration.AbstractConfiguration.getPath(AbstractConfiguration.java:36)
    at com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration.has(BasicConfiguration.java:49)
    at com.thinkaurelius.titan.graphdb.database.management.ManagementSystem.forceCloseInstance(ManagementSystem.java:173)
    at com.thinkaurelius.titan.core.schema.TitanManagement$forceCloseInstance$1.call(Unknown Source)
```

**Comment by mbroecheler** [comment]
Actually, that's not an issue but outdated documentation. See, we originally just returned the list of all open instances. However, in case of multiple running instances, people didn't know which one was which. Hence, we added "(current)" to the instance that was running the query so users could forcefully shut down all others. 
Hence, the above code should be replaced by something that shows the actual output and then explains to users what that list is (a list of all currently running instances by their unique id) and how they can shut one down by using one of those ids (without the "(current)" - explain what that means).
