### ISSUE TITLE
Failure when running TitanIndexRepair on 0.5.4

### ISSUE THREAD

**Issue by Airswoop1** [thinkaurelius/titan#1086]
Running on 0.5.4

After creating:

management.buildIndex("discover_feed_index", TitanProperty.class)
                .addKey(vertexTypePropertyKey)
                .addKey(itemIdPropertyKey)
                .addKey(itemIsSrc)
                .addKey(itemGender)
                .addKey(itemScore)
                .addKey(itemCategoriesSet)
                .addKey(itemTimeOfYearStart)
                .addKey(itemTimeOfYearEnd)
                .addKey(itemLastPublishedDate)
                .buildMixedIndex("search");

and then running:

TitanIndexRepair.cassandraRepair("conf/titan-cassandra-es.properties", "discover_feed_index", "", pt);

I receive the following exception: 

Caused by: java.lang.IllegalArgumentException: Unsupported type: []
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.getContent(ElasticSearchIndex.java:494)
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.restore(ElasticSearchIndex.java:591)

Any help would be appreciated. Thanks!

full exception is here:
java.lang.Exception: java.io.IOException: Unknown exception while executing index operation
    at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:403)
Caused by: java.io.IOException: Unknown exception while executing index operation
    at com.thinkaurelius.titan.hadoop.TitanIndexRepairMapper.map(TitanIndexRepairMapper.java:242)
    at com.thinkaurelius.titan.hadoop.TitanIndexRepairMapper.map(TitanIndexRepairMapper.java:72)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)
    at org.apache.hadoop.mapreduce.lib.chain.Chain.runMapper(Chain.java:389)
    at org.apache.hadoop.mapreduce.lib.chain.ChainMapper.run(ChainMapper.java:149)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:763)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:339)
    at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:235)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.thinkaurelius.titan.diskstorage.PermanentBackendException: Unknown exception while executing index operation
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.convert(ElasticSearchIndex.java:349)
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.restore(ElasticSearchIndex.java:600)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.restore(IndexTransaction.java:95)
    at com.thinkaurelius.titan.hadoop.TitanIndexRepairMapper.map(TitanIndexRepairMapper.java:232)
    ... 12 more
Caused by: java.lang.IllegalArgumentException: Unsupported type: []
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.getContent(ElasticSearchIndex.java:494)
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.restore(ElasticSearchIndex.java:591)
    ... 14 more
15:52:00 INFO  org.apache.hadoop.mapreduce.Job  - Job job_local57037698_0001 failed with state FAILED due to: NA
15:52:00 INFO  org.apache.hadoop.mapreduce.Job  - Counters: 0
15:52:00 ERROR com.thinkaurelius.titan.hadoop.compat.h2.Hadoop2Compiler  - Error executing [Job 1/1: TitanIndexRepairMapper]; this job has failed and 0 subsequent MapReduce job(s) have been canceled

**Comment by dalaro** [comment]
I would like more information before attempting to reproduce this.  Can you please provide at least the Titan schema definition?  The more details the better.  It's seems that this job is somehow attempting to feed an unsupported property data type into ES (maybe a list), but I don't really know how we got here.

The exception could be improved.  It's currently `IllegalArgumentException("Unsupported type: " + value)`, but it would probably be more informative if it were something like `IllegalArgumentException("Unsupported type: " + value.getClass() + " (value: " + value + ")")`
