### ISSUE TITLE
Read GraphSON fails with cardinality conflict

### ISSUE THREAD

**Issue by pluradj** [thinkaurelius/titan#1088]
Here is a reproduce snippet, using titan09 branch.

```
         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
plugin activated: aurelius.titan
gremlin> graph=TitanFactory.build().set('storage.backend','inmemory').open(); g=graph.traversal(); graph
==>standardtitangraph[inmemory:[127.0.0.1]]
gremlin> v=graph.addVertex(); v.property('name','titan')
==>vp[name->titan]
gremlin> w=graph.addVertex(); w.property('name','faunus')
==>vp[name->faunus]
gremlin> e=v.addEdge('knows',w); e.property('since',2012)
==>p[since->2012]
gremlin> graph.tx().commit()
==>null
gremlin> g.V().count()
WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
==>2
gremlin> graph.io(IoCore.graphson()).writeGraph("/tmp/test.json")
==>null
gremlin> graph=TitanFactory.build().set('storage.backend','inmemory').open(); g=graph.traversal(); graph
==>standardtitangraph[inmemory:[127.0.0.1]]
gremlin> g.V().count()
WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
==>0
gremlin> graph.io(IoCore.graphson()).readGraph("/tmp/test.json")
Key is defined for SINGLE cardinality which conflicts with specified: list
Display stack trace? [yN] y
com.thinkaurelius.titan.core.SchemaViolationException: Key is defined for SINGLE cardinality which conflicts with specified: list
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.addProperty(StandardTitanTx.java:710)
    at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.property(AbstractVertex.java:142)
    at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.property(AbstractVertex.java:23)
    at org.apache.tinkerpop.gremlin.structure.util.Attachable$Method.lambda$createVertex$13(Attachable.java:282)
    at org.apache.tinkerpop.gremlin.structure.util.Attachable$Method$$Lambda$62/262878641.accept(Unknown Source)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at org.apache.tinkerpop.gremlin.structure.util.Attachable$Method.createVertex(Attachable.java:279)
    at org.apache.tinkerpop.gremlin.structure.util.Attachable$Method.lambda$create$11(Attachable.java:134)
    at org.apache.tinkerpop.gremlin.structure.util.Attachable$Method$$Lambda$60/1987154353.apply(Unknown Source)
    at org.apache.tinkerpop.gremlin.structure.util.Attachable.attach(Attachable.java:53)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONReader.lambda$readGraph$70(GraphSONReader.java:99)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONReader$$Lambda$59/680306160.accept(Unknown Source)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONReader.readGraph(GraphSONReader.java:97)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONIo.readGraph(GraphSONIo.java:86)
    at org.apache.tinkerpop.gremlin.structure.io.Io$readGraph$0.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122)
    at groovysh_evaluate.run(groovysh_evaluate:3)
    at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:215)
    at org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:69)
    at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:185)
    at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:119)
    at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:94)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:130)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:150)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:123)
    at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:58)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:130)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:150)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:82)
    at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:215)
    at org.apache.tinkerpop.gremlin.console.Console.<init>(Console.groovy:134)
    at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:215)
    at org.apache.tinkerpop.gremlin.console.Console.main(Console.groovy:292)

```

I've discovered I can fix the problem by setting `schema.default=tp3` on the graph properties. The default in GraphDatabaseConfiguration.java is currently `blueprints`. Should `tp3` be the default now?

**Comment by pluradj** [comment]
This commit seems related to this issue https://github.com/thinkaurelius/titan/commit/36e779e7ea04b385cc10f2652cedc7dc0478d2a7

**Comment by pluradj** [comment]
Contents of /tmp/test.json

``` json
{"id":4304,"label":"vertex","inE":{"knows":[{"id":"17i-3cg-1lh-3bk","outV":4336,"properties":{"since":2012}}]},"properties":{"name":[{"id":"t6-3bk-sl","value":"faunus"}]}}
{"id":4336,"label":"vertex","outE":{"knows":[{"id":"17i-3cg-1lh-3bk","inV":4304,"properties":{"since":2012}}]},"properties":{"name":[{"id":"ta-3cg-sl","value":"titan"}]}}
```

**Comment by pluradj** [comment]
FWIW, I've backed away from using `schema.defaults=tp3` because it doesn't give the me the desired behavior on Cardinality. `blueprints` uses Cardinality.SINGLE which is what I want.

**Comment by spmallette** [comment]
@pluradj  I would argue that you don't want to use `schema.default=tp3` or `schema.default=blueprints`.  Best practice would dictate that you explicitly specify your schema.

@mbroecheler not sure if you want to try to figure out how to switch back to `single` for `tp3` - i'll leave that up to you.  if you do then you need to override `loadGraphData` in your `GraphProvider` implementation and based on the `LoadGraphWith` argument to that method you would create the expected schema for that graph.

**Comment by pluradj** [comment]
@spmallette Yes, I agree with you, but for cases when I'm building an ad-hoc graph, the autotyping is pretty handy.

**Comment by mbroecheler** [comment]
@spmallette @okram The current default cardinality for properties in Titan is SINGLE, however, Stephen changed `features().vertex().getCardinality(key)` to return LIST for compatibility with TP3. Hence the question: Should we make Titan's default cardinality for properties to LIST as well?

**Comment by spmallette** [comment]
to repost a private message:  you can do single if you implement the solution i noted above (i.e. override `GraphProvider.loadGraphData` to respect the `LoadDataWith` annotation)

**Comment by mbroecheler** [comment]
This should be fixed now.

**Comment by pluradj** [comment]
Just tested it out successfully. Thanks, Matthias!
