### ISSUE TITLE
JSON serialization errors with Gremlin Server

### ISSUE THREAD

**Issue by pluradj** [thinkaurelius/titan#1089]
I'm doing some testing with titan09 branch with the latest incubator-tinkerpop master branch, and I'm running into some errors serializing vertex properties. I will make a pull request.

Titan properties

```
# needed for Gremlin Server
gremlin.graph=com.thinkaurelius.titan.core.TitanFactory
# needed for reading GraphSON input from file?
schema.default=tp3

storage.backend=berkeleyje
storage.directory=/tmp/berk/berkdb
```

Gremlin server YAML

```
host: localhost
port: 8182
threadPoolWorker: 1
gremlinPool: 8
scriptEvaluationTimeout: 30000
serializedResponseTimeout: 30000
channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer
graphs: {
  graph: /tmp/berk/titan.properties}
plugins:
  - aurelius.titan
scriptEngines: {
  gremlin-groovy: {
    imports: [java.lang.Math],
    staticImports: [java.lang.Math.PI]},
  nashorn: {
      imports: [java.lang.Math],
      staticImports: [java.lang.Math.PI]}}
serializers:
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0 }
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { serializeResultToString: true }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.JsonMessageSerializerGremlinV1d0 }
  - { className: org.apache.tinkerpop.gremlin.driver.ser.JsonMessageSerializerV1d0 }
processors:
  - { className: org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor, config: { sessionTimeout: 28800000 }}
metrics: {
  consoleReporter: {enabled: true, interval: 180000},
  csvReporter: {enabled: true, interval: 180000, fileName: /tmp/gremlin-server-metrics.csv},
  jmxReporter: {enabled: true},
  slf4jReporter: {enabled: true, interval: 180000},
  gangliaReporter: {enabled: false, interval: 180000, addressingMode: MULTICAST},
  graphiteReporter: {enabled: false, interval: 180000}}
threadPoolBoss: 1
maxInitialLineLength: 4096
maxHeaderSize: 8192
maxChunkSize: 8192
maxContentLength: 65536
maxAccumulationBufferComponents: 1024
resultIterationBatchSize: 64
writeBufferHighWaterMark: 32768
writeBufferHighWaterMark: 65536
ssl: {
  enabled: false}
```

Node.js client

```
var uuid = require('uuid');
var WebSocket = require('ws');
var ws = new WebSocket('ws://127.0.0.1:8182/');

var reqmap = {};

function submit(name, query, delay) {
  setTimeout(function() {
      var payload = {
        requestId: uuid.v4(),
        op: 'eval',
        processor: '',
        args: {
            gremlin: query,
            language: 'gremlin-groovy'
        }
      };
      console.log('>> ' + name + ' -- ' + payload.requestId);
      reqmap[payload.requestId] = name;
      ws.send(JSON.stringify(payload));
  }, delay);
}

ws.on('open', function open() {
  submit('vertex count', 'g=graph.traversal(); g.V().count()', 0);
  submit('vertex properties', 'g=graph.traversal(); g.V().properties()', 0);
});

ws.on('message', function(data, flags) {
  // flags.binary will be set if a binary data is received.
  // flags.masked will be set if the data was masked.
  var result = JSON.parse(data);
  if (result.status.code == 200) {
    console.log('<< ' + reqmap[result.requestId] + ' -- ' + result.requestId);
    console.log(data);
  }
  else if (result.status.code == 299) {
    // stream terminator
    console.log('<| ' + reqmap[result.requestId] + ' -- ' + result.requestId);
  }
});
```

Gremlin server console output

```
[WARN] JsonMessageSerializerV1d0 - Response [ResponseMessage{requestId=071366e0-b465-4216-b9f7-0491e0056218, status=ResponseStatus{code=SUCCESS, message='', attributes={}}, result=ResponseResult{data=[vp[name->jason], vp[name->david]], meta={}}}] could not be serialized by org.apache.tinkerpop.gremlin.driver.ser.AbstractJsonMessageSerializerV1d0.
[WARN] WsGremlinResponseEncoder - The result [ResponseResult{data=[vp[name->jason], vp[name->david]], meta={}}] in the request 071366e0-b465-4216-b9f7-0491e0056218 could not be serialized and returned.
org.apache.tinkerpop.gremlin.driver.ser.SerializationException: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.IllegalStateException) (through reference chain: java.util.ArrayList[0]->com.thinkaurelius.titan.graphdb.relations.RelationIdentifier["inVertexId"])
    at org.apache.tinkerpop.gremlin.driver.ser.JsonMessageSerializerV1d0.serializeResponseAsString(JsonMessageSerializerV1d0.java:100)
    at org.apache.tinkerpop.gremlin.server.handler.WsGremlinResponseEncoder.encode(WsGremlinResponseEncoder.java:79)
    at org.apache.tinkerpop.gremlin.server.handler.WsGremlinResponseEncoder.encode(WsGremlinResponseEncoder.java:45)
    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626)
    at org.apache.tinkerpop.gremlin.server.handler.IteratorHandler.write(IteratorHandler.java:119)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
    at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:32)
    at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:908)
    at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:960)
    at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:893)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.IllegalStateException) (through reference chain: java.util.ArrayList[0]->com.thinkaurelius.titan.graphdb.relations.RelationIdentifier["inVertexId"])
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
    at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:190)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:674)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:156)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129)
    at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2240)
    at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:314)
    at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1340)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONUtil.writeWithType(GraphSONUtil.java:42)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONSerializers.serializerVertexProperty(GraphSONSerializers.java:333)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONSerializers.access$000(GraphSONSerializers.java:55)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONSerializers$VertexPropertyJacksonSerializer.serialize(GraphSONSerializers.java:68)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONSerializers$VertexPropertyJacksonSerializer.serialize(GraphSONSerializers.java:56)
    at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:113)
    at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:73)
    at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:19)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129)
    at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2240)
    at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:314)
    at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1340)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONUtil.writeWithType(GraphSONUtil.java:42)
    at org.apache.tinkerpop.gremlin.driver.ser.AbstractJsonMessageSerializerV1d0$ResponseMessageSerializer.ser(AbstractJsonMessageSerializerV1d0.java:235)
    at org.apache.tinkerpop.gremlin.driver.ser.AbstractJsonMessageSerializerV1d0$ResponseMessageSerializer.serialize(AbstractJsonMessageSerializerV1d0.java:205)
    at org.apache.tinkerpop.gremlin.driver.ser.AbstractJsonMessageSerializerV1d0$ResponseMessageSerializer.serialize(AbstractJsonMessageSerializerV1d0.java:197)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129)
    at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3385)
    at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2779)
    at org.apache.tinkerpop.gremlin.driver.ser.JsonMessageSerializerV1d0.serializeResponseAsString(JsonMessageSerializerV1d0.java:97)
    ... 16 more
Caused by: java.lang.IllegalStateException
    at com.google.common.base.Preconditions.checkState(Preconditions.java:134)
    at com.thinkaurelius.titan.graphdb.relations.RelationIdentifier.getInVertexId(RelationIdentifier.java:69)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:536)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:666)
    ... 41 more
```

The same error happens with HTTP Gremlin Server configuration, but it doesn't produce a stack trace.

**Comment by spmallette** [comment]
This issue was resolved on the TinkerPop side - please see #1090

**Comment by jbmusso** [comment]
(On a side note @pluradj, you may want to use https://github.com/jbmusso/gremlin-client if you require a JS client for Gremlin Server.)

**Comment by pluradj** [comment]
@jbmusso Yes, definitely!
