### ISSUE TITLE
titan09 buildEdgeIndex() error. Wrong signature?

### ISSUE THREAD

**Issue by dmill-bz** [thinkaurelius/titan#1098]
Hey guys,

When using the default example from the docs I get an `illegalArgumentException` : 

``` java
graph.tx().rollback();  //Never create new indexes while a transaction is active
mgmt = graph.openManagement()
time = mgmt.getPropertyKey('time')
battled = mgmt.getEdgeLabel('battled')
mgmt.buildEdgeIndex(battled, 'battlesByTime', Direction.BOTH, Order.decr, time);
mgmt.commit()
```

Here's the trace:

```
1461979 [gremlin-server-exec-1] WARN  org.apache.tinkerpop.gremlin.server.op.AbstractEvalOpProcessor  - Exception processing a script on request [RequestMessage{, requestId=bdcd9131-e417-450a-8bed-403367d1b2de, op='eval', processor='', args={gremlin=graphT.tx().rollback();mgmt=graphT.openManagement();time = mgmt.getPropertyKey('time');battled = mgmt.getEdgeLabel('battled');mgmt.buildEdgeIndex(battled, 'battlesByTime', Direction.BOTH, Order.decr, time);mgmt.commit();null, batchSize=64}}].
java.lang.IllegalArgumentException
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:77)
    at com.thinkaurelius.titan.graphdb.database.management.ManagementSystem.buildRelationTypeIndex(ManagementSystem.java:307)
    at com.thinkaurelius.titan.graphdb.database.management.ManagementSystem.buildEdgeIndex(ManagementSystem.java:293)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:189)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
    at Script43.run(Script43.groovy:1)
    at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:447)
    at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:293)
    at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
    at org.apache.tinkerpop.gremlin.groovy.engine.ScriptEngines.eval(ScriptEngines.java:89)
    at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$2(GremlinExecutor.java:187)
    at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor$$Lambda$112/1996321312.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

I'm not sure but looking at the code I find the following in `...graphdb.database.management.managementSystem`:

``` java
@Override
    public RelationTypeIndex buildEdgeIndex(EdgeLabel label, String name, Direction direction, Order sortOrder, RelationType... sortKeys) {
        return buildRelationTypeIndex(label, name, direction, sortOrder, sortKeys);
    }
// ...
    private RelationTypeIndex buildRelationTypeIndex(RelationType type, String name, Direction direction, Order sortOrder, RelationType... sortKeys) {
// ...
}
```

Looks like the signatures are off, but maybe I'm missing something ?

**Comment by dmill-bz** [comment]
My bad I've been incorrectly defining the property keys. I'll close this.
