### ISSUE TITLE
TitanIndexRepair Issue: Casting and Failure detection

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#1108]
I'm running into an issue with re-indexing on Titan 0.5.4. I have a property key on edges, for which I'd like to create a composite index. However, TitanIndexRepairMapper throws this exception when it appears to be nearing completion:

java.lang.Exception: java.io.IOException: com.thinkaurelius.titan.graphdb.types.vertices.PropertyKeyVertex cannot be cast to com.thinkaurelius.titan.hadoop.FaunusPropertyKey
    at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:403)
Caused by: java.io.IOException: com.thinkaurelius.titan.graphdb.types.vertices.PropertyKeyVertex cannot be cast to com.thinkaurelius.titan.hadoop.FaunusPropertyKey
    at com.thinkaurelius.titan.hadoop.TitanIndexRepairMapper.map(TitanIndexRepairMapper.java:242)
    at com.thinkaurelius.titan.hadoop.TitanIndexRepairMapper.map(TitanIndexRepairMapper.java:72)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)
    at org.apache.hadoop.mapreduce.lib.chain.Chain.runMapper(Chain.java:389)
    at org.apache.hadoop.mapreduce.lib.chain.ChainMapper.run(ChainMapper.java:149)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:763)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:339)
    at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:235)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: com.thinkaurelius.titan.graphdb.types.vertices.PropertyKeyVertex cannot be cast to com.thinkaurelius.titan.hadoop.FaunusPropertyKey
    at com.thinkaurelius.titan.hadoop.FaunusElement.getProperty(FaunusElement.java:321)
    at com.thinkaurelius.titan.graphdb.database.IndexSerializer.indexMatch(IndexSerializer.java:390)
    at com.thinkaurelius.titan.graphdb.database.IndexSerializer.reindexElement(IndexSerializer.java:376)
    at com.thinkaurelius.titan.hadoop.TitanIndexRepairMapper.map(TitanIndexRepairMapper.java:219)
    ... 12 more

I've attached a text file with a little more context around that stacktrace and to show the MapReduce job summary.

And here is a quick probe of the index in question:

rexster[groovy]> idx = mgmt.getGraphIndex('edge_type_composite')
==>com.thinkaurelius.titan.graphdb.database.management.TitanGraphIndexWrapper@6ea7748e
rexster[groovy]> idx.isCompositeIndex()
==>true
rexster[groovy]> idx.getIndexedElement()
==>interface com.thinkaurelius.titan.core.TitanEdge
rexster[groovy]> idx.getFieldKeys().collect{it.getClass()}
==>class com.thinkaurelius.titan.graphdb.types.vertices.PropertyKeyVertex
rexster[groovy]> idx.getFieldKeys().collect{it.getDataType()}
==>class java.lang.String
rexster[groovy]> idx.getFieldKeys().collect{it.getCardinality()}
==>SINGLE

If I change the index definition to be Mixed, the re-index process completes okay. I've also been able to do similar Composite re-indexing on Vertex.class in the past.

On a related note, the call to TitanIndexRepair.cassandraRepair() does not result in any exception being thrown to the client when I see the failure above, so the client code tries to continue on with the process of enabling the supposedly repaired index, which (obviously) isn't a functional index at this point. Is there any built-in way to determine that the index repair failed?

**Comment by dalaro** [comment]
I changed the milestone from Titan1.0 to Titan0.5.5 because the code at the center of the stacktrace has been completely rewritten.  The ClassCastException throw site and assigned type no longer exist in titan09/1.0: FaunusPropertyKey and FaunusElement are both long gone.

For "part b" of this issue: reindex jobs run through titan09's TitanManagement.updateIndex should git fulgora and return a future; these futures could and probably should complete exceptionally.  Jobs run through MapReduce/TitanIndexRepair don't have an equivalent mechanism in either titan05 or titan09.
