### ISSUE TITLE
Failure to lock against the local lock mediator causes a permanent locking exception

### ISSUE THREAD

**Issue by DanielThomas** [thinkaurelius/titan#116]
We're using a unique key to store a unique identifier on graph nodes. We're seeing large numbers of PermanentLockingExceptions due to lock contention on the index lock:

```
Caused by: com.thinkaurelius.titan.diskstorage.PermanentLockingException: Lock could not be acquired because it is held by a local transaction [LockClaim [backer=com.thinkaurelius.titan.diskstorage.util.SimpleLockConfig@2a2f00cc, key=0x2e35313934356233372d316361392d343630382d386539312d6561353930353439346263312e4b414c545552415f32, col=0x400000000000008a, expectedValue=null]]
        at com.thinkaurelius.titan.diskstorage.locking.LockingTransactionHandle.writeBlindLockClaim(LockingTransactionHandle.java:135) ~[titan-0.1.0.jar:na]
        at com.thinkaurelius.titan.diskstorage.cassandra.CassandraEmbeddedOrderedKeyColumnValueStore.acquireLock(CassandraEmbeddedOrderedKeyColumnValueStore.java:164)~[titan-0.1.0.jar:na]
        at com.thinkaurelius.titan.diskstorage.writeaggregation.BufferStoreMutator.acquireIndexLock(BufferStoreMutator.java:51) ~[titan-0.1.0.jar:na]
        at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.lockKeyedProperty(StandardTitanGraph.java:946) ~[titan-0.1.0.jar:na]
        at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.save(StandardTitanGraph.java:678) ~[titan-0.1.0.jar:na]
        at com.thinkaurelius.titan.graphdb.transaction.StandardPersistTitanTx.commit(StandardPersistTitanTx.java:169) ~[titan-0.1.0.jar:na]
        ... 34 common frames omitted
```

Locks against the backing store are retried and failures to aquire a lock result in a TemporaryLockingException. Should the local locks be similarly retried or at least result in a temporary exception to allow the entire commit to be retried?

**Comment by mbroecheler** [comment]
Just to make sure I understand correctly: Are those lock contentions correct? I mean, are you saying that there is a bug in how the locks are being acquired and validated or that it should be a different type of exception to facilitate retry?

Regarding the exception type, what we were trying to accomplish is characterize locking exceptions as follows:
- Temporary: the reason the lock application fails is due to some (possibly) temporary resource unavailability (i.e network error, or large network latency). Retrying the lock application might hence yield positive results.
- Permanent: there is an actual lock contention and therefore the transactional state might be invalid. How this can be recovered (if at all) depends on the transactional semantics and is therefore something that needs to be done in the application.

**Comment by DanielThomas** [comment]
No concern about the locking itself, I'm sure the lock contentions are correct. Just wanted to determine whether Titan should be retrying these index locks, because they feel more like an internal concern of Titan, rather than something that should bubble up to the application. They're potentially very frequent, and there might be additional, undesirable overhead from retrying the commit, that could be avoided by spinning on the lock - not sure.

When I last looked at transaction retry, the work on issue #32 wasn't completed yet, so we weren't clear on exactly what the application's role in transaction retry would be. Notice this is documented in the wiki too, I'd missed that documentation update:

https://github.com/thinkaurelius/titan/wiki/Transaction-Handling

So, unless you've also got concerns about performance or think that index locks should be handled differently when a local lock conflict occurs, consider this ticket a question that's answered. Thanks :smile:

**Comment by dalaro** [comment]
Almost all the code mentioned in this ticket has been refactored or rewritten since it opened.  The principal related classes and interfaces in master are now Locker, BackendTransaction, ExpectedValueCheckingStore, and ConsistentKeyLocker.  The exception behavior is still basically the same even though the code has changed.

Titan's built-in locking backend is intended for low contention, which in part shaped the distinction between "Permanent" and "Temporary" locking exceptions.  "Permanent" exceptions are thrown whenever the code finds that a lock can't be taken until a state change in the storage layer.  That includes finding that another thread or process holds the lock.  The name probably isn't optimal.  It sort of means "this locking failure will persist until some host mutates the the state of the locking store or one or more locks reach their (usually very long) forced expiration timeout".  "Temporary" means we couldn't tell whether the lock can be acquired or not, given the current state of the locking store.  Usually that's a service timeout.
