### ISSUE TITLE
Does titan 0.5.4 GraphOfTheGodsFactory support HBase+Solr?

### ISSUE THREAD

**Issue by twprinston** [thinkaurelius/titan#1177]
I set titan 0.5.4 HBase (1.0.0-cdh5.4.7) +Solr (4.10.3-cdh5.4.7) properties for running GraphOfTheGodsFactory example

When I run graph.query().has('place',WITHIN,Geoshape.circle(37.97,23.72,50)).edges()
I got the error:
ERROR com.thinkaurelius.titan.diskstorage.solr.SolrIndex  - Query did not complete because parameters were not recognized :
org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: Could not find collection : edges
        at org.apache.solr.client.solrj.impl.HttpSolrServer.executeMethod(HttpSolrServer.java:554)

Solr server side show querystring:
org.apache.solr.core.SolrCore.Request: [titan_shard1_replica1] webapp=/solr path=/select params={start=0&q=_:_&collection=edges&wt=javabin&fq={!geofilt+sfield%3Dcn9_g+pt%3D37.97,23.72+d%3D50.0}+distErrPct%3D0+&version=2&rows=2000} status=400 QTime=0

Does titan 0.5.4 GraphOfTheGodsFactory support HBase+Solr?

Thanks.

**Comment by dalaro** [comment]
It should be supported.  "Could not find collection : edges" sounds odd, like the collections/cores Titan wants don't actually exist.

**Comment by nashiyue** [comment]
Hi, sir~ I also use Titan(0.5.4) HBase(0.98) to run the example demo, but use the command GraphOfTheGodsFactory.load(g) get many wrong info, can you help me?
Unknown external index backend: search
Display stack trace? [yN] y
java.lang.IllegalArgumentException: Unknown external index backend: search
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)
    at com.thinkaurelius.titan.graphdb.database.management.ManagementSystem.createMixedIndex(ManagementSystem.java:485)
    at com.thinkaurelius.titan.graphdb.database.management.ManagementSystem.access$400(ManagementSystem.java:94)
    at com.thinkaurelius.titan.graphdb.database.management.ManagementSystem$IndexBuilder.buildMixedIndex(ManagementSystem.java:645)
    at com.thinkaurelius.titan.example.GraphOfTheGodsFactory.load(GraphOfTheGodsFactory.java:48)
    at com.thinkaurelius.titan.example.GraphOfTheGodsFactory$load.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at groovysh_evaluate.run(groovysh_evaluate:84)
    at groovysh_evaluate$run.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at groovysh_evaluate$run.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:67)
    at org.codehaus.groovy.tools.shell.Interpreter$evaluate.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:152)
    at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:114)
    at org.codehaus.groovy.tools.shell.Shell$leftShift$0.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:88)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:100)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
    at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:57)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:66)
    at com.thinkaurelius.titan.hadoop.tinkerpop.gremlin.Console.<init>(Console.java:78)
    at com.thinkaurelius.titan.hadoop.tinkerpop.gremlin.Console.<init>(Console.java:91)
    at com.thinkaurelius.titan.hadoop.tinkerpop.gremlin.Console.main(Console.java:95)

**Comment by trixpan** [comment]
@nashiyue 

I faced the same issue. Seems to me that although HBase is a supported backend, Cassandra was the preferred child.

Having said that I was able to connect to HBase and use the system so it may worth just skipping the demo section
