### ISSUE TITLE
Even after deleting all indices from ElasticSearch API, Titan still thinks those indices are defined

### ISSUE THREAD

**Issue by zifnab87** [thinkaurelius/titan#1180]
Since I couldn't delete my indices from Titan Java API, I deleted all indices on elasticsearch
through DELETE hostip:9200/titan.. Then when I tried building those indices  from scratch,  I get

```
Exception in thread "main" java.lang.IllegalArgumentException: An index with name 'EntityFullText' has already been defined
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
    at com.thinkaurelius.titan.graphdb.database.management.ManagementSystem.checkIndexName(ManagementSystem.java:473)
    at com.thinkaurelius.titan.graphdb.database.management.ManagementSystem.createMixedIndex(ManagementSystem.java:479)
    at com.thinkaurelius.titan.graphdb.database.management.ManagementSystem.access$400(ManagementSystem.java:109)
    at com.thinkaurelius.titan.graphdb.database.management.ManagementSystem$IndexBuilder.buildMixedIndex(ManagementSystem.java:642)
    at com.xxxx.config.DbSchemaInitialization.mixedIndices(DbSchemaInitialization.java:189)
    at com.xxxx.config.DbSchemaInitialization.setupAllForProd(DbSchemaInitialization.java:50)
    at com.xxxx.config.TestBed.main(TestBed.java:17)
```

**Comment by ghost** [comment]
This is working as designed.  

Titan tracks the existence of the index in its own store and has no way to know that the index was deleted externally or out of band.  One could imagine a feature where the integration between Titan and an indexing backend like ElasticSearch and/or Solr/SolrCloud is tighter, but this could be a substantial work effort to get "right".

**Comment by zifnab87** [comment]
@graben1437 So how can I force Titan to rebuild the indices from scratch?

**Comment by dalaro** [comment]
Did you recreate the index with the same name?

REMOVE_INDEX, dropping in ES, and creating a new index that is functionally similar but differently named might be a workaround.  Recreating the index with the same name is almost certain to cause problems, since Titan indeed uses the primary store to hold a separate and (it thinks) authoritative record of what indices exist (C*/HBase/BDB).

This sounds related to #1178.
