### ISSUE TITLE
Titan 1.0.0 GraphSONWriter.writeGraph JsonMappingException

### ISSUE THREAD

**Issue by mhfrantz** [thinkaurelius/titan#1183]
Gist of a repro: https://gist.github.com/mhfrantz/c9feddbadf56ba39dad7

```
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.IllegalStateException) (through reference chain: com.thinkaurelius.titan.graphdb.relations.RelationIdentifier["inVertexId"])
    at com.google.common.base.Preconditions.checkState(Preconditions.java:158)
    at com.thinkaurelius.titan.graphdb.relations.RelationIdentifier.getInVertexId(RelationIdentifier.java:69)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:536)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:666)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:156)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONUtil.writeWithType(GraphSONUtil.java:49)
    at org.apache.tinkerpop.gremlin.structure.util.star.StarGraphGraphSONSerializer.ser(StarGraphGraphSONSerializer.java:100)
    at org.apache.tinkerpop.gremlin.structure.util.star.StarGraphGraphSONSerializer.serialize(StarGraphGraphSONSerializer.java:64)
    at org.apache.tinkerpop.gremlin.structure.util.star.StarGraphGraphSONSerializer.serialize(StarGraphGraphSONSerializer.java:54)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129)
    at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3385)
    at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2745)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONWriter.writeVertex(GraphSONWriter.java:76)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONWriter.writeVertices(GraphSONWriter.java:104)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONWriter.writeGraph(GraphSONWriter.java:65)
```

**Comment by spmallette** [comment]
If you construct all that stuff by hand you have to be sure to tell the `GraphSONMapper` what the titan serializers are:

``` java
GraphSONMapper.build().addRegistry(TitanIoRegistry.INSTANCE).create()
```

or if you don't need to alter any aspects of `GraphSONMapper` with the builder you can do `graph.io().mapper()` and it will come with a `TitanIoRegistry` already added

**Comment by mhfrantz** [comment]
Updated gist as suggested, and the error message is now during read:

```
java.lang.IllegalArgumentException: Property value [{type=Point, coordinates=[23.7, 38.1]}] is of type class java.util.LinkedHashMap is not supported
    at org.apache.tinkerpop.gremlin.structure.Property$Exceptions.dataTypeOfPropertyValueNotSupported(Property.java:159)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.verifyAttribute(StandardTitanTx.java:564)
    at com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.property(AbstractTypedRelation.java:106)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONReader.lambda$null$56(GraphSONReader.java:115)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONReader.lambda$null$57(GraphSONReader.java:115)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONReader.lambda$readGraph$58(GraphSONReader.java:108)
    at java.util.HashMap$EntrySet.forEach(HashMap.java:1035)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONReader.readGraph(GraphSONReader.java:108)
```

Also turned on `embedTypes` (because I think I need that to restore the graph as-is), but that produces an error during write:

```
com.fasterxml.jackson.databind.JsonMappingException: Type id handling not implemented for type com.thinkaurelius.titan.core.attribute.Geoshape (by serializer of type com.thinkaurelius.titan.core.attribute.Geoshape$GeoshapeGsonSerializer)
    at com.fasterxml.jackson.databind.SerializerProvider.mappingException(SerializerProvider.java:1047)
    at com.fasterxml.jackson.databind.JsonSerializer.serializeWithType(JsonSerializer.java:142)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONUtil.writeWithType(GraphSONUtil.java:44)
    at org.apache.tinkerpop.gremlin.structure.util.star.StarGraphGraphSONSerializer.writeEdges(StarGraphGraphSONSerializer.java:162)
    at org.apache.tinkerpop.gremlin.structure.util.star.StarGraphGraphSONSerializer.ser(StarGraphGraphSONSerializer.java:83)
    at org.apache.tinkerpop.gremlin.structure.util.star.StarGraphGraphSONSerializer.serializeWithType(StarGraphGraphSONSerializer.java:71)
    at org.apache.tinkerpop.gremlin.structure.util.star.StarGraphGraphSONSerializer.serializeWithType(StarGraphGraphSONSerializer.java:54)
    at com.fasterxml.jackson.databind.ser.impl.TypeWrappedSerializer.serialize(TypeWrappedSerializer.java:32)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:129)
    at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3385)
    at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2745)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONWriter.writeVertex(GraphSONWriter.java:76)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONWriter.writeVertices(GraphSONWriter.java:104)
    at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONWriter.writeGraph(GraphSONWriter.java:65)
```

**Comment by mhfrantz** [comment]
The most recent set of errors appears to be related to the `Geoshape` type.  Other tests with graphs that do not contain this type of property seem to work with the suggested changes:

```
        final GraphSONMapper.Builder builder = graph.io(IoCore.graphson()).mapper();
        builder.embedTypes(true);
        return builder.create();
```

**Comment by spmallette** [comment]
@mhfrantz this should be fixed now in the titan10 branch.  not sure how that slipped by.  added some tests for good measure.  are you in a position to test this out to let me know if all is good on your side?

**Comment by mhfrantz** [comment]
Tested with a locally built 1.0.1-SNAPSHOT, and everything worked.

**Comment by spmallette** [comment]
thanks for testing so quickly....closing

**Comment by laxatives** [comment]
I think I'm experiencing this bug as well while trying to deserialize properties like `[{ei=EventId, ec=Catgory, es=Source}]`. Is the resolution on the write side or the read side, ie, will the next release allow me to import existing GraphSON files? Will this change be included in the next version with TinkerPop3.1.0?

**Comment by spmallette** [comment]
@laxatives i'm not sure that i follow you.  can you please elaborate on the problem?  and yes, this fix will be in the next release.

**Comment by laxatives** [comment]
Yes, my question was whether I would need to rewrite existing files. It sounds like the answer was yes, I needed to have them written with Extended mode to explicitly describe the type of the serialized object.

Titan won't support containers like ArrayList and HashMap in the future correct? We will need to provide a serializer for these formats?

**Comment by spmallette** [comment]
No - Titan won't support those that I know of.
