### ISSUE TITLE
Spring MVC Startup Issue

### ISSUE THREAD

**Issue by friksa** [thinkaurelius/titan#119]
Trying to evaluate Titan with Spring MVC, but with no luck.  I am able to recreate the issue with these steps:

1) Using STS 2.8.1 on OSX10.8 create a new Spring MVC project using the provided template (this runs fine)
2) Now add the Titan Maven dependency and restart TC server

```
    <dependency>
        <groupId>com.thinkaurelius.titan</groupId>
        <artifactId>titan</artifactId>
        <version>0.1.0</version>
    </dependency>
```

TC Server fails to startup now with the following stack trace:

``` stacktrace
SEVERE: ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/MvcTitan]]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:618)
    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:650)
    at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1582)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.ClassCastException: com.sun.jersey.server.impl.container.servlet.JerseyServletContainerInitializer cannot be cast to javax.servlet.ServletContainerInitializer
    at org.apache.catalina.startup.ContextConfig.getServletContainerInitializer(ContextConfig.java:1630)
    at org.apache.catalina.startup.ContextConfig.processServletContainerInitializers(ContextConfig.java:1538)
    at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1247)
    at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:855)
    at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:346)
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5173)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    ... 11 more
Dec 9, 2012 6:30:45 PM org.apache.catalina.startup.HostConfig deployDescriptor
SEVERE: Error deploying configuration descriptor /Users/fstrecker/sts3/vfabric-tc-server-developer-2.7.1.RELEASE/spring-insight-instance/conf/Catalina/localhost/MvcTitan.xml
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/MvcTitan]]
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:904)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:618)
    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:650)
    at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1582)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
```

**Comment by mbroecheler** [comment]
Can you give me a bit more context? What is the Titan exception you are seeing? Never used Titan with Spring MVC, so I am not sure what I am supposed to be looking at. Thanks.

**Comment by friksa** [comment]
There is not a single line of code written yet.  This is simply adding Titan's Maven POM.  At that point, the server will not start up anymore.

Spring is a very popular FrameWork used by many large and small companies:
http://www.springsource.org

Neo4j is also well integrated with Spring, but cost-prohibitive:
http://www.springsource.org/spring-data/neo4j

Hope that helps.  Let me know if I can provide more info.  Thanks!

This is the download link for STS:
http://www.springsource.org/eclipse-downloads

**Comment by mbroecheler** [comment]
Thanks! Do you know why it is not starting up? In the stack trace that you
provided, I don't see anything Titan specific. It seems to require some xml
file which is not there. Could that be the problem?

On Wed, Dec 12, 2012 at 3:35 PM, friksa notifications@github.com wrote:

> There is not a single line of code written yet. This is simply adding
> Titan's Maven POM. At that point, the server will not start up anymore.
> 
> Spring is a very popular FrameWork used by many large and small companies:
> http://www.springsource.org
> 
> Neo4j is also well integrated with Spring, but cost-prohibitive:
> http://www.springsource.org/spring-data/neo4j
> 
> Hope that helps. Let me know if I can provide more info. Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/119#issuecomment-11315272.

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by friksa** [comment]
Unfortunately I am no Maven expert.  I simply followed the instructions on your web site for adding Titan using Maven, but without luck.  It is easy to recreate with the steps provided and prevents us from evaluating Titan for a few projects that we are ready to start.  We were able to get OrientDb going with their Maven instructions in the same setup, but were hoping to try Titan with Cassandra too before making a decision.

**Comment by mbroecheler** [comment]
I will have to look into this more. The error seems to be a missing xml file, so I suspect that Spring expects some properties from the pom dependency that Titan does not currently fulfill. I am no Spring expert, so we'll need to figure out what that is exactly.

**Comment by devsprint** [comment]
I can take a look to the problem. It will be easy if you can post the pom.xml file, @friksa

**Comment by rafatuita** [comment]
I do have Titan with Spring working without any issues... please also upload your context file so we can have a look, but apparently there's an issue with classcasting of your servlet container

Caused by: java.lang.ClassCastException: com.sun.jersey.server.impl.container.servlet.JerseyServletContainerInitializer cannot be cast to javax.servlet.ServletContainerInitializer
    at org.apache.catalina.startup.ContextConfig.getServletContainerInitializer(ContextConfig.java:1630)

upload this...

 [/Users/fstrecker/sts3/vfabric-tc-server-developer-2.7.1.RELEASE/spring-insight-instance/conf/Catalina/localhost/MvcTitan.xml]

**Comment by friksa** [comment]
Had issues getting XML pasted.  Please use link:
http://pastie.org/5611511

**Comment by devsprint** [comment]
Like @rafatuita mention, there is a classpath issue. it seems that you are trying to use 2 different versions of servlet api, 2.5 and 3.0.1

In you pom, you are mentioning 2.5 version but titan has a dependency on rexter-server, that has a dependency on servlet api 3.0x . I guess, that you can confirm this by opening the pom.xml file in STS, select Dependency Hierarchy tab, and in Resolved dependency you'll see 2 different versions of javax.servlet.api 

I'm not sure how critical is the servlet api version for you, but one possible solution is to update your pom to use same version.

A second solution is to wait for Issue #120 to be fixed, just in case that you do not need rexter

**Comment by friksa** [comment]
It seems that you may be correct...  However...

Disclaimer:  I am not a Maven expert.

Spring uses servlet-api-2.5 "provided"...  

Titan has:
- rexster-core with servlet-api-3.0.1 "compile"
- hbase with servlet-api-2.5 "compile"
- hbase with jsp-api-2.1 with servlet-api-2.5 "compile"

Since the issue is at runtime, I wonder if the hbase dependency is causing the issue with the "compile" scope.

Tried to change the pom to use servlet-api-3.0.1, but STS reports an issue of not being able to find it.  I then removed the reference and restarted the server: (tc server / tomcat 7).  Now the startup still fails with the error below:

``` stacktrace
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/MvcTitan]]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:618)
    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:650)
    at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1582)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.ClassCastException: com.sun.jersey.server.impl.container.servlet.JerseyServletContainerInitializer cannot be cast to javax.servlet.ServletContainerInitializer
    at org.apache.catalina.startup.ContextConfig.getServletContainerInitializer(ContextConfig.java:1630)
    at org.apache.catalina.startup.ContextConfig.processServletContainerInitializers(ContextConfig.java:1538)
    at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1247)
    at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:855)
    at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:346)
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5173)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    ... 11 more
Jan 2, 2013 11:51:50 AM org.apache.catalina.startup.HostConfig deployDescriptor
SEVERE: Error deploying configuration descriptor /Users/fstrecker/sts3/vfabric-tc-server-developer-2.7.1.RELEASE/spring-insight-instance/conf/Catalina/localhost/MvcTitan.xml
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/MvcTitan]]
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:904)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:618)
    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:650)
    at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1582)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
```

**Comment by devsprint** [comment]
You can try to update the pom.xml and add the titan dependency as follow:

```
<dependency>
            <groupId>com.thinkaurelius.titan</groupId>
            <artifactId>titan</artifactId>
            <version>0.2.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.hbase</groupId>
                    <artifactId>hbase</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.hadoop</groupId>
                    <artifactId>hadoop-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.cassandra</groupId>
                    <artifactId>cassandra-all</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

But, this will let you use only the berkley db storage....

**Comment by friksa** [comment]
Still failing.  We gave up on Titan - so no rush here anymore.  Happy to help resolve this issue though.

``` stacktrace
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/MvcTitan]]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:618)
    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:650)
    at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1582)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.ClassCastException: com.sun.jersey.server.impl.container.servlet.JerseyServletContainerInitializer cannot be cast to javax.servlet.ServletContainerInitializer
    at org.apache.catalina.startup.ContextConfig.getServletContainerInitializer(ContextConfig.java:1630)
    at org.apache.catalina.startup.ContextConfig.processServletContainerInitializers(ContextConfig.java:1538)
    at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1247)
    at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:855)
    at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:346)
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5173)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    ... 11 more
Jan 2, 2013 12:34:19 PM org.apache.catalina.startup.HostConfig deployDescriptor
SEVERE: Error deploying configuration descriptor /Users/fs/sts3/vfabric-tc-server-developer-2.7.1.RELEASE/spring-insight-instance/conf/Catalina/localhost/MvcTitan.xml
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/MvcTitan]]
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:904)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:618)
    at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:650)
    at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1582)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
```

**Comment by devsprint** [comment]
For me it is working just fine. I'm created a new spring-mvc-showcase project and added the dependency as above. Just make sure that you clean the project from STS menu (Project/Clean) and after you are re-deploying the application on server.

**Comment by friksa** [comment]
It must be the version of STS that I am using that is causing the issue now.  I am a little behind as the new version of STS on the Mac has horrible performance.

Thanks for your help.  Please feel free to close this ticket as you found a resolution.  Hopefully it helps others evaluating Titan.

**Comment by devsprint** [comment]
I've continue a little bit the investigation and I was able to make it work with Cassandra back-end, so the dependency should be:

```
<dependency>
            <groupId>com.thinkaurelius.titan</groupId>
            <artifactId>titan</artifactId>
            <version>0.2.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.hbase</groupId>
                    <artifactId>hbase</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.hadoop</groupId>
                    <artifactId>hadoop-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

I'm using STS 3.1.0.RELEASE on Mac OS X 10.8.2 (Java 6 and Java 7), 8 Gb RAM and seems to work ok for my projects (not so much Spring...)

**Comment by friksa** [comment]
Great!  I am on STS 2.9.2.RELEASE... works great until certain Spring refactoring and then everything grinds to a halt.

Waiting for STS 3.2.RELEASE to upgrade.

**Comment by ghost** [comment]
Thank you for posting this issue and making it searchable on Google.  I ran into the same issue, but wanted to share with others the root cause and solution in my case.  My symptom was seeing the same type of error messages.

The newer build of Titan (0.3.x) depends on 'javax.servlet:javax.servlet-api:3.0.1'.  One of the downstream (or transitive) dependencies when using cassandra is 'javax.servlet:servlet-api:2.5' from cassandra-all.  servlet-api 2.5 and 3.0.1 cannot coexist in most containers such as Tomcat or Jersey.

In order to work around this, you must explicitly exclude 'javax.servlet:servlet-api:2.5' from your project.  You may need to check other dependencies to see if they are importing the 2.5 servlet-api inadvertently, as well.

**Comment by RaazTripathi** [comment]
Very helpful post

**Comment by mbroecheler** [comment]
You might also find this article helpful for getting Titan working with Spring:
http://mes-solutions.org/?p=50

**Comment by GuruPrasadP** [comment]
Hi,
Im trying with Spring-boot,able to build the war file but im getting exception in the server startup.

Caused by: java.lang.ClassCastException: Cannot cast org.springframework.web.SpringServletContainerInitializer to javax.servlet.ServletContainerInitializer
    at java.lang.Class.cast(Class.java:3369)
    at org.apache.catalina.startup.WebappServiceLoader.loadServices(WebappServiceLoader.java:182)
    ... 19 more

gone through the forums and added.

```
           <dependency>
        <groupId>javax.servlet</groupId>
        <artifactId>javax.servlet-api</artifactId>
        <version>3.1.0</version>
        <scope>provided</scope>
    </dependency>
```

But this not helpful to me.
can you guide me to resolve this
