### ISSUE TITLE
com.thinkaurelius.titan.diskstorage.locking.PermanentLockingException: Expected value mismatch for KeyColumn [k=0x200-164-214-194- 16-165-160-114-116- 37-111-116-104-101-242, c=0x  0]: expected=[] vs actual=[ 18-112-133] (store=graphindex)

### ISSUE THREAD

**Issue by qingtianfg** [thinkaurelius/titan#1199]
hi ,everyone
        when I use more titanInstance commit vertex,an error happened ,anyone knows the reason please help me ,I would be grateful,below is the error:
Caused by: com.thinkaurelius.titan.diskstorage.locking.PermanentLockingException: Expected value mismatch for KeyColumn [k=0x200-164-214-194- 16-165-160-114-116- 37-111-116-104-101-242, c=0x  0]: expected=[] vs actual=[ 18-112-133](store=graphindex)
    at com.thinkaurelius.titan.diskstorage.locking.consistentkey.ExpectedValueCheckingTransaction.checkSingleExpectedValueUnsafe(ExpectedValueCheckingTransaction.java:272)
    at com.thinkaurelius.titan.diskstorage.locking.consistentkey.ExpectedValueCheckingTransaction.access$000(ExpectedValueCheckingTransaction.java:35)
    at com.thinkaurelius.titan.diskstorage.locking.consistentkey.ExpectedValueCheckingTransaction$1.call(ExpectedValueCheckingTransaction.java:212)
    at com.thinkaurelius.titan.diskstorage.locking.consistentkey.ExpectedValueCheckingTransaction$1.call(ExpectedValueCheckingTransaction.java:209)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:56)
    at com.thinkaurelius.titan.diskstorage.locking.consistentkey.ExpectedValueCheckingTransaction.checkSingleExpectedValue(ExpectedValueCheckingTransaction.java:209)
    at com.thinkaurelius.titan.diskstorage.locking.consistentkey.ExpectedValueCheckingTransaction.checkAllExpectedValues(ExpectedValueCheckingTransaction.java:178)
    at com.thinkaurelius.titan.diskstorage.locking.consistentkey.ExpectedValueCheckingTransaction.prepareForMutations(ExpectedValueCheckingTransaction.java:143)
    at com.thinkaurelius.titan.diskstorage.locking.consistentkey.ExpectedValueCheckingStoreManager.mutateMany(ExpectedValueCheckingStoreManager.java:57)
    at com.thinkaurelius.titan.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:89)
    at com.thinkaurelius.titan.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:86)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:56)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:42)
    ... 25 more

**Comment by spmallette** [comment]
Depending on the context of what you are dong - this locking exceptions are expected.  Typically it just means that you need to retry the transaction.  if transaction retry doesn't eventually allow the transaction to complete, you might have a different problem in which case you should likely bring up your problem with specific reproduction steps on the Aurelius Graphs mailing list:

https://groups.google.com/forum/#!forum/aureliusgraphs
