### ISSUE TITLE
IllegalArgumentException when attempting to run an indexQuery against a composite index.

### ISSUE THREAD

**Issue by steowens** [thinkaurelius/titan#1205]
Aside from the fact that I have no idea what the differences are between a mixed index and a composite index and aside from the fact that I can't create a mixed index without an external backend.  I just want to put exact match keys on properties and retrieve vertexes efficiently by unique key.  But when I run TitanGraph.query() it does not use my indexes, and when I run TitanGraph.indexQuery(...), I get the following exception:

```
java.lang.IllegalArgumentException
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:111)
    at com.thinkaurelius.titan.graphdb.database.IndexSerializer.getMixedIndex(IndexSerializer.java:679)
    at com.thinkaurelius.titan.graphdb.database.IndexSerializer.executeQuery(IndexSerializer.java:603)
    at com.thinkaurelius.titan.graphdb.query.graph.IndexQueryBuilder.execute(IndexQueryBuilder.java:181)
    at com.thinkaurelius.titan.graphdb.query.graph.IndexQueryBuilder.vertices(IndexQueryBuilder.java:200)
    at com.disney.tss.keystone.persistence.titan.UserCrud.getVertex(UserCrud.java:51)
    at com.disney.tss.keystone.persistence.titan.UserCrud.get(UserCrud.java:85)
    at com.disney.tss.keystone.persistence.titan.UserCrud.get(UserCrud.java:1)
    at com.disney.tss.keystone.persistence.titan.UserCrudIntegration.testCreateUpdateAndDelete(UserCrudIntegration.java:37)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

Generated by the following code:

```
private static final MixedIndexType getMixedIndex(String indexName, StandardTitanTx transaction) {
        IndexType index = ManagementSystem.getGraphIndexDirect(indexName, transaction);
        Preconditions.checkArgument(index!=null,"Index with name [%s] is unknown or not configured properly",indexName);
    >>>error here>>>    Preconditions.checkArgument(index.isMixedIndex());
        return (MixedIndexType)index;
    }
```

**Comment by spmallette** [comment]
Seems like you just need a composite index since all you need is a direct unique match:

``` java
TitanManagement mgmt = graph.openManagement();
final PropertyKey name = mgmt.makePropertyKey("name").dataType(String.class).make();
TitanManagement.IndexBuilder nameIndexBuilder = mgmt.buildIndex("name", Vertex.class).addKey(name).unique();
TitanGraphIndex namei = nameIndexBuilder.buildCompositeIndex();
mgmt.setConsistency(namei, ConsistencyModifier.LOCK);
mgmt.commit()
```

I borrowed the above code from `GraphOfTheGodsFactory`:

https://github.com/thinkaurelius/titan/blob/ee226e52415b8bf43b700afac75fa5b9767993a5/titan-core/src/main/java/com/thinkaurelius/titan/example/GraphOfTheGodsFactory.java#L55-L61

If you have more questions about indices you should probably bring them to the aurelius mailing list:

https://groups.google.com/forum/#!forum/aureliusgraphs
