### ISSUE TITLE
Getting Could not instantiate implementation: com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex for 0.5.4 version

### ISSUE THREAD

**Issue by srini-daruna** [thinkaurelius/titan#1249]
I am trying basic java example for titan 0.5.4, in which graph is not being instantiated with the below error.

Exception in thread "main" java.lang.IllegalArgumentException: Could not instantiate implementation: com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex
    at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:55)
    at com.thinkaurelius.titan.diskstorage.Backend.getImplementationClass(Backend.java:421)
    at com.thinkaurelius.titan.diskstorage.Backend.getIndexes(Backend.java:408)
    at com.thinkaurelius.titan.diskstorage.Backend.<init>(Backend.java:139)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1748)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:110)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:93)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:73)
    at com.cdap.spark.TitanTest.main(TitanTest.java:24)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:44)
    ... 8 more
Caused by: java.lang.ExceptionInInitializerError
    at org.apache.log4j.Logger.getLogger(Logger.java:40)
    at org.elasticsearch.common.logging.log4j.Log4jESLoggerFactory.newInstance(Log4jESLoggerFactory.java:39)
    at org.elasticsearch.common.logging.ESLoggerFactory.getLogger(ESLoggerFactory.java:62)
    at org.elasticsearch.common.logging.Loggers.getLogger(Loggers.java:147)
    at org.elasticsearch.common.logging.Loggers.getLogger(Loggers.java:110)
    at org.elasticsearch.common.logging.Loggers.getLogger(Loggers.java:84)
    at org.elasticsearch.common.component.AbstractComponent.<init>(AbstractComponent.java:38)
    at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:88)
    at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:166)
    at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:125)
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.legacyConfiguration(ElasticSearchIndex.java:328)
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.<init>(ElasticSearchIndex.java:171)
    ... 13 more

Code:

import org.apache.commons.configuration.BaseConfiguration;

import com.thinkaurelius.titan.core.TitanFactory;
import com.thinkaurelius.titan.core.TitanGraph;
import com.tinkerpop.blueprints.Vertex;

public class TitanTest {

```
public static void main(String...strings){
    BaseConfiguration conf = new BaseConfiguration();

    TitanGraph g = TitanFactory.open(conf);

    Vertex v1 = g.addVertex("sri1");
    Vertex v2 = g.addVertex("sri2");

    v1.addEdge("knows", v2);
    g.commit();

}
```

}

**Comment by spmallette** [comment]
Please use the mailing list for these types of questions:

https://groups.google.com/forum/#!forum/aureliusgraphs

As for your question, it's very odd that you would get the error you are getting about ES.  You are supplying a completely empty `Configuration` object to `TitanFactory.open()`.  I would have expected a different error.  If you are just getting started, I suggest that you use Titan 1.0 (thus TinkerPop 3.x).  I also recommend reading the TinkerPop [Getting Started Tutorial](http://tinkerpop.apache.org/docs/3.1.0-incubating/tutorials-getting-started.html).
