### ISSUE TITLE
DSE issue 

### ISSUE THREAD

**Issue by akash3456** [thinkaurelius/titan#1272]
I am unable to start the solr aspect of DSE search and i get the following exception message when i execute, when i execute bin/dse cassandra start the cassandra service is started but not solr, does anyone have any guidance to offer me i know i have missed something:

bin/dse cassandra -s

message:
     ```
Cannot start node if snitch's data center (Solr) differs from previous data center (Cassandra). Please fix the snitch configuration, decommission and rebootstrap this node or use the flag -Dcassandra.ignore_dc=true.
    at org.apache.cassandra.db.SystemKeyspace.checkHealth(SystemKeyspace.java:629) ~[cassandra-all-2.1.12.1046.jar:2.1.12.1046]
    at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:290) [cassandra-all-2.1.12.1046.jar:2.1.12.1046]
    at com.datastax.bdp.server.DseDaemon.setup(DseDaemon.java:329) [dse-4.7.7.jar:4.7.7]
    at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:564) [cassandra-all-2.1.12.1046.jar:2.1.12.1046]
    at com.datastax.bdp.DseModule.main(DseModule.java:75) [dse-4.7.7.jar:4.7.7]

**Comment by ghost** [comment]
Can you provide version information on DSE and the Solr support in that version ?

**Comment by akash3456** [comment]
4.7.7 its not a problem now i have managed to clear out the
data_directories thanks for getting back to me.
