### ISSUE TITLE
Random shutdown of ElasticSearch using cassandra-es

### ISSUE THREAD

**Issue by dmill-bz** [thinkaurelius/titan#1286]
_Concerns `titan11` branch._

I'm getting failures in my application tests because it seems like ES is just shutting down at random. This concerns `cassandra-es` only for the moment. `berkeleyje-es` seems to works just fine. 

To give a bit of context, there are about 300 tests. All of which remove fixtures, add fixtures, run, then remove fixtures again from a graph created at startup. Usually each fixture contains < 100 elements. All the tests send queries to the server synchronously (each query waits for the server to respond to the previous query) and writes are all contained in transactions. 

Bellow is the `gremlin-server` error I get. Once I get this error all following tests (because I'm guessing calls to ES) fail.  Also worth noting that this particular failure occurs on `ContentOnFile` but it could be any other index (and all of these indexes work fine until the failure)

```
314374 [pool-59-thread-1] ERROR com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex  - Failed to execute ES query ElasticsearchIllegalArgumentException[failed to execute script]; nested: ScriptException[dynamic scripting for [groovy] disabled]; 
314375 [pool-59-thread-1] ERROR com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex  - Failed to execute ES query 1m
java.lang.Exception: failure in bulk execution:
[0]: index [titan], type [ContentOnFile], id [5cug], message [ElasticsearchIllegalArgumentException[failed to execute script]; nested: ScriptException[dynamic scripting for [groovy] disabled]; ]
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.mutate(ElasticSearchIndex.java:614)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:123)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:120)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:56)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:42)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.flushInternal(IndexTransaction.java:120)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.commit(IndexTransaction.java:101)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction.commitIndexes(BackendTransaction.java:125)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.commit(StandardTitanGraph.java:732)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.commit(StandardTitanTx.java:1352)
    at com.thinkaurelius.titan.graphdb.tinkerpop.TitanBlueprintsGraph$GraphTransaction.doCommit(TitanBlueprintsGraph.java:263)
    at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.commit(AbstractTransaction.java:105)
    at org.apache.tinkerpop.gremlin.structure.Transaction$commit$1.call(Unknown Source)
    at Script4.run(Script4.groovy:1)
    at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:534)
    at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:374)
    at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
    at org.apache.tinkerpop.gremlin.groovy.engine.ScriptEngines.eval(ScriptEngines.java:102)
    at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:258)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
314378 [pool-59-thread-1] ERROR com.thinkaurelius.titan.graphdb.database.StandardTitanGraph  - Error while commiting index mutations for transaction [89] on index: search
com.thinkaurelius.titan.core.TitanException: Could not execute operation due to backend exception
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:44)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.flushInternal(IndexTransaction.java:120)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.commit(IndexTransaction.java:101)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction.commitIndexes(BackendTransaction.java:125)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.commit(StandardTitanGraph.java:732)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.commit(StandardTitanTx.java:1352)
    at com.thinkaurelius.titan.graphdb.tinkerpop.TitanBlueprintsGraph$GraphTransaction.doCommit(TitanBlueprintsGraph.java:263)
    at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.commit(AbstractTransaction.java:105)
    at org.apache.tinkerpop.gremlin.structure.Transaction$commit$1.call(Unknown Source)
    at Script4.run(Script4.groovy:1)
    at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:534)
    at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:374)
    at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
    at org.apache.tinkerpop.gremlin.groovy.engine.ScriptEngines.eval(ScriptEngines.java:102)
    at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:258)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.thinkaurelius.titan.diskstorage.PermanentBackendException: Unknown exception while executing index operation
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.convert(ElasticSearchIndex.java:368)
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.mutate(ElasticSearchIndex.java:620)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:123)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:120)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:56)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:42)
    ... 18 more
Caused by: java.lang.Exception: failure in bulk execution:
[0]: index [titan], type [ContentOnFile], id [5cug], message [ElasticsearchIllegalArgumentException[failed to execute script]; nested: ScriptException[dynamic scripting for [groovy] disabled]; ]
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.mutate(ElasticSearchIndex.java:614)
    ... 22 more
```

And bellow I've included the complete **elasticsearch.log**. As you can see about 45mn into the tests ES seems to stop. This happens at random (no tests or suits in particular), and can start as early as 10-15mn in.

```
[2016-03-20 09:09:06,519][INFO ][node                     ] [Nathaniel Richards] version[1.5.1], pid[1814], build[5e38401/2015-04-09T13:41:35Z]
[2016-03-20 09:09:06,521][INFO ][node                     ] [Nathaniel Richards] initializing ...
[2016-03-20 09:09:06,586][INFO ][plugins                  ] [Nathaniel Richards] loaded [], sites []
[2016-03-20 09:09:15,615][INFO ][node                     ] [Nathaniel Richards] initialized
[2016-03-20 09:09:15,623][INFO ][node                     ] [Nathaniel Richards] starting ...
[2016-03-20 09:09:16,080][INFO ][transport                ] [Nathaniel Richards] bound_address {inet[/127.0.0.1:9300]}, publish_address {inet[/127.0.0.1:9300]}
[2016-03-20 09:09:16,160][INFO ][discovery                ] [Nathaniel Richards] elasticsearch/S1pulRMsRxCW75QqmRTGRA
[2016-03-20 09:09:20,143][INFO ][cluster.service          ] [Nathaniel Richards] new_master [Nathaniel Richards][S1pulRMsRxCW75QqmRTGRA][ubuntu][inet[/127.0.0.1:9300]], reason: zen-disco-join (elected_as_master)
[2016-03-20 09:09:20,572][INFO ][http                     ] [Nathaniel Richards] bound_address {inet[/127.0.0.1:9200]}, publish_address {inet[/127.0.0.1:9200]}
[2016-03-20 09:09:20,575][INFO ][node                     ] [Nathaniel Richards] started
[2016-03-20 09:09:20,651][INFO ][gateway                  ] [Nathaniel Richards] recovered [0] indices into cluster_state
[2016-03-20 09:09:33,926][INFO ][cluster.metadata         ] [Nathaniel Richards] [titan] creating index, cause [api], templates [], shards [5]/[1], mappings []
[2016-03-20 09:10:59,806][INFO ][cluster.metadata         ] [Nathaniel Richards] [titan] create_mapping [ContentOnMeta]
[2016-03-20 09:11:05,972][INFO ][cluster.metadata         ] [Nathaniel Richards] [titan] create_mapping [UsernameOnUserMixed]
[2016-03-20 09:11:07,664][INFO ][cluster.metadata         ] [Nathaniel Richards] [titan] create_mapping [EmailOnUserMixed]
[2016-03-20 09:11:09,190][INFO ][cluster.metadata         ] [Nathaniel Richards] [titan] create_mapping [FirstnameOnUser]
[2016-03-20 09:11:10,691][INFO ][cluster.metadata         ] [Nathaniel Richards] [titan] create_mapping [LastnameOnUser]
[2016-03-20 09:11:12,983][INFO ][cluster.metadata         ] [Nathaniel Richards] [titan] create_mapping [createdatOnUser]
[2016-03-20 09:11:14,128][INFO ][cluster.metadata         ] [Nathaniel Richards] [titan] create_mapping [updatedatOnUser]
[2016-03-20 09:11:42,105][INFO ][cluster.metadata         ] [Nathaniel Richards] [titan] create_mapping [nameOnTagMixed]
[2016-03-20 09:11:54,104][INFO ][cluster.metadata         ] [Nathaniel Richards] [titan] create_mapping [ContentOnFile]
[2016-03-20 09:11:56,166][INFO ][cluster.metadata         ] [Nathaniel Richards] [titan] create_mapping [ExpiringOnNodeMixed]
[2016-03-20 09:57:57,358][INFO ][node                     ] [Nathaniel Richards] stopping ...
[2016-03-20 09:57:57,446][INFO ][node                     ] [Nathaniel Richards] stopped
[2016-03-20 09:57:57,447][INFO ][node                     ] [Nathaniel Richards] closing ...
[2016-03-20 09:57:57,460][INFO ][node                     ] [Nathaniel Richards] closed
```

I guess my first question here would be : Is it possible to make the logging more verbose?

**Comment by dmill-bz** [comment]
To add to this. Once this occurs if I stop titan and start it again it will just hang. The only way I can get it running again is by erasing the `db/` folder which is kinda catastrophic.

Here's the message it hangs on : 

```
13:30:30.277 [PendingRangeCalculator:1] DEBUG o.a.c.s.PendingRangeCalculatorService - No bootstrapping, leaving or moving nodes, and no relocating tokens -> empty pending ranges for titan
13:30:30.277 [PendingRangeCalculator:1] DEBUG o.a.c.s.PendingRangeCalculatorService - No bootstrapping, leaving or moving nodes, and no relocating tokens -> empty pending ranges for system_traces
13:30:30.277 [PendingRangeCalculator:1] DEBUG o.a.c.s.PendingRangeCalculatorService - finished calculation for 2 keyspaces in 21ms
13:30:30.298 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
13:30:30.348 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
13:30:30.348 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
13:30:30.349 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
13:30:30.349 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: true
13:30:30.351 [main] DEBUG i.n.util.internal.PlatformDependent - Java version: 8
13:30:30.351 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
13:30:30.352 [main] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
13:30:30.352 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
13:30:30.520 [main] DEBUG i.n.util.internal.PlatformDependent - Javassist: available
13:30:30.521 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
13:30:30.521 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
13:30:30.521 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
```

Note that I get a lot of ReplayPosition entries in my log.

I've actually managed to make it go through with bootup by start/stopping it a few times but : graphs are empty, yet some indexes remain (ie I can't create new vertices with properties that were set in a previous run because they still exist in ES, even though the vertices don't exist when I `g.V()`).

This is a lot like the non consistent behavior I had initially between cassandra and es in my random issues in https://github.com/thinkaurelius/titan/issues/1113
