### ISSUE TITLE
Hbase-es configuration fails with ElasticSearch error

### ISSUE THREAD

**Issue by lindsayismith** [thinkaurelius/titan#1287]
The startup guide says to use the titan-hbase-es.properties file to start Titan against hbase.

This configuration fails relating to ElasticSearch:  

Could not instantiate implementation: com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex
Display stack trace? [yN] y
...
Caused by: org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []

I've tried changing the conf properties to disable elastic search in the same way as the berkley db file, but the issue remains

Is having a separate elasticsearch service running a prerequisite for using hbase?

**Comment by pluradj** [comment]
You should be able to find the `titan-hbase.properties` file in the Titan zip file. It does not attempt to use Elasticsearch as an external indexing backend. Drop the `titan` table in HBase from your failed attempt, then try connecting with `titan-hbase.properties`.

**Comment by lindsayismith** [comment]
Thank you, removing the titan table from HBase meant that I could now run this:

g = TitanFactory.open('conf/titan-hbase.properties')

However, now when I run the next step:

GraphOfTheGodsFactory.load(g)

I get an exception relating to the search backend:

```
java.lang.IllegalArgumentException: Unknown external index backend: search
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
        at com.thinkaurelius.titan.graphdb.database.management.ManagementSystem.createMixedIndex(ManagementSystem.j
ava:478)
        at com.thinkaurelius.titan.graphdb.database.management.ManagementSystem.access$400(ManagementSystem.java:10
9)
        at com.thinkaurelius.titan.graphdb.database.management.ManagementSystem$IndexBuilder.buildMixedIndex(Manage
mentSystem.java:642)
        at com.thinkaurelius.titan.example.GraphOfTheGodsFactory.load(GraphOfTheGodsFactory.java:66)
        at com.thinkaurelius.titan.example.GraphOfTheGodsFactory.load(GraphOfTheGodsFactory.java:51)
        at com.thinkaurelius.titan.example.GraphOfTheGodsFactory$load.call(Unknown Source)
        ....
```

Which suggests that I do need a search backend configured.  Or is there something else I can do to fix this?

**Comment by pluradj** [comment]
Try `GraphOfTheGodsFactory.loadWithoutMixedIndex(graph, true)`

https://github.com/thinkaurelius/titan/blob/1.0.0/titan-core/src/main/java/com/thinkaurelius/titan/example/GraphOfTheGodsFactory.java#L46

**Comment by lindsayismith** [comment]
Thanks, this works!
