### ISSUE TITLE
Errors when trying to connect to Cassandra backend with Titan 0.5.4

### ISSUE THREAD

**Issue by wangao1236** [thinkaurelius/titan#1298]
I start a titan server on a machine, and it works:

```
root@bd49:~/wangao/titan-0.5.4-hadoop2# ./bin/titan.sh -c cassandra-es start
Forking Cassandra...
Running `nodetool statusthrift`... OK (returned exit status 0 and printed string "running").
Forking Elasticsearch...
Connecting to Elasticsearch (127.0.0.1:9300)... OK (connected to 127.0.0.1:9300).
Forking Titan + Rexster...
Connecting to Titan + Rexster (127.0.0.1:8184).... OK (connected to 127.0.0.1:8184).
Run rexster-console.sh to connect.
root@bd49:~/wangao/titan-0.5.4-hadoop2# ./bin/gremlin.sh        

         \,,,/
         (o o)
-----oOOo-(_)-oOOo-----
00:22:50 WARN  org.apache.hadoop.util.NativeCodeLoader  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
gremlin> g = TitanFactory.open("conf/titan-cassandra-es.properties")
00:22:54 WARN  com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration  - Local setting cache.db-cache-clean-wait=20 (Type: GLOBAL_OFFLINE) is overridden by globally managed value (50).  Use the ManagementSystem interface instead of the local configuration to control this setting.
00:22:54 WARN  com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration  - Local setting cache.db-cache-time=180000 (Type: GLOBAL_OFFLINE) is overridden by globally managed value (10000).  Use the ManagementSystem interface instead of the local configuration to control this setting.
==>titangraph[cassandrathrift:[127.0.0.1]]
```

And I work to bulk load a large graph, so I use java api to connect the server, but it has exceptions:

```
root@bd49:~/wangao# java -jar titanconnection.jar 
Hello World!
org.apache.commons.configuration.BaseConfiguration@4459eb14
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.IllegalArgumentException: Could not instantiate implementation: com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftStoreManager
    at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:55)
    at com.thinkaurelius.titan.diskstorage.Backend.getImplementationClass(Backend.java:421)
    at com.thinkaurelius.titan.diskstorage.Backend.getStorageManager(Backend.java:361)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1275)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:93)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:73)
    at gov.ornl.stucco.TitanInsertDataClient.TitanConnection.BuildGraph(TitanConnection.java:20)
    at gov.ornl.stucco.TitanInsertDataClient.App.main(App.java:13)
    ... 5 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:44)
    ... 12 more
Caused by: com.thinkaurelius.titan.diskstorage.TemporaryBackendException: Temporary failure in storage backend
    at com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftStoreManager.getCassandraPartitioner(CassandraThriftStoreManager.java:218)
    at com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftStoreManager.<init>(CassandraThriftStoreManager.java:196)
    ... 17 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.SocketTimeoutException: Read timed out
    at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:129)
    at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
    at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:129)
    at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101)
    at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
    at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:362)
    at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:284)
    at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:191)
    at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
    at org.apache.cassandra.thrift.Cassandra$Client.recv_set_keyspace(Cassandra.java:599)
    at org.apache.cassandra.thrift.Cassandra$Client.set_keyspace(Cassandra.java:586)
    at com.thinkaurelius.titan.diskstorage.cassandra.thrift.thriftpool.CTConnectionFactory.makeObject(CTConnectionFactory.java:54)
    at com.thinkaurelius.titan.diskstorage.cassandra.thrift.thriftpool.CTConnectionFactory.makeObject(CTConnectionFactory.java:21)
    at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220)
    at com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftStoreManager.getCassandraPartitioner(CassandraThriftStoreManager.java:215)
    ... 18 more
Caused by: java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:170)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
    at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
    ... 32 more

```

And my code is:

```
package gov.ornl.stucco.TitanInsertDataClient;

import com.thinkaurelius.titan.core.TitanFactory;
import com.thinkaurelius.titan.core.TitanGraph;
import com.thinkaurelius.titan.core.attribute.Geoshape;
import com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration;
import com.tinkerpop.blueprints.Edge;
import com.tinkerpop.blueprints.Vertex;
import com.tinkerpop.blueprints.util.ElementHelper;
import org.apache.commons.configuration.BaseConfiguration;
import org.apache.commons.configuration.Configuration;

import java.io.File;

public class TitanConnection {
    public final String INDEX_NAME = "search";
    public String myConfig = "myTitanConfig.yaml";

    public void BuildGraph(Configuration conf) {
        TitanGraph graph = TitanFactory.open(conf);
    }

    public Configuration dbConfigFromFile(String configFilePath){
        /*File configFile = new File(configFilePath);
        Map<String, Object> fullConfigMap = configMapFromFile(configFile);
        Map<String, Object> dbConfigMap = (Map<String, Object>) fullConfigMap.get("database_connection");
        */
        //PropertiesConfiguration dbConfig = new PropertiesConfiguration();
        /*
        for(String key : dbConfigMap.keySet()){
            dbConfig.addProperty( key, dbConfigMap.get(key));
        }
        */
        Configuration conf = new BaseConfiguration();
        conf.setProperty("storage.backend","cassandrathrift");
        conf.setProperty("storage.hostname","127.0.0.1");
        conf.setProperty("storage.port", "9042");
        conf.setProperty("cache.db-cache","true");
        conf.setProperty("cache.db-cache-clean-wait","20");
        conf.setProperty("cache.db-cache-time","180000");
        conf.setProperty("cache.db-cache-size","0.25");
        conf.setProperty("index.search.backend","elasticsearch");
        conf.setProperty("index.search.hostname","127.0.0.1");
        conf.setProperty("index.search.elasticsearch.client-only","true");
        System.out.println(conf.toString());
        return conf;
    }

}
```

So why my java client doesn't work?

**Comment by pluradj** [comment]
Titan uses Thrift to communicate with Cassandra, and the Thrift port is typically `9160`. Check the `rpc_port` in the `cassandra.yaml`.

**Comment by spmallette** [comment]
Thanks for answering @pluradj  

@wangao1236 in the future, please use the mailing list for questions that involve usage: https://groups.google.com/forum/#!forum/aureliusgraphs - thanks

**Comment by wangao1236** [comment]
OK, it works. Thank you very much!! @pluradj

**Comment by ketan582** [comment]
Hi, I was trying to run Janusgraph with cassandra on my local machine server, and I am getting the same error. The rpc_port in the yaml file is set to 9160. I am using scala. My configuration setting is:

     val conf = new BaseConfiguration()


      conf.setProperty("storage.backend", "cassandrathrift")
      conf.setProperty("storage.hostname", "127.0.0.1")
      conf.setProperty("index.search.backend","elasticsearch")
      conf.setProperty("index.search.hostname", "127.0.0.1")

      val gr = JanusGraphFactory.open(conf)

**Comment by gayad** [comment]
@ketan582   in cassandra.yaml (cassandra configuration file in the conf directory), make sure that you have:
_start_rpc: true_
because it's set to _false_ by default. So it's not enough to make sure of the port, you also have to make sure the thrift rpc server will start. Then you have to re-run the cassandra.bat. I had the same problem and not it works well.
