### ISSUE TITLE
ClassCastException in TitanPropertiesStep.flatMap

### ISSUE THREAD

**Issue by jnhagelberg** [thinkaurelius/titan#1303]
Titan Version: 1.0.0

When running certain gremlin queries, we encounter the ClassCastException shown below.  This seems to happen in any queries that use a select with a by() clause that uses "__".  The stack trace below is from this query:

`g.V().where(has("hive_db.name", eq("Reporting"))).as("_src1","_src2").select("_src1","_src2").by(__."hive_db.name").by(__."hive_db.createTime" + 1).toList()
`
I've also seen a similar ClassCastException (for HashMap, instead of Long) for queries like this:

`g.V().as("a").select("a").by(__).toList()`

Stack Trace:

```
Caused by: javax.script.ScriptException: java.lang.ClassCastException: java.lang.Long cannot be cast to org.apache.tinkerpop.gremlin.structure.Element

    at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:527)
    at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:365)
    ... 35 more

Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to org.apache.tinkerpop.gremlin.structure.Element
    at com.thinkaurelius.titan.graphdb.tinkerpop.optimize.TitanPropertiesStep.flatMap(TitanPropertiesStep.java:109)
    at org.apache.tinkerpop.gremlin.process.traversal.step.map.FlatMapStep.processNextStart(FlatMapStep.java:47)
    at com.thinkaurelius.titan.graphdb.tinkerpop.optimize.TitanPropertiesStep.processNextStart(TitanPropertiesStep.java:93)
    at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:126)
    at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:37)
    at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:127)
    at org.apache.tinkerpop.gremlin.process.traversal.util.TraversalUtil.apply(TraversalUtil.java:93)
    at org.apache.tinkerpop.gremlin.process.traversal.step.map.SelectStep.map(SelectStep.java:66)
    at org.apache.tinkerpop.gremlin.process.traversal.step.map.SelectStep.map(SelectStep.java:44)
    at org.apache.tinkerpop.gremlin.process.traversal.step.map.MapStep.processNextStart(MapStep.java:37)
    at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:126)
    at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:37)
    at org.apache.tinkerpop.gremlin.process.traversal.Traversal.fill(Traversal.java:145)
    at org.apache.tinkerpop.gremlin.process.traversal.Traversal.toList(Traversal.java:102)
    at org.apache.tinkerpop.gremlin.process.traversal.Traversal$toList.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114)
    at Script1.run(Script1.groovy:1)
    at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:525)
```

**Comment by jnhagelberg** [comment]
It's looking like this might be an issue with the query.  Closing for now.  I'll reopen this if I see the issue again.
