### ISSUE TITLE
Test failure: ExpirationCacheTest.testGracePeriod

### ISSUE THREAD

**Issue by leifurhauks** [thinkaurelius/titan#1311]
Building the `titan11` branch with maven, I encountered an assertion failure [here](https://github.com/thinkaurelius/titan/blob/titan10/titan-test/src/test/java/com/thinkaurelius/titan/diskstorage/cache/ExpirationCacheTest.java#L133):

```
java.lang.AssertionError: expected:<0> but was:<1>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at com.thinkaurelius.titan.diskstorage.cache.ExpirationCacheTest.testGracePeriod(ExpirationCacheTest.java:133)
    at com.thinkaurelius.titan.diskstorage.cache.ExpirationCacheTest.testGracePeriod(ExpirationCacheTest.java:91)
```

This was on linux x86_64 with Oracle JDK8.

**Comment by leifurhauks** [comment]
This doesn't always fail, I'm not sure how to reproduce reliably.
