### ISSUE TITLE
NPE on Match step using query.batch=true and Cassandra backend

### ISSUE THREAD

**Issue by alinazemian** [thinkaurelius/titan#1325]
Hi,
I have got NPE on using match() step when query.batch is true. My query is as follows:

```
g.V().has('vertex_label','post').match(
__.as(NodeLabels.POST.toTitanString()).out(EdgeLabels.ATTACHED.toTitanString()).has(MediaAttributes.SRC.toTitanString()).count()
.as(TitanParameters.MEDIA_COUNT),
__.as(NodeLabels.POST.toTitanString()).out(EdgeLabels.ATTACHED.toTitanString()).has(MediaAttributes.URL.toTitanString()).count()
.as(TitanParameters.LINKS_COUNT),
__.as(NodeLabels.POST.toTitanString()).in(EdgeLabels.HAS_POST.toTitanString())
.has(TitanSpecificAttributes.VERTEX_LABEL.toTitanString(), entityTypeCondition.getValues().get(0).getValue())

.as(TitanParameters.ENTITY))
.select(TitanParameters.ENTITY, NodeLabels.POST.toTitanString(), TitanParameters.MEDIA_COUNT, TitanParameters.LINKS_COUNT);
```

And the NPE stack trace:

```
java.lang.NullPointerException
        at com.thinkaurelius.titan.graphdb.tinkerpop.optimize.TitanVertexStep.flatMap(TitanVertexStep.java:95)
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.FlatMapStep.processNextStart(FlatMapStep.java:47)
        at com.thinkaurelius.titan.graphdb.tinkerpop.optimize.TitanVertexStep.processNextStart(TitanVertexStep.java:88)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:140)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:54)
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.MatchStep$MatchEndStep.processNextStart(MatchStep.java:444)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:140)
        at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:117)
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.MatchStep.standardAlgorithm(MatchStep.java:305)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.ComputerAwareStep.processNextStart(ComputerAwareStep.java:47)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:140)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:54)
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.MapStep.processNextStart(MapStep.java:36)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:140)
        at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:117)
        at org.apache.tinkerpop.gremlin.console.Console$_closure3.doCall(Console.groovy:182)
        at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at org.codehaus.groovy.tools.shell.Groovysh.setLastResult(Groovysh.groovy:441)
        at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:185)
        at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:119)
        at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:94)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
        at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:130)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:150)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:123)
        at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:58)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:130)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:150)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:82)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:215)
        at org.apache.tinkerpop.gremlin.console.Console.<init>(Console.groovy:144)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:215)
        at org.ap

```

**Comment by dkuppitz** [comment]
I have a suspicion that this could be related to https://issues.apache.org/jira/browse/TINKERPOP-1335.

**Comment by alinazemian** [comment]
@dkuppitz I am not sure. what about this issue: 
https://github.com/thinkaurelius/titan/issues/1169

**Comment by dkuppitz** [comment]
Dunno, I'm not familiar with the Titan code base, but I just recently discovered this match()/select() bug in TinkerPop and since your query matches the problematic query pattern, I thought it's worth to reference the TP ticket here.

**Comment by alinazemian** [comment]
@dkuppitz I have checked the Titan code and it seems the first vertex is just loaded into multiQueryResults. Since this query works in query.batch=false mode I am suspicious about the Titan core not the TP part.

**Comment by dkuppitz** [comment]
Ok, great, that's good to know.

**Comment by alinazemian** [comment]
Is there any help regarding this issue?
