### ISSUE TITLE
HBaseDistributedStoreManagerTest test-case failing in Ubuntu 16.04

### ISSUE THREAD

**Issue by srikanthgunduboyina** [thinkaurelius/titan#1358]
Hi All,

I am trying run the Titan DB build and automated tests on an ubuntu 16.04 VM ppc64le and for the module titan-hbase-parent, test case HBaseDistributedStoreManagerTest is failing with following errors:
Tests in error:
  HBaseDistributedStoreManagerTest.setUp:35 » Titan Exception in Titan
  HBaseDistributedStoreManagerTest.tearDown:40 NullPointer
  HBaseDistributedStoreManagerTest.setUp:35 » Titan Exception in Titan
  HBaseDistributedStoreManagerTest.tearDown:40 NullPointer
  HBaseIDAuthorityTest>IDAuthorityTest.setUp:116 » Titan Exception in Titan
  HBaseIDAuthorityTest>IDAuthorityTest.tearDown:150->IDAuthorityTest.close:155 » NullPointer
  HBaseIDAuthorityTest>IDAuthorityTest.setUp:116 » Titan Exception in Titan
  HBaseIDAuthorityTest>IDAuthorityTest.tearDown:150->IDAuthorityTest.close:155 » NullPointer

Tests run: 166, Failures: 0, Errors: 8, Skipped: 0

When I have checked the console log, I am getting this message:
Running com.thinkaurelius.titan.diskstorage.hbase.HBaseDistributedStoreManagerTest
2016-11-08 19:49:04.593 [main] ERROR client.HConnectionManager$HConnectionImplementation: Check the value configured in 'zookeeper.znode.parent'. There could be a mismatch with the one configured in the master.
2016-11-08 19:49:04.595 [main] WARN  hbase.HBaseStoreManager: Unexpected exception during getDeployment()
com.thinkaurelius.titan.core.TitanException: Exception in Titan
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.getAdminInterface(HBaseStoreManager.java:962)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.ensureTableExists(HBaseStoreManager.java:747)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.getLocalKeyPartition(HBaseStoreManager.java:556)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.getDeployment(HBaseStoreManager.java:347)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.getFeatures(HBaseStoreManager.java:389)
        at com.thinkaurelius.titan.diskstorage.common.AbstractStoreManager.getMetaDataSchema(AbstractStoreManager.java:44)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseKeyColumnValueStore.<init>(HBaseKeyColumnValueStore.java:67)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.openDatabase(HBaseStoreManager.java:446)
        at com.thinkaurelius.titan.diskstorage.keycolumnvalue.KeyColumnValueStoreManager.openDatabase(KeyColumnValueStoreManager.java:29)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseDistributedStoreManagerTest.setUp(HBaseDistributedStoreManagerTest.java:35)
Caused by: org.apache.hadoop.hbase.MasterNotRunningException: Check the value configured in 'zookeeper.znode.parent'. There could be a mismatch with the one configured in the master.
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.checkIfBaseNodeAvailable(HConnectionManager.java:853)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getMaster(HConnectionManager.java:787)
        at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:177)
        at com.thinkaurelius.titan.diskstorage.hbase.HConnection0_94.getAdmin(HConnection0_94.java:27)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.getAdminInterface(HBaseStoreManager.java:960)
        ... 46 more
I checked for hbase-site.xml in the <titandb-codebase>/titan-hbase-parent/common/test/conf/hbase-site.xml and added the following configuration:
<property>
        <name>zookeeper.znode.parent</name>
        <value>/hbase</value>
 </property>
and this too didn't work for me.
Steps I followed were:
git clone https://github.com/thinkaurelius/titan && cd titan
git checkout 1.0.0
export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
mvn install
I am doing this build in Ubuntu 16.04 ppc64le. Please help me in resolving this issue.

Thanks,
Srikanth. G

**Comment by pluradj** [comment]
Sorry to say, there aren't many developers in this community with access to a `ppc64le` machine. Is this also a problem on Ubuntu 16.04 on `amd64` with `java-1.8.0-openjdk`?

**Comment by srikanthgunduboyina** [comment]
Thanks for your response @pluradj .
Actually I have checked  the same on rhel 7.2 ppc64le and all test cases were passing. But on Ubuntu 16.04 I  am seeing this issue. When ever I run the HBaseDistributedStoreManagerTest  test case, I getting this error:
**ERROR client.HConnectionManager$HConnectionImplementation: Check the value configured in 'zookeeper.znode.parent'. There could be a mismatch with the one configured in the master.**
Do I need to set anything in hbase-site.xml or any other configuration files.
I see the same test case fails in titan-hbase-094, titan-hbase-096 and titan-hbase-098 of titan-hbase-parent.
Please let me know if I am missing any configuration changes and please let me know when we generally get **Check the value configured in 'zookeeper.znode.parent'. There could be a mismatch with the one configured in the master.** this error.

Thanks in Advance.

**Comment by pluradj** [comment]
I don't think there shouldn't be any configuration changes required. The code should work the same way on RHEL vs Ubuntu.

Is the stack trace above the complete stack trace including nested exceptions?

What version of the Titan code are you compiling? What command are you issuing to start the build?

**Comment by srikanthgunduboyina** [comment]
Thanks pluradj.
I am working on titan 1.0.0 release. Verified on Ubuntu 16.04 amd64 and getting the same error:
Here is the complete trace of failure on amd64:
Running com.thinkaurelius.titan.diskstorage.hbase.HBaseIDAuthorityTest
2016-11-14 21:12:46.427 [main] ERROR client.HConnectionManager$HConnectionImplementation: Check the value configured in 'zookeeper.znode.parent'. There could be a mismatch with the one configured in the master.
Tests run: 19, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 465.195 sec <<< FAILURE! - in com.thinkaurelius.titan.diskstorage.hbase.HBaseIDAuthorityTest
testManyThreadsOneIDAuthority[0](com.thinkaurelius.titan.diskstorage.hbase.HBaseIDAuthorityTest)  Time elapsed: 0.443 sec  <<< ERROR!
com.thinkaurelius.titan.core.TitanException: Exception in Titan
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.getAdminInterface(HBaseStoreManager.java:962)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.clearStorage(HBaseStoreManager.java:482)
        at com.thinkaurelius.titan.diskstorage.IDAuthorityTest.setUp(IDAuthorityTest.java:116)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
         at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createReqestAndRun(JUnitCoreWrapper.java:139)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:111)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:84)
        at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:135)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: org.apache.hadoop.hbase.MasterNotRunningException: Check the value configured in 'zookeeper.znode.parent'. There could be a mismatch with the one configured in the master.
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.checkIfBaseNodeAvailable(HConnectionManager.java:853)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getMaster(HConnectionManager.java:787)
        at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:177)
        at com.thinkaurelius.titan.diskstorage.hbase.HConnection0_94.getAdmin(HConnection0_94.java:27)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.getAdminInterface(HBaseStoreManager.java:960)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.clearStorage(HBaseStoreManager.java:482)
        at com.thinkaurelius.titan.diskstorage.IDAuthorityTest.setUp(IDAuthorityTest.java:116)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
       at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createReqestAndRun(JUnitCoreWrapper.java:139)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:111)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:84)
        at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:135)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Thanks.

**Comment by pluradj** [comment]
Worked ok for me. Sounds like some sort of environmental issue on your end.

Here's the environment and results:

```
$ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /usr/lib/apache-maven-3.3.9
Java version: 1.8.0_111, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-47-generic", arch: "amd64", family: "unix"

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:    16.04
Codename:   xenial

$ mvn clean install -Paurelius-release -DskipTests=true -Dgpg.skip=true
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Titan: Distributed Graph Database .................. SUCCESS [  0.955 s]
[INFO] Titan-Core: Core Library for Titan ................. SUCCESS [ 13.233 s]
[INFO] Titan-Test: Test Suite for Titan ................... SUCCESS [  5.879 s]
[INFO] Titan-BerkeleyJE: Distributed Graph Database ....... SUCCESS [  1.418 s]
[INFO] Titan-Cassandra: Distributed Graph Database ........ SUCCESS [  2.858 s]
[INFO] Titan-ElasticSearch: Distributed Indexing Support .. SUCCESS [  2.424 s]
[INFO] Titan-HBase: Parent Module ......................... SUCCESS [  0.522 s]
[INFO] Titan-HBase: Version-independent Core .............. SUCCESS [  3.060 s]
[INFO] Titan-HBase: 0.94 Compatibility Shim ............... SUCCESS [  1.992 s]
[INFO] Titan-HBase: 0.96 Compatibility Shim ............... SUCCESS [  2.554 s]
[INFO] Titan-HBase: 0.98 Compatibility Shim ............... SUCCESS [  1.337 s]
[INFO] Titan-HBase: 1.0 Compatibility Shim ................ SUCCESS [  1.302 s]
[INFO] Titan-HBase: Universal binary ...................... SUCCESS [  0.474 s]
[INFO] Titan-Hadoop: Parent Module ........................ SUCCESS [  0.486 s]
[INFO] Titan-Hadoop: Version-independent Core ............. SUCCESS [  6.300 s]
[INFO] Titan-Hadoop: 1.x Compatibility Shim ............... SUCCESS [  3.773 s]
[INFO] Titan-Hadoop: 2.x Compatibility Shim ............... SUCCESS [  3.900 s]
[INFO] Titan-Hadoop: Universal binary ..................... SUCCESS [  0.416 s]
[INFO] Titan-Lucene: Indexing Support ..................... SUCCESS [  1.333 s]
[INFO] Titan-All: Complete Titan Distribution ............. SUCCESS [  1.450 s]
[INFO] Titan-Solr: Distributed Indexing Support ........... SUCCESS [  2.543 s]
[INFO] Titan-Dist: Tar and Zip Archives ................... SUCCESS [ 15.394 s]
[INFO] Titan-Dist: Archive with Hadoop 1 .................. SUCCESS [  4.569 s]
[INFO] Titan-Doc: AsciiDoc Manual for Titan ............... SUCCESS [  7.681 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

$ cd titan-hbase-parent

$ mvn clean install -Dtest=com.thinkaurelius.titan.diskstorage.hbase.HBaseDistributedStoreManagerTest
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Titan-HBase: Parent Module ......................... SUCCESS [  1.263 s]
[INFO] Titan-HBase: Version-independent Core .............. SUCCESS [  3.118 s]
[INFO] Titan-HBase: 0.94 Compatibility Shim ............... SUCCESS [ 24.935 s]
[INFO] Titan-HBase: 0.96 Compatibility Shim ............... SUCCESS [ 25.591 s]
[INFO] Titan-HBase: 0.98 Compatibility Shim ............... SUCCESS [ 24.308 s]
[INFO] Titan-HBase: 1.0 Compatibility Shim ................ SUCCESS [ 20.114 s]
[INFO] Titan-HBase: Universal binary ...................... SUCCESS [  0.291 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

$ mvn clean install -Dtest=com.thinkaurelius.titan.diskstorage.hbase.HBaseIDAuthorityTest
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Titan-HBase: Parent Module ......................... SUCCESS [  1.456 s]
[INFO] Titan-HBase: Version-independent Core .............. SUCCESS [  3.248 s]
[INFO] Titan-HBase: 0.94 Compatibility Shim ............... SUCCESS [08:45 min]
[INFO] Titan-HBase: 0.96 Compatibility Shim ............... SUCCESS [08:35 min]
[INFO] Titan-HBase: 0.98 Compatibility Shim ............... SUCCESS [08:45 min]
[INFO] Titan-HBase: 1.0 Compatibility Shim ................ SUCCESS [07:39 min]
[INFO] Titan-HBase: Universal binary ...................... SUCCESS [  0.351 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by srikanthgunduboyina** [comment]
Thanks for the quick verification and let me knowing the result.
I think this failures are coming because with the error:
 [main] ERROR client.HConnectionManager$HConnectionImplementation: Check the value configured in 'zookeeper.znode.parent'. There could be a mismatch with the one configured in the master.
Can you please help me in understanding in which scenarios we may get this error so that I can compare and resolve these issues at my end.

Thanks in Advance.

**Comment by pluradj** [comment]
That error is typically seen when HBase is configured with a non-default value for `zookeeper.znode.parent` such as `/hbase-unsecure`. The default value is `/hbase`.

Other issues could be some sort of connection error for Zookeeper. So check the typical things for a connection error, like conflicts on the IP address (perhaps IPv6 might be to blame) and the port (default for Zookeeper is `2181`).

Are you running Zookeeper/HBase/Hadoop on the machine? If so, shut them all down before building.

**Comment by srikanthgunduboyina** [comment]
Thanks you so much @pluradj 
I will try your suggestions and will let you know the results.

Thanks

**Comment by srikanthgunduboyina** [comment]
Thanks @pluradj , HBaseIDAuthorityTest passed on my amd64
When modified the /etc/hosts file in my amd64, HBaseIDAuthorityTest passed in all the hbase version modules
mvn clean install -Dtest=com.thinkaurelius.titan.diskstorage.hbase.HBaseIDAuthorityTest
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Titan-HBase: Parent Module ......................... SUCCESS [  2.759 s]
[INFO] Titan-HBase: Version-independent Core .............. SUCCESS [  6.554 s]
[INFO] Titan-HBase: 0.94 Compatibility Shim ............... SUCCESS [08:49 min]
[INFO] Titan-HBase: 0.96 Compatibility Shim ............... SUCCESS [09:01 min]
[INFO] Titan-HBase: 0.98 Compatibility Shim ............... SUCCESS [08:48 min]
[INFO] Titan-HBase: 1.0 Compatibility Shim ................ SUCCESS [07:23 min]
[INFO] Titan-HBase: Universal binary ...................... SUCCESS [  0.589 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
Change done was:
::1     localhost ip6-localhost ip6-loopback <hostname> 1<hostip>
Added the hostname and hostip

Inspite doing similar changes on ppc64le still I am having 2 error in ppc64le environment:
Tests in error:
  HBaseIDAuthorityTest>IDAuthorityTest.setUp:116 » Titan Exception in Titan
  HBaseIDAuthorityTest>IDAuthorityTest.tearDown:150->IDAuthorityTest.close:155 » NullPointer

What I have observed is on amd64 only 18 test cases are getting executed and all are passing but in the ppc64le 19 test cases are getting executed of which two are failing. Sometimes 20 test cases are getting executed of which four are failing in ppc64le.

No sure from were these extra test cases are getting executed.
@pluradj  can you please share me any pointers so that I can track from were these failures are caused.

Thanks in Advance.

**Comment by pluradj** [comment]
Don't know what else to tell you here. You could try increasing the log level during the build, not sure what the flags are off-hand. Doesn't make much sense why the test case executions would vary. You'll may need to dive into the source code.

**Comment by srikanthgunduboyina** [comment]
Thanks for your kind support @pluradj 
When ran the same steps on a different local ppc64le VM, all test cases passed.
If anyone wants to build titandb on ppc64le , you might require to run below commands on titandb source directory before proceeding to build and run the test cases:
#Replace snappy-java-1.0.5-M3.jar with snappy-java-1.1.1.7.jar,as snappy-java-1.0.5-M3.jar doesn't have ppc64le binaries
sed -i -- 's/1.0.5-M3/1.1.1.7/g' pom.xml
#test cases failing with same size of java VM in titan-es
sed -i 's/256/512/g' titan-es/src/test/bin/elasticsearch.in.sh
#[main] ERROR client.HConnectionManager$HConnectionImplementation: Check the value configured in 'zookeeper.znode.parent'. There could be a mismatch with the one configured in the master. And also check for conflicts on the IP address (perhaps IPv6 might be to blame)  as suggested by pluradj
sed -i -e 's|&lt;&#47;configuration&gt;|    &lt;property&gt;\n\t&lt;name&gt;zookeeper.znode.parent&lt;&#47;name&gt;\n\t&lt;value&gt;&#47;hbase&lt;&#47;value&gt;\n    &lt;&#47;property&gt;\n&lt;&#47;configuration&gt;|g' titan-hbase-parent/common/test/conf/hbase-site.xml

**Comment by srikanthgunduboyina** [comment]
Sorry the last command was:
sed -i -e 's|</configuration>|    <property>\n\t<name>zookeeper.znode.parent</name>\n\t<value>/hbase</value>\n    </property>\n</configuration>|g' titan-hbase-parent/common/test/conf/hbase-site.xml
