### ISSUE TITLE
Cassandra backend  --  com.thinkaurelius.titan.diskstorage.PermanentBackendException: Unexpected interrupt

### ISSUE THREAD

**Issue by rsteppac** [thinkaurelius/titan#1367]
After upgrading to Titan 1.0.0 I started to see the following exceptions under load, using Cassandra (2.2.6) as the storage backend:

```
Caused by:
com.thinkaurelius.titan.diskstorage.PermanentBackendException:
Unexpected interrupt
       at
com.thinkaurelius.titan.diskstorage.common.DistributedStoreManager.sleepAfterWrite(DistributedStoreManager.java:224)
       at
com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftStoreManager.mutateMany(CassandraThriftStoreManager.java:309)
       at
com.thinkaurelius.titan.diskstorage.locking.consistentkey.ExpectedValueCheckingStoreManager.mutateMany(ExpectedValueCheckingStoreManager.java:65)
       at
com.thinkaurelius.titan.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:90)
       at
com.thinkaurelius.titan.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:87)
       at
com.thinkaurelius.titan.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:56)
       at
com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:42)
       ... 60 more
Caused by: java.lang.InterruptedException: sleep interrupted
       at java.lang.Thread.sleep(Native Method)[:1.8.0_102]
       at java.lang.Thread.sleep(Thread.java:340)[:1.8.0_102]
       at
java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)[:1.8.0_102]
       at
com.thinkaurelius.titan.diskstorage.util.time.TimestampProviders.sleepPast(TimestampProviders.java:138)
       at
com.thinkaurelius.titan.diskstorage.common.DistributedStoreManager.sleepAfterWrite(DistributedStoreManager.java:222)
       ... 66 more
```

**Comment by lidongze0629** [comment]
Does this problem solved? I have the same exception in titan 1.0 while using Cassandra
