### ISSUE TITLE
titan-cassandra 1.0.0 with guava 25.0-jre fails

### ISSUE THREAD

**Issue by hemabs** [thinkaurelius/titan#1393]
I'm trying to use titan-cassandra 1.0.0 with guava-25.0-jre. Upon upgrade of guava from 18.0 to 25.0-jre, I see below run time exception:
[artifact:mvn] java.lang.IllegalAccessError: tried to access method com.google.common.collect.Iterators.emptyIterator()Lcom/google/common/collect/UnmodifiableIterator; from class com.thinkaurelius.titan.graphdb.query.QueryProcessor
[artifact:mvn] 	at com.thinkaurelius.titan.graphdb.query.QueryProcessor.iterator(QueryProcessor.java:55)
[artifact:mvn] 	at com.google.common.collect.Iterables$4.iterator(Iterables.java:559)
[artifact:mvn] 	at com.thinkaurelius.titan.graphdb.tinkerpop.optimize.TitanGraphStep.lambda$new$51(TitanGraphStep.java:46)
[artifact:mvn] 	at org.apache.tinkerpop.gremlin.process.traversal.step.sideEffect.GraphStep.processNextStart(GraphStep.java:94)
[artifact:mvn] 	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:140)
[artifact:mvn] 	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:54)
[artifact:mvn] 	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:37)
[artifact:mvn] 	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:126)
[artifact:mvn] 	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:37)
[artifact:mvn] 	at org.apache.tinkerpop.gremlin.process.traversal.Traversal.fill(Traversal.java:145)
[artifact:mvn] 	at org.apache.tinkerpop.gremlin.process.traversal.Traversal.toList(Traversal.java:102)

Can you let me know if these are compatible?Thanks.

Also posted question on google groups: https://groups.google.com/forum/#!topic/gremlin-users/ZzrzHKmQqvc

**Comment by mukulchakane** [comment]
facing the same issue with guava-27.0-jre upon upgrade from guava-18.0.
have we found any solution for this?
