### ISSUE TITLE
how to use titan linked to cassandra, please help me?

### ISSUE THREAD

**Issue by wuyc08** [thinkaurelius/titan#140]
I do it follow the method of Titan documents "Using Cassandra". firstly, I run a cassandra server successfully, then I code as bellow by  eclipse:
Configuration conf = new BaseConfiguration ();
conf.setProperty("storage.backend","cassandra");
conf.setProperty("storage.hostname","127.0.0.1");
conf.setProperty("storage.port",7000);
TitanGraph g = TitanFactory.open(conf);
....
But, when running it, push the Exceptions:
13/01/18 17:36:38 INFO impl.ConnectionPoolMBeanManager: Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=TitanConnectionPool,ServiceType=connectionpool
Exception in thread "main" java.lang.IllegalArgumentException: Could not instantiate storage manager class com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxStoreManager
    at com.thinkaurelius.titan.diskstorage.Backend.getStorageManager(Backend.java:215)
    at com.thinkaurelius.titan.diskstorage.Backend.<init>(Backend.java:97)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:398)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:78)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:60)
.....
please help me , thank you very much~~~my cassandra storage port is 7000, listening port is 9160.

**Comment by mbroecheler** [comment]
I believe the default port for cassandra is 9160. Please try that to connect.
Also, please use our mailinglist and not this bug tracker for questions: aureliusgraphs@googlegroups.com
Thank you.
