### ISSUE TITLE
g.getIndexedKeys() throws NPE

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#20]
This happens on a fresh instance of Cassandra and BerekeleyDB. Stack trace is after examples below.

gremlin> g = TitanFactory.open('target/testdb') 
==>standardtitangraph[local]
gremlin> g.getIndexedKeys()  
java.lang.NullPointerException
Display stack trace? [yN] 
gremlin> g.createKeyIndex('name',Vertex.class)
==>null
gremlin> g.getIndexedKeys()  
java.lang.NullPointerException
Display stack trace? [yN] 
gremlin> g.stopTransaction(SUCCESS)
==>null
gremlin> g.getIndexedKeys()  
java.lang.NullPointerException
Display stack trace? [yN] 

---

... create with BasicConfiguration to Cassandra.
gremlin> g.getIndexedKeys()
java.lang.NullPointerException
Display stack trace? [yN] y
java.lang.NullPointerException
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.getIndexedKeys(TitanBlueprintsTransaction.java:125)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.getIndexedKeys(TitanBlueprintsGraph.java:95)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:189)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at groovysh_evaluate.run(groovysh_evaluate:39)
    at groovysh_evaluate$run.call(Unknown Source)

**Comment by mbroecheler** [comment]
I had no idea you were allowed to call the method with a null argument. Is that what is going on here? If you provide null then it returns both vertex and edge indexes?

If so, I can change the implementation. This should also be documented here:
https://github.com/tinkerpop/blueprints/blob/master/blueprints-core/src/main/java/com/tinkerpop/blueprints/KeyIndexableGraph.java

**Comment by okram** [comment]
Ah! ... no. My bad, I didn't realize the method signature of the method and Groovy is "smart" in that it says, "no argument, okay, null."

Yes, close.

**Comment by mbroecheler** [comment]
Well, I changed it so that null is automatically changed to Vertex.class. I don't think that does any harm and if you do a getKeyIndexes() in groovy it does what you would expect.

**Comment by okram** [comment]
I would say make it throw a RuntimeException with a message of:

"Must provide either Vertex.class or Edge.class as an argument"
