### ISSUE TITLE
[titan02/03] NullPointerException when doing linear scan has() with Titan/BerkeleyDB

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#200]
gremlin> g.V.has('name','DARK STAR')
==>v[40660]
java.lang.NullPointerException
Display stack trace? [yN] y
java.lang.NullPointerException
    at com.thinkaurelius.titan.graphdb.types.vertices.PersistVertexTitanKey.getDefinition(PersistVertexTitanKey.java:25)
    at com.thinkaurelius.titan.graphdb.types.manager.StandardTypeFactory.createExistingPropertyKey(StandardTypeFactory.java:55)
    at com.thinkaurelius.titan.graphdb.types.manager.SimpleTypeManager.getType(SimpleTypeManager.java:154)
    at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.getExisting(AbstractTitanTx.java:178)
    at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.getExistingVertex(AbstractTitanTx.java:168)
    at com.thinkaurelius.titan.graphdb.transaction.VertexIterable$1.nextVertex(VertexIterable.java:40)
    at com.thinkaurelius.titan.graphdb.transaction.VertexIterable$1.next(VertexIterable.java:59)
    at com.thinkaurelius.titan.graphdb.transaction.VertexIterable$1.next(VertexIterable.java:29)
    at com.google.common.collect.Iterators$6.next(Iterators.java:593)
    at com.tinkerpop.pipes.util.iterators.HistoryIterator.next(HistoryIterator.java:25)
    at com.tinkerpop.pipes.IdentityPipe.processNextStart(IdentityPipe.java:19)
    at com.tinkerpop.pipes.AbstractPipe.next(AbstractPipe.java:89)
    at com.tinkerpop.gremlin.pipes.filter.PropertyFilterPipe.processNextStart(PropertyFilterPipe.java:28)
    at com.tinkerpop.gremlin.pipes.filter.PropertyFilterPipe.processNextStart(PropertyFilterPipe.java:13)
    at com.tinkerpop.pipes.AbstractPipe.hasNext(AbstractPipe.java:98)
    at com.tinkerpop.pipes.util.Pipeline.hasNext(Pipeline.java:105)

**Comment by mbroecheler** [comment]
@okram : Can you double check this? Neither Pavel nor I can reproduce. Maybe it was an intermediate commit that was broken...

``` groovy
gremlin> g = TitanFactory.open('/tmp/titan')
==>titangraph[local:/tmp/titan]
gremlin> g.loadGraphML('/Users/matthias/Development/titan/titan-0.2.0/data/graph-of-the-gods.xml')
==>null
gremlin> g.commit()
==>null
gremlin> g.V
==>v[4]
==>v[8]
==>v[12]
==>v[16]
==>v[20]
==>v[24]
==>v[28]
==>v[32]
==>v[36]
==>v[40]
==>v[44]
==>v[48]
gremlin> g.V.has('type','god').map
==>{name=pluto, type=god}
==>{name=neptune, type=god}
==>{name=jupiter, type=god}
```

**Comment by okram** [comment]
This now works for me. Tested on the original dataset that was causing the problem too (the Grateful Dead dataset).

``` text
gremlin> g = TitanFactory.open('/tmp/testing2')
==>titangraph[local:/tmp/testing2]
gremlin> g.loadGraphML('/Users/marko/software/tinkerpop/gremlin/data/graph-example-2.xml')
==>null
gremlin> g.commit()
==>null
gremlin> g.V
==>v[4]
==>v[8]
==>v[12]
==>v[16]
==>v[20]
==>v[24]
==>v[28]
...
gremlin> g.V.has('name','DARK STAR')
==>v[660]
gremlin>
```
