### ISSUE TITLE
id-block-size of 100,000 still causes problems.

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#221]
I am consistently getting this exception. 9 out of the 400 mappers died cause of it. What is the solution?

```
    ... 9 more
```

Caused by: java.lang.IllegalStateException: ID renewal thread did not complete in time.
        at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextBlock(StandardIDPool.java:66)
        at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextID(StandardIDPool.java:117)
        at com.thinkaurelius.titan.graphdb.database.idassigner.VertexIDAssigner.assignID(VertexIDAssigner.java:266)
        at com.thinkaurelius.titan.graphdb.database.idassigner.VertexIDAssigner.assignID(VertexIDAssigner.java:152)
        at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.assignID(StandardTitanGraph.java:182)
        at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.addVertex(StandardTitanTx.java:252)
        at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.addVertex(TitanBlueprintsTransaction.java:52)
        at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.addVertex(TitanBlueprintsGraph.java:129)
        at com.thinkaurelius.faunus.formats.BlueprintsGraphOutputMapReduce$Map.map(BlueprintsGraphOutputMapReduce.java:99)
        ... 13 more

**Comment by mbroecheler** [comment]
Can you tell what they are complaining about? I.e. what is the root cause?
That should be in the log file shortly before the failure.

On Fri, Apr 12, 2013 at 3:18 PM, Marko A. Rodriguez <
notifications@github.com> wrote:

> I am consistently getting this exception. 9 out of the 400 mappers died
> cause of it. What is the solution?
> 
> ```
> ... 9 more
> ```
> 
> Caused by: java.lang.IllegalStateException: ID renewal thread did not
> complete in time.
> at
> com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextBlock(StandardIDPool.java:66)
> at
> com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextID(StandardIDPool.java:117)
> at
> com.thinkaurelius.titan.graphdb.database.idassigner.VertexIDAssigner.assignID(VertexIDAssigner.java:266)
> at
> com.thinkaurelius.titan.graphdb.database.idassigner.VertexIDAssigner.assignID(VertexIDAssigner.java:152)
> at
> com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.assignID(StandardTitanGraph.java:182)
> at
> com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.addVertex(StandardTitanTx.java:252)
> at
> com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.addVertex(TitanBlueprintsTransaction.java:52)
> at
> com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.addVertex(TitanBlueprintsGraph.java:129)
> at
> com.thinkaurelius.faunus.formats.BlueprintsGraphOutputMapReduce$Map.map(BlueprintsGraphOutputMapReduce.java:99)
> ... 13 more
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/221
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by okram** [comment]
I'm consistently getting these errors when bulk loding into Titan 0.3.0 via Faunus.

Here are my loading properties in Faunus.

```
faunus.graph.output.format=com.thinkaurelius.faunus.formats.titan.cassandra.TitanCassandraOutputFormat
faunus.sideeffect.output.format=org.apache.hadoop.mapreduce.lib.output.TextOutputFormat
faunus.graph.output.titan.storage.backend=com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftStoreManager
faunus.graph.output.titan.storage.hostname=localhost
faunus.graph.output.titan.storage.port=9160
faunus.graph.output.titan.storage.keyspace=titan
faunus.graph.output.titan.storage.batch-loading=true
faunus.graph.output.titan.ids.block-size=100000
# faunus.graph.output.titan.storage.cassandra.thrift.frame_size_mb=49
# faunus.graph.output.titan.storage.cassandra.thrift.max_message_size_mb=50
faunus.graph.output.titan.infer-schema=false
faunus.graph.output.blueprints.tx-commit=5000
```

```
java.lang.IllegalArgumentException: -1
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:92)
    at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextBlock(StandardIDPool.java:71)
    at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextID(StandardIDPool.java:117)
    at com.thinkaurelius.titan.graphdb.database.idassigner.VertexIDAssigner.assignID(VertexIDAssigner.java:260)
    at com.thinkaurelius.titan.graphdb.database.idassigner.VertexIDAssigner.assignID(VertexIDAssigner.java:152)
java.lang.IllegalArgumentException: -1
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:92)
    at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextBlock(StandardIDPool.java:71)
    at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextID(StandardIDPool.java:117)
    at com.thinkaurelius.titan.graphdb.database.idassigner.VertexIDAssigner.assignID(VertexIDAssigner.java:260)
    at com.thinkaurelius.titan.graphdb.database.idassigner.VertexIDAssigner.assignID(VertexIDAssigner.java:152)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.assignID(StandardTitanGraph.java:182)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.addEdge(StandardTitanTx.java:342)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.addEdge(TitanBlueprintsTransaction.java:99)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.addEdge(TitanBlueprintsTransaction.java:94)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.addEdge(TitanBlueprintsGraph.java:169)
    at com.thinkaurelius.faunus.formats.BlueprintsGraphOutputMapReduce$Reduce.reduce(BlueprintsGraphOutputMapReduce.java:194)
    at com.thinkaurelius.faunus.formats.BlueprintsGraphOutputMapReduce$Reduce.reduce(BlueprintsGraphOutputMapReduce.java:152)
    at org.apache.hadoop.mapreduce.Reducer.run(Reducer.java:176)
    at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:650)
    at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:418)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:396)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1149)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)
```

**Comment by okram** [comment]
I have bumped to the id-block-size to 250,000. I no longer get the aforementioned exceptions. Now, instead, I'm getting consistent ConnectionRefusedExceptions.

``` text
faunus.graph.output.titan.ids.block-size=250000
faunus.graph.output.titan.storage.idauthority-wait-time=1000
```

Note that this is with very light Map/Reduce resources -- 12 mappers/reducers in a 6 node m2.4xlarge cluster.

``` text
java.io.IOException: java.lang.reflect.InvocationTargetException
    at com.thinkaurelius.faunus.mapreduce.MapSequence$Map.setup(MapSequence.java:60)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:142)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:370)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:396)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1149)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.thinkaurelius.faunus.mapreduce.MapSequence$Map.setup(MapSequence.java:39)
    ... 8 more
Caused by: com.thinkaurelius.titan.core.TitanException: Could not read partitioner information
    at com.thinkaurelius.titan.diskstorage.cassandra.AbstractCassandraStoreManager.getFeatures(AbstractCassandraStoreManager.java:148)
    at com.thinkaurelius.titan.diskstorage.Backend.<init>(Backend.java:100)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:406)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:62)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
    at com.thinkaurelius.faunus.formats.titan.GraphFactory.generateGraph(GraphFactory.java:20)
    at com.thinkaurelius.faunus.formats.BlueprintsGraphOutputMapReduce.generateGraph(BlueprintsGraphOutputMapReduce.java:61)
    at com.thinkaurelius.faunus.formats.BlueprintsGraphOutputMapReduce$Map.setup(BlueprintsGraphOutputMapReduce.java:90)
    ... 13 more
Caused by: com.thinkaurelius.titan.diskstorage.TemporaryStorageException: Temporary failure in storage backend
    at com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftStoreManager.getCassandraPartitioner(CassandraThriftStoreManager.java:73)
    at com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftStoreManager.getPartitioner(CassandraThriftStoreManager.java:64)
    at com.thinkaurelius.titan.diskstorage.cassandra.AbstractCassandraStoreManager.getFeatures(AbstractCassandraStoreManager.java:146)
    ... 20 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
    at org.apache.thrift.transport.TSocket.open(TSocket.java:183)
    at org.apache.thrift.transport.TFramedTransport.open(TFramedTransport.java:81)
    at com.thinkaurelius.titan.diskstorage.cassandra.thrift.thriftpool.CTConnectionFactory.makeRawConnection(CTConnectionFactory.java:88)
    at com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftStoreManager.getCassandraConnection(CassandraThriftStoreManager.java:405)
    at com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftStoreManager.getCassandraPartitioner(CassandraThriftStoreManager.java:70)
    ... 22 more
Caused by: java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
    at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
    at java.net.Socket.connect(Socket.java:529)
    at org.apache.thrift.transport.TSocket.open(TSocket.java:178)
    ... 26 more
```

**Comment by okram** [comment]
Here are is my Faunus properties file. Note that Hadoop is co-located with the Cassandra cluster.

``` text
# input graph parameters
faunus.graph.input.format=org.apache.hadoop.mapreduce.lib.input.SequenceFileInputFormat
faunus.input.location=friendster/

# output data (graph or statistic) parameters
faunus.graph.output.format=com.thinkaurelius.faunus.formats.titan.cassandra.TitanCassandraOutputFormat
faunus.graph.output.titan.storage.backend=cassandrathrift
faunus.graph.output.titan.storage.hostname=localhost,10.172.138.44,10.175.66.3,10.174.91.43,10.174.217.237,10.174.90.89,10.175.66.20,10.172.107.132
faunus.graph.output.titan.storage.port=9160
faunus.graph.output.titan.storage.keyspace=titan
faunus.graph.output.titan.storage.batch-loading=true
faunus.graph.output.titan.ids.block-size=250000
faunus.graph.output.titan.storage.idauthority-wait-time=1000
# faunus.graph.output.titan.storage.cassandra.thrift.frame_size_mb=49
# faunus.graph.output.titan.storage.cassandra.thrift.max_message_size_mb=50
faunus.graph.output.titan.infer-schema=false
faunus.graph.output.blueprints.tx-commit=5000

mapred.map.tasks=12
mapred.reduce.tasks=12


faunus.sideeffect.output.format=org.apache.hadoop.mapreduce.lib.output.TextOutputFormat
faunus.output.location=output
faunus.output.location.overwrite=true
```

**Comment by xedin** [comment]
So it looks like server socket rejects you connection. The could be caused by two things - you are using ('sync' rpc server) and Cassandra can't process accepts fast enough so kernel fills up it's "pending" queue and rejects all new connection attempts _or_ you use non-blocking server and there are just to many connections and kernel part happens again _or_ Cassandra + Hadoop together utilizing internal and internal connections cause that to happen.

**Comment by xedin** [comment]
Can you try switching to 'hsha' for 'rpc_server_type' cassandra.yaml? Or I can build you a custom Cassandra jar with my thrift server implementation to try out...

**Comment by okram** [comment]
My last run was with hsha as you recommended that previously.

I can try a custom cassandra jar. ping me when you are available, please.

http://markorodriguez.com

**Comment by okram** [comment]
Regarding: " there are just to many connections and kernel part happens again or Cassandra + Hadoop together utilizing internal and internal connections cause that to happen."

I have gotten the same behavior with 8 mappers (48 total connections in the cluster) as I have with 2 mappers (12 total connections). I purposely reduced the amount of communication load to see if that was the issue and it didn't change the behavior.

**Comment by okram** [comment]
Let it run with Astyanax. I'm back to getting ID renewal issues (was at 100,000 ids) as well as @Caused by: java.net.SocketTimeoutException: Read timed out@.

``` text
java.io.IOException
    at com.thinkaurelius.faunus.mapreduce.MapSequence$Map.map(MapSequence.java:83)
    at com.thinkaurelius.faunus.mapreduce.MapSequence$Map.map(MapSequence.java:19)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:144)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:370)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:396)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1149)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.thinkaurelius.faunus.mapreduce.MapSequence$Map.map(MapSequence.java:79)
    ... 9 more
Caused by: java.lang.IllegalStateException: ID renewal thread did not complete in time.
    at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextBlock(StandardIDPool.java:66)
    at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextID(StandardIDPool.java:117)
    at com.thinkaurelius.titan.graphdb.database.idassigner.VertexIDAssigner.assignID(VertexIDAssigner.java:266)
    at com.thinkaurelius.titan.graphdb.database.idassigner.VertexIDAssigner.assignID(VertexIDAssigner.java:152)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.assignID(StandardTitanGraph.java:182)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.addVertex(StandardTitanTx.java:252)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.addVertex(TitanBlueprintsTransaction.java:52)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.addVertex(TitanBlueprintsGraph.java:129)
    at com.thinkaurelius.faunus.formats.BlueprintsGraphOutputMapReduce$Map.map(BlueprintsGraphOutputMapReduce.java:100)
    ... 13 more
```

**Comment by mbroecheler** [comment]
@okram: Is Hadoop still co-located with Cassandra for those runs?

**Comment by okram** [comment]
Yes, but I'm only running 2 mappers per machine which is very light considering they are m2.4xlarge boxes. Also, I've done colocation in the past with no problems. (well, we did have problems writing data :), but that was when task trackers were dying, nothing cassandra specific -- moreover, once we figured out the "task tracker dying issue," I didn't have issues with writing data to Titan/Cassandra).

**Comment by okram** [comment]
Also realize that I can do pure Hadoop jobs all day long with no problem (SequenceFile) on this cluster configuration. Moreover, with the mapper count so low, I don't even come close to blowing a tasktracker.

**Comment by okram** [comment]
Through 5 days of configuration optimizations, this is solved....

**Comment by astubbs** [comment]
@okram, can you summerise the optimisations you had to make? And what sort of size job are you running?

**Comment by cglewis** [comment]
@okram I would love to know what the optimizations are as well.  I'm currently running into the same issue loading into Titan 0.3.2 on top of HBase using Faunus.  I've messed with several parameters including: 

faunus.graph.output.titan.ids.block-size=100000
faunus.graph.output.titan.storage.idauthority-wait-time=3000
faunus.graph.output.titan.storage.idauthority-retries=4
faunus.graph.output.titan.infer-schema=true
faunus.graph.output.blueprints.tx-commit=5000

However, changing any of them don't seem to make a difference, all of the mappers get to 100% (roughly about 500 mappers) at the same time, and then all but like 10 bail because they couldn't lock to get IDs.
