### ISSUE TITLE
Titan/Cassandra + ElasticSearch -- Data not available after transaction commits?

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#228]
I suspect this is an issue with my setup, but I can't figure out what is wrong.

``` text
more bin/cassandra-es.local
storage.backend=cassandrathrift
storage.hostname=127.0.0.1

storage.index.search.backend=elasticsearch
storage.index.search.hostname=localhost
storage.index.search.client-only=true
   // also tried with client-only=false
```

Then in Gremlin I do the following. Note the last line returns no data.

``` text
gremlin> g = TitanFactory.open('bin/cassandra-es.local')
0    [main] INFO  com.thinkaurelius.titan.diskstorage.Backend  - Configuring index [search] based on:
 backend: elasticsearch
hostname: localhost
client-only: false

67   [main] INFO  org.elasticsearch.plugins  - [Strobe] loaded [], sites []
574  [main] INFO  com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex  - Configured remote host: localhost : 9300
==>titangraph[cassandrathrift:127.0.0.1]
gremlin> g.makeType().name('name').dataType(String.class).indexed("search",Vertex.class).unique(Direction.OUT).makePropertyKey();
==>v[36028797018963978]
gremlin> g.commit()
==>null
gremlin> g.addVertex()['name'] = 'Marko A. Rodriguez'
==>Marko A. Rodriguez
gremlin> g.query().has('name',CONTAINS,'Marko').vertices()
==>v[4]
gremlin> g.commit()
==>null
gremlin> g.query().has('name',CONTAINS,'Marko').vertices()
gremlin>
```

Then check out this very odd behavior... (simply continues where the last line of the above Gremlin output ended).

``` text
gremlin> v = g.v(4)
==>v[4]
gremlin> v.map
==>{name=Marko A. Rodriguez}
gremlin> v.setProperty('name','Marko')
==>null
gremlin> v.map
==>{name=Marko}
gremlin> g.commit()
Could not commit transaction due to exception during persistence
Display stack trace? [yN] y
com.thinkaurelius.titan.core.TitanException: Could not commit transaction due to exception during persistence
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.commit(StandardTitanTx.java:805)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.commit(TitanBlueprintsGraph.java:38)
    at com.tinkerpop.blueprints.TransactionalGraph$commit.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at groovysh_evaluate.run(groovysh_evaluate:54)
    at groovysh_evaluate$run.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at groovysh_evaluate$run.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:67)
    at org.codehaus.groovy.tools.shell.Interpreter$evaluate.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:152)
    at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:114)
    at org.codehaus.groovy.tools.shell.Shell$leftShift$0.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:88)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:100)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
    at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:57)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:66)
    at com.thinkaurelius.titan.tinkerpop.gremlin.Console.<init>(Console.java:65)
    at com.thinkaurelius.titan.tinkerpop.gremlin.Console.<init>(Console.java:78)
    at com.thinkaurelius.titan.tinkerpop.gremlin.Console.main(Console.java:104)
Caused by: com.thinkaurelius.titan.diskstorage.PermanentStorageException: Unknown exception while executing index operation
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.convert(ElasticSearchIndex.java:169)
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.mutate(ElasticSearchIndex.java:301)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.flushInternal(IndexTransaction.java:88)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.commit(IndexTransaction.java:70)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction.commit(BackendTransaction.java:67)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.commit(StandardTitanTx.java:798)
    ... 48 more
Caused by: org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: no requests added;
    at org.elasticsearch.action.ValidateActions.addValidationError(ValidateActions.java:29)
    at org.elasticsearch.action.bulk.BulkRequest.validate(BulkRequest.java:375)
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:55)
    at org.elasticsearch.action.bulk.TransportBulkAction$TransportHandler.messageReceived(TransportBulkAction.java:272)
    at org.elasticsearch.action.bulk.TransportBulkAction$TransportHandler.messageReceived(TransportBulkAction.java:261)
    at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:210)
    at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:111)
    at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:560)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:787)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
    at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:560)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:787)
    at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:74)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:560)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:555)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
gremlin>
```

**Comment by okram** [comment]
Here are the version numbers I did this with:

Cassandra 1.2.2
Elasticsearch 0.20.6
Titan 0.3.0

**Comment by okram** [comment]
The plot thickens. Look at this odd behavior. 

So, I'm able to have Elasticsearch work when I add more than one vertex and that other vertex has a different name. But the name property of the first vertex (and all subsequence vertices with that name property are not accessible).

Add 100 vertices to the graph with a name of this form: "person 100 a", where 100 is a counter and 'a' is from ring[].

``` groovy
g = TitanFactory.open('bin/cassandra-es.local')
g.makeType().name('name').dataType(String.class).indexed("search",Vertex.class).unique(Direction.OUT).makePropertyKey();
g.commit()

ring = ['a','b','c']
totalTime = 0;
totalVertices = 100;
(0..totalVertices).each{
  name = 'person ' + it + ' ' + ring[it%ring.size()]
  v = g.addVertex();
  v.setProperty('name',name)
}; null

g.commit();
```

Check this query behavior out:

``` text
gremlin> g.query().has('name',CONTAINS,'a').vertices().count()
==>0
gremlin> g.query().has('name',CONTAINS,'b').vertices().count()
==>34
gremlin> g.query().has('name',CONTAINS,'c').vertices().count()
==>33
```

Note that there are 34 vertices with name containing 'a'. A linear scan proves this.

``` text
gremlin> g.V.filter{it.name.contains(' a')}.count()
==>34
```

But then watch this! I can get all the vertices that contain 'person'.

``` text
gremlin> g.query().has('name',CONTAINS,'person').vertices().count()
==>101
gremlin> 33 + 34 + 34
==>101
```

?! Mind boggling.

**Comment by okram** [comment]
Plot thickens once again.

So, it seems you can add names that have capital letters in them, BUT you can only search for names with lower case values. (e.g. "rodriguez").

HOWEVER, this doesn't explain this other odd behavior here:
  https://github.com/thinkaurelius/titan/issues/228#issuecomment-16539688

Thus, this ticket is like 4 issues in 1. Sorry. I can break apart if need be.

``` text
gremlin> g.addVertex([name:'Marko Rodriguez'])
==>v[4]
gremlin> g.addVertex([name:'James Smith'])
==>v[8]
gremlin> g.addVertex([name:'Bobby Ryan'])
==>v[12]
gremlin> g.commit()
==>null
gremlin> g.query().has('name',CONTAINS,'marko').vertices()
==>v[4]
gremlin> g.query().has('name',CONTAINS,'rodriguez').vertices()
==>v[4]
gremlin> g.query().has('name',CONTAINS,'james').vertices()
==>v[8]
gremlin> g.query().has('name',CONTAINS,'smith').vertices()
==>v[8]
gremlin> g.query().has('name',CONTAINS,'bobby ryan').vertices()
gremlin> g.query().has('name',CONTAINS,'ryan').vertices()
==>v[12]
gremlin> g.query().has('name',CONTAINS,'bobby').vertices()
==>v[12]
gremlin>
```

**Comment by okram** [comment]
And to come full circle, note that the vertices ARE available as capitalization before committing the transaction.

``` text
gremlin> g.addVertex([name:'Adam Adams'])
==>v[16]
gremlin> g.query().has('name',CONTAINS,'Adam').vertices()
==>v[16]
gremlin> g.commit()
==>null
gremlin> g.query().has('name',CONTAINS,'Adam').vertices()
gremlin> g.query().has('name',CONTAINS,'adam').vertices()
==>v[16]
```

...and still this is a big issue. (mentioned in the first section of this ticket)

``` text
gremlin> v = g.query().has('name',CONTAINS,'adam').vertices()._().next()
==>v[16]
gremlin> v.setProperty('name','Blah')
==>null
gremlin> g.commit()
Could not commit transaction due to exception during persistence
```

**Comment by okram** [comment]
It just gets odder. In the TX acts different than out of the TX but with capitals this time.

``` text
gremlin> g = TitanFactory.open('bin/cassandra-es.local')
==>titangraph[cassandrathrift:127.0.0.1]
gremlin> g.makeType().name('name').dataType(String.class).indexed("search",Vertex.class).unique(Direction.OUT).makePropertyKey();
==>v[36028797018963978]
gremlin> g.commit()
==>null
gremlin> g.addVertex([name:'Marko Rodriguez'])
==>v[4]
gremlin> g.query().has('name',CONTAINS,'Marko').vertices()
==>v[4]
gremlin> g.query().has('name',CONTAINS,'marko').vertices()
gremlin> g.commit()
==>null
gremlin> g.query().has('name',CONTAINS,'Marko').vertices()
gremlin> g.query().has('name',CONTAINS,'marko').vertices()
==>v[4]
gremlin>
```

**Comment by vantonio** [comment]
I can reproduce this with the following configuration:

`storage.backend=cassandrathrift
storage.hostname=192.168.56.202

storage.index.search.backend=elasticsearch
storage.index.search.local-mode=true
storage.index.search.client-only=false
storage.index.search.directory=/elastic/`

with the same `ActionRequestValidationException: Validation Failed: 1: no requests added` exception.
