### ISSUE TITLE
Titan with embedded Cassandra: exception on startup of first node with replication-factor=3

### ISSUE THREAD

**Issue by gnantel** [thinkaurelius/titan#236]
When launching a Titan with embedded Cassandra cluster for the first time using replication-factor=3, I get the following exception:
ERROR 2013-04-25 03:59:36,086 [main] CassandraDaemon - Exception in thread Thread[main,5,main]
com.thinkaurelius.titan.core.TitanException: Could not initialize backend
        at com.thinkaurelius.titan.diskstorage.Backend.initialize(Backend.java:214)
        at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:407)
        at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:62)
        at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
        at com.thinkaurelius.titan.tinkerpop.rexster.RexsterTitanServer.start(RexsterTitanServer.java:70)
        at com.thinkaurelius.titan.tinkerpop.rexster.RexsterTitanServer.startDaemon(RexsterTitanServer.java:80)
        at com.thinkaurelius.titan.tinkerpop.rexster.RexsterTitanServer.main(RexsterTitanServer.java:118)
Caused by: com.thinkaurelius.titan.diskstorage.TemporaryStorageException: Temporary failure in storage backend
        at com.thinkaurelius.titan.diskstorage.cassandra.embedded.CassandraEmbeddedKeyColumnValueStore.read(CassandraEmbeddedKeyColumnValueStore.java:332)
        at com.thinkaurelius.titan.diskstorage.cassandra.embedded.CassandraEmbeddedKeyColumnValueStore.read(CassandraEmbeddedKeyColumnValueStore.java:323)
        at com.thinkaurelius.titan.diskstorage.cassandra.embedded.CassandraEmbeddedKeyColumnValueStore.getInternal(CassandraEmbeddedKeyColumnValueStore.java:77)
        at com.thinkaurelius.titan.diskstorage.cassandra.embedded.CassandraEmbeddedStoreManager.getConfigurationProperty(CassandraEmbeddedStoreManager.java:343)
        at com.thinkaurelius.titan.diskstorage.Backend.initialize(Backend.java:204)
        ... 6 more
**Caused by: org.apache.cassandra.exceptions.UnavailableException: Cannot achieve consistency level QUORUM**
        at org.apache.cassandra.db.ConsistencyLevel.assureSufficientLiveNodes(ConsistencyLevel.java:250)
        at org.apache.cassandra.service.ReadCallback.assureSufficientLiveNodes(ReadCallback.java:156)
        at org.apache.cassandra.service.StorageProxy.fetchRows(StorageProxy.java:889)
        at org.apache.cassandra.service.StorageProxy.read(StorageProxy.java:829)
        at com.thinkaurelius.titan.diskstorage.cassandra.embedded.CassandraEmbeddedKeyColumnValueStore.read(CassandraEmbeddedKeyColumnValueStore.java:328)
        ... 10 more

After looking into the code, I found that during the backend initialization process, Titan ensures that the backend was created store by a compatible version of Titan:
https://github.com/thinkaurelius/titan/blob/master/titan-core/src/main/java/com/thinkaurelius/titan/diskstorage/Backend.java#L204-L212

Then I found that the CassandraEmbeddedStoreManager reads and writes configuration properties using a consistency level of QUORUM:
https://github.com/thinkaurelius/titan/blob/master/titan-cassandra/src/main/java/com/thinkaurelius/titan/diskstorage/cassandra/embedded/CassandraEmbeddedStoreManager.java#L343-L347
https://github.com/thinkaurelius/titan/blob/master/titan-cassandra/src/main/java/com/thinkaurelius/titan/diskstorage/cassandra/embedded/CassandraEmbeddedStoreManager.java#L365

The issue when running with Cassandra in embedded mode is that Titan is launching the Cassandra cluster and not connecting to an existing Cassandra cluster, thus a consistency level of QUORUM cannot be achieved.

To get past the issue on my end, I changed CassandraEmbeddedStoreManager to use a consistency level of ONE when key/rawKey is "titan-version".  I don't think this is the ideal solution but I am not familiar enough with the overall design to suggest anything better.

Thanks,

Gerard

**Comment by mbroecheler** [comment]
Titan will attempt to read from the storage backend pretty much immediately which causes this exception because the cluster hasn't "settled in" yet.

@xedin : What do you think is the best work around? Should we add a configurable "wait period" in the storage adapter?

**Comment by rsiemens77** [comment]
I'm also having this issue.  We had a failure of one of our 3-node cluster (replication factor 1), and I can't bring the failed node back because of this.  Why fail fast from this error?  I don't know the details of the wait requirement, but why not a standard exponential back-off and retry before giving up completely?

Any workaround, short of titan code modifications, so I can get my 3rd node back into my cluster?

**Comment by mbroecheler** [comment]
I pushed a fix that retries to connect in case of failure for up to 60 seconds (this is configurable via storage.setup-wait) using exponential back-off.
@rsiemens77  Please build the titan03 branch (using _mvn clean install -DskipTests_ since we just added the last unit tests to fix) and see if that works.

**Comment by xedin** [comment]
@mbroecheler I think what we should wait DatabaseDescriptor.getRpcTimeout() after first attempt to read/write attribute and set consistency to ONE, that would work for any RF.

**Comment by rsiemens77** [comment]
@mbroecheler I appreciate that responsive fix and your helpful instructions.  It worked, and saved me from recreating my cluster from scratch.

**Comment by mbroecheler** [comment]
@rsiemens77 Glat to hear it worked for you.
