### ISSUE TITLE
Hbase endback is not handlering connection exception correctly

### ISSUE THREAD

**Issue by yuanw** [thinkaurelius/titan#25]
When the HBase is not start, TitanFactory.open(config) stucks in a retry loop. by the way, I haven't successfully connected Titan with local HBase, (I tried Hbase 0.94.0, Hbase 0.92.1 on Mac) I alway got stuck in an retry loop.

**Comment by mbroecheler** [comment]
You are correct. Currently, the HBase adapter assumes that HBase is running and will wait for it to appear. This is useful, since it sometimes takes a little while for an HBase instance to receive requests. That said, the adapter should eventually time out and throw an exception.

What are the issues that you are having connecting to a local HBase instance? I have successfully connected on a Mac so that is something we should be able to sort out.

**Comment by yuanw** [comment]
Thank for the feedback. I am new to HBase, so I don't know whether it is a HBase configuration issue. 

The stack I am seeing is:

 DEBUG org.apache.hadoop.conf.Configuration - java.io.IOException: config()
    at org.apache.hadoop.conf.Configuration.<init>(Configuration.java:226)
    at org.apache.hadoop.conf.Configuration.<init>(Configuration.java:213)
    at org.apache.hadoop.security.SecurityUtil.<clinit>(SecurityUtil.java:53)
    at org.apache.hadoop.net.NetUtils.<clinit>(NetUtils.java:63)
    at org.apache.hadoop.hbase.ipc.HBaseRPC.getProxy(HBaseRPC.java:332)
    at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getMaster(HConnectionManager.java:642)
    at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:106)
    at com.thinkaurelius.titan.diskstorage.hbase.HBaseStorageManager.openDatabase(HBaseStorageManager.java:142)
    at com.thinkaurelius.titan.diskstorage.hbase.HBaseStorageManager.<init>(HBaseStorageManager.java:114)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getStorageManager(GraphDatabaseConfiguration.java:334)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:76)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:60)

**Comment by mbroecheler** [comment]
Note that this is a DEBUG log statement and not an exception that made it
all the way to the top of the stack.
You will notice that HBase has a lot of those log statements and its easy
to confuse them for worrisome exceptions.

When you try to connect Titan with Hbase is it still stuck in the loop or
does it return?

On Fri, Jun 22, 2012 at 8:02 PM, Yuan <
reply@reply.github.com

> wrote:
> 
> Thank for the feedback. I am new to HBase, so I don't know whether it is a
> HBase configuration issue.
> 
> The stack I am seeing is:
> 
>  DEBUG org.apache.hadoop.conf.Configuration - java.io.IOException: config()
>        at
> org.apache.hadoop.conf.Configuration.<init>(Configuration.java:226)
>        at
> org.apache.hadoop.conf.Configuration.<init>(Configuration.java:213)
>        at
> org.apache.hadoop.security.SecurityUtil.<clinit>(SecurityUtil.java:53)
>        at org.apache.hadoop.net.NetUtils.<clinit>(NetUtils.java:63)
>        at org.apache.hadoop.hbase.ipc.HBaseRPC.getProxy(HBaseRPC.java:332)
>        at
> org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getMaster(HConnectionManager.java:642)
>        at
> org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:106)
>        at
> com.thinkaurelius.titan.diskstorage.hbase.HBaseStorageManager.openDatabase(HBaseStorageManager.java:142)
>        at
> com.thinkaurelius.titan.diskstorage.hbase.HBaseStorageManager.<init>(HBaseStorageManager.java:114)
>        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native
> Method)
>        at
> sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
>        at
> sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
>        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
>        at
> com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getStorageManager(GraphDatabaseConfiguration.java:334)
>        at
> com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:76)
>        at
> com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:60)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/thinkaurelius/titan/issues/25#issuecomment-6522108

## 

Matthias Broecheler, PhD
http://www.matthiasb.com
E-Mail: me@matthiasb.com

**Comment by yuanw** [comment]
it stucks in the loop. From the hbase localhost web UI, I can the "titan" database is created.

**Comment by mbroecheler** [comment]
that's should not be. are you using any non default configuration, like a
different port number or something of that nature?
to investigate this matter, please send me your configuration or script,
the output produced and the hbase output. thanks
On Jun 24, 2012 4:05 PM, "Yuan" <
reply@reply.github.com>
wrote:

**Comment by yuanw** [comment]
Oops, When I use Hbase 0.92.1, everything works fine.
