### ISSUE TITLE
StackOverflowError upon rollback

### ISSUE THREAD

**Issue by zachkinstner** [thinkaurelius/titan#255]
The following [RexConnect](github.com/inthefabric/rexconnect) output demonstrates the issue.  Starting from an empty graph, make a simple `a --tests--> b` graph.  Within a session, perform an aggregation operation, then try to rollback the session:

``` c
# RexConnect> query
#   ...script (0; string): g
#   ...params (1; string; opt): 

{"timer":7,"results":["titangraph[local:data/FabricTest]"]}

# RexConnect> query
#   ...script (0; string): g.addVertex()
#   ...params (1; string; opt): 

{"timer":542,"results":[{"_id":"4","_type":"vertex"}]}

# RexConnect> query
#   ...script (0; string): g.addVertex()
#   ...params (1; string; opt): 

{"timer":191,"results":[{"_id":"8","_type":"vertex"}]}

# RexConnect> query
#   ...script (0; string): g.addEdge(g.v(4), g.v(8), "tests")
#   ...params (1; string; opt): 

{"timer":96,"results":[{"_type":"edge","_inV":"8","_id":"d-4-2F0LaTPQAK","_label":"tests","_outV":"4"}]}

# RexConnect> session
#   ...action (0; string): start

{"timer":141,"results":["55db2018-0131-455d-8c0a-b2e1e40e8ca6"]}

# RexConnect> query
#   ...script (0; string): x = []  
#   ...params (1; string; opt): 

{"timer":54,"results":[]}

# RexConnect> query
#   ...script (0; string): g.v(4).outE.aggregate(x).inV.aggregate(x).iterate()
#   ...params (1; string; opt): 

{"timer":180,"results":[null]}

# RexConnect> query
#   ...script (0; string): x
#   ...params (1; string; opt): 

{"timer":32,"results":[{"_type":"edge","_inV":"8","_id":"d-4-2F0LaTPQAK","_label":"tests","_outV":"4"},{"_id":"8","_type":"vertex"}]}

# RexConnect> session
#   ...action (0; string): rollback

//this is where it explodes
```

Rexster Server in `-d` mode reports:

```
java.lang.StackOverflowError
    at com.carrotsearch.hppc.hash.MurmurHash3.hash(MurmurHash3.java:34)
    at com.carrotsearch.hppc.Internals.rehash(Internals.java:14)
    at com.carrotsearch.hppc.LongObjectOpenHashMap.containsKey(LongObjectOpenHashMap.java:516)
    at com.thinkaurelius.titan.graphdb.transaction.vertexcache.SimpleVertexCache.contains(SimpleVertexCache.java:25)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.containsVertex(StandardTitanTx.java:199)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.getVertex(StandardTitanTx.java:210)
    at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.it(AbstractVertex.java:36)
    at com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:28)
    at com.thinkaurelius.titan.graphdb.relations.CacheEdge.it(CacheEdge.java:52)
    at com.thinkaurelius.titan.graphdb.relations.CacheEdge.getID(CacheEdge.java:77)
    at com.thinkaurelius.titan.graphdb.internal.AbstractElement.hasId(AbstractElement.java:64)
    at com.thinkaurelius.titan.graphdb.relations.RelationIdentifier.get(RelationIdentifier.java:29)
    at com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.getId(AbstractTypedRelation.java:84)
    at com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:30)
    at com.thinkaurelius.titan.graphdb.relations.CacheEdge.it(CacheEdge.java:52)
    [...continues this loop...]
```

**Comment by zachkinstner** [comment]
Workaround: try setting `x = null` before the rollback.

Also, I think I noticed during my trials that `g.v(4).outE.aggregate(x).iterate()` (without the `.inV.aggregate(x)`) has a successful rollback.

**Comment by mbroecheler** [comment]
This seems related to the following bug report from the mailing list. This has to do with the newly introduced "automatic refresh" feature in Titan when starting a new transaction. However, if that transaction was rolled back, then the refresh is bound to fail and goes into the infinite loop. This needs to be fixed and an exception thrown.

Exception in thread "pool-1-thread-1" java.lang.StackOverflowError
    at com.thinkaurelius.titan.graphdb.internal.ElementLifeCycle.hasAddedRelations(ElementLifeCycle.java:55)
    at com.thinkaurelius.titan.graphdb.vertices.StandardVertex.hasAddedRelations(StandardVertex.java:80)
    at com.thinkaurelius.titan.graphdb.relations.CacheEdge.it(CacheEdge.java:41)
    at com.thinkaurelius.titan.graphdb.relations.CacheEdge.getID(CacheEdge.java:77)
    at com.thinkaurelius.titan.graphdb.internal.AbstractElement.hasId(AbstractElement.java:64)
    at com.thinkaurelius.titan.graphdb.relations.RelationIdentifier.get(RelationIdentifier.java:29)
    at com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.getId(AbstractTypedRelation.java:84)
    at com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:30)
    at com.thinkaurelius.titan.graphdb.relations.CacheEdge.it(CacheEdge.java:52)
    at com.thinkaurelius.titan.graphdb.relations.CacheEdge.getID(CacheEdge.java:77)
    at com.thinkaurelius.titan.graphdb.internal.AbstractElement.hasId(AbstractElement.java:64)
    at com.thinkaurelius.titan.graphdb.relations.RelationIdentifier.get(RelationIdentifier.java:29)
    at com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.getId(AbstractTypedRelation.java:84)
    at com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:30)
    at com.thinkaurelius.titan.graphdb.relations.CacheEdge.it(CacheEdge.java:52)
    at com.thinkaurelius.titan.graphdb.relations.CacheEdge.getID(CacheEdge.java:77)
    at com.thinkaurelius.titan.graphdb.internal.AbstractElement.hasId(AbstractElement.java:64)
    at com.thinkaurelius.titan.graphdb.relations.RelationIdentifier.get(RelationIdentifier.java:29)
    at com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.getId(AbstractTypedRelation.java:84)
    at com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:30)
    at com.thinkaurelius.titan.graphdb.relations.CacheEdge.it(CacheEdge.java:52)
    at com.thinkaurelius.titan.graphdb.relations.CacheEdge.getID(CacheEdge.java:77)

regards
Reinhard
