### ISSUE TITLE
Thrift exception in multiIdAcquisition

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#266]
in LockKeyColumnValueStoreTest.testMultiIDAcquisition and encountered this crazy bug. Check out the attached log file that contains more information. Scary part is an ERROR in cassandra:
17693 [Thrift:16] ERROR org.apache.cassandra.thrift.CustomTThreadPoolServer  - Thrift error occurred during processing of message.
org.apache.thrift.protocol.TProtocolException: Bad version in readMessageBegin

Any idea what this is? Could you try to debug this? This has high priority since its part of the id management.
Thanks,
Matthias

com.thinkaurelius.titan.diskstorage.PermanentStorageException: Permanent failure in storage backend
    at com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftKeyColumnValueStore.convertException(CassandraThriftKeyColumnValueStore.java:268)
    at com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftKeyColumnValueStore.getSlice(CassandraThriftKeyColumnValueStore.java:131)
    at com.thinkaurelius.titan.diskstorage.idmanagement.ConsistentKeyIDManager.getCurrentID(ConsistentKeyIDManager.java:84)
    at com.thinkaurelius.titan.diskstorage.idmanagement.ConsistentKeyIDManager.getIDBlock(ConsistentKeyIDManager.java:110)
    at com.thinkaurelius.titan.diskstorage.LockKeyColumnValueStoreTest$3.run(LockKeyColumnValueStoreTest.java:389)
    at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.IndexOutOfBoundsException
    at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:88)
    at org.apache.thrift.transport.TFramedTransport.write(TFramedTransport.java:146)
    at org.apache.thrift.protocol.TBinaryProtocol.writeBinary(TBinaryProtocol.java:196)
    at org.apache.cassandra.thrift.SliceRange.write(SliceRange.java:600)
    at org.apache.cassandra.thrift.SlicePredicate.write(SlicePredicate.java:436)
    at org.apache.cassandra.thrift.Cassandra$get_slice_args.write(Cassandra.java:7275)
    at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:63)
    at org.apache.cassandra.thrift.Cassandra$Client.send_get_slice(Cassandra.java:588)
    at org.apache.cassandra.thrift.Cassandra$Client.get_slice(Cassandra.java:577)
    at com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftKeyColumnValueStore.getSlice(CassandraThriftKeyColumnValueStore.java:114)
    ... 4 more

**Comment by mbroecheler** [comment]
Solved as part of the recent ByteBuffer refactoring.
