### ISSUE TITLE
NPE on transaction commit

### ISSUE THREAD

**Issue by dbxfb** [thinkaurelius/titan#28]
Hi !

I am currently trying Titan out (snapshot 0.1), and I can't commit any transactions I make.
My code goes like this:

```
    TitanTransaction t = g.startThreadTransaction();
    [getType for TitanKeys and TitanLabels]
    [adding vertices and edges]
    t.stopTransaction(Conclusion.SUCCESS);

(i've also tried t.commit(), in vain)
```

in the end I always get the following:

ERROR ContainerResponse - The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
java.lang.NullPointerException
    at com.thinkaurelius.titan.graphdb.transaction.StandardPersistTitanTx.isDeletedRelation(StandardPersistTitanTx.java:64)
    at com.thinkaurelius.titan.graphdb.relations.factory.RelationFactoryUtil.connectRelation(RelationFactoryUtil.java:15)
    at com.thinkaurelius.titan.graphdb.relations.factory.StandardPersistedRelationFactory.createExistingProperty(StandardPersistedRelationFactory.java:41)
    at com.thinkaurelius.titan.graphdb.types.manager.StandardTypeFactory.createExistingType(StandardTypeFactory.java:37)
    at com.thinkaurelius.titan.graphdb.types.manager.SimpleTypeManager.getType(SimpleTypeManager.java:149)
    at com.thinkaurelius.titan.graphdb.types.manager.SimpleTypeManager.getType(SimpleTypeManager.java:168)
    at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.getType(AbstractTitanTx.java:247)
    at com.thinkaurelius.titan.graphdb.database.util.TypeSignature.parseTypes(TypeSignature.java:41)
    at com.thinkaurelius.titan.graphdb.database.util.TypeSignature.<init>(TypeSignature.java:26)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.getSignature(StandardTitanGraph.java:856)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.getEntry(StandardTitanGraph.java:761)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.getEntry(StandardTitanGraph.java:703)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.persist(StandardTitanGraph.java:689)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.save(StandardTitanGraph.java:642)
    at com.thinkaurelius.titan.graphdb.transaction.StandardPersistTitanTx.commit(StandardPersistTitanTx.java:171)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.stopTransaction(TitanBlueprintsTransaction.java:30)

I am using a Cassandra backend, and had no problem creating types etc., although each time I try to use a transaction it gives me this error.

After looking at both stack trace and source, I think the NPE is caused by the " deletedEdges = null; " line before calling graphdb.save(...), in the TitanTransaction.commit() method. (although I only took a quick look so you might prove me wrong here).

Thanks for your time :)
(Please do not hesitate to ask for more details if I omitted important informations)

**Comment by mbroecheler** [comment]
Thanks for submitting this bug report. I reproduced the exception in a unit test and fixed it. Please try it with your code example.

**Comment by dbxfb** [comment]
Everything works fine now! Thanks for your reactivity
