### ISSUE TITLE
Chaining has() When Multiple Keys are Used

### ISSUE THREAD

**Issue by spmallette** [thinkaurelius/titan#281]
Originally reported here:

https://groups.google.com/forum/#!topic/aureliusgraphs/VPx0-K5W5gw

chaining has() in GraphQuery when referencing to property keys marked as indices seems to generate an error:

``` text
gremlin> graph = TitanFactory.open("/tmp/t")
==>titangraph[local:/tmp/t]
gremlin> graph.makeType().name("first").dataType(String.class).indexed(Vertex.class).unique(Direction.OUT).makePropertyKey();
==>v[36028797018963978]
gremlin> graph.makeType().name("last").dataType(String.class).indexed(Vertex.class).unique(Direction.OUT).makePropertyKey();
==>v[36028797018963986]
gremlin> graph.query().has("last","x").has('first',"y").vertices()
Could not call index
Display stack trace? [yN] y
com.thinkaurelius.titan.core.TitanException: Could not call index
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$6.execute(StandardTitanTx.java:733)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$6.execute(StandardTitanTx.java:607)
    at com.thinkaurelius.titan.graphdb.query.QueryProcessor.getUnwrappedIterator(QueryProcessor.java:74)
    at com.thinkaurelius.titan.graphdb.query.QueryProcessor$OuterIterator.<init>(QueryProcessor.java:132)
    at com.thinkaurelius.titan.graphdb.query.QueryProcessor.iterator(QueryProcessor.java:48)
    at com.google.common.collect.Iterables$7.iterator(Iterables.java:611)
    at com.google.common.collect.Iterables.toString(Iterables.java:259)
    at com.google.common.collect.FluentIterable.toString(FluentIterable.java:117)
    at java.lang.String.valueOf(String.java:2826)
    at java_lang_String$valueOf.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:71)
    at org.codehaus.groovy.tools.shell.Interpreter$evaluate.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:152)
    at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:114)
    at org.codehaus.groovy.tools.shell.Shell$leftShift$0.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:88)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:100)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
    at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:57)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:66)
    at com.thinkaurelius.titan.tinkerpop.gremlin.Console.<init>(Console.java:65)
    at com.thinkaurelius.titan.tinkerpop.gremlin.Console.<init>(Console.java:78)
    at com.thinkaurelius.titan.tinkerpop.gremlin.Console.main(Console.java:104)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: expected one element but was: <v[36028797018963986]=x, v[36028797018963978]=y>
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2258)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3990)
    at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4793)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$6.execute(StandardTitanTx.java:717)
    ... 48 more
Caused by: java.lang.IllegalArgumentException: expected one element but was: <v[36028797018963986]=x, v[36028797018963978]=y>
    at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:375)
    at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:270)
    at com.thinkaurelius.titan.graphdb.database.IndexSerializer.query(IndexSerializer.java:191)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.elementQuery(StandardTitanGraph.java:169)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$6$5.call(StandardTitanTx.java:720)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$6$5.call(StandardTitanTx.java:717)
    at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4796)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3589)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2374)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2337)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2252)
    ... 51 more
```

doesn't seem to create errors when the second property key reference in the chain is not indexed:

``` java
gremlin> graph.query().has("last","x").has('test',"y").vertices()
gremlin>
```

**Comment by zachkinstner** [comment]
Is this the same issue as #279?

> doesn't seem to create errors when the second property key reference in the chain is not indexed:

I can confirm -- I noticed the same behavior.

**Comment by spmallette** [comment]
yeah...i guess this is a duplicate.  my bad.
