### ISSUE TITLE
Titan with embedded cassandra issue

### ISSUE THREAD

**Issue by akumarb2010** [thinkaurelius/titan#315]
I am facing issue while connecting to titan (with embedded cassandra mode).

My configurations:

titan-server-cassandra.properties:
storage.backend=embeddedcassandra
storage.cassandra-config-dir=file:///home/user/Work/titan-all-0.3.1/config/cassandra.yaml

I started titan as below and tried to connect with java snippet:
./bin/titan.sh config/titan-server-rexster.xml config/titan-server-cassandra.properties

I have written a simple java client code for connecting it, but getting following exception. Am I missing any other configuration?

public static TitanGraph create() {
        conf = new BaseConfiguration();
        conf.setProperty(GraphDatabaseConfiguration.STORAGE_BACKEND_KEY,
                "embeddedcassandra");
        conf.setProperty("storage.hostname", "ubuntu");
        conf.setProperty(GraphDatabaseConfiguration.STORAGE_DIRECTORY_KEY, "/tmp/titan001");

```
    Configuration index = conf.subset(
            GraphDatabaseConfiguration.INDEX_NAMESPACE).subset(INDEX_NAME);
    index.setProperty(INDEX_BACKEND_KEY, "elasticsearch");
    g = TitanFactory.open(conf);
    return g;
}
```

Please help me in resolving this issue. And is there any example for traversing the graphs through JAVA API's?  I am looking into Blueprints also.

**Comment by spmallette** [comment]
if you want to connect to a running Titan Server from a java application then you don't want this:

``` java
conf.setProperty(GraphDatabaseConfiguration.STORAGE_BACKEND_KEY,"embeddedcassandra");
```

you want to do:

``` java
conf.setProperty(GraphDatabaseConfiguration.STORAGE_BACKEND_KEY,"cassandrathrift");
```

**Comment by akumarb2010** [comment]
I modified it as below, but still getting same issue. It's considering as Berkeley storage.

public static TitanGraph create() {
        conf = new BaseConfiguration();
        conf.setProperty(GraphDatabaseConfiguration.STORAGE_BACKEND_KEY,"cassandrathrift");
        conf.setProperty("storage.hostname", "127.0.0.1");
        Configuration index = conf.subset(
                GraphDatabaseConfiguration.INDEX_NAMESPACE).subset(INDEX_NAME);
        index.setProperty(INDEX_BACKEND_KEY, "elasticsearch");
        g = TitanFactory.open(conf);
        return g;
    }

I am getting following error

Exception in thread "main" java.lang.IllegalArgumentException: Could not instantiate implementation: com.thinkaurelius.titan.diskstorage.berkeleyje.BerkeleyJEStoreManager
    at com.thinkaurelius.titan.diskstorage.Backend.getImplementationClass(Backend.java:274)
    at com.thinkaurelius.titan.diskstorage.Backend.getStorageManager(Backend.java:227)
    at com.thinkaurelius.titan.diskstorage.Backend.<init>(Backend.java:97)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:440)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:67)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
    at datacube.cube.dbloaders.titan.TitanLoader.create(TitanLoader.java:31)
    at datacube.cube.dbloaders.titan.TitanLoader.main(TitanLoader.java:123)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at com.thinkaurelius.titan.diskstorage.Backend.getImplementationClass(Backend.java:263)
    ... 7 more
Caused by: java.lang.IllegalArgumentException: Need to specify storage directory
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:88)
    at com.thinkaurelius.titan.diskstorage.common.LocalStoreManager.<init>(LocalStoreManager.java:26)
    at com.thinkaurelius.titan.diskstorage.berkeleyje.BerkeleyJEStoreManager.<init>(BerkeleyJEStoreManager.java:37)
    ... 12 more

**Comment by akumarb2010** [comment]
Istead of 

conf.setProperty(GraphDatabaseConfiguration.STORAGE_BACKEND_KEY,"cassandrathrift");
conf.setProperty("storage.hostname", "127.0.0.1");

I used below 
conf.setProperty("storage.backend","cassandrathrift");
conf.setProperty("storage.hostname","127.0.0.1");

Now it's trying to connect cassandra but still I am facing thrift issue:

Exception in thread "main" com.thinkaurelius.titan.core.TitanException: Could not connect to Cassandra to read partitioner information. Please check the connection
    at com.thinkaurelius.titan.diskstorage.cassandra.AbstractCassandraStoreManager.getFeatures(AbstractCassandraStoreManager.java:151)
    at com.thinkaurelius.titan.diskstorage.Backend.<init>(Backend.java:99)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:440)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:67)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
    at datacube.cube.dbloaders.titan.TitanLoader.create(TitanLoader.java:34)
    at datacube.cube.dbloaders.titan.TitanLoader.main(TitanLoader.java:126)
Caused by: com.thinkaurelius.titan.diskstorage.TemporaryStorageException: Temporary failure in storage backend
    at com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftStoreManager.getCassandraPartitioner(CassandraThriftStoreManager.java:74)
    at com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftStoreManager.getPartitioner(CassandraThriftStoreManager.java:65)
    at com.thinkaurelius.titan.diskstorage.cassandra.AbstractCassandraStoreManager.getFeatures(AbstractCassandraStoreManager.java:149)
    ... 6 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused: connect
    at org.apache.thrift.transport.TSocket.open(TSocket.java:185)
    at org.apache.thrift.transport.TFramedTransport.open(TFramedTransport.java:81)
    at com.thinkaurelius.titan.diskstorage.cassandra.thrift.thriftpool.CTConnectionFactory.makeRawConnection(CTConnectionFactory.java:88)
    at com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftStoreManager.getCassandraConnection(CassandraThriftStoreManager.java:409)
    at com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftStoreManager.getCassandraPartitioner(CassandraThriftStoreManager.java:71)
    ... 8 more
Caused by: java.net.ConnectException: Connection refused: connect
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.PlainSocketImpl.doConnect(Unknown Source)
    at java.net.PlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at org.apache.thrift.transport.TSocket.open(TSocket.java:180)
    ... 12 more

**Comment by mbroecheler** [comment]
Do you have cassandra running locally? Meaning, can you connect to
cassandra on the specified port 127.0.0.1?

On Tue, Jul 2, 2013 at 9:55 AM, AnilKumar notifications@github.com wrote:

> Istead of
> 
> conf.setProperty(GraphDatabaseConfiguration.STORAGE_BACKEND_KEY,"cassandrathrift");
> conf.setProperty("storage.hostname", "127.0.0.1");
> 
> I used below
> conf.setProperty("storage.backend","cassandrathrift");
> 
> conf.setProperty("storage.hostname","127.0.0.1");
> 
> Now it's trying to connect cassandra but still I am facing thrift issue:
> 
> Exception in thread "main" com.thinkaurelius.titan.core.TitanException:
> Could not connect to Cassandra to read partitioner information. Please
> check the connection
> at
> com.thinkaurelius.titan.diskstorage.cassandra.AbstractCassandraStoreManager.getFeatures(AbstractCassandraStoreManager.java:151)
> at com.thinkaurelius.titan.diskstorage.Backend.(Backend.java:99)
> 
> at
> com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:440)
> at
> com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.(StandardTitanGraph.java:67)
> at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
> at datacube.cube.dbloaders.titan.TitanLoader.create(TitanLoader.java:34)
> at datacube.cube.dbloaders.titan.TitanLoader.main(TitanLoader.java:126)
> Caused by: com.thinkaurelius.titan.diskstorage.TemporaryStorageException:
> Temporary failure in storage backend
> at
> com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftStoreManager.getCassandraPartitioner(CassandraThriftStoreManager.java:74)
> at
> com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftStoreManager.getPartitioner(CassandraThriftStoreManager.java:65)
> at
> com.thinkaurelius.titan.diskstorage.cassandra.AbstractCassandraStoreManager.getFeatures(AbstractCassandraStoreManager.java:149)
> ... 6 more
> Caused by: org.apache.thrift.transport.TTransportException:
> java.net.ConnectException: Connection refused: connect
> at org.apache.thrift.transport.TSocket.open(TSocket.java:185)
> at
> org.apache.thrift.transport.TFramedTransport.open(TFramedTransport.java:81)
> at
> com.thinkaurelius.titan.diskstorage.cassandra.thrift.thriftpool.CTConnectionFactory.makeRawConnection(CTConnectionFactory.java:88)
> at
> com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftStoreManager.getCassandraConnection(CassandraThriftStoreManager.java:409)
> at
> com.thinkaurelius.titan.diskstorage.cassandra.thrift.CassandraThriftStoreManager.getCassandraPartitioner(CassandraThriftStoreManager.java:71)
> ... 8 more
> Caused by: java.net.ConnectException: Connection refused: connect
> at java.net.PlainSocketImpl.socketConnect(Native Method)
> at java.net.PlainSocketImpl.doConnect(Unknown Source)
> at java.net.PlainSocketImpl.connectToAddress(Unknown Source)
> at java.net.PlainSocketImpl.connect(Unknown Source)
> at java.net.SocksSocketImpl.connect(Unknown Source)
> at java.net.Socket.connect(Unknown Source)
> at org.apache.thrift.transport.TSocket.open(TSocket.java:180)
> ... 12 more
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/315#issuecomment-20359282
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by akumarb2010** [comment]
Yes Cassandra is running locally.

When I am using RexsterClient, I am able to connect and as of now I am using RexsterClient.

**Comment by mbroecheler** [comment]
Can you also connect to cassandra directly? I.e. does cassandra respond at
127.0.0.1 when you connect to it from cassandra-cli for instance?

On Mon, Jul 8, 2013 at 5:40 AM, AnilKumar notifications@github.com wrote:

> Yes Cassandra is running locally.
> 
> When I am using RexsterClient, I am able to connect and as of now I am
> using RexsterClient.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/315#issuecomment-20602357
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by prachikhadke** [comment]
Was there a resolution for this issue?
