### ISSUE TITLE
ASM Dependency Issue

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#361]
I was trying to instantiate the Gremlin scripting engine, but was getting exception below while executing the line ScriptEngine engine  = new GremlinGroovyScriptEngine(); It seems that the problem is caused by asm.jar. Titan-core is pulling asm 4.0 as transient dependency and titan-hbase and gremlin groovy are pulling 3.2. In asm 4.0 visit method in ClassVisitor class is declared as final which I presume is causing  the problem. I excluded asm from titan dependency and the exception went away.

```
<dependency>
    <groupId>com.thinkaurelius.titan</groupId>
    <artifactId>titan-all</artifactId>
    <version>0.3.2</version>
    <exclusions>
        <exclusion>
            <artifactId>asm</artifactId>
            <groupId>org.ow2.asm</groupId>
        </exclusion>
    </exclusions>
</dependency>
```

Exception in thread "main" java.lang.VerifyError: class org.codehaus.groovy.runtime.callsite.GroovySunClassLoader$2 overrides final method visit.(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at org.codehaus.groovy.runtime.callsite.CallSiteGenerator.isCompilable(CallSiteGenerator.java:245)
    at org.codehaus.groovy.reflection.CachedMethod.createStaticMetaMethodSite(CachedMethod.java:284)
    at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.createStaticMetaMethodSite(StaticMetaMethodSite.java:111)
    at groovy.lang.MetaClassImpl.createStaticSite(MetaClassImpl.java:3034)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:61)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:146)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at com.tinkerpop.gremlin.groovy.Gremlin.load(Gremlin.groovy:19)
    at com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.<init>(GremlinGroovyScriptEngine.java:71)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
    at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:186)
    at com.tinkerpop.gremlin.groovy.Gremlin.<clinit>(Gremlin.groovy:15)
    at com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.<init>(GremlinGroovyScriptEngine.java:71)
    at com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngineFactory.getScriptEngine(GremlinGroovyScriptEngineFactory.java:83)
    at javax.script.ScriptEngineManager.getEngineByName(ScriptEngineManager.java:243)
    at com.ems.srm.topology.TitanGraphTraversal.main(TitanGraphTraversal.java:119)

**Comment by dalaro** [comment]
I looked at the dependency tree of the titan-all artifact using `mvn dependency:tree`.  It showed three paths to ASM:

titan-core -> kryo -> reflectasm -> asm 4.x
titan-core -> rexster-server -> jersey-server -> asm 3.x
rexster-console -> rexster-protocol -> gremlin-groovy -> groovy -> asm 3.x

An old [Kryo list thread](https://groups.google.com/forum/#!topic/kryo-users/y08SA4hrA2w) discusses incompatibilities going from ASM 3.x to 4.0 and suggests using a shaded jar to let both versions coexist. Kryo now provides a jar built with all its dependencies (including ASM) shaded, i.e. relocated from their normal package names to uniquely-prefixed package names.  It's even [documented](http://code.google.com/p/kryo/wiki/MavenShadedJAR).  This seems like the way to go.

I changed titan-core's kryo dependency to use the "shaded" classifier.  The shaded artifact contains a subset of ASM 4.0 under the package name com.esotericsoftware.reflectasm.shaded.org.objectweb.asm.  Some classes in the stock asm-4.0.jar file, such as the signature subpackage, seem missing here.  This might be an optimization caused by the `<minimizeJar>true</minimizeJar>` setting in kyro's pom.xml configuration for the maven-shade-plugin.  The Titan tests all pass locally.

The dependency tree does not include ASM 4.0 anymore.  The 4.0 jar won't be included in the `lib` folder of future Titan distros.  Some of the ASM 4.0 classes will ship with shaded classpaths inside the kryo jar, but that's it.  Those shaded ASM 4.0 classes are effectively invisible to Maven from a dependency management standpoint.

I'm still assuming -- without certainty -- that ASM 3.2 is backwards-compatible with 3.1.  Titan's dependency tree contains stuff asking for both 3.1 and 3.2.  Between Titan's parent pom `<dependencyManagement>` section and maven-enforcer-plugin's DependencyConvergence rule, we are now forcing all artifacts in group `asm` to the same version.  The version is set via the pom property `<asm3.version>3.2</asm3.version>`.  If ASM 3.1 and 3.2 are not actually compatible, then I suppose we'll have to either use the shade plugin to ship both separately or upgrade our dependencies to make them converge on a single ASM version, if that's even possible.

These changes are 95990df3beef00fd84dcc1596ddcf96c1c6829be.
