### ISSUE TITLE
Add cassandra backend configuration to support username/password authentication

### ISSUE THREAD

**Issue by GeorgeVorobiov** [thinkaurelius/titan#409]
We are running the DataStax backend cluster with default authentication policy set to password authentication. Since I couldn't' find a way to configure credentials to be used when calling cassandra, I had to disable auth in cassandra cluster (set it to org.apache.cassandra.auth.AllowAllAuthenticator) to make titan work with it.
It seems that the code is mostly there, we just need to define/pass these config entries. The thrift backend already contains code to support calling login() thrift API to provide credentials for a given connection.

**Comment by mbroecheler** [comment]
We should do the same for HBase.

**Comment by faberchri** [comment]
Do you intend to implement this in the very near future (for Cassandra)? The lack of this feature will force us to move away from Titan to a different Graph DB, which I think is a real pity.

**Comment by mbroecheler** [comment]
Keep an eye on the ticket. @xedin is on it.

**Comment by xedin** [comment]
@mbroecheler Pull is at https://github.com/thinkaurelius/titan/pull/477.

**Comment by faberchri** [comment]
:+1: Nice  :))

**Comment by mbroecheler** [comment]
@GeorgeVorobiov @faberchri : We have added the ability to configure a username and password in Titan. What you do is set "storage.username" and "storage.password" in the Titan configuration file and it will use those credentials to connect to the cluster.
The changes are on master. Please try it out.

**Comment by faberchri** [comment]
Test was positive on my local installation. Thanks for your efforts! :)

Noticed that Titan (or Cassandra?) hangs for quite a while if a user without appropriate permissions tries to access the (titan) keyspace .

Stacktrace:

```
Nov 16 2013 15:45:46 [INFO ] main com.thinkaurelius.titan.diskstorage.util.BackendOperation: Temporary storage exception during backend operation. Attempting backoff retry
com.thinkaurelius.titan.diskstorage.TemporaryStorageException: Temporary failure in storage backend
    at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getNamesSlice(AstyanaxOrderedKeyColumnValueStore.java:138)
    at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getSlice(AstyanaxOrderedKeyColumnValueStore.java:88)
    at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration$1.call(KCVSConfiguration.java:70)
    at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration$1.call(KCVSConfiguration.java:64)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:30)
    at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration.getConfigurationProperty(KCVSConfiguration.java:64)
    at com.thinkaurelius.titan.diskstorage.Backend.initialize(Backend.java:268)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1045)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:71)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
    at ch.uzh.ifi.ddis.dm.twhc.graphdb.GraphDbConnectorTest.testTitanCassandraLocalServer(GraphDbConnectorTest.java:145)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at org.testng.TestRunner.privateRun(TestRunner.java:767)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
    at org.testng.TestNG.run(TestNG.java:1057)
    at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:69)
    at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:120)
    at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:104)
    at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.netflix.astyanax.connectionpool.exceptions.BadRequestException: BadRequestException: [host=127.0.0.1(127.0.0.1):9160, latency=16(16), attempts=1]InvalidRequestException(why:User test2 has no SELECT permission on <table titan.system_properties> or any of its parents)
```

**Comment by mbroecheler** [comment]
I don't think there is much we can do about this since it between the
communication of the client and cassandra.

On Sat, Nov 16, 2013 at 6:56 AM, faberchri notifications@github.com wrote:

> Test was positive on my local installation. Thanks for your efforts! :)
> 
> Noticed that Titan (or Cassandra?) hangs for quite a while if user without
> appropriate permissions tries to access the (titan) keyspace .
> 
> Stacktrace:
> 
> Nov 16 2013 15:45:46 [INFO ] main com.thinkaurelius.titan.diskstorage.util.BackendOperation: Temporary storage exception during backend operation. Attempting backoff retry
> com.thinkaurelius.titan.diskstorage.TemporaryStorageException: Temporary failure in storage backend
>     at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getNamesSlice(AstyanaxOrderedKeyColumnValueStore.java:138)
>     at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxOrderedKeyColumnValueStore.getSlice(AstyanaxOrderedKeyColumnValueStore.java:88)
>     at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration$1.call(KCVSConfiguration.java:70)
>     at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration$1.call(KCVSConfiguration.java:64)
>     at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:30)
>     at com.thinkaurelius.titan.graphdb.configuration.KCVSConfiguration.getConfigurationProperty(KCVSConfiguration.java:64)
>     at com.thinkaurelius.titan.diskstorage.Backend.initialize(Backend.java:268)
>     at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1045)
>     at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:71)
>     at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
>     at ch.uzh.ifi.ddis.dm.twhc.graphdb.GraphDbConnectorTest.testTitanCassandraLocalServer(GraphDbConnectorTest.java:145)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:601)
>     at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
>     at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
>     at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
>     at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
>     at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
>     at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
>     at org.testng.TestRunner.privateRun(TestRunner.java:767)
>     at org.testng.TestRunner.run(TestRunner.java:617)
>     at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
>     at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
>     at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
>     at org.testng.SuiteRunner.run(SuiteRunner.java:240)
>     at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
>     at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
>     at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
>     at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
>     at org.testng.TestNG.run(TestNG.java:1057)
>     at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:69)
>     at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:120)
>     at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:104)
>     at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
>     at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
>     at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
>     at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
> Caused by: com.netflix.astyanax.connectionpool.exceptions.BadRequestException: BadRequestException: [host=127.0.0.1(127.0.0.1):9160, latency=16(16), attempts=1]InvalidRequestException(why:User test2 has no SELECT permission on <table titan.system_properties> or any of its parents)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/409#issuecomment-28628196
> .

## 

Matthias Broecheler
http://www.matthiasb.com
