### ISSUE TITLE
Transaction timeout with Hazelcast on g.commit() operation

### ISSUE THREAD

**Issue by okram** [thinkaurelius/titan#425]
With other backends, loading a 1 million edge graph  using the code fragment in

[[https://github.com/thinkaurelius/titan/wiki/Generating-Artificial-Natural-Graphs]]

...works just fine. For Hazelcast, it no likey.

```
gremlin> size = 1000000; ids = [g.addVertex().id]; rand = new Random();
==>java.util.Random@790a367f
gremlin> (1..size).each{
gremlin>   v = g.addVertex();
gremlin>   u = g.v(ids.get(rand.nextInt(ids.size())))
gremlin>   g.addEdge(v,u,'linked');
gremlin>   ids.add(u.id);
gremlin>   ids.add(v.id);
gremlin>   if(it % 1000 == 0)
gremlin>     g.commit()
gremlin> }; null
Could not commit transaction due to exception during persistence
Display stack trace? [yN] y
com.thinkaurelius.titan.core.TitanException: Could not commit transaction due to exception during persistence
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.commit(StandardTitanTx.java:950)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.commit(TitanBlueprintsGraph.java:55)
    at com.tinkerpop.blueprints.TransactionalGraph$commit.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at groovysh_evaluate$_run_closure1.doCall(groovysh_evaluate:63)
    at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:903)
    at groovy.lang.Closure.call(Closure.java:415)
    at groovy.lang.Closure.call(Closure.java:428)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1379)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1351)
    at org.codehaus.groovy.runtime.dgm$170.invoke(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at groovysh_evaluate.run(groovysh_evaluate:56)
    at groovysh_evaluate$run.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at groovysh_evaluate$run.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:67)
    at org.codehaus.groovy.tools.shell.Interpreter$evaluate.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:152)
    at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:114)
    at org.codehaus.groovy.tools.shell.Shell$leftShift$0.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:88)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:100)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
    at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:57)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:66)
    at com.thinkaurelius.titan.tinkerpop.gremlin.Console.<init>(Console.java:57)
    at com.thinkaurelius.titan.tinkerpop.gremlin.Console.<init>(Console.java:70)
    at com.thinkaurelius.titan.tinkerpop.gremlin.Console.main(Console.java:96)
Caused by: com.hazelcast.transaction.TransactionException: Transaction is timed-out!
    at com.hazelcast.transaction.impl.TransactionImpl.checkTimeout(TransactionImpl.java:224)
    at com.hazelcast.transaction.impl.TransactionImpl.prepare(TransactionImpl.java:154)
    at com.hazelcast.transaction.impl.TransactionContextImpl.commitTransaction(TransactionContextImpl.java:59)
    at com.thinkaurelius.titan.diskstorage.hazelcast.AbstractHazelcastStoreManager$HazelCastTransaction.commit(AbstractHazelcastStoreManager.java:94)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction.commit(BackendTransaction.java:75)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.commit(StandardTitanTx.java:943)
    ... 66 more
gremlin>
```

**Comment by dalaro** [comment]
Thanks for finding this.  I'm having trouble reproducing it here.  size = 1M completed in about 3 minutes without an exception.  I'm running 2M and just broke the 25 minute mark with the process at 350% CPU (100%=1 core).

Could you drop some hints -- maybe the approximate walltime this consumed?

**Comment by dalaro** [comment]
Just occurred to me: is this hazelcastcache or hazelcastkcvs?  I was on cache.

**Comment by okram** [comment]
For some reason, it works now?? ……………..apologies.

gremlin> g = TitanFactory.open('conf/titan-hazelcast.properties')
Oct 14, 2013 2:30:07 PM com.hazelcast.config.XmlConfigBuilder
INFO: Looking for hazelcast.xml config file in classpath.
Oct 14, 2013 2:30:07 PM com.hazelcast.config.XmlConfigBuilder
WARNING: Could not find hazelcast.xml in classpath.
Hazelcast will use hazelcast-default.xml config file in jar.
Oct 14, 2013 2:30:07 PM com.hazelcast.config.XmlConfigBuilder
INFO: Using configuration file file:/Users/marko/software/aurelius/titan/lib/hazelcast-all-3.0.2.jar!/hazelcast-default.xml in the classpath.
Oct 14, 2013 2:30:07 PM com.hazelcast.instance.DefaultAddressPicker
INFO: Prefer IPv4 stack is true.
Oct 14, 2013 2:30:07 PM com.hazelcast.instance.DefaultAddressPicker
INFO: Picked Address[192.168.1.124]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
Oct 14, 2013 2:30:07 PM com.hazelcast.system
INFO: [192.168.1.124]:5701 [dev] Hazelcast Community Edition 3.0.2 (20130906) starting at Address[192.168.1.124]:5701
Oct 14, 2013 2:30:07 PM com.hazelcast.system
INFO: [192.168.1.124]:5701 [dev] Copyright (C) 2008-2013 Hazelcast.com
Oct 14, 2013 2:30:07 PM com.hazelcast.instance.Node
INFO: [192.168.1.124]:5701 [dev] Creating MulticastJoiner
Oct 14, 2013 2:30:07 PM com.hazelcast.core.LifecycleService
INFO: [192.168.1.124]:5701 [dev] Address[192.168.1.124]:5701 is STARTING
Oct 14, 2013 2:30:12 PM com.hazelcast.cluster.MulticastJoiner
INFO: [192.168.1.124]:5701 [dev]

Members [1] {
    Member [192.168.1.124]:5701 this
}

Oct 14, 2013 2:30:12 PM com.hazelcast.core.LifecycleService
INFO: [192.168.1.124]:5701 [dev] Address[192.168.1.124]:5701 is STARTED
WARN  com.thinkaurelius.titan.diskstorage.hazelcast.AbstractHazelcastStoreManager  - Hazelcast does not support multiple transactions per thread
==>titangraph[hazelcastcache:/Users/marko/software/aurelius/titan/conf/../db]
gremlin> g.V
Oct 14, 2013 2:30:14 PM com.hazelcast.partition.PartitionService
INFO: [192.168.1.124]:5701 [dev] Initializing cluster partition table first arrangement...
gremlin> g.V
gremlin> size = 1000000; ids = [g.addVertex().id]; rand = new Random();
==>java.util.Random@2fd2fb58
gremlin> (1..size).each{
gremlin>   v = g.addVertex();
gremlin>   u = g.v(ids.get(rand.nextInt(ids.size())))
gremlin>   g.addEdge(v,u,'linked');
gremlin>   ids.add(u.id);
gremlin>   ids.add(v.id);
gremlin>   if(it % 1000 == 0)
gremlin>     g.commit()
gremlin> }; g.commit()
Oct 14, 2013 2:33:42 PM com.hazelcast.util.HealthMonitor
INFO: [192.168.1.124]:5701 [dev]
memory used=343.8M, free=49.2M, total=393.0M, max=455.1M, used/total=87.49% used/max=75.55%
cpu process-load=17.00%, system-load=25.00%, system-loadaverage=281.00%
Oct 14, 2013 2:34:02 PM com.hazelcast.util.HealthMonitor
INFO: [192.168.1.124]:5701 [dev]
memory used=357.8M, free=69.5M, total=427.3M, max=455.1M, used/total=83.74% used/max=78.61%
cpu process-load=17.00%, system-load=23.00%, system-loadaverage=347.00%
Oct 14, 2013 2:34:22 PM com.hazelcast.util.HealthMonitor
INFO: [192.168.1.124]:5701 [dev]
memory used=336.1M, free=135.1M, total=471.2M, max=471.2M, used/total=71.33% used/max=71.33%
cpu process-load=18.00%, system-load=24.00%, system-loadaverage=305.00%
==>null
gremlin> Oct 14, 2013 2:34:42 PM com.hazelcast.util.HealthMonitor
INFO: [192.168.1.124]:5701 [dev]
memory used=355.2M, free=101.7M, total=456.9M, max=456.9M, used/total=77.74% used/max=77.74%
cpu process-load=14.00%, system-load=27.00%, system-loadaverage=319.00%

gremlin>

**Comment by dalaro** [comment]
For future reference, I first thought this was due to us indirectly using HC transactions and running afoul of the default 2 minute timeout.  But my successful run ran three minutes (and a few seconds more -- I timed it) from the start of the loop to the finish.  Also, I don't know where we would be indirectly opening a HC transaction.  I get no recursive grep hits for getTransaction in titan-hazelcast/src/main.  So it would be in HC internals somewhere, if anywhere, I think.

**Comment by dalaro** [comment]
I was grepping for an outdated method name.  The current name is beginTransaction, and this has a hit in AbstractHazelcastStoreManager.  This looks like a genuine lead.  When `storage.transactions` is true (the default), we open a HC transaction with default options inside AbstractHazelcastStoreManager#beginTransaction.  It seems like this should expire after 2 minutes.
