### ISSUE TITLE
Re: exception when vertex property and label have the same name

### ISSUE THREAD

**Issue by pietermartin** [thinkaurelius/titan#428]
The flowing test illustrates the exception.

```
    @Test
    public void testEmailList() throws Exception {
        final String url = "/tmp/titan-test";
        File dir = new File(url);
        FileUtils.deleteDirectory(dir);
        final File f = new File(url);
        Configuration propertiesConfiguration = new PropertiesConfiguration();
        propertiesConfiguration.addProperty("storage.backend", "local");
        propertiesConfiguration.addProperty("storage.directory", f.getAbsolutePath());
        TitanGraph g = TitanFactory.open(propertiesConfiguration);

        Vertex v1 = g.addVertex(null);
        Vertex v2 = g.addVertex(null);
        v2.setProperty("emailList", "jj@jj.jj");
        g.addEdge(null, v1, v2, "emailList");
        g.commit();
    }
```

And the exception...

```
java.lang.IllegalArgumentException: The type of given name is not a label: emailList
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.getEdgeLabel(StandardTitanTx.java:618)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.addEdge(TitanBlueprintsTransaction.java:104)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.addEdge(TitanBlueprintsTransaction.java:96)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.addEdge(TitanBlueprintsGraph.java:204)
```

I understand it happens because the vertex has a key 'emailList' and a outgoing label 'emailList'.

This same test passes on other blueprints implementations so I am not quite sure if it is legal or not. I.e. is it a bug or not.

Thanks
Pieter

**Comment by mbroecheler** [comment]
In Titan, labels and keys share the same namespace. Hence, this exception is expected. I don't think that Blueprints makes any prescriptions on that and hence other implementations might treat this differently.

For Titan, this choice was made because we found schemas where labels and properties have the same name confusing.
