### ISSUE TITLE
Index issues after g.clear()

### ISSUE THREAD

**Issue by Sitin** [thinkaurelius/titan#497]
I found two strange bugs caused by g.clear() (tested in titan-server-0.4.1 via Rexster, Java 7).

Assuming that we have clear DB in each situation.
#### First case: index recreation causes server error.

If we create index then add vertex with non-indexed property than after g.clear() adding the first index will cause an internal error.

``` sh
#!/bin/sh

v1='g.addVertex(null,\[first:"spam",noi:"spam"\])'
v2='g.addVertex(null,\[first:"eggs",noi:"eggs"\])'

echo 'Add index:'
curl -X POST http://localhost:8182/graphs/graph/keyindices/vertex/first        && echo ''
echo 'List indices:'
curl -X GET  http://localhost:8182/graphs/graph/keyindices/vertex/             && echo ''

echo 'Add some nodes:'
curl -X GET  http://localhost:8182/graphs/graph/tp/gremlin?script=${v1}        && echo ''
curl -X GET  http://localhost:8182/graphs/graph/tp/gremlin?script=${v2}        && echo ''

echo 'Clear graph:'
curl -X GET  http://localhost:8182/graphs/graph/tp/gremlin?script="g.clear()"  && echo ''

echo 'Add index:'
curl -X POST http://localhost:8182/graphs/graph/keyindices/vertex/first        && echo ''
```

The last command causes error 500: `<html><body><h1>Internal Error</h1></body></html>`

Sometimes in this case server couldn't be stopped gracefully (or maybe it takes a too much time).
#### Second case: indices couldn't be recreated after clearing the graph

Let's add some indices:

``` sh
#!/bin/sh

echo 'Add some indices:'
curl -X POST http://localhost:8182/graphs/graph/keyindices/vertex/first        && echo ''
curl -X POST http://localhost:8182/graphs/graph/keyindices/vertex/second       && echo ''
echo 'List indices (["first", "second"] expected):'
curl -X GET  http://localhost:8182/graphs/graph/keyindices/vertex/             && echo ''
echo 'Ok for now.'

echo 'Clear graph:'
curl -X GET  http://localhost:8182/graphs/graph/tp/gremlin?script="g.clear()"  && echo ''
echo 'List indices after graph clearing ([] expected and will be given):'
curl -X GET  http://localhost:8182/graphs/graph/keyindices/vertex/             && echo ''

echo 'Recreate indices:'
curl -X POST http://localhost:8182/graphs/graph/keyindices/vertex/first        && echo ''
curl -X POST http://localhost:8182/graphs/graph/keyindices/vertex/second       && echo ''
echo 'Add one more index:'
curl -X POST http://localhost:8182/graphs/graph/keyindices/vertex/third        && echo ''
echo 'Now if would list indices:'
curl -X GET  http://localhost:8182/graphs/graph/keyindices/vertex/             && echo ''
echo 'Only the last index is present.'
```

The most interesting thing that the the second bug suppress appearance of the first one e.g. if we call first script after the second it won't cause server error.

**Comment by spmallette** [comment]
@mbroecheler @dalaro I'm not sure what the proper use of `clear` is and what the behavior should actually be, but it does produce some confusing output in the REPL (output that shows Rexster would get really messed up hosting a graph if someone did this).  Is the behavior below appropriate?  Could things be more clear?  Minimally, some javadoc on `clear` for expected behavior and proper usage would be good I think (I didn't see any, though perhaps the javadoc is on the underlying function calls within `clear`...`backend.clearStorage();`...i didn't go that far)

The short answer is that you can't use `clear` through Rexster because it puts the graph in a state where you need to reopen the graph instance (at least this is the case with BerkeleyDB).  

You seem to be able to at least get the `clear` to issue properly if you change your script to `g.rollback();g.clear()`.  That seems to work from the REPL.  

``` text
gremlin> g = TitanFactory.open('/tmp/testing')
==>titangraph[local:/tmp/testing]
gremlin> g.addVertex([name:"marko"])
==>v[4]
gremlin> g.commit()
==>null
gremlin> g.V
WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
==>v[4]
gremlin> g.clear()
There is 1 existing transaction opened against the Environment.
Aborting open transactions ...
aborting <Transaction id="15">
Display stack trace? [yN] y
java.lang.IllegalStateException: There is 1 existing transaction opened against the Environment.
Aborting open transactions ...
aborting <Transaction id="15">
    at com.sleepycat.je.Environment.close(Environment.java:384)
    at com.thinkaurelius.titan.diskstorage.berkeleyje.BerkeleyJEStoreManager.close(BerkeleyJEStoreManager.java:151)
    at com.thinkaurelius.titan.diskstorage.berkeleyje.BerkeleyJEStoreManager.clearStorage(BerkeleyJEStoreManager.java:168)
    at com.thinkaurelius.titan.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreManagerAdapter.clearStorage(OrderedKeyValueStoreManagerAdapter.java:59)
    at com.thinkaurelius.titan.diskstorage.Backend.clearStorage(Backend.java:454)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.clear(StandardTitanGraph.java:97)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph$clear.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at groovysh_evaluate.run(groovysh_evaluate:56)
    at groovysh_evaluate$run.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at groovysh_evaluate$run.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:67)
    at org.codehaus.groovy.tools.shell.Interpreter$evaluate.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:152)
    at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:114)
    at org.codehaus.groovy.tools.shell.Shell$leftShift$0.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:88)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:100)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
    at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:57)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:66)
    at com.thinkaurelius.titan.tinkerpop.gremlin.Console.<init>(Console.java:57)
    at com.thinkaurelius.titan.tinkerpop.gremlin.Console.<init>(Console.java:70)
    at com.thinkaurelius.titan.tinkerpop.gremlin.Console.main(Console.java:96)
gremlin> g.V
WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
Permanent exception during backend operation
Display stack trace? [yN] n
gremlin> g.rollback()
==>null
gremlin> g.clear()
Tried to remove an unkown database from the storage manager
Display stack trace? [yN] y
java.lang.IllegalArgumentException: Tried to remove an unkown database from the storage manager
    at com.thinkaurelius.titan.diskstorage.berkeleyje.BerkeleyJEStoreManager.removeDatabase(BerkeleyJEStoreManager.java:133)
    at com.thinkaurelius.titan.diskstorage.berkeleyje.BerkeleyJEKeyValueStore.close(BerkeleyJEKeyValueStore.java:70)
    at com.thinkaurelius.titan.diskstorage.keycolumnvalue.keyvalue.BaseKeyColumnValueAdapter.close(BaseKeyColumnValueAdapter.java:41)
    at com.thinkaurelius.titan.diskstorage.keycolumnvalue.CachedKeyColumnValueStore.close(CachedKeyColumnValueStore.java:148)
    at com.thinkaurelius.titan.diskstorage.Backend.clearStorage(Backend.java:450)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.clear(StandardTitanGraph.java:97)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph$clear.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at groovysh_evaluate.run(groovysh_evaluate:56)
    at groovysh_evaluate$run.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at groovysh_evaluate$run.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:67)
    at org.codehaus.groovy.tools.shell.Interpreter$evaluate.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:152)
    at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:114)
    at org.codehaus.groovy.tools.shell.Shell$leftShift$0.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:88)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:100)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
    at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:57)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:66)
    at com.thinkaurelius.titan.tinkerpop.gremlin.Console.<init>(Console.java:57)
    at com.thinkaurelius.titan.tinkerpop.gremlin.Console.<init>(Console.java:70)
    at com.thinkaurelius.titan.tinkerpop.gremlin.Console.main(Console.java:96)
gremlin> g = TitanFactory.open('/tmp/testing')
==>titangraph[local:/tmp/testing]
gremlin> g.V
WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
gremlin> g.addVertex([name:"marko"])
==>v[4]
gremlin> g.commit()
==>null
gremlin> g.clear()
==>null
gremlin> g = TitanFactory.open('/tmp/testing')
==>titangraph[local:/tmp/testing]
gremlin> g.V
WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
gremlin> g.addVertex([name:"marko"])
==>v[4]
gremlin> g.commit()
==>null
gremlin> g.clear()
==>null
```

of course, now that the `clear` works the database is in this state where i have to re-open `g`:

``` text
gremlin> g.addVertex([name:"marko"])
Attempt to use non-open Environment object().
Display stack trace? [yN] n
gremlin> g.rollback()
==>null
gremlin> g.addVertex([name:"marko"])
Attempt to use non-open Environment object().
Display stack trace? [yN] n
gremlin> g.newTransaction()
Attempt to use non-open Environment object().
Display stack trace? [yN] n
gremlin> g = TitanFactory.open('/tmp/testing')
==>titangraph[local:/tmp/testing]
gremlin> g.addVertex([name:"marko"])
==>v[4]
```

**Comment by mbroecheler** [comment]
This method was really just meant for internal use in unit testing but due to its un-safe nature it was replaced in the unit tests but the method itself never removed.

If you need to wipe clean an entire graph, follow the example in the unit tests. This will not be available through the graph itself since it requires that all graph instances be should down. Hence, this is an outside operation.

If you just want to delete the vertices and edges in the graph, do <code>g.V.remove</code>

The clear method will be removed.
