### ISSUE TITLE
Titan on HDP2, HBase 0.96

### ISSUE THREAD

**Issue by ghost** [thinkaurelius/titan#526]
Hi, I'm developing a solution on the Hortonworks Data Platform. This issue is about Titan-HBase. It seems like the existing repo only supports HBase 0.94. There are some API changes in 0.96, which is shipped with the Hortonworks HDP2 GA. Here's the error that it will currently produce:

```
[root@sandbox titan-hbase-0.4.1]# ./bin/gremlin.sh 
[...]
gremlin> conf = new BaseConfiguration();
==>org.apache.commons.configuration.BaseConfiguration@c8282a6
gremlin> conf.setProperty("storage.backend","hbase");
==>null
gremlin> conf.setProperty("storage.hostname","sandbox.hortonworks.com");
==>null
gremlin> g = TitanFactory.open(conf);
Not a host:port pair: PBUF
$
sandbox.hortonworks.com?????(
Display stack trace? [yN] 
```

It doesn't seem like it's much more than that that they've restructured the packages in regard to the use that Titan has of it. To make it work I did a couple of changes in HBaseStoreManager.java and the pom:

HBaseStoreManager.java
Line 23: `import org.apache.hadoop.hbase.io.compress.Compression;`
Line 402: `commands.setSecond(new Delete(key.as(StaticBuffer.ARRAY_FACTORY), (int) delTimestamp, 0));`

titan-hbase/pom.xml
Line 13: `<hbase.version>0.96.0-hadoop2</hbase.version>` (may be that you can set that at command line as well.
Added dependencies:
    <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-common</artifactId>
        <version>0.96.0-hadoop2</version>
    </dependency>   

Line 46: `<artifactId>hbase-client</artifactId>`

Then I compiled everything as mentioned in the HBase section of the documentation here at Github: `mvn clean install -Dhadoop.profile=2.0 -Dhadoop.version=2.2.0 -DskipTests=true`

```
gremlin> conf = new BaseConfiguration();
==>org.apache.commons.configuration.BaseConfiguration@50f47076
gremlin> conf.setProperty("storage.backend","hbase");
==>null
gremlin> conf.setProperty("storage.hostname","sandbox.hortonworks.com");
==>null
gremlin> conf.setProperty("storage.port","2181");
==>null
gremlin> g = TitanFactory.open(conf);
 WARN  org.apache.hadoop.util.NativeCodeLoader  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
==>titangraph[hbase:sandbox.hortonworks.com]
```

Confirmed in the HBase logs:

```
2013-12-17 01:47:40,570 INFO  [MASTER_TABLE_OPERATIONS-sandbox:60000-0] handler.EnableTableHandler: Table 'titan' was successfully enabled. Status: done=true
2013-12-17 01:47:40,573 DEBUG [MASTER_TABLE_OPERATIONS-sandbox:60000-0] lock.ZKInterProcessLockBase: Released /hbase/table-lock/titan/write-master:600000000000021
```

**Comment by mbroecheler** [comment]
Thanks, can you turn your changes into a pull request, please?

On Tue, Dec 17, 2013 at 2:02 AM, tommyskg notifications@github.com wrote:

> Hi, I'm developing a solution on the Hortonworks Data Platform. This issue
> is about Titan-HBase. It seems like the existing repo only supports HBase
> 0.94. There are some API changes in 0.96, which is shipped with the
> Hortonworks HDP2 GA. Here's the error that it will currently produce:
> 
> [root@sandbox titan-hbase-0.4.1]# ./bin/gremlin.sh
> [...]
> gremlin> conf = new BaseConfiguration();
> ==>org.apache.commons.configuration.BaseConfiguration@c8282a6
> gremlin> conf.setProperty("storage.backend","hbase");
> ==>null
> gremlin> conf.setProperty("storage.hostname","sandbox.hortonworks.com");
> ==>null
> gremlin> g = TitanFactory.open(conf);
> Not a host:port pair: PBUF
> $sandbox.hortonworks.com?????(
> Display stack trace? [yN]
> 
> It doesn't seem like it's much more than that that they've restructured
> the packages in regard to the use that Titan has of it. To make it work I
> did a couple of changes in HBaseStoreManager.java and the pom:
> 
> HBaseStoreManager.java
> Line 23: import org.apache.hadoop.hbase.io.compress.Compression;
> Line 402: commands.setSecond(new Delete(key.as(StaticBuffer.ARRAY_FACTORY),
> (int) delTimestamp, 0));
> 
> titan-hbase/pom.xml
> Line 13: <hbase.version>0.96.0-hadoop2</hbase.version> (may be that you
> can set that at command line as well.
> Added dependencies:
> org.apache.hbase
> hbase-common
> 0.96.0-hadoop2
> 
> Line 46: <artifactId>hbase-client</artifactId>
> 
> Then I compiled everything as mentioned in the HBase section of the
> documentation here at Github: mvn clean install -Dhadoop.profile=2.0
> -Dhadoop.version=2.2.0 -DskipTests=true
> 
> gremlin> conf = new BaseConfiguration();
> ==>org.apache.commons.configuration.BaseConfiguration@50f47076
> gremlin> conf.setProperty("storage.backend","hbase");
> ==>null
> gremlin> conf.setProperty("storage.hostname","sandbox.hortonworks.com");
> ==>null
> gremlin> conf.setProperty("storage.port","2181");
> ==>null
> gremlin> g = TitanFactory.open(conf);
>  WARN  org.apache.hadoop.util.NativeCodeLoader  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
> ==>titangraph[hbase:sandbox.hortonworks.com]
> 
> Confirmed in the HBase logs:
> 
> 2013-12-17 01:47:40,570 INFO  [MASTER_TABLE_OPERATIONS-sandbox:60000-0] handler.EnableTableHandler: Table 'titan' was successfully enabled. Status: done=true
> 2013-12-17 01:47:40,573 DEBUG [MASTER_TABLE_OPERATIONS-sandbox:60000-0] lock.ZKInterProcessLockBase: Released /hbase/table-lock/titan/write-master:600000000000021
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/526
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by ghost** [comment]
I modified the 0.5 branch corresponding to this ticket. It's probably a little rough in the edges and breaks compability with the current HBase 0.94.

Edit: And changed the versions to run on the HDP2 GA, may be your roadmap on Hadoop 2 is a little different than mine. Anyways, this one works on YARN.

**Comment by ghost** [comment]
Upon further testing, it seems like there may be more issues to iron out. Perhaps someone has a quick fix for it?

```
gremlin> g.V
==>v[4]
==>v[8]
[...]
==>v[120004]
==>v[120008]
g.v(120008)
==>v[120008]
gremlin> g.v(120008).remove()
==>null
gremlin> g.commit()
```

WARN  com.thinkaurelius.titan.diskstorage.locking.consistentkey.ConsistentKeyLocker  - Discarded expired claim on KeyColumn [k=0x0-0-0-0-0-3-169-144, c=0x40] with timestamp 1387754890110011238
WARN  com.thinkaurelius.titan.diskstorage.locking.consistentkey.ConsistentKeyLocker  - Discarded expired claim on KeyColumn [k=0x0-0-0-0-0-3-169-144, c=0x40] with timestamp 1387754967654278763
WARN  com.thinkaurelius.titan.diskstorage.locking.consistentkey.ConsistentKeyLocker  - Skipping outdated lock on KeyColumn [k=0x0-0-0-0-0-3-169-144, c=0x40] with our rid (192-168-109-128-49-64-50-55-49-55-64-115-97-110-100-98-111-120-46-104-111-114-116-111-110-119-111-114-107-115-46-99-111-109) but mismatched timestamp (actual ts 1387755332269764361, expected ts 1387755502334342679)
ERROR com.thinkaurelius.titan.diskstorage.locking.consistentkey.ConsistentKeyLocker  - Exception while deleting lock on KeyColumn [k=0x0-0-0-0-0-3-169-144, c=0x40]
java.lang.IllegalArgumentException: Row length is 0
    at org.apache.hadoop.hbase.client.Mutation.checkRow(Mutation.java:413)

**Comment by ghost** [comment]
Updated pull request to handle the issue.

**Comment by a2prn** [comment]
I have installed hadoop-2.2.0.2.0.6.0-76 and hbase-0.96.0.2.0.6.0-76-hadoop2 of HDP2 on solaris 10 and "titan-master" from github. Made changes in HBaseStoreManager.java and titan-hbase/pom.xml and then I run:                           "mvn clean install -Dhadoop.profile=2.0 -Dhadoop.version=2.2.0 -DskipTests=true"

It is completed successfully. 

when I am trying to run titan-master using ./gremlin.sh. 

gremlin> conf = new BaseConfiguration();
==>org.apache.commons.configuration.BaseConfiguration@.....
gremlin> conf.setProperty("storage.backend","hbase");
==>null
gremlin> conf.setProperty("storage.hostname","my-hostname");
==>null
gremlin> conf.setProperty("storage.port","2181");
==>null
gremlin> g = TitanFactory.open(conf);

It is giving me an ERROR:

Not a host:port pair: PBUF

```
    localhost????(
```

**Comment by mbroecheler** [comment]
Maybe the changes you made require that the hostname have a ":port"
appendix?

On Sat, Jan 4, 2014 at 7:42 PM, a2prn notifications@github.com wrote:

> I have installed hadoop-2.2.0.2.0.6.0-76 and
> hbase-0.96.0.2.0.6.0-76-hadoop2 of HDP2 on solaris 10 and "titan-master"
> from github. Made changes in HBaseStoreManager.java and titan-hbase/pom.xml
> and then I run: "mvn clean install -Dhadoop.profile=2.0
> -Dhadoop.version=2.2.0 -DskipTests=true"
> 
> It is completed successfully.
> 
> when I am trying to run titan-master using ./gremlin.sh.
> 
> gremlin> conf = new BaseConfiguration();
> ==>org.apache.commons.configuration.BaseConfiguration@.....
> 
> gremlin> conf.setProperty("storage.backend","hbase");
> ==>null
> gremlin> conf.setProperty("storage.hostname","my-hostname");
> 
> ==>null
> gremlin> conf.setProperty("storage.port","2181");
> ==>null
> gremlin> g = TitanFactory.open(conf);
> 
> It is giving me an ERROR:
> 
> Not a host:port pair: PBUF
> 
> ```
> localhost????(
> ```
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/526#issuecomment-31595532
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by a2prn** [comment]
I have tried giving hostname:port pair. The ERROR I received is:

g = TitanFactory.open(conf)
Not a host:port pair: PBUF

```
    localhost?????(
```

Display stack trace? [yN] Y
java.lang.IllegalArgumentException: Not a host:port pair: PBUF

```
    localhost?????(
```

**Comment by ghost** [comment]
@a2prn That's pretty strange if you followed my instructions. The error you get was the same as I found being the symptom for using the 0.94 HBase libraries.

**Comment by a2prn** [comment]
I have added the libraries that are required for hbase-0.96.0.2.0.6.0-76-hadoop2 and reconfigure with changes in HBaseStoreManager.java and titan-hbase/pom.xml and then I run: "mvn clean install -Dhadoop.profile=2.0 -Dhadoop.version=2.2.0 -DskipTests=true"

It is completed successfully.

when I am trying to run titan-master using ./gremlin.sh.

gremlin> conf = new BaseConfiguration();
==>org.apache.commons.configuration.BaseConfiguration@.....
gremlin> conf.setProperty("storage.backend","hbase");
==>null
gremlin> conf.setProperty("storage.hostname","my-hostname");
==>null
gremlin> conf.setProperty("storage.port","2181");
==>null
gremlin> g = TitanFactory.open(conf);

The previous Error was not there but I got below ERROR:

ERROR org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper  - ZooKeeper exists failed after 3 retries
WARN  org.apache.hadoop.hbase.zookeeper.ZKUtil  - hconnection Unable to set watcher on znode (/hbase/hbaseid)
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1041)
        at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:172)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:450)
        at org.apache.hadoop.hbase.zookeeper.ClusterId.readClusterIdZNode(ClusterId.java:61)
        at org.apache.hadoop.hbase.zookeeper.ClusterId.getId(ClusterId.java:50)
        at org.apache.hadoop.hbase.zookeeper.ClusterId.hasId(ClusterId.java:44)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.ensureZookeeperTrackers(HConnectionManager.java:720)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getMaster(HConnectionManager.java:789)
        at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:127)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.getAdminInterface(HBaseStoreManager.java:364)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.ensureColumnFamilyExists(HBaseStoreManager.java:261)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.openDatabase(HBaseStoreManager.java:215)
        at com.thinkaurelius.titan.diskstorage.Backend.getStore(Backend.java:222)
        at com.thinkaurelius.titan.diskstorage.Backend.initialize(Backend.java:234)
        at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1109)
        at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:75)
        at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
        at com.thinkaurelius.titan.core.TitanFactory$open.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at groovysh_evaluate.run(groovysh_evaluate:56)
        at groovysh_evaluate$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
        at groovysh_evaluate$run.call(Unknown Source)
        at org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:67)
        at org.codehaus.groovy.tools.shell.Interpreter$evaluate.call(Unknown Source)
        at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:152)
        at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:114)
        at org.codehaus.groovy.tools.shell.Shell$leftShift$0.call(Unknown Source)
        at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:88)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:100)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
        at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:57)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:66)
        at com.thinkaurelius.titan.tinkerpop.gremlin.Console.<init>(Console.java:57)
        at com.thinkaurelius.titan.tinkerpop.gremlin.Console.<init>(Console.java:70)
        at com.thinkaurelius.titan.tinkerpop.gremlin.Console.main(Console.java:96)
ERROR org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher  - hconnection Received unexpected KeeperException, re-throwing exception
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/hbaseid
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1041)
        at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:172)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:450)
        at org.apache.hadoop.hbase.zookeeper.ClusterId.readClusterIdZNode(ClusterId.java:61)
        at org.apache.hadoop.hbase.zookeeper.ClusterId.getId(ClusterId.java:50)
        at org.apache.hadoop.hbase.zookeeper.ClusterId.hasId(ClusterId.java:44)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.ensureZookeeperTrackers(HConnectionManager.java:720)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getMaster(HConnectionManager.java:789)
        at org.apache.hadoop.hbase.client.HBaseAdmin.<init>(HBaseAdmin.java:127)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.getAdminInterface(HBaseStoreManager.java:364)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.ensureColumnFamilyExists(HBaseStoreManager.java:261)
        at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.openDatabase(HBaseStoreManager.java:215)
        at com.thinkaurelius.titan.diskstorage.Backend.getStore(Backend.java:222)
        at com.thinkaurelius.titan.diskstorage.Backend.initialize(Backend.java:234)
        at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1109)
        at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:75)
        at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
        at com.thinkaurelius.titan.core.TitanFactory$open.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at groovysh_evaluate.run(groovysh_evaluate:56)
        at groovysh_evaluate$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
        at groovysh_evaluate$run.call(Unknown Source)
        at org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:67)
        at org.codehaus.groovy.tools.shell.Interpreter$evaluate.call(Unknown Source)
        at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:152)
        at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:114)
        at org.codehaus.groovy.tools.shell.Shell$leftShift$0.call(Unknown Source)
        at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:88)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:100)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
        at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:57)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:66)
        at com.thinkaurelius.titan.tinkerpop.gremlin.Console.<init>(Console.java:57)
        at com.thinkaurelius.titan.tinkerpop.gremlin.Console.<init>(Console.java:70)
        at com.thinkaurelius.titan.tinkerpop.gremlin.Console.main(Console.java:96)
WARN  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper  - Possibly transient ZooKeeper exception: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/master

**Comment by a2prn** [comment]
Just wondering, if their is any update.

**Comment by ghost** [comment]
@a2prn,

this seems like it's something else unrelated to this ticket. I would guess configuration issues.

**Comment by dalaro** [comment]
Thank you for working on this and turning it into a pull request.  I'm closing this since I think we hit our objectives via #539.

@a2prn, I'm not sure what the issue was there either, but on current titan05 HEAD, you could try:

```
mvn clean install -pl titan-hbase/titan-hbase-096 -am -DskipTests=true
mvn clean install -pl titan-dist # copies jars for bin/gremlin.sh, don't skip this step
bin/gremlin.sh
```

Please open a new issue if that's broken.
