### ISSUE TITLE
Repeatedly opening and closing the database using the Astyanax adapter leads to Socket Error

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#54]
Verified that Titan does properly clean up all Astyanax resources and filed an issue with Astyanax:
https://github.com/Netflix/astyanax/issues/105

The exception is:

6325301 [RetryService : 10.101.41.184(10.101.41.184):9160] DEBUG com.netflix.astyanax.thrift.ThriftConverter - Too many open files
6325301 [RetryService : 10.101.41.184(10.101.41.184):9160] ERROR org.apache.thrift.transport.TSocket - Could not configure socket.
java.net.SocketException: Too many open files
at java.net.Socket.createImpl(Socket.java:414)
at java.net.Socket.getImpl(Socket.java:477)
at java.net.Socket.setSoLinger(Socket.java:918)
at org.apache.thrift.transport.TSocket.initSocket(TSocket.java:116)
at org.apache.thrift.transport.TSocket.(TSocket.java:107)
at com.netflix.astyanax.thrift.ThriftSyncConnectionFactoryImpl$1.open(ThriftSyncConnectionFactoryImpl.java:156)
at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.reconnect(SimpleHostConnectionPool.java:314)
at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.access$100(SimpleHostConnectionPool.java:59)
at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool$1.run(SimpleHostConnectionPool.java:285)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
at java.util.concurrent.FutureTask.run(FutureTask.java:166)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:165)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
at java.lang.Thread.run(Thread.java:679)

**Comment by mbroecheler** [comment]
see: https://github.com/Netflix/astyanax/issues/105
