### ISSUE TITLE
Facing "Could not initialize backend" Error on titan-0.3.2 while connecting to Hbase-0.94.1 on Ubuntu-12.0.4 Desktop.

### ISSUE THREAD

**Issue by a2prn** [thinkaurelius/titan#558]
Hi All,

```
 I have first Installed hadoop-1.0.3 and Hbase-0.94.1 on Ubuntu-12.04 Desktop in Standalone mode and then Installed titan-all-0.3.2 for storing database generated on titan to be stored on Hbase. Then run gremlin.sh inside titan-all-0.3.2. After that entered below commands:
```

conf = new BaseConfiguration()
conf.setProperty("storage.backend","hbase")
conf.setProperty("storage.hostname","127.0.0.1")
conf.setProperty("storage.port","2181")
conf.setProperty("storage.tablename","titan")
g = TitanFactory.open(conf)

After running last command I have faced below error:

INFO zookeeper.ClientCnxn: Socket connection established to localhost/127.0.0.1:2181, initiating session
INFO zookeeper.ClientCnxn: Session establishment complete on server 127.0.0.1:2181, sessionid = 0x14399d264b10004, negotiated timeout = 180000
 INFO zookeeper.ZooKeeper: Session: 0x14399d264b10004 closed
INFO zookeeper.ClientCnxn: EventThread shut down
Could not initialize backend
Display stack trace? [yN] y
com.thinkaurelius.titan.core.TitanException: Could not initialize backend
    at com.thinkaurelius.titan.diskstorage.Backend.initialize(Backend.java:210)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:441)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:67)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
    at com.thinkaurelius.titan.core.TitanFactory$open.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at groovysh_evaluate.run(groovysh_evaluate:56)
    at groovysh_evaluate$run.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at groovysh_evaluate$run.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:67)
    at org.codehaus.groovy.tools.shell.Interpreter$evaluate.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:152)
    at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:114)
    at org.codehaus.groovy.tools.shell.Shell$leftShift$0.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:88)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:100)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
    at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:57)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:66)
    at com.thinkaurelius.titan.tinkerpop.gremlin.Console.<init>(Console.java:65)
    at com.thinkaurelius.titan.tinkerpop.gremlin.Console.<init>(Console.java:78)
    at com.thinkaurelius.titan.tinkerpop.gremlin.Console.main(Console.java:104)
Caused by: com.thinkaurelius.titan.diskstorage.TemporaryStorageException: Temporary failure in storage backend
    at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.ensureTableExists(HBaseStoreManager.java:191)
    at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.ensureColumnFamilyExists(HBaseStoreManager.java:199)
    at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.openDatabase(HBaseStoreManager.java:170)
    at com.thinkaurelius.titan.diskstorage.Backend.getStore(Backend.java:162)
    at com.thinkaurelius.titan.diskstorage.Backend.initialize(Backend.java:173)
    ... 50 more
Caused by: org.apache.hadoop.hbase.client.NoServerForRegionException: Unable to find region for  after 10 tries.
    at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegionInMeta(HConnectionManager.java:936)
    at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:841)
    at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:810)
    at org.apache.hadoop.hbase.client.HTable.finishSetup(HTable.java:232)
    at org.apache.hadoop.hbase.client.HTable.<init>(HTable.java:172)
    at org.apache.hadoop.hbase.catalog.MetaReader.getHTable(MetaReader.java:200)
    at org.apache.hadoop.hbase.catalog.MetaReader.getMetaHTable(MetaReader.java:226)
    at org.apache.hadoop.hbase.catalog.MetaReader.fullScan(MetaReader.java:705)
    at org.apache.hadoop.hbase.catalog.MetaReader.fullScan(MetaReader.java:183)
    at org.apache.hadoop.hbase.catalog.MetaReader.tableExists(MetaReader.java:448)
    at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:233)
    at com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.ensureTableExists(HBaseStoreManager.java:184)
    ... 54 more

**Comment by mbroecheler** [comment]
In you configuration, you are telling Titan to connect to HBase on
localhost (given your hostname) - hence you need to ensure that HBase is
running on localhost and accepting connections.

On Wed, Jan 15, 2014 at 11:19 PM, a2prn notifications@github.com wrote:

> Hi All,
> 
>  I have first Installed hadoop-1.0.3 and Hbase-0.94.1 on Ubuntu-12.04 Desktop in Standalone mode and then Installed titan-all-0.3.2 for storing database generated on titan to be stored on Hbase. Then run gremlin.sh inside titan-all-0.3.2. After that entered below commands:
> 
> conf = new BaseConfiguration()
> conf.setProperty("storage.backend","hbase")
> conf.setProperty("storage.hostname","127.0.0.1")
> conf.setProperty("storage.port","2181")
> conf.setProperty("storage.tablename","titan")
> g = TitanFactory.open(conf)
> 
> After running last command I have faced below error:
> 
> INFO zookeeper.ClientCnxn: Socket connection established to localhost/
> 127.0.0.1:2181, initiating session
> INFO zookeeper.ClientCnxn: Session establishment complete on server
> 127.0.0.1:2181, sessionid = 0x14399d264b10004, negotiated timeout = 180000
> INFO zookeeper.ZooKeeper: Session: 0x14399d264b10004 closed
> INFO zookeeper.ClientCnxn: EventThread shut down
> Could not initialize backend
> Display stack trace? [yN] y
> com.thinkaurelius.titan.core.TitanException: Could not initialize backend
> at com.thinkaurelius.titan.diskstorage.Backend.initialize(Backend.java:210)
> at
> com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:441)
> at
> com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.(StandardTitanGraph.java:67)
> at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
> at com.thinkaurelius.titan.core.TitanFactory$open.call(Unknown Source)
> at
> org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
> at
> org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
> at
> org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
> at groovysh_evaluate.run(groovysh_evaluate:56)
> at groovysh_evaluate$run.call(Unknown Source)
> at
> org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
> at groovysh_evaluate$run.call(Unknown Source)
> at
> org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:67)
> at org.codehaus.groovy.tools.shell.Interpreter$evaluate.call(Unknown
> Source)
> at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:152)
> at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:114)
> at org.codehaus.groovy.tools.shell.Shell$leftShift$0.call(Unknown Source)
> at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:88)
> at
> org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> at
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:606)
> at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
> at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
> at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
> at
> org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
> at
> org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
> at
> org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:100)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> at
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:606)
> at
> org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
> at
> org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
> at
> org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
> at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:57)
> at
> org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> at
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:606)
> at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
> at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
> at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
> at
> org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
> at
> org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
> at
> org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:66)
> at com.thinkaurelius.titan.tinkerpop.gremlin.Console.(Console.java:65)
> at com.thinkaurelius.titan.tinkerpop.gremlin.Console.(Console.java:78)
> at com.thinkaurelius.titan.tinkerpop.gremlin.Console.main(Console.java:104)
> Caused by: com.thinkaurelius.titan.diskstorage.TemporaryStorageException:
> Temporary failure in storage backend
> at
> com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.ensureTableExists(HBaseStoreManager.java:191)
> at
> com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.ensureColumnFamilyExists(HBaseStoreManager.java:199)
> at
> com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.openDatabase(HBaseStoreManager.java:170)
> at com.thinkaurelius.titan.diskstorage.Backend.getStore(Backend.java:162)
> at com.thinkaurelius.titan.diskstorage.Backend.initialize(Backend.java:173)
> ... 50 more
> Caused by: org.apache.hadoop.hbase.client.NoServerForRegionException:
> Unable to find region for after 10 tries.
> at
> org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegionInMeta(HConnectionManager.java:936)
> at
> org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:841)
> at
> org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:810)
> at org.apache.hadoop.hbase.client.HTable.finishSetup(HTable.java:232)
> at org.apache.hadoop.hbase.client.HTable.(HTable.java:172)
> at
> org.apache.hadoop.hbase.catalog.MetaReader.getHTable(MetaReader.java:200)
> at
> org.apache.hadoop.hbase.catalog.MetaReader.getMetaHTable(MetaReader.java:226)
> at org.apache.hadoop.hbase.catalog.MetaReader.fullScan(MetaReader.java:705)
> at org.apache.hadoop.hbase.catalog.MetaReader.fullScan(MetaReader.java:183)
> at
> org.apache.hadoop.hbase.catalog.MetaReader.tableExists(MetaReader.java:448)
> at
> org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:233)
> at
> com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager.ensureTableExists(HBaseStoreManager.java:184)
> ... 54 more
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/558
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by a2prn** [comment]
Yes. In my configuration I am running HBase on localhost.

**Comment by mbroecheler** [comment]
Mmh, then there is something wrong with your local HBase instance or the
configuration because Titan cannot find the running instance to connect
to... Did you change anything for the local HBase? Ports or such?

On Mon, Jan 20, 2014 at 9:09 PM, a2prn notifications@github.com wrote:

> Yes. In my configuration I am running HBase on localhost.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/558#issuecomment-32821933
> .

## 

Matthias Broecheler
http://www.matthiasb.com
