### ISSUE TITLE
kryo related problem breaks query

### ISSUE THREAD

**Issue by cfcodefans** [thinkaurelius/titan#601]
Hi, all

I encounter a wired problem as testing titan's feature for concept approval.

Basically what i do is to use titan+cassandra to create a bunch of vertex and query them.
version is : 
        <dependency>
            <groupId>com.thinkaurelius.titan</groupId>
            <artifactId>titan-core</artifactId>
            <version>0.4.2</version>
        </dependency>

//at first:

```
    conf = new BaseConfiguration();
    conf.setProperty("storage.backend", "cassandra");
    conf.setProperty("storage.keyspace", "titan25");
    conf.setProperty("storage.hostname", "127.0.0.1");
    conf.setProperty("storage.cassandra-config-dir", "config/cassandra.yaml");
    tg = TitanFactory.open(conf);
```

//then create key on property like
//somewhere
//static  String PROPERTY_UID = "uid";
        if (tg.getType(IUserOpers.PROPERTY_UID) == null) {
                            tg.makeKey(IUserOpers.PROPERTY_UID).dataType(Long.class).unique().indexed(Vertex.class).make();//.indexed("search", Vertex.class).unique().make();
            log.info("\n\t\tinitialize key uid");
        }

//then query it
        TitanTransaction tt = tg.newTransaction();//tg.getVertices(key, value)
        final TitanVertex uv = tt.getVertex(PROPERTY_UID, uid);
        tt.commit();
        return uv;

there I got exception thrown from kryo.
com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 54
Serialization trace:
value (com.thinkaurelius.titan.graphdb.types.TypeAttribute)
    at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119)
    at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:610)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:721)
    at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:338)
    at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:293)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:648)
    at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:605)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:221)
    at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:626)
    at com.thinkaurelius.titan.graphdb.database.serialize.kryo.KryoSerializer.readObjectNotNull(KryoSerializer.java:118)
    at com.thinkaurelius.titan.graphdb.database.EdgeSerializer.parseRelation(EdgeSerializer.java:211)
    at com.thinkaurelius.titan.graphdb.database.EdgeSerializer.readRelation(EdgeSerializer.java:119)
    at com.thinkaurelius.titan.graphdb.database.EdgeSerializer.readRelation(EdgeSerializer.java:59)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$4$3.apply(StandardTitanTx.java:780)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$4$3.apply(StandardTitanTx.java:777)
    at com.google.common.collect.Iterators$8.transform(Iterators.java:860)
    at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
    at com.thinkaurelius.titan.graphdb.query.LimitAdjustingIterator.next(LimitAdjustingIterator.java:55)
    at com.thinkaurelius.titan.graphdb.query.QueryProcessor$OuterIterator.nextInternal(QueryProcessor.java:76)
    at com.thinkaurelius.titan.graphdb.query.QueryProcessor$OuterIterator.next(QueryProcessor.java:88)
    at com.thinkaurelius.titan.graphdb.query.QueryProcessor$OuterIterator.next(QueryProcessor.java:49)
    at com.thinkaurelius.titan.graphdb.types.vertices.TitanTypeVertex.getDefinition(TitanTypeVertex.java:40)
    at com.thinkaurelius.titan.graphdb.types.vertices.TitanKeyVertex.getDataType(TitanKeyVertex.java:30)
    at com.thinkaurelius.titan.graphdb.query.QueryUtil.constraints2QNF(QueryUtil.java:161)
    at com.thinkaurelius.titan.graphdb.query.GraphCentricQueryBuilder.constructQuery(GraphCentricQueryBuilder.java:163)
    at com.thinkaurelius.titan.graphdb.query.GraphCentricQueryBuilder.vertices(GraphCentricQueryBuilder.java:139)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.getVertices(StandardTitanTx.java:983)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.getVertices(TitanBlueprintsTransaction.java:102)

wired part is this occurs randomly, I drop the key space in cassandra, run the test, it works for first two rounds of test, the third time it always fails, and I run some more rounds, some times it works, some times it fails.

the ID 54 in this log varies when it fails:
com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 54
Serialization trace:
value (com.thinkaurelius.titan.graphdb.types.TypeAttribute)

I am checking the titan and kryo code for answer, would anybody give some hint? 

Thanks in advance.

**Comment by mbroecheler** [comment]
Yes, that's very bizarre. It suggests that something is going wrong with
the serialization. The fact that its random is suprising though. That makes
it more likely a data corruption issue but I have no idea how that would be
triggered.

Do you have a complete test case that reproduces this?
Thanks,
Matthias

On Sun, Feb 23, 2014 at 9:40 PM, cfcodefans notifications@github.comwrote:

> Hi, all
> 
> I encounter a wired problem as testing titan's feature for concept
> approval.
> 
> Basically what i do is to use titan+cassandra to create a bunch of vertex
> and query them.
> //at first:
> 
> ```
> conf = new BaseConfiguration();
> conf.setProperty("storage.backend", "cassandra");
> conf.setProperty("storage.keyspace", "titan25");
> conf.setProperty("storage.hostname", "127.0.0.1");
> conf.setProperty("storage.cassandra-config-dir", "config/cassandra.yaml");
> ```
> 
> tg = TitanFactory.open(conf);
> 
> //then create key on property like
> //somewhere
> //static String PROPERTY_UID = "uid";
> if (tg.getType(IUserOpers.PROPERTY_UID) == null) {
> tg.makeKey(IUserOpers.PROPERTY_UID).dataType(Long.class).unique().indexed(Vertex.class).make();//.indexed("search",
> Vertex.class).unique().make();
> log.info("\n\t\tinitialize key uid");
> }
> 
> //then query it
> TitanTransaction tt = tg.newTransaction();//tg.getVertices(key, value)
> final TitanVertex uv = tt.getVertex(PROPERTY_UID, uid);
> tt.commit();
> return uv;
> 
> there I got exception thrown from kryo.
> com.esotericsoftware.kryo.KryoException: Encountered unregistered class
> ID: 54
> Serialization trace:
> value (com.thinkaurelius.titan.graphdb.types.TypeAttribute)
> at
> com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119)
> at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:610)
> at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:721)
> at
> com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:338)
> at
> com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:293)
> at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:648)
> at
> com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:605)
> at
> com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:221)
> at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:626)
> at
> com.thinkaurelius.titan.graphdb.database.serialize.kryo.KryoSerializer.readObjectNotNull(KryoSerializer.java:118)
> at
> com.thinkaurelius.titan.graphdb.database.EdgeSerializer.parseRelation(EdgeSerializer.java:211)
> at
> com.thinkaurelius.titan.graphdb.database.EdgeSerializer.readRelation(EdgeSerializer.java:119)
> at
> com.thinkaurelius.titan.graphdb.database.EdgeSerializer.readRelation(EdgeSerializer.java:59)
> at
> com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$4$3.apply(StandardTitanTx.java:780)
> at
> com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$4$3.apply(StandardTitanTx.java:777)
> at com.google.common.collect.Iterators$8.transform(Iterators.java:860)
> at
> com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
> at
> com.thinkaurelius.titan.graphdb.query.LimitAdjustingIterator.next(LimitAdjustingIterator.java:55)
> at
> com.thinkaurelius.titan.graphdb.query.QueryProcessor$OuterIterator.nextInternal(QueryProcessor.java:76)
> at
> com.thinkaurelius.titan.graphdb.query.QueryProcessor$OuterIterator.next(QueryProcessor.java:88)
> at
> com.thinkaurelius.titan.graphdb.query.QueryProcessor$OuterIterator.next(QueryProcessor.java:49)
> at
> com.thinkaurelius.titan.graphdb.types.vertices.TitanTypeVertex.getDefinition(TitanTypeVertex.java:40)
> at
> com.thinkaurelius.titan.graphdb.types.vertices.TitanKeyVertex.getDataType(TitanKeyVertex.java:30)
> at
> com.thinkaurelius.titan.graphdb.query.QueryUtil.constraints2QNF(QueryUtil.java:161)
> at
> com.thinkaurelius.titan.graphdb.query.GraphCentricQueryBuilder.constructQuery(GraphCentricQueryBuilder.java:163)
> at
> com.thinkaurelius.titan.graphdb.query.GraphCentricQueryBuilder.vertices(GraphCentricQueryBuilder.java:139)
> at
> com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.getVertices(StandardTitanTx.java:983)
> at
> com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.getVertices(TitanBlueprintsTransaction.java:102)
> 
> wired part is this occurs randomly, I drop the key space in cassandra, run
> the test, it works for first two rounds of test, the third time it always
> fails, and I run some more rounds, some times it works, some times it fails.
> 
> the ID 54 in this log varies when it fails:
> com.esotericsoftware.kryo.KryoException: Encountered unregistered class
> ID: 54
> Serialization trace:
> value (com.thinkaurelius.titan.graphdb.types.TypeAttribute)
> 
> I am checking the titan and kryo code for answer, would anybody give some
> hint?
> 
> Thanks in advance.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/601
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by mbroecheler** [comment]
Another reason this could happen: You created the graph with Titan 0.4.2 but opened it with an older version.

**Comment by mbroecheler** [comment]
The only way I was able to reproduce this is creating a graph with Titan 0.4.2 and opening it with 0.4.1. Make sure that all instances of Titan are running on the latest version as documented in the UPGRADE file that comes with Titan.
