### ISSUE TITLE
java.lang.IllegalStateException: Could not find type for id: 130

### ISSUE THREAD

**Issue by anvie** [thinkaurelius/titan#610]
I just use Titan 0.4.2 when using IdGraph:

``` scala
val titanDb = TitanFactory.open(config)
val rv = new IdGraph(titanDb, true, false)
```

Sometimes work and sometimes got this error:

```
Exception in thread "main" java.lang.IllegalStateException: Could not find type for id: 130
        at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
        at com.thinkaurelius.titan.graphdb.types.vertices.TitanTypeVertex.getName(TitanTypeVertex.java:30)
        at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$VertexConstructor.get(StandardTitanTx.java:321)
        at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$VertexConstructor.get(StandardTitanTx.java:291)
        at com.thinkaurelius.titan.graphdb.transaction.vertexcache.GuavaVertexCache.get(GuavaVertexCache.java:60)
        at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.getExistingVertex(StandardTitanTx.java:288)
        at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$6.apply(StandardTitanTx.java:956)
        at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$6.apply(StandardTitanTx.java:951)
        at com.google.common.collect.Iterators$8.transform(Iterators.java:860)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at com.thinkaurelius.titan.graphdb.query.LimitAdjustingIterator.next(LimitAdjustingIterator.java:55)
        at com.thinkaurelius.titan.graphdb.query.QueryProcessor$OuterIterator.nextInternal(QueryProcessor.java:76)
        at com.thinkaurelius.titan.graphdb.query.QueryProcessor$OuterIterator.<init>(QueryProcessor.java:65)
        at com.thinkaurelius.titan.graphdb.query.QueryProcessor.iterator(QueryProcessor.java:46)
        at com.google.common.collect.Iterables$7.iterator(Iterables.java:613)
        at com.google.common.collect.Iterables$7.iterator(Iterables.java:613)
        at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.getIndexedKeys(TitanBlueprintsTransaction.java:231)
        at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.getIndexedKeys(TitanBlueprintsGraph.java:150)
        at com.tinkerpop.blueprints.util.wrappers.id.IdGraph.createIndices(IdGraph.java:409)
        at com.tinkerpop.blueprints.util.wrappers.id.IdGraph.<init>(IdGraph.java:84)
```

**Comment by mbroecheler** [comment]
You are either operating on a different graph or there was a data
corruption on your graph data. Titan is trying to retrieve information on
an existing type but cannot find the data.

On Thu, Mar 13, 2014 at 6:05 PM, Robin Syihab notifications@github.comwrote:

> I just use Titan 0.4.2 when using IdGraph:
> 
> val titanDb = TitanFactory.open(config)val rv = new IdGraph(titanDb, true, false)
> 
> Sometimes work and sometimes got this error:
> 
> Exception in thread "main" java.lang.IllegalStateException: Could not find type for id: 130
>         at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
>         at com.thinkaurelius.titan.graphdb.types.vertices.TitanTypeVertex.getName(TitanTypeVertex.java:30)
>         at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$VertexConstructor.get(StandardTitanTx.java:321)
>         at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$VertexConstructor.get(StandardTitanTx.java:291)
>         at com.thinkaurelius.titan.graphdb.transaction.vertexcache.GuavaVertexCache.get(GuavaVertexCache.java:60)
>         at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.getExistingVertex(StandardTitanTx.java:288)
>         at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$6.apply(StandardTitanTx.java:956)
>         at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$6.apply(StandardTitanTx.java:951)
>         at com.google.common.collect.Iterators$8.transform(Iterators.java:860)
>         at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
>         at com.thinkaurelius.titan.graphdb.query.LimitAdjustingIterator.next(LimitAdjustingIterator.java:55)
>         at com.thinkaurelius.titan.graphdb.query.QueryProcessor$OuterIterator.nextInternal(QueryProcessor.java:76)
>         at com.thinkaurelius.titan.graphdb.query.QueryProcessor$OuterIterator.<init>(QueryProcessor.java:65)
>         at com.thinkaurelius.titan.graphdb.query.QueryProcessor.iterator(QueryProcessor.java:46)
>         at com.google.common.collect.Iterables$7.iterator(Iterables.java:613)
>         at com.google.common.collect.Iterables$7.iterator(Iterables.java:613)
>         at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.getIndexedKeys(TitanBlueprintsTransaction.java:231)
>         at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.getIndexedKeys(TitanBlueprintsGraph.java:150)
>         at com.tinkerpop.blueprints.util.wrappers.id.IdGraph.createIndices(IdGraph.java:409)
>         at com.tinkerpop.blueprints.util.wrappers.id.IdGraph.<init>(IdGraph.java:84)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/610
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by anvie** [comment]
yeah it's looks like index data was loss after some cassandra node down abnormally even the replication factor = 3, is there any way to fix this?

**Comment by mbroecheler** [comment]
Hi Robin,

was the data completely lost or is there a configuration issue where the
data is not replayed correctly to the restarted node?
If the data is actually lost, there isn't much to restore it. However, with
a properly configured cluster in RF=3 data loss should not occur and there
is an issue with the configuration.

HTH,
Matthias

On Wed, Mar 26, 2014 at 5:06 PM, Robin Syihab notifications@github.comwrote:

> yeah it's looks like index data was loss after some cassandra node down
> abnormally even the replication factor = 3, is there any way to fix this?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/thinkaurelius/titan/issues/610#issuecomment-38702956
> .

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by anvie** [comment]
I have no idea, I think this is because I'm running 3 nodes cassandra in a single machine, after re-setup cassandra nodes in different 3 machines with the same configuration this problem went away, at least until now I don't see this issue anymore.

Thx.
--robin
