### ISSUE TITLE
Error while commiting index mutations for transaction on index: search

### ISSUE THREAD

**Issue by ksmets** [thinkaurelius/titan#686]
I'm testing out the 5.0-branch and got the following exception when updating properties of existing edges that are indexed using elasticsearch.

```
54634 [Thread-15-b-1] ERROR com.thinkaurelius.titan.graphdb.database.StandardTitanGraph - Error while commiting index mutations for transaction [3] on index: search
com.thinkaurelius.titan.core.TitanException: Could not execute operation due to backend exception
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:44) ~[titan-core-0.5.0-SNAPSHOT.jar:na]
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.flushInternal(IndexTransaction.java:109) ~[titan-core-0.5.0-SNAPSHOT.jar:na]
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.commit(IndexTransaction.java:90) ~[titan-core-0.5.0-SNAPSHOT.jar:na]
    at com.thinkaurelius.titan.diskstorage.BackendTransaction.commitIndexes(BackendTransaction.java:115) ~[titan-core-0.5.0-SNAPSHOT.jar:na]
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.commit(StandardTitanGraph.java:634) ~[titan-core-0.5.0-SNAPSHOT.jar:na]
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.commit(StandardTitanTx.java:1219) [titan-core-0.5.0-SNAPSHOT.jar:na]
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.commit(TitanBlueprintsGraph.java:60) [titan-core-0.5.0-SNAPSHOT.jar:na]
    at com.tinkerpop.blueprints.util.wrappers.id.IdGraph.commit(IdGraph.java:274) [blueprints-core-2.5.0.jar:na]
    at com.tinkerpop.frames.FramedTransactionalGraph.commit(FramedTransactionalGraph.java:25) [frames-2.5.0.jar:na]

...
Caused by: java.lang.IllegalArgumentException: null
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:77) ~[guava-15.0.jar:na]
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.mutate(ElasticSearchIndex.java:352) ~[titan-es-0.5.0-SNAPSHOT.jar:na]
```

Debugging in Eclipse shows that isDeleted is set to true (while I'd expected this to be false, since I didn't delete any edge!), the hasDeletions() evaluates to false (empty list of deletions), and additions contains the correct list of changes.

Note that TitanGraph, is wrapped using IDGraph, and IDGraph.ID property keys are created for both edges and vertices.

I quickly tried reproducing the error by exteding the GraphOfTheGods example graph, with an additional transaction, but that did _not_ trigger the exception.

I'm able to get the expected results if I change the precondition check to:

```
--- a/titan-es/src/main/java/com/thinkaurelius/titan/diskstorage/es/ElasticSearchIndex.java
+++ b/titan-es/src/main/java/com/thinkaurelius/titan/diskstorage/es/ElasticSearchIndex.java
@@ -349,7 +349,8 @@ public class ElasticSearchIndex implements IndexProvider {
                     assert mutation.isConsolidated();
                     Preconditions.checkArgument(!(mutation.isNew() && mutation.isDeleted()));
                     Preconditions.checkArgument(!mutation.isNew() || !mutation.hasDeletions());
-                    Preconditions.checkArgument(!mutation.isDeleted() || !mutation.hasAdditions());
+                    //Preconditions.checkArgument(!mutation.isDeleted() || !mutation.hasAdditions());
+                   Preconditions.checkArgument(!mutation.hasDeletions() || !mutation.hasAdditions());
                     //Deletions first
                     if (mutation.hasDeletions()) {
                         if (mutation.isDeleted()) {
```

**Comment by mbroecheler** [comment]
Changing the encoding to be case insensitive should fix this.
