### ISSUE TITLE
Unable to enable batch-loading in Titan-0.5-M3 with BerkeleyDB

### ISSUE THREAD

**Issue by fitzoh** [thinkaurelius/titan#699]
This 

```
public class Main {
    public static void main(String[] args){
        TitanGraph g = TitanFactory.build()
                .set("storage.backend", "berkeleyje")
                .set("storage.directory", "graph").open();
        g.shutdown();
    }
}
```

Works fine, while this

```
public class Main {
    public static void main(String[] args){
        TitanGraph g = TitanFactory.build()
                .set("storage.backend", "berkeleyje")
                .set("storage.directory", "graph")
                .set("storage.batch-loading", true).open();
        g.shutdown();
    }
}
```

Throws a backend exception

```
Exception in thread "main" com.thinkaurelius.titan.core.TitanException: Could not execute operation due to backend exception
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:44)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:144)
    at com.thinkaurelius.titan.diskstorage.configuration.backend.KCVSConfiguration.get(KCVSConfiguration.java:85)
    at com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration.<init>(BasicConfiguration.java:36)
    at com.thinkaurelius.titan.diskstorage.configuration.ModifiableConfiguration.<init>(ModifiableConfiguration.java:17)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1221)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:92)
    at com.thinkaurelius.titan.core.TitanFactory$Builder.open(TitanFactory.java:134)
    at Main.main(Main.java:12)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: com.thinkaurelius.titan.diskstorage.PermanentBackendException: Permanent exception while executing backend operation getConfiguration
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:69)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:42)
    ... 13 more
Caused by: java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:192)
    at com.thinkaurelius.titan.diskstorage.berkeleyje.BerkeleyJETx.<init>(BerkeleyJETx.java:31)
    at com.thinkaurelius.titan.diskstorage.berkeleyje.BerkeleyJEStoreManager.beginTransaction(BerkeleyJEStoreManager.java:136)
    at com.thinkaurelius.titan.diskstorage.berkeleyje.BerkeleyJEStoreManager.beginTransaction(BerkeleyJEStoreManager.java:34)
    at com.thinkaurelius.titan.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreManagerAdapter.beginTransaction(OrderedKeyValueStoreManagerAdapter.java:52)
    at com.thinkaurelius.titan.diskstorage.Backend$3.openTx(Backend.java:394)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:131)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation$1.call(BackendOperation.java:147)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:56)
    ... 14 more
```

**Comment by dalaro** [comment]
@Fitzoh thanks for the report.  As @mbroecheler pointed out off-list, this precondition is absent in master, and it doesn't really make sense for BDB, which uses a null tx to signify an atransactional context (e.g. when transactions are disabled).  Deleted the precondition and modified the toString implementation to handle a null tx.
