### ISSUE TITLE
Titan/Hadoop 0.5 GA does not parse RDF types correctly

### ISSUE THREAD

**Issue by yuriythedev** [thinkaurelius/titan#717]
When I run Titan/Hadoop on a default RDF "rdf-input.properties" config with "titan.hadoop.input.conf.format=n-triples" in it,  I get

17:15:55 WARN  org.apache.hadoop.mapred.LocalJobRunner  - job_local1619420135_0002
java.lang.Exception: java.lang.IllegalArgumentException: No match for string "n_triples" in enum class com.thinkaurelius.titan.hadoop.formats.edgelist.rdf.RDFConfig$Syntax
        at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:403)
Caused by: java.lang.IllegalArgumentException: No match for string "n_triples" in enum class com.thinkaurelius.titan.hadoop.formats.edgelist.rdf.RDFConfig$Syntax
        at com.thinkaurelius.titan.hadoop.config.HadoopConfiguration.get(HadoopConfiguration.java:66)
        at com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration.has(BasicConfiguration.java:52)
        at com.thinkaurelius.titan.hadoop.formats.edgelist.rdf.RDFBlueprintsHandler.<init>(RDFBlueprintsHandler.java:94)
        at com.thinkaurelius.titan.hadoop.formats.edgelist.rdf.RDFRecordReader.<init>(RDFRecordReader.java:26)
        at com.thinkaurelius.titan.hadoop.formats.edgelist.rdf.RDFInputFormat.createRecordReader(RDFInputFormat.java:30)
        at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.<init>(MapTask.java:491)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:734)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:339)
        at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:235)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

The workaround is to use "titan.hadoop.input.conf.format=N_TRIPLES", as per the enum var/type.

Note that it is much harder to determine what is wrong now as the default log4j logging level seems to be ERROR now and this issue gets reported as WARN

**Comment by dalaro** [comment]
I think that exception is getting logged at WARN by LocalJobRunner.  Am I reading that right?  If so, then I think the log level is a Hadoop concern -- we can't control what level LocalJobRunner uses for that log message.

The formats are uppercase in 0.5.0, as you mentioned, and the recognized values are defined in the RDFConfig.Syntax enum.  Sorry for the bumpy transition.

**Comment by yuriythedev** [comment]
> I think that exception is getting logged at WARN by LocalJobRunner. Am I reading that right?
> I am not sure, it might depend on the Hadoop distro, but in Faunus 0.4.4. even INFO messages were displayed on the console output. Now, if you don't explicitly change it, you can only see ERROR messages. That certainly does not help to investigate issues like that :)
