### ISSUE TITLE
Looking up an invalid vertex ID returns 500 and HTML error response

### ISSUE THREAD

**Issue by BryanDonovan** [thinkaurelius/titan#727]
I'm not sure if this is an issue in Rexster or Titan, but if you request a vertex by ID, and that vertex does not exist, _and_ the ID is not valid, the response is a 500 instead of a 404, and the response body is plain-text HTML.

The below was using Titan 0.5.0 with the stock GraphOfTheGods graph on Mac OSX 10.9.4.

```
$ curl -v -XGET "localhost:8182/graphs/graph/vertices/2494" -H "accept: application/json"
* Adding handle: conn: 0x7fc842804000
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fc842804000) send_pipe: 1, recv_pipe: 0
* About to connect() to localhost port 8182 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8182 (#0)
> GET /graphs/graph/vertices/2494 HTTP/1.1
> User-Agent: curl/7.30.0
> Host: localhost:8182
> accept: application/json
>
< HTTP/1.1 500 Internal Error
< Content-Type: text/html;charset=ISO-8859-1
* Server grizzly/2.2.16 is not blacklisted
< server: grizzly/2.2.16
< Date: Mon, 25 Aug 2014 18:36:08 GMT
< Connection: close
< Transfer-Encoding: chunked
<
* Closing connection 0
<html><body><h1>Internal Error</h1></body></html>
```

If the ID is valid but non-existent, the response is a 404 like expected.

**Comment by spmallette** [comment]
are you seeing anything in the rexster logs after issuing this request?  if you look at the code in Rexster 

https://github.com/tinkerpop/rexster/blob/fd82ccd589d52cf7b42590f46a92b26b28476151/rexster-server/src/main/java/com/tinkerpop/rexster/VertexResource.java#L194

it's pretty clear that it checks for the id first and if `null` throws a NOT_FOUND.  it leads me to believe that titan may be throwing a different exception that is hopefully bubbling up to the logs somehow.  

how about other REST API routes - i see you also have problems with #728 - i'm wondering if this is all related as that code looks good too:

https://github.com/tinkerpop/rexster/blob/fd82ccd589d52cf7b42590f46a92b26b28476151/rexster-server/src/main/java/com/tinkerpop/rexster/VertexResource.java#L885

at least insofar as throwing a 404 when it is supposed to.  

Separately, if this is likely to be determined to be a problem it is likely a problem with Rexster's handling of Titan exceptions, in which case this would be an issue for Rexster's project.  Let's see what you think with respect to my inquiries...we may need to move these issues.

**Comment by BryanDonovan** [comment]
I don't see any logging in titan/logs (i.e., elasticsearch.log, cassandra.log, rexstitan.log) when I get this error.  Are there other logs I can look at, or is that all?

In #728 I do see this in rexstitan.log:

```
6816371 [Grizzly(7)] INFO  com.tinkerpop.rexster.VertexResource  - Vertex with [2560512] cannot be found.
6816371 [Grizzly(7)] ERROR com.tinkerpop.rexster.VertexResource  - javax.ws.rs.WebApplicationException
```

**Comment by spmallette** [comment]
that's weird - that's right where it should be: 

https://github.com/tinkerpop/rexster/blob/fd82ccd589d52cf7b42590f46a92b26b28476151/rexster-server/src/main/java/com/tinkerpop/rexster/VertexResource.java#L212

I wonder why you end up with a 500................ 

do you get any additional messages if you turn on more logging? not sure how you are set up...but with Rexster it's:  `bin/rexster.sh -s -d`

**Comment by BryanDonovan** [comment]
It seems to be related to the ID itself -- 2494 in this case (I generated some random integers in an integration test).  If I use a valid ID that doesn't exist, it seems to work.

I just tried starting rester with those flags (I actually edited bin/titan.sh and added them there) and I still don't see any extra log output.

**Comment by BryanDonovan** [comment]
If I try send a DELETE to the same URL with id 2494, it returns:

```
{"message":"Vertex id has unrecognized type: 2494","error":"Vertex id has unrecognized type: 2494"}
```

Nothing is logged for that either.

**Comment by spmallette** [comment]
ah - that's the problem - happens in the repl too:

``` text
gremlin> g.v('2494')
Vertex id has unrecognized type: 2494
Display stack trace? [yN] y
java.lang.IllegalArgumentException: Vertex id has unrecognized type: 2494
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)
    at com.thinkaurelius.titan.graphdb.idmanagement.IDManager.getUserVertexIDType(IDManager.java:448)
    at com.thinkaurelius.titan.graphdb.idmanagement.IDManager.getKey(IDManager.java:470)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.edgeQuery(StandardTitanGraph.java:320)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$VertexConstructor.get(StandardTitanTx.java:389)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$VertexConstructor.get(StandardTitanTx.java:372)
    at com.thinkaurelius.titan.graphdb.transaction.vertexcache.GuavaVertexCache.get(GuavaVertexCache.java:65)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.getVertex(StandardTitanTx.java:358)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.getVertex(TitanBlueprintsTransaction.java:105)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.getVertex(TitanBlueprintsGraph.java:160)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.getVertex(TitanBlueprintsGraph.java:27)
    at com.tinkerpop.blueprints.Graph$getVertex.call(Unknown Source)
    at com.tinkerpop.gremlin.groovy.loaders.GraphLoader$_load_closure3.doCall(GraphLoader.groovy:46)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:80)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.invoke(PojoMetaMethodSite.java:48)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at groovysh_evaluate.run(groovysh_evaluate:82)
    at groovysh_evaluate$run.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at groovysh_evaluate$run.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:67)
    at org.codehaus.groovy.tools.shell.Interpreter$evaluate.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:152)
    at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:114)
    at org.codehaus.groovy.tools.shell.Shell$leftShift$0.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:88)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:100)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
    at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:57)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:66)
    at com.thinkaurelius.titan.hadoop.tinkerpop.gremlin.Console.<init>(Console.java:61)
    at com.thinkaurelius.titan.hadoop.tinkerpop.gremlin.Console.<init>(Console.java:68)
    at com.thinkaurelius.titan.hadoop.tinkerpop.gremlin.Console.main(Console.java:73)
```

This is a "non-standard" exception specific to Titan.  It is not a behavior enforced by Blueprints so therefore, Rexster doesn't know anything about it.

@mbroecheler is this expected behavior?

**Comment by mbroecheler** [comment]
2494 is an invalid vertex id which triggers an exception. Where did that id come from @BryanDonovan ?

**Comment by BryanDonovan** [comment]
I generate a random number to see what happens when you use an ID that doesn't exist.  It doesn't actually exist in the graph.

**Comment by dalaro** [comment]
My thinking on this (d7873962cb6fdd73abff283b94f1dc06604d45c6's commit message)

Since this method is part of the Blueprints API, it should probably return null instead of throwing IllegalArgumentException for the (Titan-specific rather than Blueprints-standardized) range of IDs
which are outside the legal vertex ID space.  This commit changes the exception type thrown in IDManager.getUserVertexIDType to InvalidIDException, which inherits from TitanException and in turn RuntimeException.  StandardTitanTx.getVertex catches InvalidIDException, logs a warning, and then returns null.

I think nothing needs to be done to make bogus schema vertex IDs return null, since they follow a different logic path in IDManager.getKey that just converts the long into a byte buffer.  Not
sure though.

**Comment by dalaro** [comment]
In case it was unclear in the previous comment:  I think this one is a Titan/BP contract issue on getVertex.  It's not a Rexster issue.

**Comment by mbroecheler** [comment]
That's a good fix and no, we don't need to do something similar for the
schema since that is most certainly an exception.
Maybe we should make the log message debug instead of warning since this is
the expected behavior?

On Thu, Sep 25, 2014 at 8:25 PM, Dan LaRocque notifications@github.com
wrote:

> In case it was unclear in the previous comment: I think this one is a
> Titan/BP contract issue on getVertex. It's not a Rexster issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thinkaurelius/titan/issues/727#issuecomment-56861880.

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by dalaro** [comment]
> Maybe we should make the log message debug instead of warning since this is the expected behavior?

Sounds good, will do.
