### ISSUE TITLE
StackOverflowError involving stale vertex

### ISSUE THREAD

**Issue by dalaro** [thinkaurelius/titan#744]
Kishore Senji posted [a test case](https://groups.google.com/d/msg/aureliusgraphs/nVkl0WiD4Vs/rfJNyHz7aIYJ):

```
/* using titan 0.5 */

g=TitanFactory.build().set("storage.backend", "berkeleyje").set("schema.default", "none").set("storage.directory", "/tmp/"+System.nanoTime()).set("query.force-index", true).open();

tm = g.getManagementSystem();

name = tm.makePropertyKey("name").dataType(String.class).make();
age = tm.makePropertyKey("age").dataType(Integer.class).make();
tm.buildIndex('byName',Vertex.class).addKey(name).unique().buildCompositeIndex();

tm.commit();

cartman = g.addVertex(["name" : "cartman", "age" : 10]);
stan    = g.addVertex(["name" : "stan", "age" : 8]);

g.commit();

cartman = g.V("name", "cartman").next();

g.commit();

g.multiQuery(com.google.common.collect.Lists.newArrayList(g.query().has("name", "cartman").vertices())).properties().collect{it.value.iterator().next()};
g.multiQuery(cartman).properties().collect{it.value.iterator().next()}; /* This will cause stack over flow */

g.commit();
```

That produces:

```
java.lang.StackOverflowError
        at java.util.concurrent.atomic.AtomicReferenceArray.checkedByteOffset(AtomicReferenceArray.java:77)
        at java.util.concurrent.atomic.AtomicReferenceArray.get(AtomicReferenceArray.java:125)
        at com.google.common.cache.LocalCache$Segment.getFirst(LocalCache.java:2688)
        at com.google.common.cache.LocalCache$Segment.getEntry(LocalCache.java:2695)
        at com.google.common.cache.LocalCache$Segment.getLiveEntry(LocalCache.java:2716)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2753)
        at com.google.common.cache.LocalCache.getIfPresent(LocalCache.java:3921)
        at com.google.common.cache.LocalCache$LocalManualCache.getIfPresent(LocalCache.java:4715)
        at com.thinkaurelius.titan.graphdb.transaction.vertexcache.GuavaVertexCache.get(GuavaVertexCache.java:59)
        at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.getVertex(StandardTitanTx.java:358)
        at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.it(AbstractVertex.java:40)
        at com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:29)
        at com.thinkaurelius.titan.graphdb.relations.CacheProperty.it(CacheProperty.java:49)
        at com.thinkaurelius.titan.graphdb.relations.CacheProperty.getLongId(CacheProperty.java:72)
        at com.thinkaurelius.titan.graphdb.internal.AbstractElement.hasId(AbstractElement.java:96)
        at com.thinkaurelius.titan.graphdb.relations.RelationIdentifier.get(RelationIdentifier.java:34)
        at com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:32)
        at com.thinkaurelius.titan.graphdb.relations.CacheProperty.it(CacheProperty.java:49)
        at com.thinkaurelius.titan.graphdb.relations.CacheProperty.getLongId(CacheProperty.java:72)
        (... repeated frames omitted ...)
        at com.thinkaurelius.titan.graphdb.internal.AbstractElement.hasId(AbstractElement.java:96)
        at com.thinkaurelius.titan.graphdb.relations.RelationIdentifier.get(RelationIdentifier.java:34)
        at com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:32)
        at com.thinkaurelius.titan.graphdb.relations.CacheProperty.it(CacheProperty.java:49)
        at com.thinkaurelius.titan.graphdb.relations.CacheProperty.getLongId(CacheProperty.java:72)
        (line above is the outermost frame available in the exception trace)
```

I think this is supposed to just work.  If it can't work for some efficiency/correctness reason that I'm missing, we should still detect it and throw a more useful exception.

**Comment by anvie** [comment]
Maybe this is similar issue?

```
[error]     ThrowableException: null (TraversableLike.scala:233)
[error] com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2767)
[error] com.google.common.cache.LocalCache.getIfPresent(LocalCache.java:3921)
[error] com.google.common.cache.LocalCache$LocalManualCache.getIfPresent(LocalCache.java:4715)
[error] com.thinkaurelius.titan.graphdb.transaction.vertexcache.GuavaVertexCache.get(GuavaVertexCache.java:59)
[error] com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.getVertex(StandardTitanTx.java:358)
[error] com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.it(AbstractVertex.java:40)
[error] com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:29)
[error] com.thinkaurelius.titan.graphdb.relations.CacheProperty.it(CacheProperty.java:49)
[error] com.thinkaurelius.titan.graphdb.relations.CacheProperty.getLongId(CacheProperty.java:72)
[error] com.thinkaurelius.titan.graphdb.internal.AbstractElement.hasId(AbstractElement.java:96)
[error] com.thinkaurelius.titan.graphdb.relations.RelationIdentifier.get(RelationIdentifier.java:34)
[error] com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:32)
[error] com.thinkaurelius.titan.graphdb.relations.CacheProperty.it(CacheProperty.java:49)
[error] com.thinkaurelius.titan.graphdb.relations.CacheProperty.getLongId(CacheProperty.java:72)
[error] com.thinkaurelius.titan.graphdb.internal.AbstractElement.hasId(AbstractElement.java:96)
[error] com.thinkaurelius.titan.graphdb.relations.RelationIdentifier.get(RelationIdentifier.java:34)
[error] com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:32)
[error] com.thinkaurelius.titan.graphdb.relations.CacheProperty.it(CacheProperty.java:49)
[error] com.thinkaurelius.titan.graphdb.relations.CacheProperty.getLongId(CacheProperty.java:72)
[error] com.thinkaurelius.titan.graphdb.internal.AbstractElement.hasId(AbstractElement.java:96)
[error] com.thinkaurelius.titan.graphdb.relations.RelationIdentifier.get(RelationIdentifier.java:34)
[error] com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:32)
[error] com.thinkaurelius.titan.graphdb.relations.CacheProperty.it(CacheProperty.java:49)
[error] com.thinkaurelius.titan.graphdb.relations.CacheProperty.getLongId(CacheProperty.java:72)
[error] com.thinkaurelius.titan.graphdb.internal.AbstractElement.hasId(AbstractElement.java:96)
[error] com.thinkaurelius.titan.graphdb.relations.RelationIdentifier.get(RelationIdentifier.java:34)
[error] com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:32)
[error] com.thinkaurelius.titan.graphdb.relations.CacheProperty.it(CacheProperty.java:49)
[error] com.thinkaurelius.titan.graphdb.relations.CacheProperty.getLongId(CacheProperty.java:72)
[error] com.thinkaurelius.titan.graphdb.internal.AbstractElement.hasId(AbstractElement.java:96)
[error] com.thinkaurelius.titan.graphdb.relations.RelationIdentifier.get(RelationIdentifier.java:34)
[error] com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:32)
[error] com.thinkaurelius.titan.graphdb.relations.CacheProperty.it(CacheProperty.java:49)
[error] com.thinkaurelius.titan.graphdb.relations.CacheProperty.getLongId(CacheProperty.java:72)
[error] com.thinkaurelius.titan.graphdb.internal.AbstractElement.hasId(AbstractElement.java:96)
[error] com.thinkaurelius.titan.graphdb.relations.RelationIdentifier.get(RelationIdentifier.java:34)
[error] com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:32)
[error] com.thinkaurelius.titan.graphdb.relations.CacheProperty.it(CacheProperty.java:49)
[error] com.thinkaurelius.titan.graphdb.relations.CacheProperty.getLongId(CacheProperty.java:72)
[error] com.thinkaurelius.titan.graphdb.internal.AbstractElement.hasId(AbstractElement.java:96)
[error] com.thinkaurelius.titan.graphdb.relations.RelationIdentifier.get(RelationIdentifier.java:34)
[error] com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.it(AbstractTypedRelation.java:32)
```

It's happened when iterate trough `Stream` (result from gremlin pipe executed before mutation) after edge mutation, likes stalled cache issue.

**Comment by arisAlexis** [comment]
added some information here

https://groups.google.com/forum/#!topic/aureliusgraphs/6haBdWmHGlk
