### ISSUE TITLE
Possible race-condition when closing BerkeleyJE adapter

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#75]
This exception seems to indicate a race condition when closing BerkeleyJE in multi-threaded transactions. However, this exception might also due to the stress testing on BerkeleyJE layer (this exception occurred on iteration 43 of the test suite).

Encountered error in testCompetingThreads
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.thinkaurelius.titan.blueprints.LocalBlueprintsTest.doTestSuite(LocalBlueprintsTest.java:125)
        at com.thinkaurelius.titan.blueprints.LocalBlueprintsTest.doTestSuite(LocalBlueprintsTest.java:98)
        at com.thinkaurelius.titan.blueprints.LocalBlueprintsTest.testTransactionalGraphTestSuite(LocalBlueprintsTest.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at junit.framework.TestCase.runTest(TestCase.java:168)
        at junit.framework.TestCase.runBare(TestCase.java:134)
        at junit.framework.TestResult$1.protect(TestResult.java:110)
        at junit.framework.TestResult.runProtected(TestResult.java:128)
        at junit.framework.TestResult.run(TestResult.java:113)
        at junit.framework.TestCase.run(TestCase.java:124)
        at junit.framework.TestSuite.runTest(TestSuite.java:232)
        at junit.framework.TestSuite.run(TestSuite.java:227)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:249)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:142)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:113)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:104)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.IllegalStateException: There is 1 existing transaction opened against the Environment.
Aborting open transactions ...
aborting <Transaction id="267">
        at com.sleepycat.je.Environment.close(Environment.java:384)
        at com.thinkaurelius.titan.diskstorage.berkeleydb.je.BerkeleyJEStorageManager.close(BerkeleyJEStorageManager.java:204)
        at com.thinkaurelius.titan.diskstorage.util.KeyValueStorageManagerAdapter.close(KeyValueStorageManagerAdapter.java:51)
        at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.shutdown(StandardTitanGraph.java:118)
        at com.tinkerpop.blueprints.TransactionalGraphTestSuite.testCompetingThreads(TransactionalGraphTestSuite.java:447)
        at com.thinkaurelius.titan.blueprints.TransactionalTitanGraphTestSuite.testCompetingThreads(TransactionalTitanGraphTestSuite.java:34)
        ... 32 more
Testing testVertexReattachment...
**\* TOTAL TIME [TitanSpecificBlueprintsTestSuite]: 273.10649502277374 ***
Tests run: 10, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 20.867 sec <<< FAILURE!

**Comment by espeed** [comment]
I'm getting this error when building the lastest GitHub master...

https://gist.github.com/3711518

$ uname -a
Linux life 3.5.2-3.fc17.x86_64 #1 SMP Tue Aug 21 19:06:52 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

$ java -version
java version "1.7.0_06-icedtea"
OpenJDK Runtime Environment (fedora-2.3.fc17.2-x86_64)
OpenJDK 64-Bit Server VM (build 23.2-b09, mixed mode)

UPDATE: Actually, OpenJDK is not the Java set in my env...

$  /usr/java/latest/bin/java -version
java version "1.7.0_03"
Java(TM) SE Runtime Environment (build 1.7.0_03-b04)
Java HotSpot(TM) 64-Bit Server VM (build 22.1-b02, mixed mode)

**Comment by mbroecheler** [comment]
In Titan 0.3.0 the way record iterators are handled by titan has changed to be more robust. Since then, this problem has not occurred.
