### ISSUE TITLE
Supress KCVSLog$MessagePuller class lookup WARNING / cache the lookup result

### ISSUE THREAD

**Issue by OndraZizka** [thinkaurelius/titan#753]
In a modularized environment, the WARN below pops up really often.
Looks like some internal Titan stuff which doesn't really affect functionality.
Perhaps the result of class lookup could be cached and not attempted again, so the WARNING would only appear once?
Thanks for considering.

2014-09-09 23:48:11 WARNING com.thinkaurelius.titan.diskstorage.log.kcvs.KCVSLog$MessagePuller run Could not read messages for timestamp [Timepoint[1410298135147000 μs]](this read will be retried)
java.lang.NoClassDefFoundError: com/thinkaurelius/titan/diskstorage/log/kcvs/KCVSLog$MessagePuller$1
    at com.thinkaurelius.titan.diskstorage.log.kcvs.KCVSLog$MessagePuller.getOperation(KCVSLog.java:772)
    at com.thinkaurelius.titan.diskstorage.log.kcvs.KCVSLog$MessagePuller.run(KCVSLog.java:709)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)

**Comment by dalaro** [comment]
Can you tell us more about the runtime environment's classloader and classpath? `KCVSLog$MessagePuller$1.class` is part of the titan-core jar, so I'm assuming you're running Titan inside some kind of container with special classloading behavior (or you've repacked/filtered the contents of the titan-core jar).

**Comment by OndraZizka** [comment]
The environment is JBoss Modules, i.e. graph-like classloading (not hierarchical).
That is used through JBoss Forge, which is a wrapper around JBoss Modules allowing Maven Artifacts to be used as modules.
It's kind of light-weight OSGi alternative.

**Comment by OndraZizka** [comment]
More info: We only see it in tests. It might be triggered of a quick successive inits / shutdowns of a graph, in combination with the way Forge tests work - it copies all modules .jar's to a temp directory, and then deletes them. I.e. we call `.shutdown()` on graph, and delete the .jar's, and the bug is that some logging thread keeps running for a bit longer and fails finding the expected classes.

**Comment by OndraZizka** [comment]
After closing the graph properly, https://github.com/windup/windup/pull/286, this stopped happening. I guess this can be closed, unless you want to add some graceful handling. Thanks.

**Comment by ghost** [comment]
Originator wrote "I guess this can be closed, unless you want to add some graceful handling. Thanks."

Can we close this now, or is there some additional work that is planned ?

**Comment by dalaro** [comment]
I'm not sure what the next steps should be.  I looked at the linked issue, but I couldn't figure out what it implied for Titan in terms of graceful handling.  I'm closing it by default -- but don't hesitate to reopen or open-new if you want to pick this back up.
