### ISSUE TITLE
java.nio.channels.OverlappingFileLockException when set property for one vertex that indexed using lucene

### ISSUE THREAD

**Issue by huiwenhan** [thinkaurelius/titan#757]
Get following error:
ERROR [com.thinkaurelius.titan.graphdb.database.StandardTitanGraph] Error while commiting index mutations for transaction [2364] on index: search
com.thinkaurelius.titan.core.TitanException: Could not execute operation due to backend exception
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:44)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.flushInternal(IndexTransaction.java:119)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.commit(IndexTransaction.java:100)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction.commitIndexes(BackendTransaction.java:124)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.commit(StandardTitanGraph.java:639)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.commit(StandardTitanTx.java:1228)
    at com.sfb.wsa.cd.uptake.graph.titan.model.vertex.access.TagDao.add(TagDao.java:32)
    at com.sfb.wsa.cd.uptake.profiles.jobs.ImportProfileJob.main(ImportProfileJob.java:108)
Caused by: com.thinkaurelius.titan.diskstorage.PermanentBackendException: Could not create writer
    at com.thinkaurelius.titan.diskstorage.lucene.LuceneIndex.getWriter(LuceneIndex.java:111)
    at com.thinkaurelius.titan.diskstorage.lucene.LuceneIndex.mutate(LuceneIndex.java:146)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:122)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:119)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:56)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:42)
    ... 7 more
Caused by: org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@C:\tmp\titan\wsa\emp\lucene\tagmixedIndex\write.lock: java.nio.channels.OverlappingFileLockException
    at org.apache.lucene.store.Lock.obtain(Lock.java:89)
    at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:710)
    at com.thinkaurelius.titan.diskstorage.lucene.LuceneIndex.getWriter(LuceneIndex.java:108)
    ... 12 more
Caused by: java.nio.channels.OverlappingFileLockException
    at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:267)
    at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:164)
    at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1078)
    at java.nio.channels.FileChannel.tryLock(FileChannel.java:1165)
    at org.apache.lucene.store.NativeFSLock.obtain(NativeFSLockFactory.java:148)
    at org.apache.lucene.store.Lock.obtain(Lock.java:100)
    ... 14 more

**Comment by dalaro** [comment]
Did you call `TitanFactory.open` multiple times in one Java VM?  If so, did you have only one graph open at a time, and did you call `graph.shutdown()` on all of the graphs when you were done with them?

If you can reproduce this reliably, then please show us how.

**Comment by dalaro** [comment]
Incidentally, I initially thought this could potentially be related to #761, but IndexReaders do not appear to have any bearing on the Writer locks.  I might be mistaken though.

**Comment by mukil** [comment]
Google brought me here, so I just wanted to leave you this hint:

This seems to be related to using Java to initialize an existing file-db which is located on a storage formatted as MS-DOS FAT (e.g. usb stick) on Mac OS X.

See also: https://github.com/elastic/elasticsearch/issues/1451 

(I have this issue when trying to init my neo4j file-db with lucene)
