### ISSUE TITLE
rexster-server error for titan 0.5.0

### ISSUE THREAD

**Issue by huiwenhan** [thinkaurelius/titan#759]
C:\software\nosql\rexster\rexster-server-2.5.0\rexster-server-2.5.0>bin\rexster.bat -s -c config\rexster.xml
[INFO] Application - .:Welcome to Rexster:.
[INFO] RexsterProperties - Using [C:\software\nosql\rexster\rexster-server-2.5.0\rexster-server-2.5.0\config\rexster.xml] as configuration source.
[INFO] Application - Rexster is watching [C:\software\nosql\rexster\rexster-server-2.5.0\rexster-server-2.5.0\config\rexster.xml] for change.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/software/nosql/rexster/rexster-server-2.5.0/rexster-server-2.5.0/lib/slf4j-log4j12-1.7.2.jar!/org/slf4j/impl/Sta
ticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/software/nosql/rexster/rexster-server-2.5.0/rexster-server-2.5.0/ext/titan/slf4j-log4j12-1.7.5.jar!/org/slf4j/im
pl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[INFO] Reflections - Reflections took 8948 ms to scan 417 urls, producing 143 keys and 11163 values
[INFO] GraphDatabaseConfiguration - Generated unique-instance-id=c0a8016611484-IBM-RR0A746AMG41
[INFO] Backend - Configuring index [search]
Exception in thread "main" java.lang.VerifyError: Cannot inherit from final class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:188)
        at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:42)
        at com.thinkaurelius.titan.diskstorage.Backend.getImplementationClass(Backend.java:425)
        at com.thinkaurelius.titan.diskstorage.Backend.getIndexes(Backend.java:412)
        at com.thinkaurelius.titan.diskstorage.Backend.<init>(Backend.java:131)
        at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1604)
        at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:107)
        at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:92)
        at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:71)
        at com.thinkaurelius.titan.tinkerpop.rexster.TitanGraphConfiguration.configureGraphInstance(TitanGraphConfiguration.java:33)
        at com.tinkerpop.rexster.config.GraphConfigurationContainer.getGraphFromConfiguration(GraphConfigurationContainer.java:124)
        at com.tinkerpop.rexster.config.GraphConfigurationContainer.<init>(GraphConfigurationContainer.java:54)
        at com.tinkerpop.rexster.server.XmlRexsterApplication.reconfigure(XmlRexsterApplication.java:99)
        at com.tinkerpop.rexster.server.XmlRexsterApplication.<init>(XmlRexsterApplication.java:47)
        at com.tinkerpop.rexster.Application.<init>(Application.java:97)
        at com.tinkerpop.rexster.Application.main(Application.java:189)

C:\software\nosql\rexster\rexster-server-2.5.0\rexster-server-2.5.0>

**Comment by huiwenhan** [comment]
fixed ,delete lucene-core-3.6.2 on \rexster-server-2.5.0\lib\
