### ISSUE TITLE
Error with primitive type when using Frames

### ISSUE THREAD

**Issue by ghost** [thinkaurelius/titan#779]
java.lang.IllegalArgumentException: Value [false] is not an instance of the expected data type for property key [isFooBoolean] and cannot be converted. Expected: boolean, found: class java.lang.Boolean
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:119) ~[guava-14.0.jar:na]
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.verifyAttribute(StandardTitanTx.java:506) ~[titan-core-0.5.0.jar:na]
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.addPropertyInternal(StandardTitanTx.java:647) ~[titan-core-0.5.0.jar:na]
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.setProperty(StandardTitanTx.java:716) ~[titan-core-0.5.0.jar:na]
    at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.setProperty(AbstractVertex.java:244) ~[titan-core-0.5.0.jar:na]
    at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.setProperty(AbstractVertex.java:239) ~[titan-core-0.5.0.jar:na]
    at com.tinkerpop.frames.annotations.PropertyAnnotationHandler.processElement(PropertyAnnotationHandler.java:34) ~[frames-2.5.0.jar:na]
    at com.tinkerpop.frames.annotations.PropertyAnnotationHandler.processElement(PropertyAnnotationHandler.java:11) ~[frames-2.5.0.jar:na]
    at com.tinkerpop.frames.FramedElement.invoke(FramedElement.java:89) ~[frames-2.5.0.jar:na]
    at com.sun.proxy.$Proxy133.setFooBoolean(Unknown Source) ~[na:na]

**Comment by mbroecheler** [comment]
This one has slipped through the cracks.
@bluestix Could you tell us what your schema definition looks like?

**Comment by ghost** [comment]
This works but requires casting:

``` Java
public interface PlayerPresenceGraphTitan extends VertexFrame{

  public static final String CHAT_BANNED = "chatBanned";
  public static final String IS_ADMIN = "isAdmin";


  @Property(CHAT_BANNED)
  public void setChatBanned(Object chatBanned );
  @Property(CHAT_BANNED)
  public Object isChatBanned();


  @Property(IS_ADMIN)
  public void setAdmin(Object isAdmin);
  @Property(IS_ADMIN)
  public Object isAdmin();

  //getters/setters
}
```

This doesn't work and fails with the error above regardless of whether I use boolean or Boolean:

``` Java
public interface PlayerPresenceGraphTitan extends VertexFrame{

  public static final String CHAT_BANNED = "chatBanned";
  public static final String IS_ADMIN = "isAdmin";


  @Property(CHAT_BANNED)
  public void setChatBanned(Boolean chatBanned );
  @Property(CHAT_BANNED)
  public Boolean isChatBanned();


  @Property(IS_ADMIN)
  public void setAdmin(Boolean isAdmin);
  @Property(IS_ADMIN)
  public Boolean isAdmin();

  //getters/setters
}
```

**Comment by mbroecheler** [comment]
Also, @bluestix, which version of Titan are you suing? Newer versions should not allow primitive datatype definitions for this reason, however, it seems that this is the case here. Wonder how that is possible.

**Comment by ghost** [comment]
titan-cassandra 0.5.0

**Comment by BrynCooke** [comment]
Unbelievably I have actually seen this before.
You have Kryo 2.21 on your classpath.

The error can be replicated outside of Frames using the following code:

```
        Map<String, Object> config = new HashMap<>();
        config.put("storage.backend", "cassandra");
        config.put("storage.hostname", "localhost");
        config.put("storage.cassandra.keyspace", "test");

        TitanGraph g = TitanFactory.open(new MapConfiguration(config));

        TitanManagement ms = g.getManagementSystem();
        PropertyKey test = ms.makePropertyKey("test").dataType(Boolean.class).make();
        ms.buildIndex("testIndex", Vertex.class).addKey(test).buildCompositeIndex();
        ms.commit();

        Vertex v = g.addVertex(null);
        v.setProperty("test", true);

        g.commit();
        g.shutdown();
```

java.lang.IllegalArgumentException: Value [true] is not an instance of the expected data type for property key [test] and cannot be converted. Expected: boolean, found: class java.lang.Boolean

Simply remove your kryo dependency and let titan use the version that it requires and the issue will likely go away.

Let us know.
