### ISSUE TITLE
NPE in StandardTitanGraph.assignIDs

### ISSUE THREAD

**Issue by jasonculverhouse** [thinkaurelius/titan#78]
This  this exception is thrown when I am performing a lot of concurrent writes to the graph database from several threads and several processes.    I have storage.flush-ids=false with a Cassandra backend  I can provide some additional information if required.

204790 [pool-1-thread-20] DEBUG com.thinkaurelius.titan.graphdb.database.StandardTitanGraph  - Saving transaction. Added 18164, removed 0
216626 [pool-1-thread-20] DEBUG com.thinkaurelius.titan.diskstorage.locking.LockingTransactionHandle  - About to sleep for 85 ms
228350 [pool-1-thread-20] WARN  xxx.titan.MyGraph  - Storage exception: com.thinkaurelius.titan.core.TitanException: Could not commit transaction due to exception during persistence
    at com.thinkaurelius.titan.graphdb.transaction.StandardPersistTitanTx.commit(StandardPersistTitanTx.java:176)
    at xxx.titan.MyGraph.addAccount(MyGraph.java:296)
    at xxx.titan.MyGraph$GraphInsertJob.execute(MyGraph.java:57)
    at xxx.titan.MyGraph$GraphWorker$Worker.run(MyGraph.java:138)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
Caused by: com.thinkaurelius.titan.diskstorage.PermanentStorageException: Unidentified exception occurred during persistence
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.save(StandardTitanGraph.java:711)
    at com.thinkaurelius.titan.graphdb.transaction.StandardPersistTitanTx.commit(StandardPersistTitanTx.java:169)
    ... 9 more
Caused by: java.lang.NullPointerException
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.assignIDs(StandardTitanGraph.java:575)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.save(StandardTitanGraph.java:609)
    ... 10 more

**Comment by mbroecheler** [comment]
I could not quite isolate the problem, but there have been a bunch of improvements to the ID assignment module. Could you try running your code again and see if you still get the same issue?

**Comment by mbroecheler** [comment]
Closing the issue for now. Please re-open if the issue persists.
