### ISSUE TITLE
NoClassDefFound errors in 0.5.1 startup when not all titan dependencies are included

### ISSUE THREAD

**Issue by miechus** [thinkaurelius/titan#785]
When starting Titan 0.5.1 with only part of the dependencies (i.e. titan-cassandra without titan-hbase), an error is thrown in the log:

 java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/ZooKeeperConnectionException

This is caused by the ReflectiveConfigOptionLoader.loadStandard() method which includes classes from all Titan dependencies such as Berkeley, HBase and Cassandra. To hack around this issue we had to include all the dependencies so that classes included in the loadStandard() method are available in the class loader.

**Comment by dalaro** [comment]
Please paste the exception, including stacktrace, and the preceding 3 lines in the log.

The list iterated in `loadStandard` is a performance optimization; attempting to load those classes is usually faster than walking the classpath looking for option definitions.  Titan is intended to tolerate ClassNotFoundExceptions generated while attempting to load any or all of those classes:

https://github.com/thinkaurelius/titan/blob/0.5.1/titan-core/src/main/java/com/thinkaurelius/titan/core/util/ReflectiveConfigOptionLoader.java#L131-155

So DEBUG messages like these in the log are harmless:

```
367  [main] DEBUG com.thinkaurelius.titan.core.util.ReflectiveConfigOptionLoader  - Unable to load class com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager with loader sun.misc.Launcher$AppClassLoader@5c647e05
java.lang.ClassNotFoundException: com.thinkaurelius.titan.diskstorage.hbase.HBaseStoreManager
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:340)
        at com.thinkaurelius.titan.core.util.ReflectiveConfigOptionLoader.loadStandard(ReflectiveConfigOptionLoader.java:144)
        at com.thinkaurelius.titan.diskstorage.configuration.ConfigNamespace.getChild(ConfigNamespace.java:68)
        at com.thinkaurelius.titan.diskstorage.configuration.ConfigElement.parse(ConfigElement.java:169)
        at com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration.getAll(BasicConfiguration.java:80)
        at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1319)
        at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:91)
        at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:60)
        at com.thinkaurelius.titan.test.Main.main(Main.java:11)
```

As long as you _don't_ see any messages like these:

```
456  [main] INFO configuration.BasicConfiguration: Ignored configuration entry for storage.hostname since it does not map to an option
java.lang.IllegalArgumentException: Unknown configuration element in namespace [root.storage]: hostname
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)
        at com.thinkaurelius.titan.diskstorage.configuration.ConfigElement.parse(ConfigElement.java:170)
```

If you're seeing something different in the log than I just described, then I need to look at it.

**Comment by miechus** [comment]
The problem is not a warning. Here are the snippets of the stack traces - please note that in our app Spring fails to initialize and the app simply does not start:

```
...nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean
 with name 'XXXXXX': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'XXXXXXX' defined in class path resource [XXXXXXXX]: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [XXXXXXX] threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/Zo
oKeeperConnectionException
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java
:292)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1185)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:700)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)

...

Caused by: java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/ZooKeeperConnectionException
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:270)
        at com.thinkaurelius.titan.core.util.ReflectiveConfigOptionLoader.loadStandard(ReflectiveConfigOptionLoader.java:144)
        at com.thinkaurelius.titan.diskstorage.configuration.ConfigNamespace.getChild(ConfigNamespace.java:68)
        at com.thinkaurelius.titan.diskstorage.configuration.ConfigElement.parse(ConfigElement.java:169)
        at com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration.getAll(BasicConfiguration.java:80)
        at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1319)
        at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:91)
        at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:71)
```

**Comment by dalaro** [comment]
Thanks, that helped me get the problem.

d71100e92d1a2879d0a63409b40273b28e24a2ee makes Titan catch any type of Throwable on the affected lines, instead of just ClassNotFoundException.  This will be part of 0.5.2.  It should apply cleanly atop 0.5.1 if you prefer to recompile.  This should turn the exception into a DEBUG log message.  It appears to do so in testing here.

I think at least one class in the list at https://github.com/thinkaurelius/titan/blob/0.5.1/titan-core/src/main/java/com/thinkaurelius/titan/core/util/ReflectiveConfigOptionLoader.java#L104-L117 must
- be present on the app's classpath and
- refer to other types which are not on the classpath, generating a NCDFE (a subtype of java.lang.LinkageError)

It may be possible to work around this problem in lieu of applying the patch by providing ZK 3.4.5 (and whatever other types aren't resolving) on the app classpath at runtime.  However, that would be a workaround, not a long-term fix.  The fix is the linked patch above.
