### ISSUE TITLE
"Unknown configuration element in namespace" in TitanHadoop 0.5.1

### ISSUE THREAD

**Issue by skiefer** [thinkaurelius/titan#787]
Since we are using Titan 0.5.1 we are getting many exceptions like the following in TitanHadoop:

``` text
2014-10-16 13:32:30.221  INFO 25498 [main] --- com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration : Ignored configuration entry for storage.hostname-0 since it does not map to an option

java.lang.IllegalArgumentException: Unknown configuration element in namespace [root.storage]: hostname-0
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)
    at com.thinkaurelius.titan.diskstorage.configuration.ConfigElement.parse(ConfigElement.java:170)
    at com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration.getAll(BasicConfiguration.java:80)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1319)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:91)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:81)
    at com.thinkaurelius.titan.hadoop.formats.util.input.current.TitanHadoopSetupImpl.<init>(TitanHadoopSetupImpl.java:37)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:44)
    at com.thinkaurelius.titan.hadoop.formats.util.TitanInputFormat.setConf(TitanInputFormat.java:44)
    at com.thinkaurelius.titan.hadoop.formats.cassandra.TitanCassandraInputFormat.setConf(TitanCassandraInputFormat.java:53)
    at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:62)
    at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:117)
    at org.apache.hadoop.mapred.JobClient.writeNewSplits(JobClient.java:1051)
    at org.apache.hadoop.mapred.JobClient.writeSplits(JobClient.java:1071)
    at org.apache.hadoop.mapred.JobClient.access$700(JobClient.java:179)
    at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:983)
    at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:936)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190)
    at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:936)
    at org.apache.hadoop.mapreduce.Job.submit(Job.java:550)
    at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:580)
    at com.thinkaurelius.titan.hadoop.compat.h1.Hadoop1Compiler.run(Hadoop1Compiler.java:315)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:79)
    at com.thinkaurelius.titan.hadoop.HadoopPipeline.submit(HadoopPipeline.java:1092)
    at com.iqser.gin.batch.common.FaunusTasklet.execute(FaunusTasklet.java:92)
    at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
    at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
    at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:271)
    at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:77)
    at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368)
    at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
    at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
    at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
    at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:198)
    at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
    at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:64)
    at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:67)
    at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:162)
    at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:141)
    at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:134)
    at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:304)
    at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
    at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
    at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:128)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
    at org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration$PassthruAdvice.invoke(SimpleBatchConfiguration.java:127)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
    at com.sun.proxy.$Proxy42.run(Unknown Source)
    at com.iqser.gin.batch.common.AbstractBatchIntegrationTest.executeJob(AbstractBatchIntegrationTest.java:41)
    at com.iqser.gin.batch.BatchPatternJobIntegrationTest.launchJob(BatchPatternJobIntegrationTest.java:89)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
    at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
    at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:233)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:87)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
    at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
    at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
    at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
    at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:176)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

2014-10-16 13:32:30.223  INFO 25498 [main] --- com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration : Ignored configuration entry for storage.port-0 since it does not map to an option
```

This configuration is causing the errors:

``` properties
storage.backend=cassandrathrift
storage.keyspace=titan
storage.port=9160
storage.hostname=127.0.0.1

index.search.backend=elasticsearch
index.search.hostname=127.0.0.1

cache.db-cache = true
cache.db-cache-clean-wait = 0
cache.db-cache-time = 0
cache.db-cache-size = 0.25

titan.hadoop.input.conf.storage.backend=cassandrathrift
titan.hadoop.input.conf.storage.hostname=localhost
titan.hadoop.input.conf.storage.port=9160
titan.hadoop.input.conf.storage.cassandra.keyspace=titan
titan.hadoop.input.conf.storage.batch-loading=true
titan.hadoop.input.infer-schema=true
titan.hadoop.output.conf.storage.backend=cassandrathrift
titan.hadoop.output.conf.storage.hostname=localhost
titan.hadoop.output.conf.storage.port=9160
titan.hadoop.output.conf.storage.cassandra.keyspace=titan
titan.hadoop.output.conf.storage.batch-loading=true
titan.hadoop.output.infer-schema=true
titan.hadoop.sideeffect.format=org.apache.hadoop.mapreduce.lib.output.TextOutputFormat

mapreduce.jobtracker.staging.root.dir=target/tmp/jobtracker
```

It seems that the "-0" is added in Hadoop1Compiler:

``` java
    private void addConfiguration(final Configuration configuration) {
        for (final Map.Entry<String, String> entry : configuration) {
            this.getConf().set(entry.getKey() + "-" + this.mapSequenceClasses.size(), entry.getValue()); // TODO why does this line exist?
            this.getConf().set(entry.getKey(), entry.getValue());
        }
    }
```

**Comment by dalaro** [comment]
These INFO messages and ensuing exception traces are noisy but harmless.  That line is a relic from earlier revisions of FaunusCompiler and Hadoop1Compiler.  At this point, I think it's completely vestigial, but I need to remove it and test before saying that for certain.

As long as each stacktrace listed above is preceded by an INFO line with the `Ignored configuration entry...` message that you pasted, these settings will be ignored by Titan, but the other settings in the configuration will still be honored.

**Comment by dalaro** [comment]
The commit which made the stacktrace part of the logging output is d1597002b06f802192a0e61b5f11463d77e993de.  This commit is included in 0.5.0 and 0.5.1 (but not the 0.5.0-MX milestone releases).

**Comment by skavulya** [comment]
I see the following errors in Titan 0.5.2 when I try to configure ids.num-partitions or ids.placement. Are my settings for ids.num-partitions being ignored, or is this a harmless exception? Thanks.

From com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration in ForkJoinPool-1-worker-29 Ignored configuration entry for ids.num-partitions since it does not map to an option 
java.lang.IllegalArgumentException: Unknown configuration element in namespace [root.ids]: num-partitions
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:119)
        at com.thinkaurelius.titan.diskstorage.configuration.ConfigElement.parse(ConfigElement.java:170)
        at com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration.getAll(BasicConfiguration.java:80)
        at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1274)
        at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:91)
        at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:71)

**Comment by dalaro** [comment]
That's strange.  I think you're seeing a separate issue @skavulya.  The original issue reported by @skiefer involved Hadoop1Compiler generating vestigial config keys with numeric suffixes, e.g. ids.num-partitions-0, ids.num-partitions-1, etc.  I don't see any numeric suffix on the config key in your comment -- this problem is not necessarily harmless and looks pretty concerning.  Would you please open a separate issue with the commands and config to reproduce?

**Comment by skavulya** [comment]
I managed to reproduce the issue. I'll open a new issue.

**Comment by vitordouzi** [comment]
I try something like this using titan-core 0.5.2 . When I try to open a titan using cassandra and elasticsearch, but, when I call TitanFactory.open("ini.properties") same problems occurs, like:

```
3710 [main] INFO  com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration  - Ignored configuration entry for storage.index.search.backend since it does not map to an option
java.lang.IllegalArgumentException: Unknown configuration element in namespace [root.storage]: index
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)
    at com.thinkaurelius.titan.diskstorage.configuration.ConfigElement.parse(ConfigElement.java:170)
    at com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration.getAll(BasicConfiguration.java:80)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1327)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:91)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:60)
    at com.lbd.projetoprototipo1.Indexer.Indexer.<init>(Indexer.java:64)
    at com.lbd.projetoprototipo1.Main.Main.main(Main.java:18)
3712 [main] INFO  com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration  - Ignored configuration entry for storage.index.search.hostname since it does not map to an option
java.lang.IllegalArgumentException: Unknown configuration element in namespace [root.storage]: index
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)
    at com.thinkaurelius.titan.diskstorage.configuration.ConfigElement.parse(ConfigElement.java:170)
    at com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration.getAll(BasicConfiguration.java:80)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1327)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:91)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:60)
    at com.lbd.projetoprototipo1.Indexer.Indexer.<init>(Indexer.java:64)
    at com.lbd.projetoprototipo1.Main.Main.main(Main.java:18)
3712 [main] INFO  com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration  - Ignored configuration entry for storage.index.search.client-only since it does not map to an option
java.lang.IllegalArgumentException: Unknown configuration element in namespace [root.storage]: index
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)
    at com.thinkaurelius.titan.diskstorage.configuration.ConfigElement.parse(ConfigElement.java:170)
    at com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration.getAll(BasicConfiguration.java:80)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1327)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:91)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:60)
    at com.lbd.projetoprototipo1.Indexer.Indexer.<init>(Indexer.java:64)
    at com.lbd.projetoprototipo1.Main.Main.main(Main.java:18)
```

using as "ini.properties" file:

```
storage.backend=cassandra
storage.hostname=127.0.0.1

storage.index.search.backend=elasticsearch
storage.index.search.hostname=127.0.0.1,127.0.0.2,127.0.0.3
storage.index.search.client-only=false
```

in #787, @dalaro say: "These INFO messages and ensuing exception traces are noisy but harmless. [...]"

As you can see, I try use three elasticsearchs in same machine (it's usual). however, when I begin the index contruction, using

```
TitanManagement mgmt = graph.getManagementSystem();
PropertyKey pKey = mgmt.makePropertyKey(key).dataType(String.class).make();
mgmt.buildIndex(key, Vertex.class).addKey(pKey).buildMixedIndex("search");
```

this problem occurs

```
Exception in thread "main" java.lang.IllegalArgumentException: Unknown external index backend: search
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)
    at com.thinkaurelius.titan.graphdb.database.management.ManagementSystem.createMixedIndex(ManagementSystem.java:485)
    at com.thinkaurelius.titan.graphdb.database.management.ManagementSystem.access$400(ManagementSystem.java:94)
    at com.thinkaurelius.titan.graphdb.database.management.ManagementSystem$IndexBuilder.buildMixedIndex(ManagementSystem.java:645)
    at com.lbd.projetoprototipo1.Indexer.Indexer.addKeyVertex(Indexer.java:108)
    at com.lbd.projetoprototipo1.Indexer.Indexer.loadConfigure(Indexer.java:94)
    at com.lbd.projetoprototipo1.Indexer.Indexer.<init>(Indexer.java:68)
    at com.lbd.projetoprototipo1.Main.Main.main(Main.java:18)
```
