### ISSUE TITLE
Elastic search crashes in local-mode due to skipped config option

### ISSUE THREAD

**Issue by tomersagi** [thinkaurelius/titan#796]
Hi,
I think the latest commit to Titan 0.5.0 has created a new bug. 
When using a standard berkeley-db+es config the elastic search options do not get parsed and an exception is catched:

```
13:15:14.720 [main] INFO  c.t.t.d.c.BasicConfiguration - Ignored configuration entry for index.search.elasticsearch.client-only since it does not map to an option
```

This can be traced to Basicconfiguration.java line 83. For some reason the elastic search options, namely:

```
index.search.elasticsearch.client-only=false
index.search.elasticsearch.local-mode=true
```

Are not found in the namespace. 
Later, the elastic search constructor finds no configuration and defaults to remote mode, since no remote options are configured, it crashes:

```
testDriver(hpl.alp2.titan.test.DriverTest)  Time elapsed: 261.722 sec  <<< ERROR!
```

java.lang.IllegalArgumentException: Could not instantiate implementation: com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex
    at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:219)
    at org.elasticsearch.client.transport.support.InternalTransportClusterAdminClient.execute(InternalTransportClusterAdminClient.java:85)
    at org.elasticsearch.client.support.AbstractClusterAdminClient.health(AbstractClusterAdminClient.java:123)
    at org.elasticsearch.action.admin.cluster.health.ClusterHealthRequestBuilder.doExecute(ClusterHealthRequestBuilder.java:93)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85)
    at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59)
    at com.thinkaurelius.titan.diskstorage.es.ElasticSearchIndex.<init>(ElasticSearchIndex.java:198)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at com.thinkaurelius.titan.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:44)
    at com.thinkaurelius.titan.diskstorage.Backend.getImplementationClass(Backend.java:425)
    at com.thinkaurelius.titan.diskstorage.Backend.getIndexes(Backend.java:412)
    at com.thinkaurelius.titan.diskstorage.Backend.<init>(Backend.java:131)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1604)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:107)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:92)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:60)
    at hpl.alp2.titan.importers.TitanImporter.init(TitanImporter.java:47)
    at hpl.alp2.titan.test.DriverTest.testDriver(DriverTest.java:52)

This was tried on a clean slate with no previous database created and db / search directories deleted. 

See related here: [https://groups.google.com/forum/#!topic/aureliusgraphs/Zbd87qNKOUM]

The same config worked on a snapshot jar of 0.5.0 taken a while ago, when I relinked my project to the current 0.5.0 using maven I started getting this error. 
Thanks,
Tomer

**Comment by dalaro** [comment]
0.5.2-SNAPSHOT has been the active snapshot version and the version on the titan09 branch since Oct 9.  0.5.0's release tag was created on Aug 14, and I doubt anyone has pushed a 0.5.0-SNAPSHOT since then, which doesn't line up with the timeframe for this bug.  Which snapshot version are you using exactly?

**Comment by tomersagi** [comment]
I'm using a maven dependency now:

```
<dependency>
        <groupId>com.thinkaurelius.titan</groupId>
        <artifactId>titan-core</artifactId>
        <version>0.5.0</version>
 </dependency>
```

I can try and upgrade to 0.5.2-Snapshot and report the results.

**Comment by dalaro** [comment]
0.5.0 is fine.  You do _not_ need to upgrade to 0.5.2-SNAPSHOT.  I was confused by the words "snapshot" and "latest commit" in your original message.

Did you also depend on titan-es and on titan-berkeleyje?  You need both of these dependencies in your pom to run a Titan graph against BDB + ES as described in your original posting.  If in doubt, please post your pom.xml and the output of `mvn dependency:tree -Dverbose=true`.

**Comment by tomersagi** [comment]
I did of course depend on them as well. You could see from the trace I posted that the appropriate classes have been found and called upon.

**Comment by dalaro** [comment]
Thanks, just checking.  Can you please increase the log level on `com.thinkaurelius.titan.core.util.ReflectiveConfigOptionLoader` to DEBUG?  This should emit additional info about why index.search.elasticsearch.client-only is failing to map to an option object at runtime.

**Comment by tomersagi** [comment]
I don't know what happened, but the issue went away. It's still not running, but now it's a different error. I'll try and handle it on my own and if I'm stuck I'll open a new issue.
