### ISSUE TITLE
"wrong key class" errors - Sequence File Output

### ISSUE THREAD

**Issue by keith-hinde** [thinkaurelius/titan#806]
Using 0.5.0.

Every time I try to run a Sequence File Output extract job against my graph, the mapreduce jobs fail with the following error:

Error: java.io.IOException: wrong key class: org.apache.hadoop.io.NullWritable is not class org.apache.hadoop.io.LongWritable

Hadoop (2.2.0) is working fine, for both regular mapreduce jobs and also GraphSON extracts from the same Graph (stored in Cassandra). The properties file I'm using looks a little like this:

titan.hadoop.input.format=com.thinkaurelius.titan.hadoop.formats.cassandra.TitanCassandraInputFormat
titan.hadoop.input.conf.storage.backend=cassandrathrift

titan.hadoop.output.format=org.apache.hadoop.mapreduce.lib.output.SequenceFileOutputFormat
titan.hadoop.sideeffect.output.format=org.apache.hadoop.mapreduce.lib.output.TextOutputFormat
titan.hadoop.output.location=output
titan.hadoop.output.location.overwrite=true

Looking at the syslog in the userjobs folder for a failed attempt, I find errors like this:

2014-11-04 10:48:06,536 ERROR [main] org.apache.hadoop.security.UserGroupInformation: PriviledgedActionException as:hduser (auth:SIMPLE) cause:java.io.IOException: wrong key class: org.apache.hadoop.io.NullWritable is not class org.apache.hadoop.io.LongWritable

**Comment by keith-hinde** [comment]
By way of an update - I'm seeing this same error on a clean install (different machine) of 0.5.1 running Graph of the Gods against a BDB backed graph,

**Comment by mbroecheler** [comment]
Not quite following: you are using BDB as the backend but your input format
states that you are trying to read from cassandra?

On Tue, Nov 4, 2014 at 6:20 AM, lw47 notifications@github.com wrote:

> By way of an update - I'm seeing this same error on a clean install
> (different machine) of 0.5.1 running Graph of the Gods against a BDB backed
> graph,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thinkaurelius/titan/issues/806#issuecomment-61645552.

## 

Matthias Broecheler
http://www.matthiasb.com

**Comment by keith-hinde** [comment]
Hi Matthias - Thanks for the reply. The original problem showed up when running against my cassandra cluster, but I created a basic (BDB) instance to try and establish if it was a Cassandra specific issue or not. I established that I was seeing the issue regardless of backends.

**Comment by dalaro** [comment]
@lw47 did your properties file set  `cassandra.input.partitioner.class`?  It's not in what was pasted.  HadoopGraph `g._` can't even get that far without a partitioner when I test it on 0.5.1/hadoop2.  I don't think this is causing the issue, but I also don't think I have a complete picture of your config.  By the way, are you running `g._` or something else?

**Comment by keith-hinde** [comment]
Hi,

Unfortunately I don't have access to the Cassandra cluster today, but I did manage to replicate this issue using a fresh instance of 0.5.1 against a single Hadoop node. Here are the details:

Config File

# input graph parameters

titan.hadoop.input.format=com.thinkaurelius.titan.hadoop.formats.graphson.GraphSONInputFormat
titan.hadoop.input.location=examples/graph-of-the-gods.json

# titan.hadoop.graph.input.vertex-query-filter=v.query().limit(0)

# output data parameters

titan.hadoop.output.format=org.apache.hadoop.mapreduce.lib.output.SequenceFileOutputFormat
titan.hadoop.sideeffect.format=org.apache.hadoop.mapreduce.lib.output.TextOutputFormat
titan.hadoop.output.location=analysis
titan.hadoop.output.location.overwrite=true

# hadoop pipeline specific settings (global to the entire pipeline)

# titan.hadoop.pipeline.map-spill-over=500

titan.hadoop.pipeline.track-paths=true
titan.hadoop.pipeline.track-state=true

Commands

g = HadoopFactory.open('conf/hadoop/titan-graphson-seqfile.properties')
g._

Starts the job, but on first map generates a bunch of these:

13:52:34 INFO  org.apache.hadoop.mapreduce.Job  - Task Id : attempt_1415885648755_0004_m_000000_2, Status : FAILED
Error: java.io.IOException: wrong key class: org.apache.hadoop.io.NullWritable is not class org.apache.hadoop.io.LongWritable
        at org.apache.hadoop.io.SequenceFile$Writer.append(SequenceFile.java:1305)
        at org.apache.hadoop.mapreduce.lib.output.SequenceFileOutputFormat$1.write(SequenceFileOutputFormat.java:83)
        at org.apache.hadoop.mapreduce.lib.output.LazyOutputFormat$LazyRecordWriter.write(LazyOutputFormat.java:115)
        at org.apache.hadoop.mapred.MapTask$NewDirectOutputCollector.write(MapTask.java:634)
        at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)
        at org.apache.hadoop.mapreduce.lib.chain.Chain$ChainRecordWriter.write(Chain.java:254)
        at org.apache.hadoop.mapreduce.lib.chain.ChainMapContextImpl.write(ChainMapContextImpl.java:110)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)
        at com.thinkaurelius.titan.hadoop.mapreduce.IdentityMap$Map.map(IdentityMap.java:62)
        at com.thinkaurelius.titan.hadoop.mapreduce.IdentityMap$Map.map(IdentityMap.java:36)
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)
        at org.apache.hadoop.mapreduce.lib.chain.Chain.runMapper(Chain.java:389)
        at org.apache.hadoop.mapreduce.lib.chain.ChainMapper.run(ChainMapper.java:149)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:763)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:339)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:162)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1491)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:157)

Then dies - all map tasks failed.

Does that help?

**Comment by keith-hinde** [comment]
Interestingly - same config, but running g.V.count() actually runs to completion - producing the correct total (12) and producing a sequence file to boot (Not sure if it's valid though).

Dumping out all vertices via g.V fails, as does dumping out edges via g.E.

**Comment by dalaro** [comment]
@lw47 Your GraphSON -> SequenceFile config and test case reproduces the issue here just as you described.  Thanks, very helpful.

**Comment by dalaro** [comment]
This now has a test (0c28ed51f4be7d8a178024d7b46bbcd11f05038b) and a fix (520e7c650e08ebc2d6b86bfa1515f032006259f4).  Thanks again for the reproducible test case.

**Comment by keith-hinde** [comment]
Thanks guys - glad to help!
