### ISSUE TITLE
loading graph with faunus fails because KryoSerializer buffer too small

### ISSUE THREAD

**Issue by mglusiuk** [thinkaurelius/titan#809]
During loading graph to titan(backend cassandra) using faunus job I have this exception:

com.esotericsoftware.kryo.KryoException: Buffer too small: capacity: 0, required: 1
at com.esotericsoftware.kryo.io.Input.require(Input.java:152)
at com.esotericsoftware.kryo.io.Input.readInt(Input.java:337)
at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:747)
at com.esotericsoftware.kryo.Kryo.readObjectOrNull(Kryo.java:668)
at com.thinkaurelius.titan.graphdb.database.serialize.kryo.KryoSerializer.readObject(KryoSerializer.java:128)
at com.thinkaurelius.faunus.FaunusElement$ElementProperties.readFields(FaunusElement.java:262)
at com.thinkaurelius.faunus.FaunusElement.readFields(FaunusElement.java:207)
at com.thinkaurelius.faunus.FaunusVertex.readFields(FaunusVertex.java:286)
at org.apache.hadoop.io.serializer.WritableSerialization$WritableDeserializer.deserialize(WritableSerialization.java:67)
at org.apache.hadoop.io.serializer.WritableSerialization$WritableDeserializer.deserialize(WritableSerialization.java:40)
at org.apache.hadoop.mapreduce.ReduceContext.nextKeyValue(ReduceContext.java:117)
at org.apache.hadoop.mapreduce.ReduceContext.nextKey(ReduceContext.java:92)
at org.apache.hadoop.mapreduce.Reducer.run(Reducer.java:176)
at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:649)
at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:418)
at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:415)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190)
at org.apache.hadoop.mapred.Child.main(Child.java:249)

**Comment by dalaro** [comment]
Can you please share the steps to reproduce this error, including the `HadoopFactory.open` configuration of the job(s) that cause it?

**Comment by dkuppitz** [comment]
This was resolved in #716. The setting that allows you to change the Kryo buffer size is documented here: http://s3.thinkaurelius.com/docs/titan/0.5.1/hadoop-config-ref.html#_titan_hadoop_serializer

**Comment by dalaro** [comment]
@dkuppitz that seems like a reasonable explanation.  I hadn't even considered the size limit.  Thanks!

@mglusiuk please try increasing the setting Daniel linked.  And please reopen this issue if you increase it an order of magnitude or two and the problem still appears.

**Comment by mglusiuk** [comment]
Thank you for suggestion it is possible that my data have some supernodes with a lot of edges. I will try to use this setting as you suggested.

**Comment by mglusiuk** [comment]
@dkuppitz is this setting available in faunus/titan 0.4.4?

**Comment by dkuppitz** [comment]
No, it was changed in 0.5.2. Previous versions use the hard limit of 10 MB.

**Comment by mglusiuk** [comment]
Any suggestion how can I deal with this problem in 0.4.4?

**Comment by dkuppitz** [comment]
When I faced this problem in 0.4.4 I wasn't able to find a work-around. Ultimately I changed the [hard limit](https://github.com/thinkaurelius/titan/blob/0.4.4/titan-core/src/main/java/com/thinkaurelius/titan/graphdb/database/serialize/kryo/KryoSerializer.java#L37) and recompiled Faunus.
