### ISSUE TITLE
Errors when trying to connect to Cassandra backend with Titan 0.4.4

### ISSUE THREAD

**Issue by levin-royl** [thinkaurelius/titan#813]
I am using titan-all-0.4.4. The Cassandra database is located on a machine called rcc-hrl-kvg-469 and listening on port 9160. Note that when I am using a local installation of cassandra (i.e., running on the same machine as Titan) everything looks fine.

Here is my titan config file:

autotype=none

storage.backend=cassandra
storage.hostname=rcc-hrl-kvg-469
storage.port=9160
storage.tablename=MY_DATA-Version-1

storage.index.search.backend=lucene
storage.index.search.directory=C:\TitanIndex\MY_DATA-Version-1-LuceneIndex
storage.index.search.client-only=false
storage.index.search.local-mode=true

Here is the error I am getting when attempting to create a TitanGraph via the method TitanFactory.open(config):

starting ...
 INFO [main](ConnectionPoolMBeanManager.java:45) - Registering mbean: com.netflix.MonitoredResources:type=ASTYANAX,name=ClusterTitanConnectionPool,ServiceType=connectionpool
 INFO [main](CountingConnectionPoolMonitor.java:181) - AddHost: rcc-hrl-kvg-469
Exception in thread "main" java.lang.IllegalArgumentException: Could not instantiate implementation: com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxStoreManager
    at com.thinkaurelius.titan.diskstorage.Backend.instantiate(Backend.java:355)
    at com.thinkaurelius.titan.diskstorage.Backend.getImplementationClass(Backend.java:367)
    at com.thinkaurelius.titan.diskstorage.Backend.getStorageManager(Backend.java:311)
    at com.thinkaurelius.titan.diskstorage.Backend.<init>(Backend.java:121)
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1173)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.<init>(StandardTitanGraph.java:75)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:40)
    at com.ibm.graphdb.GraphUtil.connectToGraph(GraphUtil.java:654)
    at com.ibm.relational2graph.Main.main(Main.java:61)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at com.thinkaurelius.titan.diskstorage.Backend.instantiate(Backend.java:344)
    ... 8 more
Caused by: com.thinkaurelius.titan.diskstorage.TemporaryStorageException: Temporary failure in storage backend
    at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxStoreManager.ensureKeyspaceExists(AstyanaxStoreManager.java:550)
    at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxStoreManager.<init>(AstyanaxStoreManager.java:276)
    ... 13 more
Caused by: com.netflix.astyanax.connectionpool.exceptions.PoolTimeoutException: PoolTimeoutException: [host=rcc-hrl-kvg-469(9.148.243.236):9160, latency=10001(10001), attempts=1]Timed out waiting for connection
    at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.waitForConnection(SimpleHostConnectionPool.java:218)
    at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.borrowConnection(SimpleHostConnectionPool.java:185)
    at com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover.borrowConnection(RoundRobinExecuteWithFailover.java:66)
    at com.netflix.astyanax.connectionpool.impl.AbstractExecuteWithFailoverImpl.tryOperation(AbstractExecuteWithFailoverImpl.java:67)
    at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:256)
    at com.netflix.astyanax.thrift.ThriftClusterImpl.executeSchemaChangeOperation(ThriftClusterImpl.java:146)
    at com.netflix.astyanax.thrift.ThriftClusterImpl.addKeyspace(ThriftClusterImpl.java:246)
    at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxStoreManager.ensureKeyspaceExists(AstyanaxStoreManager.java:545)
    ... 14 more

**Comment by mbroecheler** [comment]
You might not have the rights to access that remote machine or something else is blocking the traffic. It seems that you are trying to run Titan locally against a remote Cassandra instance. That is not a recommended way of operating Titan.

**Comment by nitinknoldus** [comment]
hi broecheler,
whats the solution to this problem ?
