### ISSUE TITLE
Getting an error when running simple Gremlin script in Faunus

### ISSUE THREAD

**Issue by levin-royl** [thinkaurelius/titan#815]
I am using titan-all version 0.4.4
## Code:

```
    Configuration config = GraphUtil.readGraphConfigFromFile("titandb-faunus-remote.properties");

    FaunusGraph g = new FaunusGraph(FaunusUtil.toHadoopConfig(config));

    FaunusPipeline pipe = new FaunusPipeline(g);
    pipe.V().groupCount(ElementKeySchema.typeToken);
    pipe.submit();
```
## Config File:
# input graph parameters

faunus.graph.input.format=com.thinkaurelius.faunus.formats.titan.hbase.TitanHBaseInputFormat
faunus.graph.input.titan.storage.backend=hbase
faunus.graph.input.titan.storage.hostname=rcc-hrl-kvg-469
faunus.graph.input.titan.storage.port=21810
faunus.graph.input.titan.storage.tablename=IBM-Connections-Version-5
# output data (graph or statistic) parameters

faunus.graph.output.format=com.thinkaurelius.faunus.formats.titan.hbase.TitanHBaseOutputFormat
faunus.graph.output.titan.storage.backend=hbase
faunus.graph.output.titan.storage.hostname=rcc-hrl-kvg-469
faunus.graph.output.titan.storage.port=21810
faunus.graph.output.titan.storage.tablename=analysis
faunus.graph.output.titan.storage.read-only=true
faunus.graph.output.titan.storage.batch-loading=true

faunus.sideeffect.output.format=org.apache.hadoop.mapreduce.lib.output.TextOutputFormat
faunus.output.location=hdfs://rcc-hrl-kvg-469:9100/user/royl/department-groupcount
faunus.output.location.overwrite=true
faunus.mapreduce.faunuscompiler.pathEnabled=true

fs.default.name=hdfs://rcc-hrl-kvg-469:9100/user/royl

mapred.remote.os=Linux
mapred.job.tracker=rcc-hrl-kvg-469:9101
mapred.max.split.size=5242880
mapred.job.reuse.jvm.num.tasks=-1
## Error:

Exception in thread "main" java.lang.IncompatibleClassChangeError: Found class org.objectweb.asm.ClassVisitor, but interface was expected
    at org.codehaus.groovy.classgen.AsmClassGenerator.visitClass(AsmClassGenerator.java:129)
    at org.codehaus.groovy.control.CompilationUnit$14.call(CompilationUnit.java:770)
    at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:970)
    at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:548)
    at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:526)
    at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:503)
    at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:302)
    at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:281)
    at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:267)
    at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:214)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getScriptClass(GroovyScriptEngineImpl.java:352)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:128)
    at javax.script.AbstractScriptEngine.eval(Unknown Source)
    at com.thinkaurelius.faunus.FaunusPipeline.validateClosure(FaunusPipeline.java:1096)
    at com.thinkaurelius.faunus.FaunusPipeline.groupCount(FaunusPipeline.java:939)
    at com.thinkaurelius.faunus.FaunusPipeline.groupCount(FaunusPipeline.java:925)
    at com.ibm.graphdb.analytics.AnalyticsMain.basicFaunusTests(AnalyticsMain.java:72)
    at com.ibm.graphdb.analytics.AnalyticsMain.main(AnalyticsMain.java:61)

**Comment by dkuppitz** [comment]
Looks like the `groupCount` closure is causing the error. Where does `ElementKeySchema.typeToken` come from?

**Comment by levin-royl** [comment]
Thanks for your response, I thought of that and even removed the groupby altogether (i.e., running no query at all) but still I get the same error. Seems to me like there is some conflict with jar versions but I can't find out what's causing it ...

**Comment by dkuppitz** [comment]
The stacktrace contains:

```
at com.thinkaurelius.faunus.FaunusPipeline.validateClosure(FaunusPipeline.java:1096)
at com.thinkaurelius.faunus.FaunusPipeline.groupCount(FaunusPipeline.java:939)
at com.thinkaurelius.faunus.FaunusPipeline.groupCount(FaunusPipeline.java:925)
```

Not sure how you're able to get the same error if you remove the `groupCount` step. Please try to use a very basic query, like:

```
new FaunusPipeline(g).V().count().submit();
```

**Comment by levin-royl** [comment]
I meant similar error. Here is what I get using the count query you suggested:

FYI--- the code is running from my local machine (in eclipse) and the graph is stored in a remove server running hbase.

Exception in thread "main" java.lang.VerifyError: class org.codehaus.groovy.runtime.callsite.GroovySunClassLoader$2 overrides final method visit.(IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteGenerator.isCompilable(CallSiteGenerator.java:245)
    at org.codehaus.groovy.reflection.CachedMethod.createStaticMetaMethodSite(CachedMethod.java:284)
    at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.createStaticMetaMethodSite(StaticMetaMethodSite.java:111)
    at groovy.lang.MetaClassImpl.createStaticSite(MetaClassImpl.java:3034)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:61)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:146)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at com.tinkerpop.gremlin.groovy.Gremlin.load(Gremlin.groovy:19)
    at com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.<init>(GremlinGroovyScriptEngine.java:70)
    at com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.<init>(GremlinGroovyScriptEngine.java:61)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
    at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:186)
    at com.tinkerpop.gremlin.groovy.Gremlin.<clinit>(Gremlin.groovy:15)
    at com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.<init>(GremlinGroovyScriptEngine.java:70)
    at com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.<init>(GremlinGroovyScriptEngine.java:61)
    at com.thinkaurelius.faunus.formats.VertexQueryFilter.<clinit>(VertexQueryFilter.java:29)
    at com.thinkaurelius.faunus.formats.titan.hbase.TitanHBaseInputFormat.setConf(TitanHBaseInputFormat.java:54)
    at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:62)
    at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:117)
    at org.apache.hadoop.mapred.JobClient.writeNewSplits(JobClient.java:1051)
    at org.apache.hadoop.mapred.JobClient.writeSplits(JobClient.java:1071)
    at org.apache.hadoop.mapred.JobClient.access$700(JobClient.java:179)
    at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:983)
    at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:936)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Unknown Source)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190)
    at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:936)
    at org.apache.hadoop.mapreduce.Job.submit(Job.java:550)
    at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:580)
    at com.thinkaurelius.faunus.mapreduce.FaunusCompiler.run(FaunusCompiler.java:326)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:79)
    at com.thinkaurelius.faunus.FaunusPipeline.submit(FaunusPipeline.java:1075)
    at com.thinkaurelius.faunus.FaunusPipeline.submit(FaunusPipeline.java:1058)
    at com.ibm.graphdb.analytics.AnalyticsMain.basicFaunusTests(AnalyticsMain.java:74)
    at com.ibm.graphdb.analytics.AnalyticsMain.main(AnalyticsMain.java:61)

**Comment by dalaro** [comment]
@levin-royl Which version of ASM is on the runtime classpath when the latest exception you pasted is thrown?

**Comment by dkuppitz** [comment]
Maybe [this discussion](https://groups.google.com/forum/#!msg/aureliusgraphs/i72ZJG0yafg/Ax45LA4ESb4J) on the mailing list can help. Seems like some people ran into the same - or at least into a related - issue.
