### ISSUE TITLE
When IDBlockThread failes to claim ID block after lockRetries there is no way for the process to recover

### ISSUE THREAD

**Issue by jasonculverhouse** [thinkaurelius/titan#82]
Here's a stack trace where  the `IDBlockThread` fails to allocate an id block after `lockTimes = 3`  Most of the time I see the process successfully get a new ID block after 1 retry.   In this case the storage exception bubbles up into  `IDBlockThread.run()` and there is no opportunity to recover.  I guessing there are ~4 to 6 processes writing to the graph when this happend.

```
28041974 [pool-1-thread-11] DEBUG com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool  - Starting id block renewal thread upon 1410599901

28042494 [Thread-3777] DEBUG com.thinkaurelius.titan.diskstorage.util.OrderedKeyColumnValueIDManager  - Failed to acquire ID block [1410700001,1410800001) (another host claimed it first)

28042928 [Thread-3777] DEBUG com.thinkaurelius.titan.diskstorage.util.OrderedKeyColumnValueIDManager  - Failed to acquire ID block [1410800001,1410900001) (another host claimed it first)

28043454 [Thread-3777] DEBUG com.thinkaurelius.titan.diskstorage.util.OrderedKeyColumnValueIDManager  - Failed to acquire ID block [1410900001,1411000001) (another host claimed it first)

28616961 [pool-1-thread-5] ERROR java.lang.IllegalArgumentException
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:76)
    at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextBlock(StandardIDPool.java:63)
    at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextID(StandardIDPool.java:104)
    at com.thinkaurelius.titan.graphdb.database.idassigner.SimpleVertexIDAssigner.nextEdgeID(SimpleVertexIDAssigner.java:93)
    at com.thinkaurelius.titan.graphdb.database.idassigner.SimpleVertexIDAssigner.getNewID(SimpleVertexIDAssigner.java:54)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.assignID(StandardTitanGraph.java:571)
    at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.registerNewEntity(AbstractTitanTx.java:121)
    at com.thinkaurelius.titan.graphdb.relations.factory.StandardPersistedRelationFactory.createNewProperty(StandardPersistedRelationFactory.java:66)
    at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.addProperty(AbstractTitanTx.java:204)
    at com.thinkaurelius.titan.graphdb.vertices.AbstractTitanVertex.addProperty(AbstractTitanVertex.java:221)
    at com.thinkaurelius.titan.graphdb.blueprints.BlueprintsVertexUtil.setProperty(BlueprintsVertexUtil.java:33)
    at com.thinkaurelius.titan.graphdb.vertices.AbstractTitanVertex.setProperty(AbstractTitanVertex.java:232)
```

**Comment by mbroecheler** [comment]
I am assuming that you are loading a lot of data when this happens? In that case, its best to increase the id block size so that there isn't that much contention on the blocks. Also, increasing the retry-times will help in this case. Check the graph configuration: https://github.com/thinkaurelius/titan/wiki/Graph-Configuration.

In general, I think we should increase the default retry attempts for id acquisition. As you pointed out, if this fails, the consequences are pretty fatal.
