### ISSUE TITLE
Titan-Hadoop does not respect the output.location in properties.

### ISSUE THREAD

**Issue by dbeaumon** [thinkaurelius/titan#822]
Titan 0.5.0 / Hadoop 2.5.1

First, `conf/titan/titan-graphson.properties` does not have an `output.location` nor override output location like Faunus did. In essence, the bottom two properties are not present.

``` text
titan.hadoop.output.location=output
titan.hadoop.output.location.overwrite=true
```

However, when the bottom two properties are added, Titan-Hadoop ignores the `output.location` specified and always makes the directory `jobs`. This is weird. Why is the output not going to `output`.

Finally, at the completion of the job, the following exception always happen (even when the `output.location` is specified as `jobs`.

``` groovy
gremlin> g.getConf('titan')
==>titan.hadoop.input.location=loadlab.json
==>titan.hadoop.sideeffect.format=org.apache.hadoop.mapreduce.lib.output.TextOutputFormat
==>titan.hadoop.output.location.overwrite=true
==>titan.hadoop.output.location=jobs
==>titan.hadoop.output.format=com.thinkaurelius.titan.hadoop.formats.noop.NoOpOutputFormat
==>titan.hadoop.input.format=com.thinkaurelius.titan.hadoop.formats.graphson.GraphSONInputFormat
gremlin> g.E.count()
16:47:46 WARN  org.apache.hadoop.mapreduce.JobSubmitter  - Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
16:47:50 INFO  org.apache.hadoop.mapreduce.lib.input.FileInputFormat  - Total input paths to process : 1
16:47:50 INFO  org.apache.hadoop.mapreduce.JobSubmitter  - number of splits:9
16:47:50 INFO  org.apache.hadoop.mapreduce.JobSubmitter  - Submitting tokens for job: job_1411855254216_0058
16:47:56 INFO  org.apache.hadoop.mapreduce.Job  - The url to track the job: http://http://gd-dt-theta-02:8088/proxy/application_1411855254216_0058/
16:47:56 INFO  org.apache.hadoop.mapreduce.Job  - Running job: job_1411855254216_0058
16:48:04 INFO  org.apache.hadoop.mapreduce.Job  - Job job_1411855254216_0058 running in uber mode : false
16:48:04 INFO  org.apache.hadoop.mapreduce.Job  -  map 0% reduce 0%
16:48:18 INFO  org.apache.hadoop.mapreduce.Job  -  map 1% reduce 0%

...
16:51:59 INFO  org.apache.hadoop.mapreduce.Job  -  map 92% reduce 26%
16:52:06 INFO  org.apache.hadoop.mapreduce.Job  -  map 96% reduce 26%
16:52:08 INFO  org.apache.hadoop.mapreduce.Job  -  map 96% reduce 30%
16:52:09 INFO  org.apache.hadoop.mapreduce.Job  -  map 100% reduce 100%
16:52:09 INFO  org.apache.hadoop.mapreduce.Job  - Job job_1411855254216_0058 completed successfully
No enum constant org.apache.hadoop.mapreduce.JobCounter.VCORES_MILLIS_REDUCES
Display stack trace? [yN] y
java.lang.RuntimeException: No enum constant org.apache.hadoop.mapreduce.JobCounter.VCORES_MILLIS_REDUCES
    at com.thinkaurelius.titan.hadoop.tinkerpop.gremlin.ResultHookClosure.call(ResultHookClosure.java:44)
    at groovy.lang.Closure.call(Closure.java:428)
    at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:231)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:64)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at org.codehaus.groovy.tools.shell.Groovysh.setLastResult(Groovysh.groovy:324)
    at org.codehaus.groovy.tools.shell.Groovysh.this$3$setLastResult(Groovysh.groovy)
    at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2416)
    at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3347)
    at org.codehaus.groovy.tools.shell.Shell.setProperty(Shell.groovy)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setGroovyObjectProperty(ScriptBytecodeAdapter.java:528)
    at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:152)
    at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:114)
    at org.codehaus.groovy.tools.shell.Shell$leftShift$0.call(Unknown Source)
    at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:88)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
    at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:100)
    at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
    at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:57)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
    at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:66)
    at com.thinkaurelius.titan.hadoop.tinkerpop.gremlin.Console.<init>(Console.java:61)
    at com.thinkaurelius.titan.hadoop.tinkerpop.gremlin.Console.<init>(Console.java:68)
    at com.thinkaurelius.titan.hadoop.tinkerpop.gremlin.Console.main(Console.java:73)
Caused by: java.lang.IllegalArgumentException: No enum constant org.apache.hadoop.mapreduce.JobCounter.VCORES_MILLIS_REDUCES
    at java.lang.Enum.valueOf(Enum.java:238)
    at org.apache.hadoop.mapreduce.counters.FrameworkCounterGroup.valueOf(FrameworkCounterGroup.java:148)
    at org.apache.hadoop.mapreduce.counters.FrameworkCounterGroup.findCounter(FrameworkCounterGroup.java:182)
    at org.apache.hadoop.mapreduce.counters.AbstractCounters.findCounter(AbstractCounters.java:154)
    at org.apache.hadoop.mapreduce.TypeConverter.fromYarn(TypeConverter.java:240)
    at org.apache.hadoop.mapred.ClientServiceDelegate.getJobCounters(ClientServiceDelegate.java:370)
    at org.apache.hadoop.mapred.YARNRunner.getJobCounters(YARNRunner.java:511)
    at org.apache.hadoop.mapreduce.Job$7.run(Job.java:756)
    at org.apache.hadoop.mapreduce.Job$7.run(Job.java:753)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:422)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1491)
    at org.apache.hadoop.mapreduce.Job.getCounters(Job.java:753)
    at org.apache.hadoop.mapreduce.Job.monitorAndPrintJob(Job.java:1361)
    at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:1289)
    at com.thinkaurelius.titan.hadoop.compat.h2.Hadoop2Compiler.run(Hadoop2Compiler.java:299)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
    at com.thinkaurelius.titan.hadoop.HadoopPipeline.submit(HadoopPipeline.java:1092)
    at com.thinkaurelius.titan.hadoop.HadoopPipeline.submit(HadoopPipeline.java:1075)
    at com.thinkaurelius.titan.hadoop.tinkerpop.gremlin.ResultHookClosure.call(ResultHookClosure.java:39)
    ... 53 more
gremlin> 
```

**Comment by dalaro** [comment]
This has been added to titan05 and works much like it did back in Faunus 0.4; it overrides the default value of the FileOutputFormat output path property for the final job in a chain when set.  Also added a test.
