### ISSUE TITLE
Invoking TitanFactory.open with nonexistent file argument throws exception

### ISSUE THREAD

**Issue by dalaro** [thinkaurelius/titan#831]
If a JVM's first `TitanFactory.open` call passes a nonexistent configuration file, then TitanFactory gets into the else block on lines 169-190 where it tries to decode a backend shorthand.  This leads to a circular reference between static initializers triggered on line 173 which eventually generates an ExceptionInInitializerError:

```
gremlin> g = TitanFactory.open('nonexistent/file')
java.lang.ExceptionInInitializerError
Display stack trace? [yN] y
java.lang.ExceptionInInitializerError
        at com.thinkaurelius.titan.diskstorage.Backend$5.<init>(Backend.java:559)
        at com.thinkaurelius.titan.diskstorage.Backend.<clinit>(Backend.java:558)
        at com.thinkaurelius.titan.core.TitanFactory.getLocalConfiguration(TitanFactory.java:173)
        at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:60)
        at com.thinkaurelius.titan.core.TitanFactory$open.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
        (rest of the Groovy REPL stack frames omitted...)
Caused by: java.lang.NullPointerException
        at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<clinit>(GraphDatabaseConfiguration.java:766)
        ... 56 more
```

Workaround: pass an extant properties file to `TitanFactory.open` on the initial invocation of that method after VM startup.  This triggers static initializers in a safe order.  Subsequent invocations can use either a file or shorthand argument.

Slated fix: add a failing test that exercises the shorthand-parsing logic path in `TitanFactory.open` right after VM start, then break static initializer circularity that led to this exception, which should fix the test.

**Comment by dalaro** [comment]
This is tested in c546e13325756f7ed68b3d4f72ced4e097fee7ff.  I broke the static initializer cycle in a2149cec1d2d9b52b1bad596ef8cb1accdd2f3db by pulling the canonical maps of index provider and store manager names and classes into small, self-contained enum classes used by both Backend and GraphDatabaseConfiguration.  Some of Backend's static initializers continue to reference static fields in GraphDatabaseConfiguration, but not the other way around.
