### ISSUE TITLE
Cannot get titan-hadoop (with titan-all 0.5.1) to work on a windows machine

### ISSUE THREAD

**Issue by levin-royl** [thinkaurelius/titan#833]
I am running a simple titan-hadoop-gremlin query (within windows eclipse) on my windows machine that also has cassandra installed.
## Here is my log file (with the error)

5418 [main] WARN  org.apache.hadoop.util.NativeCodeLoader  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
5482 [main] ERROR com.thinkaurelius.titan.hadoop.config.HBaseAuthHelper  - Not obtaining HBase Auth Token for MapReduce job VerticesMap.Map
5499 [main] ERROR org.apache.hadoop.util.Shell  - Failed to locate the winutils binary in the hadoop binary path
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
    at org.apache.hadoop.util.Shell.getQualifiedBinPath(Shell.java:278)
    at org.apache.hadoop.util.Shell.getWinUtilsPath(Shell.java:300)
    at org.apache.hadoop.util.Shell.<clinit>(Shell.java:293)
    at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:76)
    at org.apache.hadoop.conf.Configuration.getStrings(Configuration.java:1514)
    at org.apache.hadoop.io.serializer.SerializationFactory.<init>(SerializationFactory.java:58)
    at org.apache.hadoop.io.DefaultStringifier.<init>(DefaultStringifier.java:62)
    at org.apache.hadoop.mapreduce.lib.chain.Chain.setMapperConf(Chain.java:726)
    at org.apache.hadoop.mapreduce.lib.chain.Chain.addMapper(Chain.java:646)
    at org.apache.hadoop.mapreduce.lib.chain.ChainMapper.addMapper(ChainMapper.java:126)
    at com.thinkaurelius.titan.hadoop.compat.h2.Hadoop2Compiler.addMap(Hadoop2Compiler.java:169)
    at com.thinkaurelius.titan.hadoop.HadoopPipeline.V(HadoopPipeline.java:283)
    at com.ibm.titanlytics.Main.main(Main.java:37)
5868 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation  - mapred.jar is deprecated. Instead, use mapreduce.job.jar
5869 [main] INFO  com.thinkaurelius.titan.hadoop.config.job.JobClasspathConfigurers  - Uploading jars on classpath DistributedCache in lieu of a mapred job jar
6088 [main] INFO  com.thinkaurelius.titan.hadoop.compat.h2.Hadoop2Compiler  - Compiled to 1 MapReduce job(s)
6089 [main] INFO  com.thinkaurelius.titan.hadoop.compat.h2.Hadoop2Compiler  - Executing job 1 out of 1: VerticesMap.Map
6107 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation  - session.id is deprecated. Instead, use dfs.metrics.session-id
6108 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics  - Initializing JVM Metrics with processName=JobTracker, sessionId=
Exception in thread "main" java.lang.NullPointerException
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1010)
    at org.apache.hadoop.util.Shell.runCommand(Shell.java:404)
    at org.apache.hadoop.util.Shell.run(Shell.java:379)
    at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:589)
    at org.apache.hadoop.util.Shell.execCommand(Shell.java:678)
    at org.apache.hadoop.util.Shell.execCommand(Shell.java:661)
    at org.apache.hadoop.fs.RawLocalFileSystem.setPermission(RawLocalFileSystem.java:639)
    at org.apache.hadoop.fs.RawLocalFileSystem.mkdirs(RawLocalFileSystem.java:435)
    at org.apache.hadoop.fs.FilterFileSystem.mkdirs(FilterFileSystem.java:277)
    at org.apache.hadoop.mapreduce.JobSubmissionFiles.getStagingDir(JobSubmissionFiles.java:125)
    at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:344)
    at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1268)
    at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1265)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1491)
    at org.apache.hadoop.mapreduce.Job.submit(Job.java:1265)
    at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:1286)
    at com.thinkaurelius.titan.hadoop.compat.h2.Hadoop2Compiler.run(Hadoop2Compiler.java:292)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
    at com.thinkaurelius.titan.hadoop.HadoopPipeline.submit(HadoopPipeline.java:1092)
    at com.thinkaurelius.titan.hadoop.HadoopPipeline.submit(HadoopPipeline.java:1075)
    at com.ibm.titanlytics.Main.main(Main.java:38)
## Code

```
    URL propertiesUrl = ConfigurationUtils.locate("titandb-hadoop-cassandra.properties");
    File propertiesFile = ConfigurationUtils.fileFromURL(propertiesUrl);

    HadoopGraph graph = HadoopFactory.open(propertiesFile.toString());

    HadoopPipeline pipe = new HadoopPipeline(graph);
    pipe.V();
    pipe.submit();

    System.out.println("done.");
```

I also tried replacing pipe.V() with pipe.V().count() but I get the same error.
## config_file
# input graph parameters

titan.hadoop.input.format=com.thinkaurelius.titan.hadoop.formats.cassandra.TitanCassandraInputFormat
titan.hadoop.input.conf.storage.backend=cassandrathrift
titan.hadoop.input.conf.storage.hostname=localhost
titan.hadoop.input.conf.storage.port=9160
titan.hadoop.input.conf.storage.cassandra.keyspace=testdata
cassandra.input.partitioner.class=org.apache.cassandra.dht.Murmur3Partitioner
# output data parameters

titan.hadoop.output.format=com.thinkaurelius.titan.hadoop.formats.graphson.GraphSONOutputFormat
titan.hadoop.sideeffect.format=org.apache.hadoop.mapreduce.lib.output.TextOutputFormat
titan.hadoop.jobdir.overwrite=true
titan.hadoop.jobdir.location=job

**Comment by dalaro** [comment]
This seems to be the same problem as in #832:

```
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
```

**Comment by levin-royl** [comment]
The problems may indeed be similar but they are not the same. Here (in #833) I am trying to use titan-hadoop and in the previous issue (#832) I am merely using titan (i.e., without hadoop).
Note that in both cases it is a development configuration so its easier for me to work in eclipse running titan locally and using the remote linux machine as the storage backend service.
Hence, I do not want (or need) to install hadoop or hbase on my local machine.
