### ISSUE TITLE
SOLR issues with DSE Search

### ISSUE THREAD

**Issue by fitzoh** [thinkaurelius/titan#837]
Datastax enterprise is a commercial cassandra distribution, which comes with a built in SOLR solution, DSE Search.

Directions for using DSE Search with titan are listed in the [titan docs](http://s3.thinkaurelius.com/docs/titan/current/solr.html#dse-search)

DSE Search does not have the ability to do atomic updates
http://www.datastax.com/documentation/datastax_enterprise/3.2/datastax_enterprise/srch/srchUse.html

> The commit log replaces the Solr updatelog, which is not supported in DSE Search/Solr. Consequently, atomic updates and real-time get that require the updateLog are not supported. In Cassandra, a write is atomic at the row-level, meaning inserting or updating columns in a row is treated as one write operation.

It appears that titan-solr makes use of atomic updates, which causes issues when attempting to use DSE search as an index provider.

The use of atomic updates was mentioned byby @xedin in the initial pull request, #372 

```
11-18-2014 13:48:36,468 [INFO] [SimpleAsyncTaskExecutor-8] com.thinkaurelius.titan.diskstorage.util.BackendOperation  - Temporary exception during backend operation [IndexMutation]. Attempting backoff retry.
com.thinkaurelius.titan.diskstorage.TemporaryBackendException: Unable to complete query on Solr.
    at com.thinkaurelius.titan.diskstorage.solr.SolrIndex.storageException(SolrIndex.java:763)
    at com.thinkaurelius.titan.diskstorage.solr.SolrIndex.mutate(SolrIndex.java:298)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:122)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:119)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:56)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:42)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.flushInternal(IndexTransaction.java:119)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.commit(IndexTransaction.java:100)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction.commitIndexes(BackendTransaction.java:124)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.commit(StandardTitanGraph.java:643)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.commit(StandardTitanTx.java:1299)
    at com.company.graph.titan.GraphDaoTitan.persist(GraphDaoTitan.java:90)
    at com.company.service.titan.GraphPersistListener.listen(GraphPersistListener.java:72)
    at com.companyservice.titan.GraphPersistListener.listen(GraphPersistListener.java:62)
    at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
    at org.springframework.amqp.rabbit.listener.adapter.MessageListenerAdapter.invokeListenerMethod(MessageListenerAdapter.java:482)
    at org.springframework.amqp.rabbit.listener.adapter.MessageListenerAdapter.onMessage(MessageListenerAdapter.java:373)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:650)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:576)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$001(SimpleMessageListenerContainer.java:78)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$1.invokeListener(SimpleMessageListenerContainer.java:161)
    at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
    at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:74)
    at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:263)
    at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:168)
    at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:98)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
    at com.sun.proxy.$Proxy50.invokeListener(Unknown Source)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.invokeListener(SimpleMessageListenerContainer.java:1177)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:559)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:950)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:934)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$600(SimpleMessageListenerContainer.java:78)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1045)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: Atomic document updates are not supported unless <updateLog/> is configured
    at org.apache.solr.client.solrj.impl.HttpSolrServer.executeMethod(HttpSolrServer.java:554)
    at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:210)
    at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:206)
    at org.apache.solr.client.solrj.impl.LBHttpSolrServer.request(LBHttpSolrServer.java:478)
    at com.thinkaurelius.titan.diskstorage.solr.SolrIndex.commitDocumentChanges(SolrIndex.java:378)
    at com.thinkaurelius.titan.diskstorage.solr.SolrIndex.mutate(SolrIndex.java:295)
    ... 42 more
11-18-2014 13:48:37,900 [ERROR] [SimpleAsyncTaskExecutor-8] com.thinkaurelius.titan.diskstorage.solr.SolrIndex  - Unable to save documents to Solr as one of the shape objects stored were not compatible with Solr.
org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: Atomic document updates are not supported unless <updateLog/> is configured
    at org.apache.solr.client.solrj.impl.HttpSolrServer.executeMethod(HttpSolrServer.java:554)
    at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:210)
    at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:206)
    at org.apache.solr.client.solrj.impl.LBHttpSolrServer.request(LBHttpSolrServer.java:478)
    at com.thinkaurelius.titan.diskstorage.solr.SolrIndex.commitDocumentChanges(SolrIndex.java:378)
    at com.thinkaurelius.titan.diskstorage.solr.SolrIndex.mutate(SolrIndex.java:295)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:122)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:119)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:56)
    at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:42)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.flushInternal(IndexTransaction.java:119)
    at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.commit(IndexTransaction.java:100)
    at com.thinkaurelius.titan.diskstorage.BackendTransaction.commitIndexes(BackendTransaction.java:124)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.commit(StandardTitanGraph.java:643)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.commit(StandardTitanTx.java:1299)
    at com.company.graph.titan.GraphDaoTitan.persist(GraphDaoTitan.java:90)
    at com.company.service.titan.GraphPersistListener.listen(GraphPersistListener.java:72)
    at com.company.service.titan.GraphPersistListener.listen(GraphPersistListener.java:62)
    at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
    at org.springframework.amqp.rabbit.listener.adapter.MessageListenerAdapter.invokeListenerMethod(MessageListenerAdapter.java:482)
    at org.springframework.amqp.rabbit.listener.adapter.MessageListenerAdapter.onMessage(MessageListenerAdapter.java:373)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:650)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:576)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$001(SimpleMessageListenerContainer.java:78)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$1.invokeListener(SimpleMessageListenerContainer.java:161)
    at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
    at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:74)
    at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:263)
    at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:168)
    at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:98)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
    at com.sun.proxy.$Proxy50.invokeListener(Unknown Source)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.invokeListener(SimpleMessageListenerContainer.java:1177)
    at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:559)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:950)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:934)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$600(SimpleMessageListenerContainer.java:78)
    at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1045)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by xedin** [comment]
Currently we only support atomic updates because it's problematic to pull whole documents on every update, but in future we are considering adding a mode which will do that.

**Comment by rushmorem** [comment]
Any updates on this? I want to use DSE Search but Titan expects a newer version of Solr than the one in DSE 4.7.3 so I can't even use the Solr configs that come with Titan.

**Comment by rushmorem** [comment]
It would be real nice if Titan 1.0 is released with support for DSE Search 4.7.x.

**Comment by mbroecheler** [comment]
Unfortunately, DSE Search does not support atomic document updates which means that it cannot support updates in Titan without extraordinary cost.

**Comment by jeromatron** [comment]
Should we remove the section of the docs talking about how to configure Titan to use DSE Search at this point since it doesn't use the updateLog?  Specifically http://s3.thinkaurelius.com/docs/titan/1.0.0/solr.html#dse-search ?

Or would there be alternative way on the DSE Search side that could enable this without supporting the Solr updateLog?

I just spent some time trying to get it working and to help update the docs and I think if there is no way it can be done, we should remove the current instructions and make a note about it not working with DSE Search and the reason - if only to not frustrate people.  We could also make a note indicating that DSE will include a graph database in the near future for those wanting to stick with DSE but for now, with Titan, it is recommended to use either Elastic Search or Solr to index in that manner.

What do you think?

**Comment by ghost** [comment]
It is not clear to me after reading through this what the "Issue" with Titan is, other than documentation that might need removing.  It sounds like the "Issue", in this case is that, at least at te time of reporting (over a year ago) DataStax Enterprise Edition didn't have key capabilities and was back level in its Solr support.  

Can someone provide an update on if DSE now works, or if we should move forward with removal of the DSE documentation from Titan ?
