### ISSUE TITLE
Unknown configuration element in namespace when reflective config option loader disabled

### ISSUE THREAD

**Issue by skavulya** [thinkaurelius/titan#850]
Some configuration options in the IDs namespace are not recognized when the reflective config option loader is disabled. 

I tried disabling the reflective config loader because I was trying to figure out why vertex writes were significantly slower in Titan 0.5.1 and Titan 0.5.2 in my system when compared to Titan 0.5.0. I don't think the reflective config loader is the reason for the slowdown in my system, but I came across this error when I tried disabling the loader.

Steps to reproduce: titan-0.5.2-hadoop2
export TITAN_LOAD_CFG_OPTS=false
bin/gremlin.sh -l INFO

gremlin> conf = new BaseConfiguration()
gremlin> conf.setProperty("storage.hostname", "localhost")
gremlin> conf.setProperty("ids.num-partitions", 20)
gremlin> conf.setProperty("storage.backend", "hbase")
gremlin> conf.setProperty("storage.hbase.table", "test_graph")
gremlin> graph = TitanFactory.open(conf)

15:35:46 INFO  com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration  - Ignored configuration entry for ids.num-partitions since it does not map to an option
java.lang.IllegalArgumentException: Unknown configuration element in namespace [root.ids]: num-partitions
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)
        at com.thinkaurelius.titan.diskstorage.configuration.ConfigElement.parse(ConfigElement.java:170)
        at com.thinkaurelius.titan.diskstorage.configuration.BasicConfiguration.getAll(BasicConfiguration.java:80)
        at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1327)
        at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:91)
        at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:71)
        at com.thinkaurelius.titan.core.TitanFactory$open.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at groovysh_evaluate.run(groovysh_evaluate:82)
        at groovysh_evaluate$run.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
        at groovysh_evaluate$run.call(Unknown Source)
        at org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:67)
        at org.codehaus.groovy.tools.shell.Interpreter$evaluate.call(Unknown Source)
        at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:152)
        at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:114)
        at org.codehaus.groovy.tools.shell.Shell$leftShift$0.call(Unknown Source)
        at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:88)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:100)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:272)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
        at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:57)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1079)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:148)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:66)
        at com.thinkaurelius.titan.hadoop.tinkerpop.gremlin.Console.<init>(Console.java:70)
        at com.thinkaurelius.titan.hadoop.tinkerpop.gremlin.Console.<init>(Console.java:83)
        at com.thinkaurelius.titan.hadoop.tinkerpop.gremlin.Console.main(Console.java:87)

**Comment by dalaro** [comment]
Hi @skavulya.  Here's some background.

Titan's config system relies on numerous `ConfigOption` and `ConfigNamespace` instances defined as static fields on classes throughout the codebase.  The `ConfigNamespace`s form a tree with `ConfigOption` at the leaves.  When Titan reads a string config key, it walks the tree from the root, looking for the corresponding `ConfigOption` instance, then uses the matching `ConfigOption` to validate and parse the string config key and its asssociated value.

It's not guaranteed that the static initializers on fields defining all these `ConfigNamespace`s and `ConfigOption`s will execute prior to invocation of `TitanFactory.open`.  But they're needed then for string config key parsing.  Also, some of the options are defined in modules that may not necessarily be present at runtime (e.g. titan-hbase may not be present on a Cassandra deployment), so not all of the possible `ConfigOption` references can be hardcoded.  That's why ReflectiveConfigOptionLoader exists.  We could hardcode options in titan-core (including ids.num-partitions) but since the reflective config option loader is already delicate and tweaking it is error-prone, the added complexity and questionable benefit of special-casing titan-core with a new logic path is not that appealing.

When you disable ReflectiveConfigOptionLoader like this, then you're responsible for initializing any `ConfigOption`s corresponding to keys in your config file.  This doesn't happen for ids.num-partitions in the gremlin session you pasted, hence the string config key is unrecognized.  This is an uncommon configuration and not recommended for general use.  Anyway, if you're still intent on disabling it, then here are a couple ways to approach this without the loader.
- call `Class.forName` on the enclosing class
- reference the field -- by logging its toString at DEBUG, for instance -- to fire its initializer prior to `TitanFactory.open`

For example, pasting this into the gremlin.sh prompt will do the latter for ids.num-partitions so that the string key can parse without the loader:

```
com.thinkaurelius.titan.graphdb.database.idassigner.placement.SimpleBulkPlacementStrategy.CONCURRENT_PARTITIONS
```

**Comment by skavulya** [comment]
Thanks for the clarification!
