### ISSUE TITLE
Timestamp conversion issues

### ISSUE THREAD

**Issue by dkuppitz** [thinkaurelius/titan#853]
If you use timestamps created by Titan (see http://s3.thinkaurelius.com/docs/titan/0.5.2/titan-config-ref.html#_storage_meta) in a query, e.g.

``` groovy
yesterday = System.currentTimeMillis() - 1000 * 60 * 60 * 24
timestamp = new StandardTimestamp(yesterday, TimeUnit.MILLISECONDS)
v.bothE().has('$timestamp', Compare.LESS_THAN, timestamp).remove()
```

...then all you get is an exception:

```
com.thinkaurelius.titan.core.SchemaViolationException: Value [Timestamp[1417100515434 ms]] is not an instance of the expected data type for property key [$timestamp] and cannot be converted. Expected: interface com.thinkaurelius.titan.core.attribute.Timestamp, found: class com.thinkaurelius.titan.diskstorage.util.time.StandardTimestamp
 at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.verifyAttribute(StandardTitanTx.java:547)
 at com.thinkaurelius.titan.graphdb.query.QueryUtil.addConstraint(QueryUtil.java:182)
 at com.thinkaurelius.titan.graphdb.query.QueryUtil.constraints2QNF(QueryUtil.java:172)
 at com.thinkaurelius.titan.graphdb.query.vertex.BasicVertexCentricQueryBuilder.constructQuery(BasicVertexCentricQueryBuilder.java:385)
 at com.thinkaurelius.titan.graphdb.query.vertex.VertexCentricQueryBuilder.execute(VertexCentricQueryBuilder.java:62)
 at com.thinkaurelius.titan.graphdb.query.vertex.VertexCentricQueryBuilder.titanEdges(VertexCentricQueryBuilder.java:79)
 at com.thinkaurelius.titan.graphdb.query.vertex.VertexCentricQueryBuilder.edges(VertexCentricQueryBuilder.java:98)
 at com.tinkerpop.pipes.transform.VertexQueryPipe.processNextStart(VertexQueryPipe.java:113)
 at com.tinkerpop.pipes.transform.VertexQueryPipe.processNextStart(VertexQueryPipe.java:19)
 at com.tinkerpop.pipes.AbstractPipe.next(AbstractPipe.java:89)
 at com.tinkerpop.pipes.IdentityPipe.processNextStart(IdentityPipe.java:19)
 at com.tinkerpop.pipes.AbstractPipe.next(AbstractPipe.java:89)
 at com.tinkerpop.pipes.IdentityPipe.processNextStart(IdentityPipe.java:19)
 at com.tinkerpop.pipes.AbstractPipe.hasNext(AbstractPipe.java:98)
 at com.tinkerpop.pipes.util.Pipeline.hasNext(Pipeline.java:105)
 at com.tinkerpop.gremlin.java.GremlinPipeline.remove(GremlinPipeline.java:1607)
<snip>
```

I'm not sure whether the property name is indeed `$timestamp`, the client who reported the bug used a String constant in the original query, I just took the property name from the stacktrace.

**Comment by dkuppitz** [comment]
:+1:

**Before:**

```
gremlin> Titan.version()
==>0.5.2
gremlin> import com.thinkaurelius.titan.diskstorage.util.time.StandardTimestamp
gremlin> import java.util.concurrent.TimeUnit
...
gremlin> g = TitanFactory.open("conf/titan-cassandra-es.properties")
==>titangraph[cassandrathrift:[127.0.0.1]]
gremlin> v1 = g.addVertex(null)
==>v[256]
gremlin> v2 = g.addVertex(null)
==>v[512]
gremlin> v1.addEdge("knows", v2)
==>e[dc-74-1lh-e8][256-knows->512]
gremlin> g.commit()
==>null
gremlin> yesterday = System.currentTimeMillis() - 1000 * 60 * 60 * 24
==>1420757188022
gremlin> g.V().bothE().has('$timestamp', Compare.GREATER_THAN_EQUAL, new StandardTimestamp(yesterday, TimeUnit.MILLISECONDS))
Value [Timestamp[1420757188022 ms]] is not an instance of the expected data type for property key [$timestamp] and cannot be converted. Expected: interface com.thinkaurelius.titan.core.attribute.Timestamp, found: class com.thinkaurelius.titan.diskstorage.util.time.StandardTimestamp
Display stack trace? [yN] N
```

**After:**

```
gremlin> Titan.version()
==>0.5.3-SNAPSHOT
gremlin> import java.util.concurrent.TimeUnit
gremlin> import com.thinkaurelius.titan.core.attribute.Timestamp
...
gremlin> g = TitanFactory.open("conf/titan-cassandra-es.properties")
==>titangraph[cassandrathrift:[127.0.0.1]]
gremlin> v1 = g.addVertex(null)
==>v[256]
gremlin> v2 = g.addVertex(null)
==>v[512]
gremlin> v1.addEdge("knows", v2)
==>e[dc-74-1lh-e8][256-knows->512]
gremlin> g.commit()
==>null
gremlin> yesterday = System.currentTimeMillis() - 1000 * 60 * 60 * 24
==>1420758191198
gremlin> g.V().bothE().has('$timestamp', Compare.GREATER_THAN_EQUAL, new Timestamp(yesterday, TimeUnit.MILLISECONDS))
==>e[dc-74-1lh-e8][256-knows->512]
==>e[dc-74-1lh-e8][256-knows->512]
```

In both cases the following line was added to `titan-cassandra-es.properties`:

```
storage.meta.edgestore.timestamps=true
```
