### ISSUE TITLE
GraphQuery use Contain.IN Predicate

### ISSUE THREAD

**Issue by boliza** [thinkaurelius/titan#882]
my schema is:

``` Java
VertexLabel label = mgmt.makeVertexLabel("bloggerLabel").make();
PropertyKey bloggerId= mgmt.makePropertyKey("bloggerId").dataType(String.class).make();
TitanGraphIndex bloggerIdIndex = mgmt.buildIndex("bloggerIdIndex", Vertex.class).indexOnly(label ).addKey(bloggerId).unique().buildCompositeIndex();
mgmt.setConsistency(bloggerIdIndex, ConsistencyModifier.LOCK);
mgmt.addIndexKey(getExternalIndex(Vertex.class), bloggerId, Mapping.STRING.getParameter());
```

the first query is:

``` Java
Iterable<Vertex> vertexes = tx.query()
                /*.has("label", "bloggerLabel")*/
                .has("bloggerId", Contain.IN, ImmutableList.of("teboliza", "teshengwj2003"))
                .vertices();
assertTrue(Iterables.size(vertexes) == 2);
```

the test passed,but when I add an condition like this:

``` Java
Iterable<Vertex> vertexes = tx.query()
                .has("label", "bloggerLabel")
                .has("bloggerId", Contain.IN, ImmutableList.of("teboliza", "teshengwj2003"))
                .vertices();
assertTrue(Iterables.size(vertexes) == 2);
```

get an exception:

``` Java
com.thinkaurelius.titan.core.TitanException: Could not process individual retrieval call 
    at com.thinkaurelius.titan.graphdb.query.QueryUtil.processIntersectingRetrievals(QueryUtil.java:233)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$8.execute(StandardTitanTx.java:1195)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$8.execute(StandardTitanTx.java:1064)
    at com.thinkaurelius.titan.graphdb.query.QueryProcessor$LimitAdjustingIterator.getNewIterator(QueryProcessor.java:195)
    at com.thinkaurelius.titan.graphdb.query.LimitAdjustingIterator.hasNext(LimitAdjustingIterator.java:54)
    at com.thinkaurelius.titan.graphdb.query.ResultSetIterator.nextInternal(ResultSetIterator.java:40)
    at com.thinkaurelius.titan.graphdb.query.ResultSetIterator.<init>(ResultSetIterator.java:30)
    at com.thinkaurelius.titan.graphdb.query.QueryProcessor.iterator(QueryProcessor.java:56)
    at com.google.common.collect.Iterables$7.iterator(Iterables.java:613)
    at com.google.common.collect.Iterables.size(Iterables.java:108)
    at com.antfact.nest.graph.test.RelationTest.testVertexWithVertexLabel(RelationTest.java:129)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.internal.runners.TestMethodRunner.executeMethodBody(TestMethodRunner.java:99)
    at org.junit.internal.runners.TestMethodRunner.runUnprotected(TestMethodRunner.java:81)
    at org.junit.internal.runners.BeforeAndAfterRunner.runProtected(BeforeAndAfterRunner.java:34)
    at org.junit.internal.runners.TestMethodRunner.runMethod(TestMethodRunner.java:75)
    at org.junit.internal.runners.TestMethodRunner.run(TestMethodRunner.java:45)
    at org.junit.internal.runners.TestClassMethodsRunner.invokeTestMethod(TestClassMethodsRunner.java:75)
    at org.junit.internal.runners.TestClassMethodsRunner.run(TestClassMethodsRunner.java:36)
    at org.junit.internal.runners.TestClassRunner$1.runUnprotected(TestClassRunner.java:42)
    at org.junit.internal.runners.BeforeAndAfterRunner.runProtected(BeforeAndAfterRunner.java:34)
    at org.junit.internal.runners.TestClassRunner.run(TestClassRunner.java:52)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:130)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: com.thinkaurelius.titan.core.TitanException: Could not call index
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$8$6.call(StandardTitanTx.java:1188)
    at com.thinkaurelius.titan.graphdb.query.QueryUtil.processIntersectingRetrievals(QueryUtil.java:231)
    ... 33 more
Caused by: java.lang.IllegalArgumentException
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:111)
    at com.thinkaurelius.titan.graphdb.database.IndexSerializer.query(IndexSerializer.java:527)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$8$6$1.call(StandardTitanTx.java:1184)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$8$6$1.call(StandardTitanTx.java:1181)
    at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4739)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
    at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4736)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx$8$6.call(StandardTitanTx.java:1181)
    ... 34 more
```

**Comment by mbroecheler** [comment]
Which version of Titan is this?

**Comment by boliza** [comment]
@mbroecheler sorry I forget mark the titan version,I using tian 0.5.2

**Comment by dalaro** [comment]
Thanks for the detailed report, @boliza 

I reproduced this titan05.  I've adapted this into a test case which I'll commit and push soon.  An external index is not required to produce this exception.

**Comment by boliza** [comment]
@dalaro could Contain.IN effect using CompositeIndex?

**Comment by dalaro** [comment]
Deleted precondition following discussion with @mbroecheler in 4e38eca1540b4b42d2c722b8f063adda5c87f537.
