### ISSUE TITLE
Null pointer exception when doing getEdges

### ISSUE THREAD

**Issue by crakjie** [thinkaurelius/titan#897]
vertex.getEdges(Direction.IN) give some time ( rarely )

```
java.lang.NullPointerException
    at com.thinkaurelius.titan.graphdb.database.EdgeSerializer.parseRelation(EdgeSerializer.java:103)
    at com.thinkaurelius.titan.graphdb.database.EdgeSerializer.readRelation(EdgeSerializer.java:69)
    at com.thinkaurelius.titan.graphdb.transaction.RelationConstructor.readRelation(RelationConstructor.java:61)
    at com.thinkaurelius.titan.graphdb.transaction.RelationConstructor$1$1.next(RelationConstructor.java:46)
    at com.thinkaurelius.titan.graphdb.transaction.RelationConstructor$1$1.next(RelationConstructor.java:34)
    at com.thinkaurelius.titan.graphdb.query.LimitAdjustingIterator.next(LimitAdjustingIterator.java:80)
    at com.google.common.collect.Iterators$7.computeNext(Iterators.java:646)
    at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
    at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
    at com.thinkaurelius.titan.graphdb.query.ResultSetIterator.nextInternal(ResultSetIterator.java:40)
    at com.thinkaurelius.titan.graphdb.query.ResultSetIterator.<init>(ResultSetIterator.java:30)
    at com.thinkaurelius.titan.graphdb.query.QueryProcessor.iterator(QueryProcessor.java:56)

```

**Comment by dalaro** [comment]
Which version of Titan produces this exception?  Could you describe steps to reproduce this at least some of the time, assuming it's reproducible?

Guessing that this is 0.5.2, the trace suggests something like the serializer reading a relation with null multiplicity.

**Comment by crakjie** [comment]
Ok I look up a lot and I found how to reproduce it.

 mgmt.getEdgeLabel("labelName")

and g.getVertices.map( v => v.getEdges )

Will throw nul pointer exception when ( I think ) v get Edge without label.

It could be nice to have a real and explicit exception, no ?

**Comment by mbroecheler** [comment]
This strongly suggests data inconsistency in the underlying data store.

**Comment by metlos** [comment]
I get the same error in Titan 0.5.4 when doing `Vertex.getPropertyKeys()` with Cassandra backend.

While I appreciate this might be an "inconsistency in the data store" - could you provide some guidance on how to repair the inconsistencies?

**Comment by abelamtech** [comment]
This happened to me and it was not a source of error in the underlying data store. I could trace the error to the deletion of a PropertyKey while there were existing vertices with properties referring to that PropertyKey. Is this a normal behavior? I wonder if titan should not prevent us from removing PropertyKeys when they are being used by existing vertices.
