### ISSUE TITLE
MAX_WAIT_TIME that the StandardIDPool waits for the IDBlockThread is too short

### ISSUE THREAD

**Issue by jasonculverhouse** [thinkaurelius/titan#91]
I'm pretty sure this has to be at least idauthority-wait-time \* idauthority-retries (300 \* 20) = 6000 vs the 2000 it is right now.

If I load a large amount vertices with batch-loading=true from a map reduce job sooner of later you will end up with a stack trace as follows with out seeing the "Could not acquire new ID block from storage" exception.

```
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:76)
    at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextBlock(StandardIDPool.java:63)
    at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextID(StandardIDPool.java:104)
    at com.thinkaurelius.titan.graphdb.database.idassigner.SimpleVertexIDAssigner.nextNodeID(SimpleVertexIDAssigner.java:97)
    at com.thinkaurelius.titan.graphdb.database.idassigner.SimpleVertexIDAssigner.getNewID(SimpleVertexIDAssigner.java:60)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.assignID(StandardTitanGraph.java:571)
    at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.registerNewEntity(AbstractTitanTx.java:121)
    at com.thinkaurelius.titan.graphdb.vertices.factory.StandardVertexFactories$1.createNew(StandardVertexFactories.java:23)
    at com.thinkaurelius.titan.graphdb.transaction.AbstractTitanTx.addVertex(AbstractTitanTx.java:133)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.addVertex(TitanBlueprintsTransaction.java:41)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsGraph.addVertex(TitanBlueprintsGraph.java:100)
```

**Comment by mbroecheler** [comment]
This has been fixed in the "storage" branch and will be merged back into master for the 0.2 release.
