### ISSUE TITLE
Traversal and Transaction - Titan 0.9M1

### ISSUE THREAD

**Issue by spmallette** [thinkaurelius/titan#921]
Reported here in the mailing list: 

https://groups.google.com/d/msg/aureliusgraphs/JgMlZsuXhgg/slJF-qrpngMJ

but something i discovered a while back on my own and discussed with @dalaro - not sure that we came to a solution or if this is fixed.  i figured i would create an issue to prevent forgetting about it again.  

it's pretty easy to recreate the problem:

``` text
gremlin> :remote connect tinkerpop.server conf/remote.yaml
==>Connected - localhost/127.0.0.1:8182
gremlin> :> g
==>standardtitangraph[berkeleyje:db/berkeley]
gremlin> :> g.addVertex("name","stephen")
==>v[256]
gremlin> :> g.V().count()
==>1
gremlin> :> g.V()
==>v[256]
gremlin> :> g.V().values("name")
==>stephen
```

all works as expected - it can clearly serialize all of that.  the use of `has` triggers this:

``` text
gremlin> :> g.V().has("name","stephen")
WARN  io.netty.channel.DefaultChannelPipeline  - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException
    at com.tinkerpop.gremlin.driver.Handler$GremlinResponseHandler.channelRead0(Handler.java:45)
    at com.tinkerpop.gremlin.driver.Handler$GremlinResponseHandler.channelRead0(Handler.java:21)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at com.tinkerpop.gremlin.driver.handler.WebSocketClientHandler.channelRead0(WebSocketClientHandler.java:72)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
Response iteration and serialization exceeded the configured threshold for request [[RequestMessage{, requestId=a8d487f8-935b-478e-898a-4c45a60aefa6, op='eval', processor='', args={gremlin=g.V().has("name","stephen"), batchSize=64}}, [TitanGraphStep([[name,eq,stephen]])]]] - Operation cannot be executed because the enclosing transaction is closed
```

This could be a problem in Gremlin Server and nothing to do with the Titan implementation.

**Comment by spmallette** [comment]
I've been able to recreate the problem in the regular Gremlin Console:

``` text
gremlin> g = TitanFactory.open("conf/titan-berkeleydb.properties")
==>standardtitangraph[berkeleyje:/home/smallette/jvm/titan-console-0.9.0-M1/conf/../db/berkeley]
gremlin> g.addVertex("name","stephen")
==>v[256]
gremlin> g.tx().commit()
==>null
gremlin> t = g.V().has("name","stephen");null
==>null
gremlin> g.tx().commit()
==>null
gremlin> t
Operation cannot be executed because the enclosing transaction is closed
Display stack trace? [yN] n
```

Basically, the transaction closes but isn't auto-reopened for some reason.  Note that is behavior is different from 0.5.x which works perfectly:

``` text
gremlin> g = TitanFactory.open('conf/titan-berkeleydb.properties')
==>titangraph[berkeleyje:/home/smallette/jvm/titan-0.5.2-hadoop1/conf/../db/berkeley]
gremlin> g.addVertex([name:"stephen"])
==>v[256]
gremlin> g.commit()
==>null
gremlin> t = g.V.has("name","stephen");null
==>null
gremlin> g.commit()
==>null
gremlin> t
16:32:03 WARN  com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx  - Query requires iterating over all vertices [(name = stephen)]. For better performance, use indexes
==>v[256]
```

I assume that we want this working like 0.5.x and that I don't need to adjust Gremlin Server at all.  Please let me know if there is some different opinion on that.

**Comment by spmallette** [comment]
I've added a test to TP3 in the commit above to enforce the expected operation.

**Comment by mbroecheler** [comment]
This has been fixed as the TP test case now passes.

**Comment by gepengxu** [comment]
I find same issue ,When Load data GSON Format to Titan cluster,by Titan-hadoop(0.5.1),
on the TitanGraphOutputMapReduce execute the EdgeMap,find such issue
java.io.IOException: Operation cannot be executed because the enclosing transaction is closed
    at com.thinkaurelius.titan.hadoop.formats.util.TitanGraphOutputMapReduce$EdgeMap.map(TitanGraphOutputMapReduce.java:534)
    at com.thinkaurelius.titan.hadoop.formats.util.TitanGraphOutputMapReduce$EdgeMap.map(TitanGraphOutputMapReduce.java:496)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:140)
    at org.apache.hadoop.mapreduce.lib.chain.Chain$MapRunner.run(Chain.java:321)
Caused by: java.lang.IllegalStateException: Operation cannot be executed because the enclosing transaction is closed
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.verifyOpen(StandardTitanTx.java:266)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.getVertex(StandardTitanTx.java:351)
    at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.it(AbstractVertex.java:40)
    at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.it(AbstractVertex.java:24)
    at com.thinkaurelius.titan.graphdb.internal.AbstractEl

how can solve it
