### ISSUE TITLE
Why this exception

### ISSUE THREAD

**Issue by boliza** [thinkaurelius/titan#928]
``` Java
java.lang.IllegalArgumentException: Cannot access a removed vertex: v[105384064512]
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)[99:com.google.guava:17.0.0]
    at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.query(AbstractVertex.java:118)
    at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.getProperty(AbstractVertex.java:136)
    at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.getProperty(AbstractVertex.java:152)
```

I use vertex id to load vertex,when get the unique property ,throw this exception

**Comment by boliza** [comment]
more infomation
I use titan0.5.2,using titan in OSGI.

**Comment by mbroecheler** [comment]
This indicates that the vertex has been deleted.

**Comment by boliza** [comment]
I'am confused , Some of the exception vertex id ,can load by rexster ,some vertex has not the unique property.
