### ISSUE TITLE
titan.properties on classpath results in startup failure.

### ISSUE THREAD

**Issue by rjbriody** [thinkaurelius/titan#929]
Seen in 0.9.M1

Having a titan.properties on the classpath causes a failure on startup.

```
Exception in thread "main" java.lang.ExceptionInInitializerError
    at com.thinkaurelius.titan.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1296)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:91)
    at com.thinkaurelius.titan.core.TitanFactory.open(TitanFactory.java:71)
    at runnable.TestConfBug.main(TestConfBug.java:21)
Caused by: java.lang.UnsupportedOperationException
    at com.google.common.collect.ImmutableMap.put(ImmutableMap.java:326)
    at com.thinkaurelius.titan.diskstorage.Backend.registerShorthands(Backend.java:726)
    at com.thinkaurelius.titan.diskstorage.Backend.<clinit>(Backend.java:717)
    ... 4 more
```

The problem is that an ImmutableMap is returned and passed on the following line:

```
registerShorthands(props, "storage.", StandardStoreManager.getAllManagerClasses())
```

...then registerShorthands calls put on the Immutable Map

```
shorthands.put(shorthand, clazz);
```

...which results in the `UnsupportedOperationException`.

Taking a step back, I wonder if auto-loading titan.properties is actually useful (but I'm not clear on it's original purpose).

**Comment by dalaro** [comment]
Thanks for the report.  I think this involved two separate problems:
- When I made the maps of shorthand->classname immutable, I didn't account for the code in the trace, which attempts to put custom entries from `titan.properties` into those maps
- `titan.properties` is a collision-prone name; it's too likely that a user will name their config file `titan.properties` to make assumptions about its contents (in this case, that it contains index and/or storage backend shorthand name-to-class mappings)

Defining custom shorthand names for backends is useful, but centralizing this info in a single file is not a great way to go about it.  Also, I'm not sure whether anyone actually cares about the custom shorthand feature (which is probably undocumented).  I went back and forth on this in my commits linked above, but in the end I removed the custom shorthand feature altogether.

If there's any demand for custom shorthand definition, then we might want to look at an alternative that allows us to spread these mappings out across multiple files, so that a preferred shorthand name can ship in the same jar that contains the implementation (maybe but not necessarily ServiceLoader).
