### ISSUE TITLE
AbstractVertex.setProperty issuing avoidable reads on unindexed Card.SINGLE propkeys

### ISSUE THREAD

**Issue by dalaro** [thinkaurelius/titan#931]
``` groovy
// I edited the cfg to set storage.backend=cassandra, but it's not material to this issue
g = TitanFactory.open("conf/titan-cassandra-es.properties")
m = g.getManagementSystem()
m.makePropertyKey('foo').dataType(String.class).make()
m.commit()
v = g.addVertex(null)
// Next setProperty does not issue any storage reads (OK)
v.setProperty('foo', 'bar')
g.commit()
v = g.v(256)
// Next setProperty calls removeProperty, which in turn calls getSlice; seems unnecessary
v.setProperty('foo', 'baz')
```

The trace line numbers are slightly different on 0.5.0 and titan05 (0.5.4-SNAPSHOT as of this writing), but the behavior appears to be the same on both versions.  Setting a breakpoint in the backend implementation's getSlice will trip when `setProperty` invokes `removeProperty` on a preexisting (i.e. non-new) vertex.  In the particular case of a Cardinality.SINGLE pkey with no indices, I think `setProperty` shouldn't need to read the current value like this.

Here's the trace from `setProperty` to the seemingly unnecessary `getSlice` as of titan05's current HEAD (69b0788d86422d6e50555e1830b46639137e305c).  It terminates in Astyanax since I set `storage.backend=cassandra` in the config file (default atm is cassandrathrift).

``` text
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
      at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getNamesSlice(AstyanaxKeyColumnValueStore.java:112)
      at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getNamesSlice(AstyanaxKeyColumnValueStore.java:78)
      at com.thinkaurelius.titan.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getSlice(AstyanaxKeyColumnValueStore.java:67)
      at com.thinkaurelius.titan.diskstorage.keycolumnvalue.KCVSProxy.getSlice(KCVSProxy.java:65)
      at com.thinkaurelius.titan.diskstorage.keycolumnvalue.cache.ExpirationKCVSCache.getSlice(ExpirationKCVSCache.java:83)
      at com.thinkaurelius.titan.diskstorage.BackendTransaction$1.call(BackendTransaction.java:256)
      at com.thinkaurelius.titan.diskstorage.BackendTransaction$1.call(BackendTransaction.java:253)
      at com.thinkaurelius.titan.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:56)
      at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:42)
      at com.thinkaurelius.titan.diskstorage.BackendTransaction.executeRead(BackendTransaction.java:428)
      at com.thinkaurelius.titan.diskstorage.BackendTransaction.edgeStoreQuery(BackendTransaction.java:253)
      at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.edgeQuery(StandardTitanGraph.java:365)
      at com.thinkaurelius.titan.graphdb.query.vertex.SimpleVertexQueryProcessor$2.get(SimpleVertexQueryProcessor.java:109)
      at com.thinkaurelius.titan.graphdb.query.vertex.SimpleVertexQueryProcessor$2.get(SimpleVertexQueryProcessor.java:106)
      at com.thinkaurelius.titan.graphdb.vertices.CacheVertex.loadRelations(CacheVertex.java:47)
      at com.thinkaurelius.titan.graphdb.query.vertex.SimpleVertexQueryProcessor.getBasicIterator(SimpleVertexQueryProcessor.java:106)
      at com.thinkaurelius.titan.graphdb.query.vertex.SimpleVertexQueryProcessor.iterator(SimpleVertexQueryProcessor.java:63)
      at com.thinkaurelius.titan.graphdb.transaction.RelationConstructor$1$1.<init>(RelationConstructor.java:36)
      at com.thinkaurelius.titan.graphdb.transaction.RelationConstructor$1.iterator(RelationConstructor.java:34)
      at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.removeProperty(AbstractVertex.java:268)
      at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.setProperty(StandardTitanTx.java:760)
      at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.setProperty(AbstractVertex.java:244)
      at com.thinkaurelius.titan.graphdb.vertices.AbstractVertex.setProperty(AbstractVertex.java:239)
```

My last touch on a test related to this functionality was in b08be31fdb9b428b18389d1261cd834fa414c8bd, and I initially wondered if there was some connection between this problem and my last touch.  I don't think that's the case.  0.5.0 predates that commit.  Since 0.5.0 appears to perform this avoidable getSlice, I think that commit isn't related.

**Comment by mbroecheler** [comment]
Short story: Do `tx = graph.buildTransaction().consistencyChecks(false).start()` when opening the transaction to avoid the read for now.

Long story: There is a bit of weirdness here. Without the above configure Titan will prematurely read the old property state in order to be able to apply for a lock. However, if locking is disabled for this particular property, then that's sort of in vain.

**Comment by rossabaker** [comment]
Will that workaround have any impact on the integrity of a unique index?  That also triggers a read.

**Comment by dalaro** [comment]
@rossabaker yes, the workaround is only safe on transactions that don't actually needs locks.  We're working on modifying Titan to detect when it's safe to forego this read, which should obviate the `consistencyChecks(false)` call (that's not intended to be the long-term solution).

I'm going to follow up with some more detail in our separate thread about this.
