### ISSUE TITLE
Conversion issue when trying to set a long value on an edge

### ISSUE THREAD

**Issue by dkuppitz** [thinkaurelius/titan#937]
Trying to set a `Long` on an edge fails when you're using the setting:

```
storage.meta.edgestore.timestamps=true
```

Check out the [sample code](https://github.com/dkuppitz/titan-sandbox/tree/simon) that reproduces the issue.

**Comment by dkuppitz** [comment]
Same problem occurs when you try to remove a property with a `Long` value.

**Comment by mbroecheler** [comment]
Is that on 0.5.3 @dkuppitz ? Can you post the stack trace please?

**Comment by dkuppitz** [comment]
[It is](https://github.com/dkuppitz/titan-sandbox/blob/simon/pom.xml#L15). The [stacktrace](https://github.com/dkuppitz/titan-sandbox/commit/7146d60b5c5d92fbc1818b9cbe1ba959d37fee94) for `setProperty()`:

```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot use implicit type [$timestamp] when setting property
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)
    at com.thinkaurelius.titan.graphdb.relations.StandardEdge.setPropertyDirect(StandardEdge.java:54)
    at com.thinkaurelius.titan.graphdb.relations.CacheEdge.copyProperties(CacheEdge.java:67)
    at com.thinkaurelius.titan.graphdb.relations.CacheEdge.update(CacheEdge.java:73)
    at com.thinkaurelius.titan.graphdb.relations.CacheEdge.setPropertyDirect(CacheEdge.java:111)
    at com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.setProperty(AbstractTypedRelation.java:113)
    at com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.setProperty(AbstractTypedRelation.java:119)
    at Sandbox.main(Sandbox.java:29)
```

...and for `removeProperty()`:

```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot use implicit type [$timestamp] when setting property
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)
    at com.thinkaurelius.titan.graphdb.relations.StandardEdge.setPropertyDirect(StandardEdge.java:54)
    at com.thinkaurelius.titan.graphdb.relations.CacheEdge.copyProperties(CacheEdge.java:67)
    at com.thinkaurelius.titan.graphdb.relations.CacheEdge.update(CacheEdge.java:73)
    at com.thinkaurelius.titan.graphdb.relations.CacheEdge.removePropertyDirect(CacheEdge.java:116)
    at com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.removeProperty(AbstractTypedRelation.java:99)
    at com.thinkaurelius.titan.graphdb.relations.AbstractTypedRelation.removeProperty(AbstractTypedRelation.java:93)
    at Sandbox.main(Sandbox.java:29)
```

**Comment by mbroecheler** [comment]
Oh, this is a good one ;-)
