### ISSUE TITLE
Hadoop read failure on edge property

### ISSUE THREAD

**Issue by dalaro** [thinkaurelius/titan#941]
This reproduces in two separate shell invocations.

First `gremlin.sh` invocation uses OLTP to load GotG:

``` groovy
g = TitanFactory.open('conf/titan-cassandra-es.properties')
GraphOfTheGodsFactory.load(g)

v = g.V('name', 'jupiter').next()

m = g.getManagementSystem()
m.makeEdgeLabel('hatedBy').multiplicity(Multiplicity.MANY2ONE).unidirected().make()
m.commit()
g.commit()

v.outE('father').next().setProperty('hatedBy', v)
g.shutdown()
```

Next `gremlin.sh` uses OLAP to count vertices.   It dies in FaunusSchemaManager.

``` groovy
h = HadoopFactory.open('conf/hadoop/titan-cassandra-input.properties')
h.V.count() // This line should fail
```

Here's the exception:

```
java.lang.Exception: java.lang.RuntimeException: java.lang.IllegalArgumentException: Name does not identify a property key:  [hatedBy]
        at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:403)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Name does not identify a property key:  [hatedBy]
        at org.apache.hadoop.mapreduce.lib.chain.Chain.joinAllThreads(Chain.java:526)
        at org.apache.hadoop.mapreduce.lib.chain.ChainMapper.run(ChainMapper.java:169)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:763)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:339)
        at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:235)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.IllegalArgumentException: Name does not identify a property key:  [hatedBy]
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:120)
        at com.thinkaurelius.titan.hadoop.FaunusSchemaManager.getPropertyKey(FaunusSchemaManager.java:138)
        at com.thinkaurelius.titan.hadoop.FaunusElement.getProperty(FaunusElement.java:334)
        at com.tinkerpop.blueprints.util.io.graphson.GraphSONUtility.createPropertyMap(GraphSONUtility.java:649)
        at com.tinkerpop.blueprints.util.io.graphson.GraphSONUtility.objectNodeFromElement(GraphSONUtility.java:218)
        at com.tinkerpop.blueprints.util.io.graphson.GraphSONUtility.jsonFromElement(GraphSONUtility.java:198)
        at com.tinkerpop.blueprints.util.io.graphson.GraphSONUtility.jsonFromElement(GraphSONUtility.java:388)
        at com.thinkaurelius.titan.hadoop.formats.graphson.HadoopGraphSONUtility.toJSON(HadoopGraphSONUtility.java:128)
        at com.thinkaurelius.titan.hadoop.formats.graphson.GraphSONRecordWriter.write(GraphSONRecordWriter.java:43)
        at com.thinkaurelius.titan.hadoop.formats.graphson.GraphSONRecordWriter.write(GraphSONRecordWriter.java:19)
        at org.apache.hadoop.mapreduce.lib.output.MultipleOutputs.write(MultipleOutputs.java:433)
        at org.apache.hadoop.mapreduce.lib.output.MultipleOutputs.write(MultipleOutputs.java:411)
        at com.thinkaurelius.titan.hadoop.mapreduce.util.SafeMapperOutputs.write(SafeMapperOutputs.java:34)
        at com.thinkaurelius.titan.hadoop.mapreduce.util.CountMapReduce$Map.map(CountMapReduce.java:74)
        at com.thinkaurelius.titan.hadoop.mapreduce.util.CountMapReduce$Map.map(CountMapReduce.java:39)
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)

```

Running these two snippets in the same shell does not produce a failure.

Reproduced on titan05 HEAD 69b0788d86422d6e50555e1830b46639137e305c.

**Comment by dalaro** [comment]
@dkuppitz points out that this can also be reproduced without restarting the shell:

``` groovy
g = TitanFactory.open('titan-0.5.3-hadoop2/conf/titan-cassandra-es.properties')
GraphOfTheGodsFactory.load(g)

v = g.V('name', 'jupiter').next()

m = g.getManagementSystem()
m.makeEdgeLabel('hatedBy').multiplicity(Multiplicity.MANY2ONE).unidirected().make()
m.commit()

v.outE('father').next().setProperty('hatedBy', v)

g.commit()

v.outE('father').next()['hatedBy']
g.V.count()

h = HadoopFactory.open('titan-0.5.3-hadoop2/conf/hadoop/titan-cassandra-input.properties')
h.V.count()
```

**Comment by dalaro** [comment]
I just edited the headline and issue summary to reference unidirected edges instead of some vague "edge prop".  Debugging did seem to show that this was specific to unidirected edges in titan-hadoop.  `FaunusElement.getPropertyKeysDirect` (incorrectly, I think) returned the name of an edge label for a unidirected edge.  This led to an exception when GraphSONUtility (correctly, from its perspective) attempts to call getProperty on the name of that uni edge label.  Little bit more discussion in the commit message for 79a942a43203bb32b4051edb298fdc312d36a950.
