### ISSUE TITLE
AssertionError in LongSerializer.read with "storage.meta.edgestore.timestamps" set to "true"

### ISSUE THREAD

**Issue by skiefer** [thinkaurelius/titan#945]
If "storage.meta.edgestore.timestamps" is set to "true", I get the following Exception:

``` Java
testGetStatements(com.iqser.gin.server.persistence.titan.StatementPersistenceServiceImplIntegrationTest)  Time elapsed: 3.477 sec  <<< FAILURE!
java.lang.AssertionError: null
    at com.thinkaurelius.titan.diskstorage.util.StaticArrayEntryList$LongSerializer.read(StaticArrayEntryList.java:582)
    at com.thinkaurelius.titan.diskstorage.util.StaticArrayEntryList$LongSerializer.read(StaticArrayEntryList.java:564)
    at com.thinkaurelius.titan.diskstorage.util.StaticArrayEntryList.parseMetaData(StaticArrayEntryList.java:487)
    at com.thinkaurelius.titan.diskstorage.util.StaticArrayEntryList.get(StaticArrayEntryList.java:68)
    at com.thinkaurelius.titan.diskstorage.util.StaticArrayEntryList.get(StaticArrayEntryList.java:15)
    at java.util.AbstractList$Itr.next(AbstractList.java:358)
    at com.thinkaurelius.titan.graphdb.transaction.RelationConstructor$1$1.next(RelationConstructor.java:46)
    at com.thinkaurelius.titan.graphdb.transaction.RelationConstructor$1$1.next(RelationConstructor.java:34)
    at com.tinkerpop.pipes.util.iterators.HistoryIterator.next(HistoryIterator.java:25)
    at com.tinkerpop.pipes.IdentityPipe.processNextStart(IdentityPipe.java:19)
    at com.tinkerpop.pipes.AbstractPipe.next(AbstractPipe.java:89)
    at com.tinkerpop.pipes.util.Pipeline.next(Pipeline.java:115)
    at com.tinkerpop.pipes.util.PipeHelper.fillCollection(PipeHelper.java:52)
    at com.tinkerpop.gremlin.java.GremlinPipeline.toList(GremlinPipeline.java:1564)
    at com.iqser.gin.server.persistence.titan.StatementPersistenceServiceImpl.getStatements(StatementPersistenceServiceImpl.java:111)
    at com.iqser.gin.server.persistence.titan.StatementPersistenceServiceImplIntegrationTest.testGetStatements(StatementPersistenceServiceImplIntegrationTest.java:112)
```

 when calling the following code:

``` Java
public List<Statement> getStatements(long contentId) {
    List<Statement> result = new ArrayList<>();
    Vertex contentVertex = transactionService.getCurrentTransaction().getVertex(contentId);
    if (contentVertex != null) {
        List<Edge> statementEdges = new GremlinPipeline<Iterable<Edge>, Edge>(contentVertex.getEdges(
                Direction.BOTH, "statement")).toList();
        result.addAll(edgeToStatementConverter.convertToStatements(statementEdges));
    }
    return result;
}
```

while this code is working without any problems:

``` Java
public List<Statement> getStatements(long contentId) {
    List<Statement> result = new ArrayList<>();
    Vertex contentVertex = transactionService.getCurrentTransaction().getVertex(contentId);
    if (contentVertex != null) {
        for(Edge edge : contentVertex.getEdges(Direction.BOTH, "statement")) {
            result.add(edgeToStatementConverter.convertToStatement(edge));
        }
    }
    return result;
}
```

The query seems only to be failing if the graph contains one "statement" edge pointing to the vertex. It there is an edge which is starting from the vertex the AssertionError does not occur.
The Problems occurred with Titan 0.5.3.

**Comment by mbroecheler** [comment]
@skiefer I have not yet been able to reproduce this on another dataset. 
When you say:

> The query seems only to be failing if the graph contains one "statement" edge pointing to the vertex. It there is an edge which is starting from the vertex the AssertionError does not occur.

Does that apply to both pieces of code you pasted above or only to the first? In other words, is it the GremlinPipeline that is causing problems here or the one edge pointing in the other direction?

Bumping to 0.5.5 to not delay 0.5.4.

**Comment by skiefer** [comment]
Yes, the GremlinPipeline seems to cause this problem. The second code snippet is the workaround for the problem.

**Comment by mbroecheler** [comment]
Still not able to reproduce.

**Comment by mbroecheler** [comment]
@dkuppitz Could you try to reproduce this and figure out what the issues is? Why is the pipeline causing such a failure where normal iteration isn't?

**Comment by dkuppitz** [comment]
Hm, I tried a lot of scenarios with the Graph of the Gods, but I got no exception at all. Maybe you have some corrupted data?

@skiefer Does it also happen if you use the following code instead?

``` java
public List<Statement> getStatements(long contentId) {
    List<Statement> result = new ArrayList<>();
    Vertex contentVertex = transactionService.getCurrentTransaction().getVertex(contentId);
    if (contentVertex != null) {
        List<Edge> statementEdges = new GremlinPipeline<Vertex, Edge>(contentVertex).both("statement").toList();
        result.addAll(edgeToStatementConverter.convertToStatements(statementEdges));
    }
    return result;
}
```

**Comment by skiefer** [comment]
This Code is is working correctly:

``` java
public List<Statement> getStatements(long contentId) {
    List<Statement> result = new ArrayList<>();
    Vertex contentVertex = transactionService.getCurrentTransaction().getVertex(contentId);
    if (contentVertex != null) {
        List<Edge> statementEdges = new GremlinPipeline<Vertex, Edge>(contentVertex).bothE("statement").toList();
        result.addAll(edgeToStatementConverter.convertToStatements(statementEdges));
    }
    return result;
}
```

I dont think that the data is corrupted. The problem occurres in a simple integration test which is executed on a fresh cassandra instance.

**Comment by skiefer** [comment]
I just tried to isolate the problem and I'm not able to reproduce it anymore.

**Comment by dkuppitz** [comment]
Please reopen if you find a way to reproduce it.
