### ISSUE TITLE
Trying to serialise a Geoshape as GraphSON give an odd error message.

### ISSUE THREAD

**Issue by BrynCooke** [thinkaurelius/titan#953]
Titan 0.9

I know this isn't supported currently but the error message could be better.

```
Caused by: java.lang.IllegalArgumentException: This shape is not a circle
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:93)
    at com.thinkaurelius.titan.core.attribute.Geoshape.getRadius(Geoshape.java:156)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.get(BeanPropertyWriter.java:679)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:534)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:597)
```

The bean property writer is just going through all the get methods on geoshape.

**Comment by mbroecheler** [comment]
Closing this in favor of fixing #954.
