### ISSUE TITLE
Catch exception trying to unregister in shutdown

### ISSUE THREAD

**Issue by mbroecheler** [thinkaurelius/titan#979]
and proceed with shutdown.

See user reported error:

I tried to debug the code and found that during graph shutdown there are attempts made to write data to the backend which fails as other cassandra node is down and there is no quorum. It makes shutdown to throw an uncaught exception and various threads keep running.

For example following line in StandardTitanGraph.shutdown()
globalConfig.remove(REGISTRATION_TIME,config.getUniqueGraphId());

Since only other cassandra node is down at this time,  it throws TemporaryBackendException which is not handled, it aborts the shutdown execution leaving other threads running.
I modified the code to catch above exception but then again data is written during shutdown of Bakend.

I am curious, is it a good idea to write something to storage during shutdown of the graph??

Complete stack trace:

com.thinkaurelius.titan.core.TitanException: Could not execute operation due to backend exception

```
at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:44)

at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:144)

at com.thinkaurelius.titan.diskstorage.configuration.backend.KCVSConfiguration.set(KCVSConfiguration.java:145)

at com.thinkaurelius.titan.diskstorage.configuration.backend.KCVSConfiguration.set(KCVSConfiguration.java:122)

at com.thinkaurelius.titan.diskstorage.configuration.backend.KCVSConfiguration.remove(KCVSConfiguration.java:163)

at com.thinkaurelius.titan.diskstorage.configuration.ModifiableConfiguration.remove(ModifiableConfiguration.java:42)

at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.shutdownInternal(StandardTitanGraph.java:189)

at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.shutdown(StandardTitanGraph.java:157)

at com.abc.itrp.ers.graph.DataSource$1.run(DataSource.java:60)

at com.abc.itrp.ers.graph.DataSource.releaseGraph(DataSource.java:64)

at com.abc.itrp.ers.graph.QuorumCheckThread.run(QuorumCheckThread.java:82)
```

**Comment by dalaro** [comment]
I modified titan09's `StandardTitanGraph.shutdownInternal` to catch and log exceptions, then proceed with remaining shutdown actions.  This leans heavily on AutoCloseable and I didn't try to backport to titan05.

Regarding the question -- "is it a good idea to write something to storage during shutdown of the graph?" -- yes, as long as those writes are just optimizations rather than necessary, and as long as Titan handles failure to write gracefully.  In this case, Titan should just remove its instance uniqueid from the list of live instances, then write some metadata for clean resumption of the mgmt and perhaps tx logs.
