### ISSUE TITLE
java.lang.ClassNotFoundException on running bin/gremlin.sh

### ISSUE THREAD

**Issue by ventlam** [thinkaurelius/titan#98]
I am new to titan,just follow Getting Started ,download and unzip the titian.zip,and the run ./bin/gremlin.sh ,cause error as below :
Exception in thread "main" java.lang.NoClassDefFoundError: JAVA_HOME=/usr/lib/jvm/java-6-sun
Caused by: java.lang.ClassNotFoundException: JAVA_HOME=.usr.lib.jvm.java-6-sun
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
Could not find the main class: JAVA_HOME=/usr/lib/jvm/java-6-sun.  Program will exit.

My environment is ubuntu 10.04 ,JAVA_HOME=/usr/lib/jvm/java-6-sun-1.6.0.22

**Comment by okram** [comment]
I don't believe this is an issue with Gremlin, but your environment. If you can isolate it to Gremlin, please reopen and provide more information (or the fix). Thanks.
