### ISSUE TITLE
BerkleyElasticsearchTest fails on subsequent runs

### ISSUE THREAD

**Issue by BrynCooke** [thinkaurelius/titan#990]
BerkleyElasticsearchTest
When running the unit tests I sometimes errors, these look like actual test errors but they go away if I do a clean build.

This is a very common stack trace for testGraphOfGodsFactoryCreate:

```
com.thinkaurelius.titan.core.SchemaViolationException: Adding this property for key [~T$SchemaName] and value [rt%name] violates a uniqueness constraint [SystemIndex#~T$SchemaName]
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.addPropertyInternal(StandardTitanTx.java:746)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.setProperty(StandardTitanTx.java:781)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.addProperty(StandardTitanTx.java:704)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.makeSchemaVertex(StandardTitanTx.java:834)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.makePropertyKey(StandardTitanTx.java:854)
    at com.thinkaurelius.titan.graphdb.types.StandardPropertyKeyMaker.make(StandardPropertyKeyMaker.java:86)
    at com.thinkaurelius.titan.example.GraphOfTheGodsFactory.load(GraphOfTheGodsFactory.java:45)
    at com.thinkaurelius.titan.example.GraphOfTheGodsFactory.create(GraphOfTheGodsFactory.java:38)
    at com.thinkaurelius.titan.diskstorage.es.BerkeleyElasticsearchTest.testGraphOfTheGodsFactoryCreate(BerkeleyElasticsearchTest.java:50)
```

**Comment by BrynCooke** [comment]
Running mvn test twice in a row will cause the issue to surface:
Results :

Failed tests: 
  BerkeleyElasticsearchTest>TitanIndexTest.testCompositeAndMixedIndexing:649 expected:<25> but was:<13>
  BerkeleyElasticsearchTest>TitanIndexTest.testRawQueries:830 expected:<500> but was:<0>
  BerkeleyElasticsearchTest>TitanIndexTest.testConditionalIndexing:570 expected:<50> but was:<0>
  BerkeleyElasticsearchTest>TitanIndexTest.testIndexing:266 expected:<25> but was:<4>

Tests in error: 
  BerkeleyElasticsearchTest.testGraphOfTheGodsFactoryCreate:52 » SchemaViolation

**Comment by BrynCooke** [comment]
The Graph of gods test was actually never being cleared out. Somehow this single test failing had an interaction with the other tests that caused them to also fail.
