### ISSUE TITLE
Allow ID allocation to resume after continuous failures exceeding ids.renew-timeout

### ISSUE THREAD

**Issue by dalaro** [thinkaurelius/titan#992]
This is assigned somewhat arbitrarily to 0.5.5.  It may also apply to 0.9 (not sure yet).

Looking at StandardIDPool.java in 0.5.4, I think I see the following:
- Successive IO failures when attempting to claim a new ID block in the storage backend which take (collectively) longer than ids.renew-timeout will set StandardIDPool.nextBlock = null.
- If StandardIDPool.nextBlock is null, calls to StandardIDPool.nextID will not start a new allocation attempt.  nextID will call nextBlock, which then throws an IllegalArgumentException without talking to the storage backend.  I don't see how we can get out of this state once we enter it, even if the storage backend later becomes responsive enough to satisfy new ID block allocation attempts.

The first next step is to add a test that proves the behavior describes above actually exists in controlled conditions.  Then we can change StandardIDPool.

**Comment by skiefer** [comment]
I can confirm this behaviour in Titan 0.5.3.
Once I'm getting this exception, it re-occurres continuously and I cannot get out of this state:

``` java
java.lang.IllegalArgumentException: null
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:111)
    at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextBlock(StandardIDPool.java:152)
    at com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool.nextID(StandardIDPool.java:193)
    at com.thinkaurelius.titan.graphdb.database.idassigner.VertexIDAssigner.assignID(VertexIDAssigner.java:330)
    at com.thinkaurelius.titan.graphdb.database.idassigner.VertexIDAssigner.assignID(VertexIDAssigner.java:185)
    at com.thinkaurelius.titan.graphdb.database.idassigner.VertexIDAssigner.assignID(VertexIDAssigner.java:151)
    at com.thinkaurelius.titan.graphdb.database.StandardTitanGraph.assignID(StandardTitanGraph.java:385)
    at com.thinkaurelius.titan.graphdb.transaction.StandardTitanTx.addEdge(StandardTitanTx.java:675)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.addEdge(TitanBlueprintsTransaction.java:132)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.addEdge(TitanBlueprintsTransaction.java:124)
    at com.thinkaurelius.titan.graphdb.blueprints.TitanBlueprintsTransaction.addEdge(TitanBlueprintsTransaction.java:28)
    at com.iqser.gin.server.persistence.titan.StatementPersistenceServiceImpl.add(StatementPersistenceServiceImpl.java:78)
```

The exception occurres when Cassandra is under heavy load.

**Comment by dalaro** [comment]
I just pushed a new test method for this scenario and associated fix.

**Comment by concretevitamin** [comment]
@dalaro @skiefer any advice for overcoming this issue in Titan 0.5.4? Or, equivalently, any quick tunings we can do to Cassandra so that it behaves more nicely?

**Comment by dalaro** [comment]
This particular bug requires ID allocation to repeatedly fail / take longer than `ids.renew-timeout`.  Are you seeing repeated "Lock write succeeded but took too long: duration foo exceeded bar"?  A succession of these can accumulate to `ids.renew-timeout`.  It's one way this can happen, though maybe not the only way.  `ids.authority.wait-time` should control bar.
